### ISSUE TITLE
Lingering style notes from #996

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1002]
A number of smaller style issues where noted in #996—this can be good onboarding work for new team members in the spring. Go to the closed pull requests list, find #996, then go over the comments from the last review, changing the code accordingly without incurring regressions

**Comment by kdahlquist** [comment]
This will be the next one that @ceciliazaragoza and @akaiap will tackle this week.

**Comment by ntran18** [comment]
I also found repetitive code in scripts in `generate_network.py`, `generate_new_network_version.py` and `generate_sgd_network_from_yeastract_network.py`

![image](https://github.com/dondi/GRNsight/assets/108908370/006568c2-69ee-4f0b-b6bb-bbaf272e034d)

**Comment by ceciliazaragoza** [comment]
I found a lingering `/* eslint-disable max-len */` in line 1 at the top of `server/dals/protein-dal.js`, so removed the comment, fixed multiline string in the file, and ran lint and test with all tests passing.

**Comment by ceciliazaragoza** [comment]
> I also found repetitive code in scripts for `generate_network.py`, `generate_new_network_version.py` and `generate_sgd_network_from_yeastract_network.py`
> 
> ![image](https://private-user-images.githubusercontent.com/108908370/298446489-006568c2-69ee-4f0b-b6bb-bbaf272e034d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Nzk3OTgsIm5iZiI6MTcwNTk3OTQ5OCwicGF0aCI6Ii8xMDg5MDgzNzAvMjk4NDQ2NDg5LTAwNjU2OGMyLTY5ZWUtNGYwYi1iNmJiLWJiYWYyNzJlMDM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMzExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTE5YWEyNzRjMTBmOTU4NWJkZTczNThhNjY0YTQ4M2RiZjFkOWY1MzM0MjU0NTJkMjg1ZDZmY2MwMzIwMmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nRDxwwp7xplPlZCP5lirbLKcJZDL9KOHYDA2peSmDbg)

A'Kaia and I are working on this issue that Maika brought up, and for the second comment shouldn't the print string be `print(f'Creating REGULATORS TO REGULATORS MATRIX\n')`?

**Comment by ceciliazaragoza** [comment]
A'Kaia and I worked on the issue that Maika suggested, and lint and test are all passing.

**Comment by ceciliazaragoza** [comment]
I also added the createMatrix method to `generate_new_network_version.py` and removed the redundancy in `if result != False`, changing to `if result`

**Comment by dondi** [comment]
@ceciliazaragoza will issue a PR to merge with `beta` for these changes. In addition, @kdahlquist pointed out that we need to reinstate the practice of doing QA on our pull requests in accordance with the https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist

So for this PR, @ceciliazaragoza will copy/paste the checklist on this wiki page on the pull request, and the team will work through the checklist together

If any checklist item regressions are found, the team will:
1. Check to see if the regression exists in production (v6.0.8) or beta (v7.0.8)
2. Check to see if an issue has already been reported for it (specific focus on the recent items entered by @kdahlquist)
3. Update the PR comment thread as needed so the team knows where an issue stands
4. Seek to fix the issue
5. Iterate on the checklist until, as far as we know, all items are addressed

For @nchun2, her work in GRNmap sets her up as the “import/export” specialist between GRNmap and GRNsight. She can focus on items that ensure smooth file-based data flow between the two systems. @kdahlquist will write a specific issue
