### ISSUE TITLE
Release v6.0.4 to production

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1005]
- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [x] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [x] the [feature JSON files](https://github.com/dondi/GRNsight-archive/tree/main/documents/developer_documents/testing_script_generator) file should be updated
    - [x] the new feature also needs to be added to the [Pull Request Checklist](https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist)
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
    - [x] Update Travis and Coveralls badges to reference the master branch
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [x] Update version numbers in _package.json_
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [x] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Refresh (pull) the `master` clone on _grnsight.cs.lmu.edu_
    - [x] Update the version number and modification date on `gh-pages`
    - [x] Update the About page with release notes (GitHub release item without issue numbers)
        - [x] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [x] Update modification date
    - [x] Add news item about the release to the News page
        - [x] Update modification date
        - [x] Link news item to the corresponding release notes in the About page
    - [x] Update Documentation page with any new features or updates to old features
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
    - [x] Update Travis and Coveralls badges to reference the beta branch
    - [x] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [x] Publish to _npm_ (`npm publish`)
    - [x] _npm_ requires all `.0`s in the semantic version
- [x] Update version number/other relevant information at current bioinformatics listing sites
    - [x] Elixir 
        - [x] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [x] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [x] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by kdahlquist** [comment]
We went through the checklist and verified that unchecked items have not been completed.

**Comment by dondi** [comment]
* @Onariaginosa to take point on release notes and new export features
* @Sarronnn to take point on client-side testing (focus on export section)
* @ntran18 and @ahmad00m to take point on documentation items (most likely after release notes are out)

**Comment by kdahlquist** [comment]
@Sarronnn needs to know how to generate and post the client-side testing document.  Look in the GRNsight archive repository.  The first line of the code should say how to run it. https://github.com/dondi/GRNsight-archive/tree/main/documents/developer_documents/testing_script_generator

**Comment by ahmad00m** [comment]
Updated  documentation based on the latest release notes.

**Comment by Sarronnn** [comment]
Generated and posted the client-side testing document: https://github.com/dondi/GRNsight-archive/blob/main/documents/developer_documents/testing_script_generator/GRNsightTestingDocument.pdf

**Comment by kdahlquist** [comment]
@Sarronnn is going to finish the feature JSON and pull request checklist.  @ahmad00m is going to finish the About and News webpages.

**Comment by ahmad00m** [comment]
@ahmad00m has updated the about page with release notes and finished the news items in the news page. Also, I checked the compatibility of GRNsight on Safari v16.2 and Chrome v109.0.5414.119 and it doesn't seem to have any issues. Though I have not yet updated compatibility notes on about page so others can check for it as well.

**Comment by Sarronnn** [comment]
- The feature JSON file has been updated
- The new feature is in the Pull Request Checklist
- Client-side features have been documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.

**Comment by dondi** [comment]
@Sarronnn can you please double-check that the updates are complete? We found the following items actually missing still, and there may be more:
* Load from database
* Export to image

**Comment by Sarronnn** [comment]
Do you mean updates to the Client Side Testing Document?

<img width="1008" alt="Screenshot 2023-03-28 at 11 06 13 PM" src="https://user-images.githubusercontent.com/89826597/228441307-41473cc3-9a34-4a4a-9759-66fb866a7fbc.png">
<img width="1021" alt="Screenshot 2023-03-28 at 11 07 35 PM" src="https://user-images.githubusercontent.com/89826597/228441541-c8ab291c-dcba-4494-a69c-2c558f73c17a.png">

**Comment by Sarronnn** [comment]
Ona walked Maika and I through the whole process, so the JSON files are now up to date.

**Comment by kdahlquist** [comment]
Closing.
