### ISSUE TITLE
Edges on the Right Side of the Nodes Being Drawn Differently Than The Rest

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#101]
When an edge is on the right side of the target node, it has a curve that is much more extreme than the other edges. In most of the edges, the curve from the source node to the target node is a smooth line when the nodes get close, as seen in the lines from GLN3 -> MGA2 and SMP1 -> MGA2:
![properpath](https://cloud.githubusercontent.com/assets/6444156/3683232/39be5cb0-12df-11e4-94cb-13a1de192eee.png)

However, on the opposite side, the lines become much more exaggerated. This makes equal centering on the right and left sides very difficult, and also causes cosmetic bugs. This can be seen in the same two edges below:
![curlypath](https://cloud.githubusercontent.com/assets/6444156/3683243/7aa5cd12-12df-11e4-9702-527ece1cc972.png)

I'm not sure what's causing it, but I can confirm that this bug is also present on the master copy of GRNsight.

**Comment by kdahlquist** [comment]
Offsets are different on different sides of the node.  Edge and blunt end are not meeting exactly.

**Comment by kdahlquist** [comment]
@NAnguiano is still looking for the source of the problem.  She's tried a bunch of stuff, but not everything yet so she will keep looking.

**Comment by dondi** [comment]
@NAnguiano has found the code that sets the initial value; @dondi suggests looking at the `tick` function to see how that value changes over time.

**Comment by NAnguiano** [comment]
This has been almost completely fixed. The difference between the distances of the top and left verses the bottom and right is now extremely small. 

Here is what the difference used to look like:
![grn_old_br](https://cloud.githubusercontent.com/assets/6444156/6136524/1f112704-b126-11e4-942f-264d6b47bd0b.png)
![grn_old_tl](https://cloud.githubusercontent.com/assets/6444156/6136525/1f1c67c2-b126-11e4-856e-178fd73f7fca.png)

Here is what it looks like now:
![grn_new_br](https://cloud.githubusercontent.com/assets/6444156/6136530/27e5873a-b126-11e4-919f-45c724541a33.png)
![grn_new_tl](https://cloud.githubusercontent.com/assets/6444156/6136531/27eeafcc-b126-11e4-8e51-0e5c911db2f8.png)

**Comment by dondi** [comment]
As a potential quick fix (but cancel if this has been tried before), maybe play with SVG line properties like miter limit and/or linejoin to see if the endpoint can be rendered more smoothly, thus mitigating the corner effect.

**Comment by NAnguiano** [comment]
The SVG line properties had been tried before and were not successful at fixing the issue. I fiddled around with the offsets on the largest repressor bars and it seemed to fix the problem. Let me know if any of you see any more bars sticking out on one side. I should hopefully be able to fix any of them by manually tinkering around with the offset values.

**Comment by dondi** [comment]
A little more tweaking needed when the nodes are close to each other, but otherwise a good step forward.

**Comment by NAnguiano** [comment]
I've tweaked more, and encountered a problem that I'm not sure how to fix. It seems that when the source node is to the left of and above/below the target node, the edge is supposed to be angled in the way that it appears below:
![grnsight_left](https://cloud.githubusercontent.com/assets/6444156/6356247/ee6e610c-bc10-11e4-8bdd-eb70d9d4359a.png)
And when the node is to the right of and anove/below the target node, the edge is supposed to be angled this way:
![grnsight_right](https://cloud.githubusercontent.com/assets/6444156/6356248/ef53852a-bc10-11e4-9754-15a0854b276e.png)

But sometimes, if you drag the node directly above the node, drag it down, and then drag to one side, the curved edge won't switch directions, causing visual errors. 
![grnsight_incorrect_side](https://cloud.githubusercontent.com/assets/6444156/6356276/302e5156-bc11-11e4-9c10-287bcbdf5dbd.png)
This also happens on the arrowheads. 
![grnsight_flop_arrow](https://cloud.githubusercontent.com/assets/6444156/6356377/cbf008aa-bc11-11e4-8f83-89f10db66ace.png)

Moving the node around a bit more causes the edge to snap to the correct place, which fixes the problem:
![grnsight_correctside](https://cloud.githubusercontent.com/assets/6444156/6356281/3ea605bc-bc11-11e4-802b-d36ee7158c31.png)

However, I'm not sure how to fix that issue. I've also had this happen a few times: 
![grnsight_bottomwrong](https://cloud.githubusercontent.com/assets/6444156/6356389/e3850d3a-bc11-11e4-800c-437f419925f3.png)

I think this has to do with how the edges are being drawn, but I'm not fully sure what to do about it.

**Comment by dondi** [comment]
We will try solve this by making the edges straight when the nodes fall within a certain distance.

**Comment by dondi** [comment]
A proposed straightening approach can be reviewed and we can decide the threshold at which the curve becomes straight.

**Comment by dondi** [comment]
Suggested use case for trying out thresholds is Demo 4.

**Comment by dondi** [comment]
Current notes: (a) ensure that horizontal and vertical distances look the same, (b) vertically center horizontal edges, (c) base distance on distance from edge of nodes, not centers (corollary to (a)), (d) experiment with gradual straightening rather than snap-to-straight.

And also the threshold for straightening looks OK.

**Comment by dondi** [comment]
An update has been posted to Beta; most of the issues were addressed except for (b) (i.e., vertical centering still problematic when the edge gets sufficiently thick).

**Comment by kdahlquist** [comment]
Current behavior approved.
