### ISSUE TITLE
Travis has imposed usage limit need solution

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1010]
@dondi will investigate Travis and figure out what to do about it.

**Comment by dondi** [comment]
I found their docs on usage (https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source) and have contacted their support team to request open source credits. Still waiting to hear back

**Comment by kdahlquist** [comment]
By default, no longer a free account in Travis, only trial account.  We were a trial account, but used up our credits.  If you are Open Source, e-mail them, which @dondi  did.  He'll keep us updated.

**Comment by dondi** [comment]
Here’s part of the response:

> We offer an Open Source Subscription for free to non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
>  
> * You are a project lead or regular committer (latest commit in the last month)
> * Project must be at least 3 months old and is in active development (with regular commits and activity)
> * Project meets the [OSD](https://opensource.org/docs/osd) specification
> * Project must not be an expressly commercial project
> * Project can not provide commercial services or distribute paid versions of the software
>  
> Does this sound like you and your project? We'd be very happy to support you!

So it looks like I need to tell them “yes” and we’ll see what they say

**Comment by dondi** [comment]
We have been given a new batch of 25,000 credits! We actually had a –30 balance previously so the current tally is 24,970

The procedure, I was told, is to ask again whenever we run out. Our original allocation of 35,000 credits was granted on 2020-11-20 and lasted around two years. So we’ll see. Closing this for now
