### ISSUE TITLE
Bug review of v6.0.4

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1012]
To start the semester, let’s:
* Do a wave of testing on the latest production release to identify bugs
* Review existing GitHub issues to identify pre-existing priority bugs (e.g., the “shrinking graph” bug, etc.)
* Log any new issues
* Prioritize/tag any existing issues that require attention sooner rather than later

**Comment by Sarronnn** [comment]
Update on these bugs: 
- Issue #980 , the bug is not replicable on my end so we should be good.
- Issue #945, bug is replicable on Beta v6.0.3, but not on my branch

**Comment by Onariaginosa** [comment]
New bug found #1018

**Comment by dondi** [comment]
@Sarronnn will focus on this for March 22–29

**Comment by dondi** [comment]
Include Lambda implementation in the scope of this issue

**Comment by Sarronnn** [comment]
**Two new possible bugs:**
<img width="724" alt="Screenshot 2023-03-28 at 10 49 31 PM" src="https://user-images.githubusercontent.com/89826597/228438572-4909eb8f-5c95-4753-9e00-34c7ffc90276.png">
<img width="713" alt="Screenshot 2023-03-28 at 10 50 55 PM" src="https://user-images.githubusercontent.com/89826597/228438839-a0099914-af24-4c88-8a5e-4119a1a80ced.png">

**Comment by Sarronnn** [comment]
These are now distinct issues: #1033 and #1034

**Comment by kdahlquist** [comment]
Closing because issues reported here have their own issues now.
