### ISSUE TITLE
update Client Side Testing Document wiki to be compatible with multiple featureList.json files

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1017]
Scan the wiki to make sure that it's clear that there is no longer a single `featureList.json` file, but a family of files.  Also make it clear that this is living in the grnsight-archive.

https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document

**Comment by ntran18** [comment]
I took a look and changed the Wiki page from a single `featureList.json` file to `[GRNsight-archives]Features.json`. It's clear that this is living in the grnsight-archive
