### ISSUE TITLE
Investigate Yeastmine for information on Protein - Protein Interactions Mode

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#1020]
I went on SGD/YeastMine to see if there was anything related to querying for protein protein interactions. In the proteins tab you could query for all proteins. The following screenshot captures all of the information you can receive for each protein result.

![image](https://user-images.githubusercontent.com/21343072/219078447-5b196978-c19f-48b3-8180-65f38d5faaf9.png)

In the interactions tab, I found that you can query based on complex and it returns the complex participants. You can restrict the query such that you return complexes that contain a given protein. The following screenshot captures all of the information you can recieve for each complex -- participant pairing (The database seems to be stored as a many to many)

![image](https://user-images.githubusercontent.com/21343072/219080216-676a3fab-bff0-4c72-844d-1e2d5605341b.png)
![image](https://user-images.githubusercontent.com/21343072/219080305-dc82d044-56a5-44a3-a799-f7492d924b46.png)

My preliminary inclination is to store the protein data in the following schema
![image](https://user-images.githubusercontent.com/21343072/219086087-00332708-b347-43f7-821d-eeb0c6c7a4d0.png)

Is there anything that should be revised?

Side note: I didn't know the language of protein - protein interactions, so I read [this article](https://www.pnas.org/doi/epdf/10.1073/pnas.93.1.13) for preliminary knowledge.

**Comment by kdahlquist** [comment]
@Onariaginosa, we are actually not going to use the "complex" annotations.  There is a different query for "physical interactions" that we will use. See this example
https://yeastmine.yeastgenome.org/yeastmine/results.do?trail=%257Cquery

**Comment by kdahlquist** [comment]
Retain "Gene" and "Protein" tables.  But instead of "Complex" and "Protein-Complex" we will have a table called "Physical-Interactions"

Physical Interactions table would be two-column table with protein1 and protein2

**Comment by kdahlquist** [comment]
Change schema names to be more informative:
- Gene Regulatory Network schema
- Gene Expression schema
- Protein-Protein Interactions schema
- GRNSettings schema

**Comment by Onariaginosa** [comment]
Here is the revised schema:
![image](https://user-images.githubusercontent.com/21343072/219141987-6a191e44-4445-4611-8934-a08baee9fd2e.png)

**Comment by kdahlquist** [comment]
This looks fine.  I think if you are doing the physical interactions query, you won't get additional information about the protein, like length, molecular weight, or P1 (which I don't know what that is anyway).

We could consider bringing down the other physical interactions data that comes with the query such as:

- Interaction Detection Methods Identifier
- Experiment Name

and put them in the "Physical_Interactions" table so that we preserve the meta data about the interaction.

**Comment by Onariaginosa** [comment]
We get the length, molecular weight, etc. when we get all proteins using the proteins query. Should I still keep them? Attached is the new proposed schema

![image](https://user-images.githubusercontent.com/21343072/219148483-677a15e1-8b22-4fba-845f-db2930e48e32.png)

**Comment by kdahlquist** [comment]
Go ahead and keep the data.

@Onariaginosa has created the schema, it loads properly, and she is working on getting the data from Yeastmine.

After, shift over to working on the controls, and DAL.

Working on changing names from "Spring 2022" to better names.  Wants to deploy during Spring Break.

**Comment by Onariaginosa** [comment]
Progress Report: I renamed the schemas as requested. I also created the generator scripts for the protein interactions database. Note: It takes approximately and hour and 45 minutes (give or take) to get all of the physical interactions between the proteins . . . . . . Will focus on the loader scripts and DAL next before working on the UI.

**Comment by kdahlquist** [comment]
Add source to schema so that generate network modal can act the same as the grn network generator.
