### ISSUE TITLE
LMU URS 2023

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1021]
Abstracts are due 2/19/23

**Comment by kdahlquist** [comment]
- 250 words
- @ahmad00m , @Sarronnn , and @ntran18 will compose the abstract on the wiki by Thursday and @kdahlquist and @dondi will review; submit by Friday
- https://academics.lmu.edu/orca/symposium/application/
- Focus on new features in v6.0

**Comment by ahmad00m** [comment]
Here is the link to the [abstract](https://github.com/dondi/GRNsight/wiki/2023-Undergraduate-Research-Symposium-Abstract,-Ahmad-Mersaghian,-Sarron-Tadesse,-and-Mika-Tran) in wiki.

**Comment by kdahlquist** [comment]
@ntran18, how do you want your name to appear on the abstract?  "Maika Tran" or "Ngan N. Tran" ?

**Comment by kdahlquist** [comment]
I have reviewed and edited the title and abstract.  @dondi , will you please take a look?  Pending @dondi's approval and @ntran18's reply as to how she wants her name to appear, it is OK to submit.

**Comment by dondi** [comment]
I have reviewed it and made some minor updates (mainly the third-to-last sentence). Ready to go 📤

**Comment by dondi** [comment]
Oh except for how Maika @ntran18 would like to list her name

**Comment by ntran18** [comment]
i would prefer my name as Ngan N. Tran to appear on the abstract. Thanks for asking me this!

**Comment by ntran18** [comment]
I edited the abstract for my name!

**Comment by dondi** [comment]
Great! I edited the title to match. The new abstract URL is now: https://github.com/dondi/GRNsight/wiki/2023-Undergraduate-Research-Symposium-Abstract,-Ahmad-Mersaghian,-Sarron-Tadesse,-and-Ngan-N.-Tran

**Comment by kdahlquist** [comment]
I added @ahmad00m's and @Sarronnn's middle initials to the page title as well for consistency.  New URL: https://github.com/dondi/GRNsight/wiki/2023-Undergraduate-Research-Symposium-Abstract,-Ahmad-R.-Mersaghian,-Sarron-A.-Tadesse,-and-Ngan-N.-Tran

@ahmad00m, you should go ahead and submit on behalf of the group.

**Comment by ahmad00m** [comment]
Sounds good, Will do!

**Comment by ahmad00m** [comment]
The abstract is submitted! 
<img width="737" alt="Screenshot 2023-02-17 at 2 51 17 PM" src="https://user-images.githubusercontent.com/75926755/219812312-0a89390f-af8a-4707-967b-834676981cc4.png">

**Comment by kdahlquist** [comment]
Draft of poster due by March 8 for review and possible edits.  Aim to print early in the week of the 13th.

**Comment by ahmad00m** [comment]
Here is the draft of our poster [Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx](https://github.com/dondi/GRNsight/files/10923263/Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx)

**Comment by kdahlquist** [comment]
My first impression of the poster is that it needs a bigger picture overview to align with the new title (which you need to put on the poster!)  For example, I think you should create an updated figure that shows the interactions with the databases, updating the one form the original GRNsight paper:
![image](https://user-images.githubusercontent.com/6463867/223797779-ba1efc08-395d-40a9-b222-70a53bb50d55.png)

I'm also linking to the poster I made for the Yeast Genetics Conference I went to last August.  I updated the figure that shows the main GRNsight interface, which you should use.  Also, see the "New workflow" figure I made that shows the importance of why we need the generate GRN from SGD and export features.
[Dahlquist_Yeast-Genetics_2022-2.pptx](https://github.com/dondi/GRNsight/files/10923657/Dahlquist_Yeast-Genetics_2022-2.pptx)

**Comment by dondi** [comment]
Action item breakdown:
- Updated architecture diagram to integrate database and contents
    - Depending on space: convey that the server and the database are in “the cloud”
- Integrate top-level workflow diagram from Yeast Genetics poster
- Ensure that user interface diagram is updated/tailored to the poster content
- Update poster layout for the content; move bugs and fixes down

**Comment by ahmad00m** [comment]
Here is the revised version of our poster presentation. Looking forward for your feedback.
[Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx](https://github.com/dondi/GRNsight/files/10953563/Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx)

**Comment by ahmad00m** [comment]
I forgot to mention that we need to change our availability numbers for this current version.

**Comment by kdahlquist** [comment]
[Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx](https://github.com/dondi/GRNsight/files/10975167/Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx)

I made adjustments to some language and formatting.  It is ready for @dondi's review.

**Comment by kdahlquist** [comment]
The section on updated export function just repeats in words what the previous two panels are showing in figures.  There is room there to show the database schemas and provide more technical information about the architecture/database.

**Comment by ahmad00m** [comment]
I was trying to replace updated export function of the poster with this image but it would look extremely small. I could add snippets of what the expression and network database look like on our systems with no bullet points and explain that in stead! 
![Database ER diagram (crow's foot)](https://user-images.githubusercontent.com/75926755/225190314-9756e5e3-12b3-4aad-ad22-a1531a9b6670.jpeg)

I could use these snippets if that's preferable!
<img width="468" alt="pic 2" src="https://user-images.githubusercontent.com/75926755/225190933-deb7c8e8-9421-47fb-84c4-88bfdd7d1fc7.png">
<img width="468" alt="Picture1" src="https://user-images.githubusercontent.com/75926755/225190939-08078da5-e23f-4173-8997-dbdff73a77c3.png">

**Comment by kdahlquist** [comment]
The only thing in the improvements and bug fixes that is really a new feature is the DAL.  You could combine the two sections of "export" and "new features/bug fixes" to give you some more real estate to show both the schema and code snippets.  The gene name thing is interesting, but would need more explanation; the schema and sample tables has more "meat" to them.

**Comment by ahmad00m** [comment]
I rearranged and removed some of the irrelevant bullets as well as incorporated the fall 2021 schema. Added a figure of schemas present currently as well as showing where the expression and network data are present on the schema and gave a visual of how the data looks like. Also, combined the two sections as requested.
[Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx](https://github.com/dondi/GRNsight/files/10976106/Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx)

**Comment by dondi** [comment]
Poster overall looks good. The tech details are accurate and the architecture diagram has been updated correctly (though the edges look a little…wobbly? 😅)

Content-wise, the only thing I can think of is, do we want to mention that this is all hosted on Amazon Web Services? Not such a huge factoid before but now that we also have a database running “in the cloud,” that mention might have more impact. It can potentially be stated somewhere in the lower-left box since that’s the one focused on architecture

**Comment by ahmad00m** [comment]
[Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx](https://github.com/dondi/GRNsight/files/10983527/Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx)

**Comment by kdahlquist** [comment]
This is the version I submitted for printing.
[Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx](https://github.com/dondi/GRNsight/files/10983824/Mersaghian_Tadesse_Tran_LMU_SYMPOSIUM_2023.pptx)

**Comment by ahmad00m** [comment]
Poster is now uploaded to GRNsight-archives for record keeping.

**Comment by kdahlquist** [comment]
Poster is printed and ready for pick-up in FEA 101 (admin office).
