### ISSUE TITLE
Edit the information in the menu bar to say GRN source

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1023]
Upon review we want to edit the information in the menu bar that appears when a user loads a network.
- Keep the demo names the same
- Keep it the same if the user uploads their own Excel workbook (display the filename)
- But when generating network from the database, it should appear: "GRN (Yeastmine - SGD 2022-0307; 3 genes, 0 edges)" for example.

**Comment by Onariaginosa** [comment]
Completed on my branch. PR will be released shortly

**Comment by kdahlquist** [comment]
Implemented in Beta 6.0.7
