### ISSUE TITLE
Bug: None of the edges are displaying

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#1024]
I noticed this on my local branch, the production master branch and the production beta branch that there were no edges being displayed at all. I tested this on networks with edges I knew to exist for sure, and no edges appeared. I fixed this on my branch and a pr will be issued shortly, as this is an urgent and (somewhat) breaking bug, However, please note that my branch is updated to use more than a single network source, and the renamed schemas so this should be pulled with caution.

**Comment by kdahlquist** [comment]
verified fixed on 6.0.7
