### ISSUE TITLE
GRNsight Website certificate is expired

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#1027]
We can't access GRNsight because the website certificate expired on March 16th. I tried on both Chrome and Firefox and neither of them load. Chrome just says that GRNsight can't be accessed, but Firefox gave me the actual error. Sadly, there is no button to ignore the warning on either.
![image](https://user-images.githubusercontent.com/21343072/226962021-30278899-2768-4709-87d0-53647d12ed6c.png)
![image](https://user-images.githubusercontent.com/21343072/226962711-468f26fc-7dd9-4464-9c16-eb0279cbc117.png)

**Comment by kdahlquist** [comment]
Masao fixed this!
