### ISSUE TITLE
Change names for environment variables pertaining to the database

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#1030]
We should rename the server environment variables `EXPRESSION_DB_USERNAME` and `EXPRESSION_DB_PASSWORD` to something more generic like `DB_USERNAME` and `DB_PASSWORD` because our database contains more than just expression data now.

**Comment by kdahlquist** [comment]
Elevating the priority of this issue to see if it is an "easy" fix.

**Comment by ntran18** [comment]
The variables are saved in .env file but I don't know where the file is.

**Comment by dondi** [comment]
Ah yes that’s true—the _.env_ file is actually not meant to be committed in case it contains secrets. (notice that it is in _.gitignore_)

I can look for mine and can send you a copy by other means

**Comment by ntran18** [comment]
Yes! I don't expect I have access to that file 😅. Can you just help me to fix the variable names? And I can fix it in code. 

EXPRESSION_DB_USERNAME -> DB_USERNAME
EXPRESSION_DB_PASSWORD -> DB_PASSWORD

We can confirm if this is a good name to change, then I will make a PR with the name change. When @dondi merge, @dondi  can change the variable names in `.env` file

**Comment by dondi** [comment]
Sounds like a plan! 👌🏽
