### ISSUE TITLE
Can only change dataset from bottom option, not top

### ISSUE THREAD

**Issue by Sarronnn** [dondi/GRNsight#1033]
<img width="703" alt="Screenshot 2023-04-11 at 11 38 28 PM" src="https://user-images.githubusercontent.com/89826597/231372175-72a4515d-9eac-4927-811d-093146ac321e.png">
<img width="703" alt="Screenshot 2023-04-11 at 11 39 24 PM" src="https://user-images.githubusercontent.com/89826597/231372678-a78614a9-5c42-4e72-ad7e-8e1aec3b41f1.png">

**Comment by kdahlquist** [comment]
This still has some problems on Beta 7.0.2
- If I select the top and bottom datasets from the side panel, the changes are not reflected in the top menu.  It does weird things
    - If I select the top dataset first from the side panel, then the right top dataset is reflected in the menu, but not the bottom dataset.
    - If I select the bottom dataset first from the side panel, then neither the top dataset or bottom dataset are checked off in the menu.
- Strange things happen when selecting datasets from the top menu.

**Comment by dondi** [comment]
Fundamentally, the core issue is that the selected dataset should be centralized to an internal state value: whenever any control or UI element changes this value, that change should lead to the same code regardless of the source. Doing so will ensure that the internal behavior is always the same independent of whether the change was made on the sidebar or the menu

**Comment by dondi** [comment]
@ntran18 as a PR for this and that is what the “review requested” tag indicates; however she documents that a subsequent bug appears which seems to be more related to the dataset than the UI

@ntran18 will extract this as a separate issue, likely to be addressed after this one is merged into `beta`

**Comment by dondi** [comment]
The UI-level bug appears to be fixed but the fix is disrupted by a new issue that appears to occur at the data level, especially for expression data sets that come from the database and are not read from the network directly. Will consider this item as closed but @ntran18 will write up and investigate the missing data portion as a new issue

The new issue can reference this one in case we need to review how it was discovered
