### ISSUE TITLE
Restrict Graph to Viewport Bug

### ISSUE THREAD

**Issue by Sarronnn** [dondi/GRNsight#1034]
<img width="725" alt="Screenshot 2023-04-11 at 11 42 46 PM" src="https://user-images.githubusercontent.com/89826597/231373078-2cd0920b-c042-4fb7-8cc7-8f4f2d840e57.png">

**Comment by Sarronnn** [comment]
<img width="1434" alt="Screenshot 2023-04-11 at 11 49 32 PM" src="https://user-images.githubusercontent.com/89826597/231374610-95eb9a23-ef39-4a39-9cf9-263a1fdaba0e.png">
-Same error as #945 ; looks like the root cause is the specific dependency versions that are installed when running a version of Node that is too old. But I want to double check with Dondi

**Comment by dondi** [comment]
Reproduction confirmed during meeting; @nchun2 will isolate the bug further and will post a comment detailing how it can be reproduced:
- Meeting reproduction was done on production; need to check if this also happens in beta
- Try other variations:
    - Loading demo from side panel
    - Loading network from database via menu/side-panel
    - Loading network from file via menu/side-panel
- When isolation comment is complete, @nchun2 can reassign to @ntran18

**Comment by nchun2** [comment]
The bug also occurs in beta when the "restrict graph to viewport" function is selected from the top menu, but not from the side menu. Occurs in both production and beta when the network is loaded from a database on either the top menu or the side menu. It seems that the bug occurs whenever the view function is selected from the top menu.

**Comment by dondi** [comment]
Great! I’m adding @ntran18 to this bug but will keep @nchun2 for now in case some clarification is needed for reproducing the bug

**Comment by ntran18** [comment]
The main problem with this is originally `Restrict Graph to Viewport` in the top menu has a class called "viewportOption", and whenever this class is change, it will update `grnState.viewportSize`. However, `Restrict Graph to Viewport` is not a viewport size, so there is no constant for that, and when passed to `grnState.viewportSize`, it is a null value, and the graph keeps changing the size.

**Comment by kdahlquist** [comment]
Confirmed that this is fixed in beta 7.0.2 on Firefox
