### ISSUE TITLE
Scheduling GRNsight meeting for Fall 2023

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1042]
It's time to schedule the weekly GRNsight meetings for the Fall. Besides your course schedule (which we can access on PROWL), please add a comment to this issue with other restrictions we need to schedule around for the fall.  We are aiming to have a 1-hour meeting.

**Comment by kdahlquist** [comment]
Maybe Wednesdays 3:45-4:45 would work?

**Comment by dondi** [comment]
I have sent an email to everyone listing possibilities based on what I know of everyone’s class schedules; please check and respond when you get the chance, thanks!

**Comment by dondi** [comment]
Weekly meeting schedule settled via email
