### ISSUE TITLE
Search (magnifying glass) button is too small in Load from Database modal

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1050]
The Search (magnifying glass) button is too small in Load from Database modal.  See screenshot below:

![image](https://github.com/dondi/GRNsight/assets/6463867/b49edcdc-b639-48a6-82c8-200ad0749627)

**Comment by kdahlquist** [comment]
Assigning this priority 0 for @ntran18

**Comment by dondi** [comment]
Deployed as beta 7.0.6; upon review we noticed that the border was missing. In addition we were able to track down the specific regression that occurred from `master`, which is that the `.glyphicon` style rule was changed. @ntran18’s PR made a different set of changes

@ntran18 will compare the `master` CSS with the new `beta` to see whether we can restore the CSS more directly

**Comment by kdahlquist** [comment]
confirmed fixed in beta 7.0.7
