### ISSUE TITLE
Deeper integration of distinct network types

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1061]
The introduction of protein-protein networks has triggered deeper implications on how GRNsight’s features should manifest. This issue seeks to capture the overall picture and may eventually be broken up into sub-issues:
* Switching network modes: the current implementation of network mode switching affects only the way the network is rendered and not its data:
    * Node names should change: Can be done (mostly) via text transform
    * Connections should change: Pull from database; will need a modal/alert that existing edge data will be replaced (particularly if the edges came from the user via file upload)
        * What about reverting?  if both modes came from the database, one could toggle between them, but if a user uploaded a network and then changed it, would they just then need to reupload their file? (yes?)
    * Expression data remains parallel and can be retained between mode changes
* Demos for protein-protein networks
* Other issues may continue to emerge as we think through the feature more deeply

**Comment by kdahlquist** [comment]
Going through the features to think about which need to be updated for PPI (protein-protein interaction) networks.

Network menu
- need demo file(s) for PPI networks
- Open File: 
    - only .xlsx and .sif should be allowed for PPI, not .graphml
    - check .sif format for PPI
- Network Mode
    - menu should be available when GRNsight first loads
    - then it would affect which file types are allowed in the Open File menu and which default network type comes up in the Load from Database modal.

Layout is not affected

Node
- Node coloring can be left as is, with a disclaimer that it is displaying gene expression (mRNA-level data) and not protein-level data

**Comment by dondi** [comment]
We reviewed this at the meeting, and in general these do look like they don’t require a React port to do; however the number of items may still exceed the time remaining in the semester. Maybe we target a final version early next semester?

One small note: instead of having the Network Mode lock in which files can be opened, would it be possible for the open-file command itself to determine the Network Mode based on the selected file? e.g., if the user picks a GraphML file, then we switch to GRN network mode for sure. Also if opening a demo, we can switch the Network Mode automatically at that time

**Comment by kdahlquist** [comment]
With regard to the Network mode, we would need to look at all possible scenarios to make sure that they will work as expected.  GraphML is straightforward, but .sif and .xlsx might be a little more difficult to "discover" from the file type.

**Comment by dondi** [comment]
The items on this issue have been broken out #1065, #1066, #1067, #1068, #1069, and #1070 so this issue in itself can be closed.
