### ISSUE TITLE
Update local setups to include grnsettings

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1062]
With the merging of #992 to `beta`, the GRNsight app now expects to have a `grnsettings` table and so local setups need to have this as well before merging/pulling the latest `beta`. Documentation can be found here:

https://github.com/dondi/GRNsight/tree/beta/database/grnsettings-database

**Comment by kdahlquist** [comment]
- @nchun2 needs to set up her database with GRNsettings
- needs to be some tweaks to the documentation

**Comment by ntran18** [comment]
Some modification needs to be included in the documentation. These are modifications when running with M1 Mac. 

1. Indicate this is one command with examples
![image](https://github.com/dondi/GRNsight/assets/108908370/6cb25a61-e94a-4eb6-9849-b4b7d10d0566)

2. Command to login to the database (alternative command if the command provided got issue)
`psql <address to database>`

3. Insert the new database name
`INSERT INTO grnsettings(expression_dataset) VALUES ('the new default database name');`

Need to know what is the default database name: Currently is 'dahlquist_2018'

**Comment by dondi** [comment]
Looks good; for the `-f schema.sql` command, we may as well move the `-f schema.sql` to right after `psql` because Windows requires it there; macOS also accepts it there
```
psql -f schema.sql postgresql://localhost/postgres
```
and
```
psql -f schema.sql -U postgres <address to database>
```

**Comment by dondi** [comment]
Final revisions were made to the documentation and the settings database has now been successfully set up for both @ntran18 and @nchun2
