### ISSUE TITLE
Adjust Open File for varying network modes (GRN/PPI)

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1066]
The Open File functionality needs to support PPIs more “natively” than they do now. Specifically:
* only .xlsx and .sif should be allowed for PPI, not .graphml
* check .sif format for PPI

In addition, instead of having the Network Mode lock in which files can be opened, would it be possible for the open-file command itself to determine the Network Mode based on the selected file? e.g., if the user picks a GraphML file, then we switch to GRN network mode for sure. Also if opening a demo, we can switch the Network Mode automatically at that time

For .sif files, an edge label of `pp` indicates a PPI. Thus, “pre-reading” a .sif can also set Network Mode upon opening

**Comment by ntran18** [comment]
https://github.com/user-attachments/assets/ce5bb60d-a826-4279-9349-046f8410355a

I believe PR #1085 already fix this issue. This video didn't test the excel files.

**Comment by dondi** [comment]
Verified on v7.1.11 beta during 12/4 meeting
