### ISSUE TITLE
Node coloring does not support protein-level expression data

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1068]
Node coloring is currently completely gene expression-centric. For now, the immediate task is to:
* Include a disclaimer that we are displaying gene expression (mRNA-level data) and not protein-level data (separated out into #1071)

Eventually, we can explore to prospect of doing node coloring based on protein-level data

**Comment by dondi** [comment]
@ntran18 notes that this might be a matter of matching up node names when showing a PPI network because `p` is appended to the end and capitalization is different

**Comment by ntran18** [comment]
I'm able to make the node coloring appear for PPI if the user loads it from the database. However, the demos still have issue with displaying the node coloring.

**Comment by dondi** [comment]
Confirmed in `beta`

**Comment by kdahlquist** [comment]
confirmed in beta 7.1.7
