### ISSUE TITLE
Can the Open dialog box restrict to filetypes of .xlsx?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#107]
I had a quick thought--can the open dialog box restrict the choice of files to ones of type .xlsx only?  This would be another way of enforcing choice of the correct filetype.

**Comment by NAnguiano** [comment]
The firefox but was fixed. Firefox now only allows for xlsx files to be uploaded. This fixes the need for the unit test in #139

**Comment by anuvarsh** [comment]
I was able to replicate the fix that @NAnguiano mentioned. Since Chrome does not allow wrong file types either, this issue is resolved. Closing.
