### ISSUE TITLE
Meeting time for Spring 2024 semester

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1076]
Need to set a meeting time for Spring 2024 semester.

Dr. Dahlquist is not available
- MW 11:50-1:30
- T 12:00-1:30
- TR 1:45-3:00
- F 3:00-4:00

**Comment by dondi** [comment]
@ntran18 @nchun2 @ceciliazaragoza if you have other restrictions beyond your class schedules, please let me know so that I can factor those into the possible time slots for our weekly meeting; thanks!

(I’ll eventually include @akaiap here when she confirms her invite to join)

**Comment by nchun2** [comment]
In addition to my classes, I'm unavailable Monday and Wednesday from 1:30 to 4:30, Tuesday from 11:30 to 1:30, and Friday from 1:30 to 3:30.

**Comment by dondi** [comment]
Greetings—after tallying up everyone’s schedules (at least what I can access), it’s looking like we have the following possibilities:
- Tuesdays between 9am and 11am (so any single hour within that window)
- Thursdays between 12pm and 1:30pm—except for me every other week (@kdahlquist knows what that is 😁)
- Fridays between 8am and 9:30am 

I can share the overall tally under separate cover. Any thoughts?

**Comment by ceciliazaragoza** [comment]
All the times work for me, except Thursdays I am available after 12:30pm and Friday afternoons I am busy from 3pm-5pm.

**Comment by ntran18** [comment]
All the times work for me. However, I would prefer Tuesday 10 - 11 am, since everyone can join every week and it's not early in the morning.

**Comment by kdahlquist** [comment]
I concur with @ntran18, Tuesdays 10-11 sounds good.

**Comment by dondi** [comment]
Sounds good, looks like we have a frontrunner! Tuesdays 10–11am

**Comment by akaiap** [comment]
Yes! That works for me as well!

**Comment by dondi** [comment]
Looks like we’re going with Tuesdays 10–11am then! Which means our first meeting will be tomorrow January 9 at 10am. I’ll send out the Zoom link under separate cover
