### ISSUE TITLE
Problems opening .sif and .graphml files

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1079]
I'm having an intermittent problem opening .sif files in beta 7.0.8.  Sometimes I can open one and sometimes it won't load after selecting it in the open dialog.  After that the open button on the left panel also becomes unresponsive.  I'm using latest version of Firefox as my browser.

**Comment by kdahlquist** [comment]
It's not intermittent.  I discovered that it is definitely nonfunctional in beta 7.0.8, but I can open the .sif file in production 6.0.7.  The production functionality has a different problem that I will report in a different issue.  I think that this will block our ability to release 7.0.8 to production because it is a major regression of functionality.

**Comment by kdahlquist** [comment]
Tested a .graphml file and it also doesn't open in beta 7.0.8.  I zipped the graphml file because Github doesn't support its filetype.
[4-gene_4-edge_Manual-Cytoscape_test-naming.zip](https://github.com/dondi/GRNsight/files/14027535/4-gene_4-edge_Manual-Cytoscape_test-naming.zip)

**Comment by kdahlquist** [comment]
Note that .graphml files cannot contain PPI network information, so it will only be a GRN.

For unweighted sif, "pd" means it is a GRN. "pp" means it is a PPI.

For weighted sif, then it can only be GRN.

**Comment by dondi** [comment]
PR has been merged into `beta` but the merge might not have interacted well with the preceding merge. @ntran18 and possibly @ceciliazaragoza/@akaiap can help test the new version following the PR checklist

**Comment by ntran18** [comment]
I test the function locally and it works. @ceciliazaragoza also helped me to test it. I will talk to Dondi to know more about what the problem is.

**Comment by ntran18** [comment]
I tried to ssh to the server to stop it and rerun again. However, I wasn't able to stop it. My question is, is the beta currently running the latest version?

**Comment by dondi** [comment]
@ntran18 you can do a `git pull` while cd’ed into GRNsight-beta to make sure that it has the latest code

**Comment by ceciliazaragoza** [comment]
After taking a look at the server, it seems that there is an npm run start-dev process running on a deleted screen. We are unable to view the console logs from npm run start-dev on the current screen, and when we try running the NODE_ENV command, it says that the port is already in use.

**Comment by ntran18** [comment]
The code is updated, but I found an error in my code. For sif file, we have two workbookType - Weighted and Unweighted. I know if the import file have pp or pd, it determine the networkMode. How about if it's not either pp or pd, but is a value. It's a weighted workbook, but then what is the type?

**Comment by dondi** [comment]
If I recall correctly, the presence of weights implies that the graph is a GRN because PPIs don’t have weighted edges. We can verify this with @kdahlquist at our meeting

**Comment by kdahlquist** [comment]
Yes, the presence of weights means that it is a GRN.  We don't support weights for PPI yet.  If we ever do, then we'd need to come up with a way to distinguish weighed sifs.  But for the moment, they should be treated as weighted GRNs.

**Comment by ntran18** [comment]
This issue is fixed.

**Comment by kdahlquist** [comment]
I have confirmed that I can open three types of sif files, unweighted GRN, weighted GRN, and unweighted sif in beta 7.0.13
