### ISSUE TITLE
node coloring glitch when loading network from database

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1080]
Do this in beta 7.0.8:
- load a GRN from the database
- uncheck node coloring
- recheck nod coloring--the checkbox gets checked and the node coloring comes back in the display, but the options don't show on the side panel

This bug is also seen in production 6.0.7

**Comment by ceciliazaragoza** [comment]
I tried this on beta 7.0.13 and this behavior no longer seems to be occurring. However, I do see that this is an issue when checking and unchecking node coloring for PPIs. @kdahlquist Should I disable the ability to check or uncheck node coloring for PPIs?

**Comment by kdahlquist** [comment]
I think we should keep the ability to check/uncheck node coloring for PPIs.  People might have protein-expression data that they want to visualize or they might want to overlay the mRNA expression data on the PPI network.

**Comment by ceciliazaragoza** [comment]
I mentioned that the workbook was the issue during the meeting, but after looking over the code again, that was not the issue. There was a check for grnState.mode === NETWORK_PPI_MODE where grnState.nodeColoring.nodeColoringEnabled was set to false. I was able to get the Node Coloring Menu to show with PPIs, but should the options below "Enable Node Coloring" still display when viewing a PPI?
<img width="374" alt="image" src="https://github.com/dondi/GRNsight/assets/105010308/0f2d39de-ccbe-4339-90bb-46d7306302c8">

**Comment by kdahlquist** [comment]
Yes, those options should show because they enable the user to customize how the nodes are colored.

**Comment by dondi** [comment]
We clarified at the 4/23 meeting that we can go ahead and have the warning appear each time. A “don’t show this again” option might be something for the future

**Comment by ceciliazaragoza** [comment]
I am able to display a warning each time a PPI is displayed and node coloring is enabled. I am thinking of making the default behavior for grnState to enable node coloring, but is there any case where nodeColoring should be disabled where we wouldn't want to enable node coloring by default?

**Comment by kdahlquist** [comment]
Here are the use cases:
* User uploads their own PPI network with their own expression data in the workbook; node-coloring should be enabled.
* User uploads their own PPI network with no expression data in the workbook; node-coloring should default to disabled
* User loads a PPI network from the back-end database; node-coloring should default to disabled.  If they then enable node coloring to use our expression database, that is when the warning should pop up.

For the warning message, will you please replace the word "accurate" with "appropriate".  I don't think we need to have the sentence about checking the format of their workbook.  Presumably if they made their workbook with expression data, they meant to do that.

While I am thinking about it, the use cases for a GRN should be:
* User uploads their own GRN network with their own expression data in the workbook; node-coloring should be enabled.
* User uploads their own GRN network with no expression data in the workbook; node-coloring should default to disabled
* User loads a GRN network from the back-end database; node-coloring should default to disabled.  

I.e., if a user is not uploading their own data through a file upload, then they should be forced to enable node coloring.

**Comment by ceciliazaragoza** [comment]
Got it. There are cases that should default to disabled or enabled, but are there any cases where we completely disable the option to enable node coloring? Previously, the node coloring menu was grayed out when using PPIs, so is there another case where we would do the same?

**Comment by kdahlquist** [comment]
I don't think there is a case where it would be grayed out completely.

**Comment by dondi** [comment]
After reviewing the deployment on `beta`, it was noted that:
* The node coloring options only appear in the menu bar and not the sidebar after activation
* Node coloring data doesn’t appear when an expression dataset is selected (the warnings do show up as expected)

**Comment by dondi** [comment]
@ceciliazaragoza will also move the warning message outside of the network-opening routine so that it will only open at the point that node coloring is enabled. This will result in a distinct dialog from the one used in the PR, which is meant to catch data integrity issues with an uploaded workbook or network

**Comment by ntran18** [comment]
"The node coloring options only appear in the menu bar and not the sidebar after activation" issue. Is it the same issue I reported #1055?

**Comment by ceciliazaragoza** [comment]
I was able to make the sidebar and navbar display all node coloring options when node coloring enabled by adding a boolean var to grnState. I still have to investigate how to make node coloring display on PPI nodes.

**Comment by ntran18** [comment]
Confirmed this is fixed in beta

**Comment by dondi** [comment]
Confirmed from my end as well

**Comment by kdahlquist** [comment]
confirmed fixed in beta 7.1.7
