### ISSUE TITLE
node coloring top menu availability of options

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1081]
On the side panel of beta 7.0.8, if you uncheck node coloring, the options disappear from the panel and only reappear when the bock is checked again.  On the top menu, if you uncheck node coloring, the options are still there and clickable.  The behavior should be the same as the side panel.

**Comment by ceciliazaragoza** [comment]
Pull Request Checklist
- [ ] Travis C.I. build passes
- [ ] All five Demos look as expected when loaded
- [ ] Reload works as expected
- [ ] Loading file with Error brings up error modal, and it looks as expected
- [ ] Loading file with Warning brings up warnings modal
- [ ] Loading a network from the database looks as expected when loaded
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF, GraphML and Excel
- [ ] Graph can be exported to PNG, SVG and PDF
- [ ] Expression data and Additional Sheets can be exported to Excel
- [ ] Print works as expected
- [ ] Restrict graph to viewport works as expected (check/uncheck)
- [ ] Viewport Size Changing works as expected (small/medium/large/fit)
- [ ] Toggle between Grid Layout and Force Graph Layout works as expected
- [ ] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [ ] Enabling and disabling node coloring works as expected
- [ ] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [ ] Weighted graph loaded with the "Enable Edge Coloring" option checked appears as expected
- [ ] Hide/Show Weights works as expected (always/never/upon mouseover)
- [ ] Edge Weight Normalization Factor can be changed (set/reset)
- [ ] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [ ] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [ ] D-pad left/right/top/bottom/center works as expected
- [ ] Zoom slider changes number and has effect on graph (viewport and menu)
- [ ] Right click on a node opens gene page, page is populated with correct data
