### ISSUE TITLE
Checking restrict graph to viewport makes the D-pad and zoom slider on the viewport disappear

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1083]
Beta 7.0.8
- Checking restrict graph to viewport makes the D-pad and zoom slider on the viewport disappear. It seems to reappear if unchecked again.

**Comment by ceciliazaragoza** [comment]
@kdahlquist I was able to remove the D-pad disappearing issue. Should I also make it so that the user can use their cursor to navigate around the graph?

**Comment by kdahlquist** [comment]
Oh, I see that when "Restrict graph to viewport" is checked, you can no longer move the graph with your mouse.  We should still be able to move the graph around.  We should be able to move it as long as it doesn't go outside the viewport.

**Comment by dondi** [comment]
PR has been merged and deployed to `beta` and feedback has been provided on restrict-graph-to-viewport behavior; the notion is that the graph is the object itself and the d-pad + zoom control that object within the visible rectangle of the browser. @dondi and @ceciliazaragoza will workshop through the full suite of behaviors sometime this week

**Comment by dondi** [comment]
The remaining issue appears to be restriction under < 1 zoom; @dondi pointed out that this is mathematically the composition of matrices representing translation and scale; @ceciliazaragoza can experiment with that then also plan to meet with @dondi to look directly at how the thresholds are computed

**Comment by ceciliazaragoza** [comment]
I met with @dondi last week and he helped me understand how to calculate the borders of the viewport, so now stay within the viewport at all levels of zoom. Now working on clamping the nodes so that the nodes do not move outside of the viewport.

**Comment by ceciliazaragoza** [comment]
I met with @dondi last week to ensure that size of flexBox is being calculated correctly. When move graph to the left and left border is in view, the right bounding border is too wide, and when move graph to the right and the right border is in view the left bounding border is too wide. Will need to use the xTranslation and graphZoom to see when the left or right borders are in view. Also need to alter bounds so that clamp graph correctly when zoomed out less than 100%.

**Comment by dondi** [comment]
@ceciliazaragoza is homing in on the final values of the thresholds; somewhere along the way, we’ll plan a live demo with @kdahlquist to confirm/calibrate the expected behaviors of the restrict-to-viewport feature

**Comment by ceciliazaragoza** [comment]
Can manually change the size of the boundingRectangle, but cannot get it to match the borders of the viewport consistently. May consider restructuring graph so that bounding is jus the viewport svg itself

**Comment by kdahlquist** [comment]
Just make sure that when the restrict graph to viewport is unchecked that the graph would then not be bounded by the viewport.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 7.0.15!
