### ISSUE TITLE
Setup ssh keys to facilitate GRNsight deployments

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1088]
@ntran18 @ceciliazaragoza @akaiap should check in with @dondi sometime this week in order to get their ssh keys set up for GRNsight deployments. This will allow them to connect to the `beta` server and update `beta` as needed

**Comment by ceciliazaragoza** [comment]
@ntran18 and I went to Dondi's office hours today and set up our ssh keys so we can deploy to beta. Maika and I also learned how to kill the server 😅 and different server commands.

**Comment by akaiap** [comment]
Went to @dondi 's office hours last week and was able to set up the ssh key!
