### ISSUE TITLE
make LMU URS poster so it can be printed before the March 15 symposium

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1090]
Just found out today that LMU URS abstracts are due Monday, Feb. 5: https://academics.lmu.edu/orca/symposium/application/  @ntran18, will you lead the effort to compose the abstract on the wiki?  We will need to do this remotely because we are not meeting again until after it is due.  @nchun2, let's have you work on a separate abstract about your work on GRNmap.

I'm going to email ORCA about extending the deadline.  I only heard this announcement today.  It doesn't seem like it went out in any regular communication channels.  However, we should aim for Monday anyway.

**Comment by ntran18** [comment]
I can try doing that. When would be the best day I need to be done for review?

**Comment by kdahlquist** [comment]
Is it possible to have it done by Friday?

**Comment by ntran18** [comment]
I just finished the abstract in Wiki, please take a look: https://github.com/dondi/GRNsight/wiki/2024-Undergraduate-Research-Symposium-Abstract,-Ngoc-K.-Tran,-Cecilia-J.-Zaragoza,-and-A'Kaia-Phelps

**Comment by kdahlquist** [comment]
I got us an extension until Friday the 9th.  We can review the abstract in our meeting on Tuesday.  @nchun2, you can have until Tuesday if you need it for your abstract as well.  We'll review with @bengfitzpatrick on Wednesday at our meeting.

**Comment by dondi** [comment]
The abstract was reviewed at the 2/6 meeting and is near final form, but we’ll let it settle a little longer before sending the green light (GRNlight) to @ntran18

**Comment by ntran18** [comment]
The application is extended to Feb 15

**Comment by ntran18** [comment]
We can finalize the abstract on Tuesday and I will submit it

**Comment by kdahlquist** [comment]
@ntran18 has the abstract been submitted?

**Comment by ntran18** [comment]
I'm going to submit today. I just noticed I forgot to add @nchun2  in the abstract. Will she also present for GRNsight or just GRNmap?

**Comment by kdahlquist** [comment]
She has her own abstract for GRNmap, so she won't be included as an author on the GRNsight abstract.

**Comment by ntran18** [comment]
<img width="1333" alt="image" src="https://github.com/dondi/GRNsight/assets/108908370/31090105-92b8-4cad-b0c6-027058683328">

Which one should I choose for these questions?

**Comment by kdahlquist** [comment]
Say "no" to each.

**Comment by ntran18** [comment]
<img width="1439" alt="image" src="https://github.com/dondi/GRNsight/assets/108908370/70e37b85-76ea-43a3-9323-872fcd6223b6">

I submitted

**Comment by kdahlquist** [comment]
Yay!  I'm changing the title of this issue for making the poster.

**Comment by dondi** [comment]
Update plan for the UGRS 2024 poster:
- Center version of TAGC poster to become the left panel because it introduces GRNsight and its PPI changes
- New section will highlight changes made in late 2023
    * Directed vs. undirected edges
    * PPI demo graph
    * Import/export based on network type
    * Section about on-going development

**Comment by akaiap** [comment]
The first draft of the poster is done! -- waiting for review from @ceciliazaragoza and @ntran18 , then it will be ready to send to @kdahlquist and @dondi!

**Comment by akaiap** [comment]
After many revisions, the poster is completed! Here is the link! Please let me know anything I can edit, change and/or reposition! 
(Slide 2) [https://lmu0-my.sharepoint.com/:p:/g/personal/ntran18_lion_lmu_edu/ESeJpYC_krhHstzRBIdIOqkBE2ty6zAIJSM3OgElkLZqEQ?e=mXBslL]

**Comment by kdahlquist** [comment]
The poster is looking good!  Here are some suggestions for edits:
* In the title, "a Web" should go on the second line to make the line break fall on the change of ideas.
* In the title box, you don't need to provide the link to GRNmap since you are not talking about it in your poster.
* I know you took the first panel from my poster, which was being displayed at a professional conference where the audience already knew the difference between GRNs and PPI.  However, at the symposium, you will need to explain it to your audience.  I would make the PPI graph on the bottom of the first panel smaller so that you can include some background on the difference between a GRN and PPI.  I think I can provide a graphic for you to use.
* I'm going to post this comment now and add more edits in another comment.

**Comment by kdahlquist** [comment]
* Remove the period from the title at the top of the middle panel.
* In the acknowledgments section, you don't need to thank people that are authors on the poster.  Also, again, you don't need to mention GRNmap since you are not talking about it on the poster.  Instead, you can still thank Nikki.  A'Kaia and Cecilia need to thank their funding source.  "AP and CJZ would like to thank the HHMI STEM Research Learning Community for funding."
* Remove reference to GRNmap under availability section.
* Beta is now at 7.0.13, so that should be updated in the middle panel and also under the availability section.

**Comment by kdahlquist** [comment]
![155-VitaminDReceptor_VDRcryo](https://github.com/dondi/GRNsight/assets/6463867/b73c50a1-3b34-404f-891f-e4c4a3f83dd8)
https://pdb101.rcsb.org/motm/155
You can use this image to show a regulatory transcription factor bound to DNA in a GRN.  Be sure to cite the URL

**Comment by kdahlquist** [comment]
You can use this image for a protein-protein interaction:
https://pdb101.rcsb.org/motm/236
![236-Cyclin_and_Cyclindependent_Kinase-1fin](https://github.com/dondi/GRNsight/assets/6463867/4c152ed9-fc6c-4803-a6cd-11795ea194a7)

If you go to the website, there is also a link to download a high-resolution image.

**Comment by kdahlquist** [comment]
You will want to explain that in the GRN, the nodes represent both the regulatory transcription factor protein, and the gene that encodes it.  An arrow represents a regulatory transcription factor either activating (arrowhead, red color) or repressing (blunt end, blue color) the gene for another regulatory transcription factor.

A protein-protein physical interaction is when two proteins bind to each other.  Each node represents a protein, and each edge represents their binding interaction.

**Comment by kdahlquist** [comment]
![image](https://github.com/dondi/GRNsight/assets/6463867/cc4887e9-8661-40c2-a61e-e1a27f89cfcf)
Transcription Factors Control Gene Expression by Binding to Regulatory DNA Sequences
Activators increase gene expression
Repressors decrease gene expression
Transcription factors are themselves proteins that are encoded by genes

**Comment by kdahlquist** [comment]
In the future directions panel:
* delete "as shown above" for the first bullet point because the figures that was referring to are no longer part of the poster.
* "Focusing" should be "Focus"
* The next sentence should be its own bullet point, "Improve" instead of "Improving"
* I don't think the last two bullet points are necessary.  They are covered by the previous points, I think.

**Comment by kdahlquist** [comment]
At the bottom of the left panel, you can focus on the differences between the PPI and GRN (background). Then you can move the screenshot of the PPI up to the top of the middle panel, so it will be right next to the GRN example.  Then you don't need the additional screenshots that you have there.

Then you can reorganize the next information to describe how you would load a PPI:
* choose the new PPI demo file
* Upload a PPI (with the column A1 altered)
* Upload a SIF (simple interaction format)
* GraphML not available for PPI

For the comparison between the pd sif and pp sif, please redo the screenshot from Excel so that it has a white background.  It can also be smaller since it will end up printing quite large in the way you are showing it now.

**Comment by ceciliazaragoza** [comment]
> The poster is looking good! Here are some suggestions for edits:
> 
> * In the title, "a Web" should go on the second line to make the line break fall on the change of ideas.
> * In the title box, you don't need to provide the link to GRNmap since you are not talking about it in your poster.
> * I know you took the first panel from my poster, which was being displayed at a professional conference where the audience already knew the difference between GRNs and PPI.  However, at the symposium, you will need to explain it to your audience.  I would make the PPI graph on the bottom of the first panel smaller so that you can include some background on the difference between a GRN and PPI.  I think I can provide a graphic for you to use.
> * I'm going to post this comment now and add more edits in another comment.

- [ ] In the title, "a Web" should go on the second line to make the line break fall on the change of ideas.
- [ ] In the title box, you don't need to provide the link to GRNmap since you are not talking about it in your poster.
- [ ] I know you took the first panel from my poster, which was being displayed at a professional conference where the audience already knew the difference between GRNs and PPI.  However, at the symposium, you will need to explain it to your audience.  I would make the PPI graph on the bottom of the first panel smaller so that you can include some background on the difference between a GRN and PPI.  I think I can provide a graphic for you to use.

**Comment by ceciliazaragoza** [comment]
> * Remove the period from the title at the top of the middle panel.
> * In the acknowledgments section, you don't need to thank people that are authors on the poster.  Also, again, you don't need to mention GRNmap since you are not talking about it on the poster.  Instead, you can still thank Nikki.  A'Kaia and Cecilia need to thank their funding source.  "AP and CJZ would like to thank the HHMI STEM Research Learning Community for funding."
> * Remove reference to GRNmap under availability section.
> * Beta is now at 7.0.13, so that should be updated in the middle panel and also under the availability section.

- [ ] Remove the period from the title at the top of the middle panel.
- [ ] In the acknowledgments section, you don't need to thank people that are authors on the poster.  Also, again, you don't need to mention GRNmap since you are not talking about it on the poster.  Instead, you can still thank Nikki.  A'Kaia and Cecilia need to thank their funding source.  "AP and CJZ would like to thank the HHMI STEM Research Learning Community for funding."
- [ ]  Remove reference to GRNmap under availability section.
- [ ] Beta is now at 7.0.13, so that should be updated in the middle panel and also under the availability section.

**Comment by ceciliazaragoza** [comment]
> In the future directions panel:
> 
> * delete "as shown above" for the first bullet point because the figures that was referring to are no longer part of the poster.
> * "Focusing" should be "Focus"
> * The next sentence should be its own bullet point, "Improve" instead of "Improving"
> * I don't think the last two bullet points are necessary.  They are covered by the previous points, I think.

- [ ]  delete "as shown above" for the first bullet point because the figures that was referring to are no longer part of the poster.
- [ ] "Focusing" should be "Focus"
- [ ] The next sentence should be its own bullet point, "Improve" instead of "Improving"
- [ ] I don't think the last two bullet points are necessary.  They are covered by the previous points, I think.

**Comment by ceciliazaragoza** [comment]
> At the bottom of the left panel, you can focus on the differences between the PPI and GRN (background). Then you can move the screenshot of the PPI up to the top of the middle panel, so it will be right next to the GRN example. Then you don't need the additional screenshots that you have there.
> 
> Then you can reorganize the next information to describe how you would load a PPI:
> 
> * choose the new PPI demo file
> * Upload a PPI (with the column A1 altered)
> * Upload a SIF (simple interaction format)
> * GraphML not available for PPI
> 
> For the comparison between the pd sif and pp sif, please redo the screenshot from Excel so that it has a white background. It can also be smaller since it will end up printing quite large in the way you are showing it now.

- [ ] At the bottom of the left panel, you can focus on the differences between the PPI and GRN (background). Then you can move the screenshot of the PPI up to the top of the middle panel, so it will be right next to the GRN example. Then you don't need the additional screenshots that you have there.
- [ ] choose the new PPI demo file
- [ ] Upload a PPI (with the column A1 altered)
- [ ] Upload a SIF (simple interaction format)
- [ ] GraphML not available for PPI
- [ ] For the comparison between the pd sif and pp sif, please redo the screenshot from Excel so that it has a white background. It can also be smaller since it will end up printing quite large in the way you are showing it now.

**Comment by ceciliazaragoza** [comment]
> ![155-VitaminDReceptor_VDRcryo](https://private-user-images.githubusercontent.com/6463867/312160009-b73c50a1-3b34-404f-891f-e4c4a3f83dd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjgyMjcsIm5iZiI6MTcxMDI2NzkyNywicGF0aCI6Ii82NDYzODY3LzMxMjE2MDAwOS1iNzNjNTBhMS0zYjM0LTQwNGYtODkxZi1lNGM0YTNmODNkZDguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTgyNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQxOTliMmVjODU4YzYwYzA4NDNlNDU1YTY0ZDQ1OWIwZWEzNjMzODYwZDE2N2MzMWIxZGU2YjhlYTBjMDcwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e7QdFtW-Lh0aAbBO5FggRCuuDOO8CzDZ4mFLua06PBA) https://pdb101.rcsb.org/motm/155 You can use this image to show a regulatory transcription factor bound to DNA in a GRN. Be sure to cite the URL

How should we cite? Can I put in the caption next to the image: "Image from: https://pdb101.rcsb.org/motm/155"?

**Comment by kdahlquist** [comment]
Yes, definitely put the image caption and then include a full APA-formatted citation to the URL in the references list.  The image that has Leu1 and Leu3 is one that I created so you don't need to cite that one.

**Comment by ceciliazaragoza** [comment]
The poster has been edited based on @kdahlquist feedback and is ready for review.

**Comment by kdahlquist** [comment]
I made a few minor tweaks and uploaded the final version to GRNsight-archive here: https://github.com/dondi/GRNsight-archive/blob/main/documents/posters/Tran_Zaragoza_Phelps_LMU_SYMPOSIUM_2024.pptx

It's been sent for printing!

**Comment by kdahlquist** [comment]
Poster should be ready for pick-up in FEA 101 if you haven't picked it up already.
