### ISSUE TITLE
Importing empty network with network tab of Excel file crashes the website

### ISSUE THREAD

**Issue by ntran18** [dondi/GRNsight#1091]
@ceciliazaragoza mentioned in PR #1085 . When importing an Excel file with a network tab with empty data, the website will stop working.

**Comment by ceciliazaragoza** [comment]
I worked on this, and I added a try-catch that catches the error if data[0][0] for cell A1 is undefined.

**Comment by ceciliazaragoza** [comment]
Adjusted code for lint errors.
