### ISSUE TITLE
Further testing opening sif files for GRNs and PPIs

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1102]
There is a test case that needs to be done with regard to .sif files.  If a user creates an unweighted .sif file with a mix of "pd" and "pp" designations, it should return an error telling the user that it needs to be all "pd" or all "pp" and that GRNsight does not support the display of networks of mixed type.

I just tried it really quick and it opens as a GRN.

**Comment by dondi** [comment]
Merged and verified on 10/23
