### ISSUE TITLE
When exporting to Excel, the option to export the "network_weights" sheet should be available at all times

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1108]
When exporting to Excel, the option to export the "network_weights" sheet should be available at all times.  The "network_optimized_weights" sheet should only be available if there is edge weight data, but the "network_weights" sheet should always be available.  It should be identical to the "network" sheet.

I apologize if I said differently before.

**Comment by ntran18** [comment]
When `network_weights` is empty, then should the sheet for network_weights be empty sheet? The `network_weights` option is disabled because there is no data for that.

**Comment by kdahlquist** [comment]
The "network_weights" sheet should be identical to the "network" sheet.  Copy over the data from the "network" sheet.

**Comment by dondi** [comment]
Confirmed that **network_weights** is available in `beta` but unavailable in production
