### ISSUE TITLE
Scheduling Fall group meetings

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1115]
Hi @dondi, @ceciliazaragoza, @ntran18, @akaiap, and @nchun2!  I hope you have had a great summer!  It is time to work on scheduling our weekly meetings for the Fall.  Please note any time constraints you have in addition to your classes, which I can get off of PROWL in the comments.  We are aiming to have our first meeting the first week of class.

**Comment by kdahlquist** [comment]
After looking over everyone's schedules and consulting with @dondi, it looks like Wednesdays at 12:30-1:30 would work for everyone.  Please let me know as soon as possible if this is a problem for anyone.

**Comment by ceciliazaragoza** [comment]
That time works for me!

**Comment by akaiap** [comment]
Hi! That works for me as well!

**Comment by ntran18** [comment]
Hi all, the time works for me! Thanks!
