### ISSUE TITLE
Migrate CI unit-testing and coverage reports to GitHub Actions

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1118]
As seen in #1044 and #1095, our existing use of Travis and Coveralls for automated tests and coverage reports, respectively, has become out of date and potentially no longer feasible given changes to how Travis and Coveralls operate. In the meantime, GitHub introduced their Actions tab and this is a potential replacement for both services

We can explore how to do that and transition accordingly when ready

**Comment by dondi** [comment]
Sample repo that has CI set up with GitHub actions: https://github.com/vitejs/vite

**Comment by akaiap** [comment]
- Documented the migration process and steps in the Wiki. -- [https://github.com/dondi/GRNsight/wiki/Migrating-from-Travis-CI-to-GitHub-Actions](Wiki)
- Began studying documentation for workflow file instructions for Github actions

**Next Steps for this week**
- Create branch 
- And begin writing instructions for the yml file

**Comment by dondi** [comment]
Branch is ready to go but @akaiap just needs to finish SSH key setup in order to push to the repo. She will do this 10/17 and signal the group if there are any questions

**Comment by akaiap** [comment]
- Created the SSH key setup 
- Additionally, created a pull request with the new changes to the yml file

**Comment by dondi** [comment]
We took a look at the latest version of the config file and noticed that the initial core issue with running the latest settings involves the `on` block in the YAML file

@akaiap can do additional lookup on this value so that we can get the Action to execute at precisely the times that we want (e.g., upon every push vs. upon every PR, etc.)

@ceciliazaragoza found a link that looks like a good start: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

**Comment by akaiap** [comment]
**Updates:**

_Success!_
-  CI testing has been successfully integrated into GitHub Actions! 
-  The workflow file now completes the build process, runs unit tests, and finishes the build smoothly. 
- During testing, I discovered that Node.js version 20.x was incompatible with the current canvas module, so I downgraded it to 18.x.
**Future notes:**
- To enable the workflow to use a higher version of Node.js, we need to upgrade the canvas package to a version that supports Node.js 20.x. (in package json)

**Comment by dondi** [comment]
The `review requested` for this issue isn’t a traditional “QA” action, but just a general monitoring now that any push to `beta`—and any branches taken from `beta` from this point—should automatically a generate a workflow run, seen in the Actions tab:
<img width="685" alt="image" src="https://github.com/user-attachments/assets/691e8c55-c9b4-4ad3-af62-502c735147d0">

We can review results at the 11/20 meeting and close the issue then

**Comment by dondi** [comment]
We’ve seen a few cycles of this and it looks good to go
