### ISSUE TITLE
End markers are missing

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1122]
@nchun2 was trying to display the network from the attached workbook.  It is a 3-gene, 4-edge network.  Two of the end markers are there and 2 are not.
[DB5_derived_sample_network_bi_B_constants_output.xlsx](https://github.com/user-attachments/files/17285367/DB5_derived_sample_network_bi_B_constants_output.xlsx)
![image](https://github.com/user-attachments/assets/cc1a2ae2-a624-4548-829a-b4755cb3f905)

**Comment by dondi** [comment]
Another potential use case: `GLN3` on Demo #2

Further observation is that the problem manifests differently in Safari vs. Firefox/Chrome, but there is an issue nonetheless (marker is completely missing from GLN3 in Firefox/Chrome, but it appears although without the angle adjustment in Safari)

**Comment by ceciliazaragoza** [comment]
I did Open File with [DB5_derived_sample_network_bi_B_constants_output.xlsx](https://github.com/user-attachments/files/17285367/DB5_derived_sample_network_bi_B_constants_output.xlsx), and this is the output I got which seems to be as expected.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/2f509f53-7df5-42f1-a601-67d915a7d120">

**Comment by dondi** [comment]
Let’s have other team members look at this and see if we can corroborate

**Comment by ntran18** [comment]
The issue happens in `master` but not in `beta`. Possibly that Cecilia's PRs on tick fix it.

**Comment by dondi** [comment]
End markers look OK for me in `beta` also. I opened the workbook plus also looked at Demo #2. Definitely better behavior than production deployment

**Comment by dondi** [comment]
We can close this but in testing it, we discovered #1142
