### ISSUE TITLE
Navbar dataset for node coloring selected is not checked

### ISSUE THREAD

**Issue by ntran18** [dondi/GRNsight#1139]
https://github.com/user-attachments/assets/82dc7fa6-2b53-46ea-b31f-57d4b81b4645

**Comment by kdahlquist** [comment]
Do you mean the demos?  They were never meant to be checked.  The demo file selected shows up by name in the green bar so the user always knows what is being displayed.  I guess we can check it if you really think it is needed, but it wasn't planned that way.

**Comment by ntran18** [comment]
No, I mean when you want to change the dataset for node coloring, the check doesn't reflect the change we made. However, it seems like my fix for #1053 fixed it. Need a confirmation whether the issue is fixed if merge the fixes for #1053

**Comment by ntran18** [comment]
Since PR #1138 is merged, I can change the tag from code review to review request

**Comment by dondi** [comment]
Confirmed in `beta`
