### ISSUE TITLE
Count files uploaded to server to track usage of GRNsight

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#116]
This is separate from Google Analytics (#115) which only tracks hits to the web site.  To monitor usage, we need to count how many files are uploaded.

**Comment by dondi** [comment]
OK, an inaugural version of this has been implemented and committed to the `ga-integration` branch. I made sure that `ga-integration` was in sync with `beta` before committing.

New `node` packages will be required: `node-uuid` and `request`. They need to be `npm install`ed as usual or else the spreadsheet upload service will not work.

Uploads are reported as “pageviews” to the */GRNsight/upload* URL. To retrieve the value, use the same `/ga` service that we have been using for accessing other counts; i.e., `/ga?path=upload`.

**Comment by dondi** [comment]
New approach taken; that means the aforementioned `node` packages are no longer needed. All the rest should still be the same.

**Comment by kdahlquist** [comment]
Once this is released, we can add a "xxx files have been uploaded and viewed with GRNsight." message to the footers of the home and beta pages. The process is the same as others; add an Ajax call to `/ga?path=upload` to get the count.

**Comment by dondi** [comment]
Released!
