### ISSUE TITLE
Advertise GRNsight on external sites

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#120]
@kdahlquist will recruit some outside users/testers for GRNsight as to get ready for the NAR paper.

**Comment by kdahlquist** [comment]
We need to register GRNsight with the ELIXIR Tools and Data Services Registry https://elixir-registry.cbs.dtu.dk/

**Comment by anuvarsh** [comment]
I looked into registering GRNsight into ELIXIR and it seems as if all that needs to happen is that an account must be made with an academic email address, and then a form must be filled out with information about your tool.
![image](https://cloud.githubusercontent.com/assets/8509674/11285869/a838754a-8ec6-11e5-932d-88de5a94c974.png)
I created an account to see what the form that needed to be filled out looked like. The information about GRNsight that would be added includes:
*Summary
*Function
*Contact
*Publications
*Documentation
*Credits
*Supplementary information
More information regarding content that needs to be added can be accessed here: https://docs.google.com/document/d/1oFHd4qleXHEKVXPYcSTomLXUFVvOCf7WtcmVraEuc7k/edit#

**Comment by kdahlquist** [comment]
I created an account with bioinformatics.org and requested an account with their wiki. Once my account is approved, I can create a wiki page for GRNsight (and GRNmap and XMLPipeDB).

I tried to create an account with the Elixir Data and Tools Registry, but am having a problem logging in.  Once this is resolved, I can register our projects with them.

**Comment by kdahlquist** [comment]
I requested a link to GRNsight with bioinformatics.ca

**Comment by kdahlquist** [comment]
I sent a follow-up e-mail to links{at}bioinformatics{dot}ca to find out the status of being added to the links directory.

**Comment by kdahlquist** [comment]
My forum post about GRNsight at bioinformatics.org was posted on January 4, 2016 here:
http://www.bioinformatics.org/forums/forum.php?forum_id=11896

I submitted another request to join their wiki so that I could get a login and create a wiki page for GRNsight.

**Comment by kdahlquist** [comment]
I was in the midst of setting up my wiki account for bioinformatics.org and getting a password reset from Elixir and I stopped receiving e-mails.  I think that there is a problem with LMU's e-mail server since I was able to get some messages and then they just stopped.  Sigh.  I guess I will have to finish this another day.

**Comment by kdahlquist** [comment]
OK, bioinformatics.org is done.  I created wiki pages there for GRNsight, GRNmap, and XMLPipeDB.  I put links to those pages on the GRNsight and GRNmap Links pages as well.

**Comment by kdahlquist** [comment]
I have sent an e-mail to registry-core@elixir-dk.org to try to see if I can get my login for Elixir fixed.

**Comment by kdahlquist** [comment]
@dondi should create a login for the Elixir Tools and Data registry so that he can register GRNsight since @kdahlquist is not hearing back from them.

**Comment by dondi** [comment]
OK, I’ve logged in and created an entry. I did some “educated guesses” for topics and functions plus other content was largely copy/pasted from our About page. More information can probably be added here and there. But at least we're in: https://bio.tools/tool/lmu.edu/GRNsight/1.12

**Comment by kdahlquist** [comment]
OK, I see it.  I think we'll need to tweak it when we have our face-to-face meeting this week and can work on it together.  It seems the info that is now in our about paragraph should go into credits and that our about paragraph should describe more about the functionality.

**Comment by dondi** [comment]
Yes, definitely. I just guessed a few in order to throw something up there, so I was expecting we would indeed revise it.

**Comment by kdahlquist** [comment]
I updated the Elixir entry.  It is strange that the free text description of the function does not actually appear on the GRNsight Elixer page, but does in the search results.  Anyway, I'm not going to mess with it any more and will close this now.

**Comment by kdahlquist** [comment]
I spoke face-to-face with the Elixir team and they are currently working on an overhaul of the site.  The new site can be found at https://dev.bio.tools/.  The new version has a password reset link.

We can review our listing and give them feedback as well.

Our tool is now up on bioinformatics.ca here:

https://bioinformatics.ca/links_directory/resource/83363/grnsight-web-application-and-service-visualizing-models-small-medium-scale-gene

**Comment by kdahlquist** [comment]
More discussion with Elixir group:  keyword/description was confusing, information is available on a rollover of the "i" icon in the keyword cloud tag.

**Comment by kdahlquist** [comment]
GRNsight is now listed in the Bioinformatics Links Directory at bioinformatics.ca here:  https://bioinformatics.ca/links_directory/resource/83363/grnsight-web-application-and-service-visualizing-models-small-medium-scale-gene

@kdahlquist is responsible for maintaining our entry in this resource.

**Comment by kdahlquist** [comment]
I got a password reset from the Elixir group, but it doesn't work and I could not create an account on the dev.bio.tools because it said the username was taken.  I've e-mailed them this result.

**Comment by kdahlquist** [comment]
With the registration on the BioJS repository #286, I'm going to close this one.  We'll look into updating Elixir at some point in the future, but it is not worth holding this issue open for.
