### ISSUE TITLE
Duplicate gene in matrix

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#128]
Testing a duplicate gene in the matrix on the side, top, or both
- related to issue #126 because in first two test cases either side or top will have an extra gene

**Comment by anuvarsh** [comment]
Added all duplicate gene test files to the unit testing framework. All tests currently passing.

**Comment by dondi** [comment]
As more tests get implemented, look for opportunities to consolidate similar testing blocks as functions. Not obligatory but might help with maintenance in the future.
