### ISSUE TITLE
Add "Page visited xxx times" via Google Analytics

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#134]
Now that #115 is finished, time to separate this as an issue of its own.

**Comment by dondi** [comment]
We will reawaken the thread of exploring automatic insertion via Google Analytics.

**Comment by dondi** [comment]
@dondi has gotten GRNsight@gmail.com set up to use analytics and is now at the point where the code needs to login via OAuth.

**Comment by dondi** [comment]
@dondi has been able to connect to the Google Analytics API. The unknown exploratory part of this task is done, and the rest should come more smoothly.

**Comment by dondi** [comment]
Google Analytics integration code largely complete; now the next step is to use this code in the dondi.github.io website. @dondi will temporarily play with the beta settings and a single page from dondi.github.io. Once that is OK, @NAnguiano and @anuvarsh can propagate change to other pages.

Footer to be changed into one paragraph not to exceed the width of the home-to-beta links; page view count will be added as a sentence to that paragraph: "This page has been accessed _____ times."

**Comment by dondi** [comment]
Once integration with web pages has been done, we will do a fast-track release to 1.8.4 so that these changes can go into the `master` branch.

**Comment by dondi** [comment]
OK, the Beta page is now piloting this functionality. See the bottom of http://dondi.github.io/GRNsight/beta.html. If this is good, then (a) the change can be propagated to all other changes, and (b) we can fold this change into `master`. Because I mistakenly branched off `beta`, doing so implies a quick release.

**Comment by dondi** [comment]
@NAnguiano will do a merge of all three standing branches (beta, ga-integration, and test-suite) into master for a new release 1.10. Manual testing still needed, but once verified we can move on to the next milestones.

**Comment by NAnguiano** [comment]
That was a doozy of a merge. But it is done (and functional!)! I've officially merged all the branches together and put the new release live. I added some release notes for the 1.10 release, but these can definitely be expanded and refined. I just wanted to get everything up and running. The "Page accessed xx times" is functional at the bottom of each page.
