### ISSUE TITLE
Uploading a wrong file type

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#139]
Chrome doesn't allow wrong file type to upload

Firefox:
* .docx file resulted in following error message: 

> Invalid input file. Please select an Excel Workbook (.xlsx) file. Note that Excel 97-2003 Workbook (.xls) files are not able to be read by GRNsight.

* .doc has same error message as previous.
* Music files had same error message
* .jpg had same error message as earlier
* .png had same error message as earlier
* .pdf had same error message as earlier
* .java had same error message as earlier
* .ppt had same error message as earlier
* .pptx had same error message as earlier
* .xls had same error message as earlier

**Comment by kdahlquist** [comment]
This was related to issue #107 and appears to now be handled well by the latest versions of our supported browsers (Firefox, Chrome). Closing for this reason.
