### ISSUE TITLE
Implement error message framework

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#144]
I didn't see any notes on this from last week's meeting.  @dondi mentioned a three-part framework for error messages that goes something like

* state what happened
* state what could have caused the error
* suggest ways of fixing it.

@dondi also talked about having a set of functions for error handling that runs so that it can spit out a bunch of errors all at once, so the user doesn't have to find them one at a time.

this was originally a comment to #128

**Comment by dondi** [comment]
One of the original motivations for doing this framework was to make it easy to test automatically. So we can close this issue once we have reached the point where we can start defining tests that capture certain files then check if the returned errors for those files are correct.

**Comment by dondi** [comment]
To consolidate our errors, @NAnguiano will start compiling the error objects into an overall collection of errors, keyed by some code (e.g., `MISSING_GENE_NAME`). That way, we have a centralized place for reviewing/editing error messages and eventually @anuvarsh’s unit tests can reference the same structure.

**Comment by dondi** [comment]
Questions for @NAnguiano: How complete is this? Can this issue be considered a "solved but on-going task" now? Or should we leave it open?

**Comment by dondi** [comment]
In terms of an overall framework, this can be considered done. Of course the error list will be refined over time.
