### ISSUE TITLE
When weighted graph loaded, show message about mouseovers

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#153]
Based on the feedback on our SCCUR abstract #152, when a weighted graph is loaded, let's put a message on the screen instructing the user that he/she can mouseover the edges to see the weight parameter values.

"Mouse over the edges to see the weight parameter values." 

Put this message underneath the "undo" button on the left side of the screen.

**Comment by NAnguiano** [comment]
This has been added to the state diagram, which is now viewable [here](https://github.com/dondi/GRNsight/wiki/Testing-Protocol). Reassigning to @kdahlquist for review.

**Comment by kdahlquist** [comment]
state diagram changes made and posted.
