### ISSUE TITLE
Use release mechanism to tag releases

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#161]
We should start using the release mechanism to tag code with release versions.  Since we did not do this previously, we will start with v1.6.  Tag everything currently in Master as v1.6.  Then we merge the beta and master we will then tag that with v1.8, and then it will be part of our workflow thereafter.

We can then put our release notes in the actual release notes place (and copy it over to the About page, too).

**Comment by dondi** [comment]
v1.6.0 release draft has been published. We can give this another go with v1.8.0 when it is ready. Ultimately it was fairly straightforward—tag the desired commit, create a new release, edit the description. The downloadables at the bottom are actually built by GitHub automatically upon release publication, based on the indicated git tag.

**Comment by dondi** [comment]
Two releases down, standard procedure from now on.
