### ISSUE TITLE
News item about SCCUR poster

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#162]
Add a news item about your poster at SCCUR! Date it for Saturday and model it after the other news items about other presentations.  You can add a link to your abstract on the SCCUR web site.

**Comment by kdahlquist** [comment]
Instead of saying "Click here to view abstract. Click here to view the poster." You could say "Click here to read the abstract and here to view the poster."  Just make the word "here" link to the appropriate sites, respectively.

**Comment by anuvarsh** [comment]
Make this change, reassigning to @kdahlquist for review.

**Comment by kdahlquist** [comment]
confirmed and closing
