### ISSUE TITLE
Add links to GRNmap throughout GRNsight web site

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#163]
The GRNmap download page is live!  We should now add the following links to GRNmap to our pages:

1.  Create a news item that says "Our sister project, GRNmap: Gene Regulatory Network modeling and parameter estimation, has an executable available for download."  Link the word download to http://kdahlquist.github.io/GRNmap/downloads.html.
2.  On the about page in the middle paragraph, link the first instance of the word GRNmap to the GRNmap home page at http://kdahlquist.github.io/GRNmap/index.html.
3. On the Documentation, under Getting Started, link the first instance of the word GRNmap to the GRNmap home page.
4.  On the Documentation page, under section 1, link the first instance of the word GRNmap to the GRNmap home page.
5.  On the Links page, under Software, create a link called GRNmap and link it to the GRNmap home page.
6.  We'll also add your poster to the publications page, but the final version is not done yet.  Once I have the final version in hand, I'll post it to SlideShare and we can create the links to it like for the other presentations.  We'll create a new section called "Posters" for it.

**Comment by kdahlquist** [comment]
For the news item on the news page, can you link "GRNmap Gene Regulatory Network modeling and parameter estimation" to the GRNmap home page. (Keep the link to the download page).

**Comment by anuvarsh** [comment]
Just pushed this change. Reassigning to @kdahlquist for review.

**Comment by kdahlquist** [comment]
I guess I wasn't clear as to what I wanted here:

The "headline" "GRNmap Available For Download" should not be a hyperlink.
The words "GRNmap Gene Regulatory Network modeling and parameter estimation" should link to the GRNmap home page, the word "download" at the end of the sentence should still link to the download page.

**Comment by anuvarsh** [comment]
I misread it the first time! Just made the correct change. Sorry about that.

**Comment by anuvarsh** [comment]
Accidentally hit close and comment instead of just comment.

Also, I just misread it last time! Just made the correct change. Sorry about that.

**Comment by kdahlquist** [comment]
Confirmed!
