### ISSUE TITLE
move demo #3 and #4 to master branch

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#167]
I don't exactly know where we are at with the merge/release of v1.8.  However, I need the demo files numbers 3 and 4 to be available on the master ASAP (they are only available on beta right now).  I am submitting the paper today that references those files and gives a link to the GRNsight home page, so I need them to be on the main page.  If we're ready to merge/release v1.8, that's great.  If not, can we at least make that change?  I know that making that piecemeal change is not correct procedure, but I don't want to delay submitting the paper.  Thanks!

**Comment by NAnguiano** [comment]
The only thing left for 1.8 was to check for files that could cause errors (Issue #151), and I just went ahead and did that. There was one question about the text data-type, but if that isn't fully necessary for the release, I can go ahead and release 1.8 now onto the master.

**Comment by dondi** [comment]
Go ahead with this and relay the final commit ID to me; I can tag and release as v1.8.0. We can always release a v1.8.1 to close any late-breaking loose ends.

**Comment by kdahlquist** [comment]
That sounds great! Thanks!

**Comment by NAnguiano** [comment]
Merge is complete! The commit id is 5d4ffbed4f47e0fad1d512849b8ef0abb8b9faed.

**Comment by dondi** [comment]
OK, tag is made and release is in draft form. I derived the release notes from issue #150. Feel free to take a look; I can publish after a few days if there are no further changes.

**Comment by dondi** [comment]
Oh, direct link: https://github.com/dondi/GRNsight/releases/tag/untagged-c33004a9954f0025290b

**Comment by dondi** [comment]
Demos verified as moved successfully.
