### ISSUE TITLE
Write "About" and "Documentation" for v1.8

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#169]
Write text for "About" and "Documentation" for v1.8.

Remember, we need to change the documentation to state that gene names (nodes) are treated as case-preserving. i.e., When we compare them, we do not care about case, but we will keep the capitalization that the user originally entered.

Reference #150 for release notes.

**Comment by kdahlquist** [comment]
Here is some text for the About page.  Text for the documentation page is still to come, but please go ahead and add this now.

GRNsight v1.8 includes the following new features and bug fixes:
* Two additional demo files have been provided for users to view:  Demo #3 Unweighted GRN (21 genes, 31 edges) and Demo #4 (21 genes, 31 edges, Schade et al. 2004 data).
* GRNsight now allows the user to upload spreadsheets with asymmetric adjacency matrices.  I.e., the number, identity, and order of genes across the top and side of the adjacency matrix does not have to match.
* The size of the bounding box for the graph has been fixed to a particular size.
* Edges between nodes no longer go outside the bounding box; self-referential edges do still go outside the bounding box--this will be addressed in a future release.
* A bug in Firefox that was chopping off points of arrowheads has been fixed.
* When a weighted graph is displayed, a message appears underneath the Undo Reset button to remind the user to "Mouse over the edges to see the weight parameter values."
* A workaround for printing in Firefox has been described.

**Comment by kdahlquist** [comment]
I've made the changes to the Documentation page text and will send it out separately as a Word document.  What I did was copy the entire text of the page into a word document and then highlight in yellow the parts that are changed, so you can see the changes in the context of the entire page.  You should just be able to copy and paste the text.  Note that I also made some corrections here in there due to typos and other stuff.

**Comment by anuvarsh** [comment]
I inserted the new text into both the About page and the Documentation page. I'm checking again to see if I missed any "regular" to "pointy" arrowhead fixes, but let me know if anyone catches anything.

**Comment by kdahlquist** [comment]
I've verified the changes to the About page.  Can we now add a sentence to the relevant news item:

"For a description of the new features, please see the About page.", linking the words "About page" to go to the appropriate release notes with the section opened.

I've gone through the changes to the documentation page.  There are some additional edits that need to be made.  I'm going to resend the word document, this time highlighting in magenta the further changes (the yellow is still there).  Some of them are my mistakes and some of them are things that you overlooked.  In particular, there is one case where the text needs to be italicized, a few cases where there is a double quote where there should be a single quote (apostrophe), and one case where I made a parenthetical note about adding a hyperlink, but you just copied the note onto the page.

I've had to change some of the references to "pointy" to "regular (pointy)" and some back to "regular" because I forgot that the Preferences menu item actually makes a reference to "regular" not "pointy" arrowheads.

**Comment by anuvarsh** [comment]
I went through again and added the changes that were indicated. While rereading the Documentation page, I noticed there were a few more references to "regular arrowheads" without the clarification that they are pointy. A couple were describing text that is already on the website, but for the others I went ahead and added (pointy). Let me know if I should delete any of those, or if I made any other mistakes.

**Comment by kdahlquist** [comment]
There are two instances where it says (point) instead of (pointy) in section 3.  When these are fixed, I think we will be caught up on changes.

**Comment by anuvarsh** [comment]
Just made those fixes!

**Comment by kdahlquist** [comment]
Confirmed and closing
