### ISSUE TITLE
Slight edit to GRNsight web site footer

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#170]
Can we make a slight edit to the GRNsight web site footer that appears on every page?  Instead of 

This web site is free and open to all users and there is no login requirement.
Web site content is available under the Creative Commons Attribution Non-Commercial Share Alike. GRNsight code is available under the open source BSD license. 

Can it say (with the appropriate links preserved)?

This web site is free and open to all users and there is no login requirement.
Web site content is available under the Creative Commons Attribution Non-Commercial-Share Alike 3.0 Unported License.
GRNsight code is available under the open source BSD license.

**Comment by anuvarsh** [comment]
I changed the footer on all of the website pages.

**Comment by dondi** [comment]
Confirmed on footer.
