### ISSUE TITLE
Error in Console upon loading beta or master

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#171]
When either beta or master is loaded, the following error appears in the console:

"Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://dondi.github.io" from accessing a frame with origin "http://grnsight.cs.lmu.edu". Protocols, domains, and ports must match."

**Comment by dondi** [comment]
I visited both pages just now and did not see the error. It sounded like just loading the pages triggered the error, but when I did, I didn't see anything. I also loaded the demos but did not see an issue either. If I’m missing steps to replicate properly please let me know.

**Comment by NAnguiano** [comment]
It happens immediately upon loading the page in Chrome, though upon a further glance, it doesn't appear to happen in Firefox or Safari.

**Comment by dondi** [comment]
I tried with Chrome just now and I did not see the message either. I only saw the console log for what presumably is the parsed graph object. I’m on Chrome 39.0.2171.99 64-bit.

**Comment by anuvarsh** [comment]
I also saw the error that Nicole mentioned on both Beta and Master. I am on Chrome Version 39.0.2171.95 (64-bit).

**Comment by NAnguiano** [comment]
![grnsight error example](https://cloud.githubusercontent.com/assets/6444156/5822178/8b78d1b8-a086-11e4-8b9d-aa8c68c53110.png)

Here is the error. It appears every time that I load the webpage for beta or master. I am on Chrome Version 39.0.2171.99 (64-bit).

**Comment by dondi** [comment]
Wow, that is truly odd---I tried it again now and still didn't see it. Hmmm.

**Comment by kdahlquist** [comment]
We verified in the meeting that the bug does not appear on @kdahlquist 's computer so maybe it has something to do with the LMUMAIN vs STUDENT domain?  Or something else that is different on a faculty vs. student computer.

**Comment by dondi** [comment]
We have discovered that being logged in to the Chrome browser appears to produce the error. That's it...

**Comment by dondi** [comment]
Because this appears to be just an error message and something beyond our control *and* does not exhibit user-level issues, we shall close…
