### ISSUE TITLE
LMU Undergraduate Research Symposium 2015

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#172]
Abstracts are due February 13 by 5:00 PM, submitted online from link on following page:

http://academics.lmu.edu/symposium/2015symposium/applicationprocess/

**Comment by dondi** [comment]
2015 instructions can be found here: http://academics.lmu.edu/symposium/2015symposium/

**Comment by NAnguiano** [comment]
Abstract can be up to 250 words or 3,000 characters.

**Comment by kdahlquist** [comment]
It's on the FAQ page :)  http://academics.lmu.edu/symposium/faq/#6

**Comment by dondi** [comment]
Done and submitted 2015-02-10.
