### ISSUE TITLE
v1.8.1 bug fix for reset button

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#173]
Before a graph is loaded, the reset button does not work on v1.8.   @NAnguiano has fixed it on v1.9 beta and recommends a v.1.8.1 release for this patch.

**Comment by dondi** [comment]
Fixed by @NAnguiano and releasable as v1.8.2 alongside bounding box constraint fix.

**Comment by NAnguiano** [comment]
v1.8.2 has been released. I put the release live, added the news item, and adjusted the version number on the site. We can adjust the release notes as necessary.

**Comment by dondi** [comment]
Confirmed.
