### ISSUE TITLE
Updates to demo files number 3 and 4 and need to clean up demo files folder

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#174]
I've verified that we need to update demo files 3 and 4 to conform to the supplementary data files Dr. Fitzpatrick and I are submitting with our manuscript.  They will be attached to an e-mail and are named:

21-genes_31-edges_Schade-data_input.xlsx

and

21-genes_31-edges_Schade-data_estimation_output.xlsx

I remember that we had a conversation in which we agreed that while these filenames do not exactly conform to our style guide (since they have underscores), there is actually a good reason for this as the underscores are the harder punctuation between descriptive phrases in the filename.

While looking for and downloading the current demo files from the repository, things are kind of messy there.  There are versions of files with both conventions for filenames.

I want to plant a flag and insist that the filenames that I chose above be used and to make any necessary changes to the GRNsight code to accommodate them.

Please also delete from the demo files folder on both master and beta any unused files.  This folder should only have the four demo files that are in use in master/beta, according to the filename convention above.  (Now that I think about it, probably demos number 1 and 2 have to have their names change like above, i.e, 21-genes_50-edges_Dahlquist-data_input.xlsx and 21-genes_50-edges_Dahlquist-data_estimation-output.xlsx).

If we can give this a fairly high priority, that would be great--we are submitting the manuscript today or tomorrow.

**Comment by NAnguiano** [comment]
I've updated the demo files and renamed the two other demo files to match with the naming convention of the two new files. I also removed the files that didn't belong in the demo files folder. I've changed them in both beta and master.

**Comment by kdahlquist** [comment]
Verified and closing.  Thank you for responding so quickly.
