### ISSUE TITLE
v1.8.2 About and News

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#175]
So, to catch up with v1.8.2, there are no changes needed for the documentation page, but we need to add the release notes to the About page and then link to it from the News page.

For the About page:
GRNsight v1.8 includes the following new features and bug fixes: 
* Nodes and self-referential edges no longer go outside the bounding box of the graph.
* A bug was fixed that had inactivated the reset button before graph is loaded.

**Comment by kdahlquist** [comment]
Here's the embed link to my slides on Slideshare for the systems Biology Conference:

<iframe src="//www.slideshare.net/slideshow/embed_code/44236648" width="476" height="400" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>

Can you put it on our publications page and then link to it on the News page?

Here is the link to the conference web site to use:  http://ccbs.uci.edu/scsb2015home

**Comment by NAnguiano** [comment]
The about page changes have been made, and the slides have been embedded on the publications page and linked on the news page.

**Comment by kdahlquist** [comment]
For the about page, I'd like to see a separate section for v1.8.2, not just put the release notes under v1.8.

**Comment by kdahlquist** [comment]
confirmed and closing
