### ISSUE TITLE
Error message for duplicate gene

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#176]
The current error message for a duplicate message looks like:
![image](https://cloud.githubusercontent.com/assets/8509674/6123867/726d9d02-b0bc-11e4-8760-2d747a396a75.png)

Just a small grammatical error. It should read "There exists a..." instead of "There exist a..."

**Comment by NAnguiano** [comment]
I can't believe I never noticed that in all the times I've seen that error message. It's fixed now!

**Comment by anuvarsh** [comment]
Looks good! Closing.
