### ISSUE TITLE
LMU Undergraduate Research Symposium 2015 poster

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#178]
Symposium is Saturday, March 21.  We want the poster to be ready for printing at our meeting on Tuesday, March 17 (Happy St. Patrick's Day!), which means that we need to see the draft by the previous Tuesday, March 10 (three weeks from today).

Begin with the poster from SCCUR and revise from there.  @kdahlquist has some feedback on that poster that wasn't incorporated due to time constraints at that time.

Commit the poster to the documents folder using the naming convention that we used for SCCUR (sub LMUSymposium) and upload all new versions there (for version control).

**Comment by dondi** [comment]
Stay consistently with the same graph and data as much as possible, so that viewers can compare them more directly (e.g., manual vs. GRNsight).

**Comment by dondi** [comment]
Just need to upload the final version then we can close this.

**Comment by NAnguiano** [comment]
Uploaded, so closing this up!
