### ISSUE TITLE
Consolidate similar testing blocks for easier maintenance and readability

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#181]
As more tests get implemented, look for opportunities to consolidate similar testing blocks as functions. Not obligatory but might help with maintenance in the future.

**Comment by anuvarsh** [comment]
Tests with similar error codes have been grouped together according to the number of errors they have and the error code that they use. The tests are now grouped to have both the input and the output sheet of the same test condition in the same unit test.

**Comment by dondi** [comment]
Adjustment has been made for existing tests; this issue can be considered done because @anuvarsh has figured out how to do it and this will not be an issue in the future.
