### ISSUE TITLE
Combine / and /index.html Google Analytics counts

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#183]
Because we have not customized our GA data collection, the page views for `/` and `/index.html` are counted separately even though they lead to the same page. As a workaround, we can customize the GA reporting for that page to just add the two numbers together.

**Comment by NAnguiano** [comment]
The two counts are now combined. Going to either / or index.html now displays the combined total number of views for both pages.

**Comment by kdahlquist** [comment]
confirmed and closing.
