### ISSUE TITLE
Collapsible sections for News page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#184]
Create collapsible sections for News page with one section for 2014 and one section for 2015 news; default 2014 news to be closed and default 2015 news to be open when the page is opened.

**Comment by NAnguiano** [comment]
The collapsible sections have been implemented. Let me know what you think!

**Comment by kdahlquist** [comment]
Have headers for sections just labeled "2014" and "2015" instead of "2015 News".

**Comment by kdahlquist** [comment]
confirmed and closing
