### ISSUE TITLE
Release notes for v1.10

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#187]
We need add the release notes for v1.10 to the About page and the News page.

**Comment by kdahlquist** [comment]
GRNsight v1.10 includes the following new features and bug fixes:

- Implementation of unit testing framework to facilitate test-driven development (TDD).
- Adjusted and refined space between repressor bars and their attached nodes.
- Added page counter to the bottom of each webpage based data collected through Google Analytics.

**Comment by NAnguiano** [comment]
I replaced the previous wording with the wording currently listed under the release.

**Comment by kdahlquist** [comment]
We don't want to have links to the individual issues on the web site About page, just on the developer release page.

**Comment by kdahlquist** [comment]
confirmed and closing
