### ISSUE TITLE
Blunt markers are not centered especially for thick edges

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#188]
Blunt markers do not appear centered depending on orientation; effect is pronounced when the edge is thicker.

**Comment by anuvarsh** [comment]
Updates were made on the blunt markers of especially thick edges.

**Comment by anuvarsh** [comment]
During the last lab meeting we discovered that centering the edges when they are curved uncenters the edges when they are straight. The new plan of action is to create separate coordinates for straight edges and curved edges.

**Comment by dondi** [comment]
I’ve made some adjustments to the blunt-edge positioning code. It visually looks more balanced now, though varying thicknesses still have small differences. But for now, worth a review.

**Comment by kdahlquist** [comment]
Before the beta-server crashed, I was looking at this test file which is in the graph-tests folder:

all-negative-weights.xlsx

Some of the thicker edges in this file are not centered.  If I could pull it up again, I could be more specific, but it's fairly easy to see if you arrange them in a box layout so all the edges are straight.

There are two issues, the blunt marker is not centered on the edge.  I've also noticed that the blunt marker is also not centered on the node box.

**Comment by yshin4** [comment]
Trying to fix the issue by changing the refX value of the marker attribute when it is referring to itself. When value is too low the arrow is hard to see and when the value is too high it gets off the center of the edge. For now adjusted the numbers so it has a mutual distance away from the node and away from the center (in order to minimize the visual offset).

**Comment by kdahlquist** [comment]
Maybe this should be a new issue, but it seems to be a side effect of the changes we have been making to the edges/end markers either on this issue or #318 or #392 or #333.

When I load the test file "all-negative-weights.xlsx", the blunt end marker is not a uniform distance away from the node for all thicknesses.  As the edge gets thicker, the end marker gets progressively closer to the node until it is touching for medium-weights and above.
![blunt-end-markers-too-close](https://cloud.githubusercontent.com/assets/6463867/25251969/27c5d16c-25d0-11e7-934b-c7bc60a47838.jpg)

**Comment by kdahlquist** [comment]
As for the centering, it looks to me like they mostly look OK, except for E-5 to E-6, E-6 to E-7 and E-7 to E-8 in the screenshot in the comment above.

**Comment by kdahlquist** [comment]
After playing with it a bit more, I realize that it's a left vs. right thing and not the thickness.  If the blunt end marker is on the right side of a node, it's too close to the node; if it's on the left, it's OK.  Top and bottom are OK.

**Comment by kdahlquist** [comment]
@NAnguiano says look at issue #101.

**Comment by kdahlquist** [comment]
@yshin4, this issue is a lower priority than #318.  I labeled it for the next release because the work you have done to this point will be included even if we need to do some further tweaks later.

**Comment by NAnguiano** [comment]
Just for reference, I noted that the above marker issue is also present on arrowheads as well.
![screen shot 2017-04-21 at 11 41 54 am](https://cloud.githubusercontent.com/assets/6444156/25291708/0dbe2806-2688-11e7-8113-9dca3a1643b4.png)

**Comment by yshin4** [comment]
Seems like I have to adjust values just like refX to be in a good ratio, but I haven't looked at this problem yet. Will be getting back to it next semester.

**Comment by kdahlquist** [comment]
De-labeling this "for next release" because we've reached a stopping point for now.

**Comment by kdahlquist** [comment]
@yshin4: does your pull request also cover this issue?

**Comment by kdahlquist** [comment]
If so, please mark as review requested and assign it to me.

**Comment by yshin4** [comment]
No, I have not got to this one yet.

**Comment by yshin4** [comment]
At first, I only changed the MINIMUM_DISTANCE values in smartPathEnd function, so that the value is larger when the target node is to the left of the source node. However, this only worked for the smaller sized edges so I assigned a larger distance value accordingly as the thickness becomes larger than 9. Below are the screenshots of the result.

Left markers adjusted from E1 - E6
![image](https://user-images.githubusercontent.com/16246811/30841524-c26a6998-a231-11e7-9ad5-7d4459c26249.png)

Left markers adjusted from E7 - E14
![image](https://user-images.githubusercontent.com/16246811/30841643-4f312222-a232-11e7-9509-cfef92b8da64.png)

@kdahlquist please review the screenshots and see if there are any adjustments to make.

**Comment by yshin4** [comment]
Edited the arrowheads that @NAnguiano mentioned as well. It looks as this now:

![image](https://user-images.githubusercontent.com/16246811/30939702-3f0b1c4c-a393-11e7-8447-73a35c03e6e8.png)

**Comment by kdahlquist** [comment]
I think I need to see this live on beta so I can play with it myself.  Some of the edges in the screenshots are not perfectly straight, so it's hard to tell.  Can we make this "live" on beta?

**Comment by dondi** [comment]
I’ve merged and pushed this to `beta`, which is now at 2.2.3.

**Comment by dondi** [comment]
However, upon looking at the _edge-tests_ files that got added, I don’t see the one from her comment above. So @yshin4 if you could please issue a pull request with that file, that would be great. Make sure to merge `beta` because that has your updates plus the eslint changes.

**Comment by yshin4** [comment]
@dondi Sorry, I don't know which file you're talking about. Will you kindly specify which comment you are looking at?

**Comment by dondi** [comment]
[This comment](https://github.com/dondi/GRNsight/issues/188#issuecomment-332078103)

**Comment by yshin4** [comment]
@dondi That one was already in the test files folder. It is all-negative-weights.xlsx file in the graph-tests folder.

**Comment by dondi** [comment]
OK cool—let’s make it a practice then to supply filenames with screenshots, to improve verifiability and replicability.

**Comment by yshin4** [comment]
Sounds good, will do.

**Comment by dondi** [comment]
Completed, with test files, and now on the `beta` branch.
