### ISSUE TITLE
Investigate error with "dCIN5GendronModel1.xlsx" file

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#189]
This is an input file (dCIN5GendronModel1.xlsx) that one of the students in my biomath modeling class has created.  It will not load in GRNsight; the error given in the beta version says the gene name in row 0, column 28 appears to be invalid.  It seems OK to me, so I was wondering if you could provide more insight as to what is going wrong here.

If I copy and paste just the adjacency matrix into a fresh sheet and rename that sheet "network", the error is fixed, which suggests to me that it is actually something outside the bound of the adjacency matrix that is causing the error.

**Comment by kdahlquist** [comment]
We think it is something outside of the adjacency matrix proper (in the columns to the right).

We need to modify GRNsight so that it ignores anything in the cells outside of the bounds of the adjacency matrix.

**Comment by kdahlquist** [comment]
It seems like the student created the file with LibreOffice instead of MS Excel, so that might have been a factor.

**Comment by NAnguiano** [comment]
I tested a few files that I created using LibreOffice and they all ran alright. I've confirmed that it is caused by data outside the matrix causing the spreadsheet controller to work improperly. The solution is to detect data outside of the matrix and report it to the user.

**Comment by NAnguiano** [comment]
The new test file "10-genes-0-edges.xlsx" returns a similar error. I think they may be related, but I'm not fully sure. Grabbing just the adjacency matrix and moving it to a new spreadsheet allows it to load just fine.

**Comment by anuvarsh** [comment]
A unit test was created for this file. It currently fails.

**Comment by NAnguiano** [comment]
I looked into what was going on with this. The spreadsheet controller would throw an error whenever it encountered "NaN" or "undefined" anywhere in the matrix. I put in a check for both NaN and undefined, so those values are currently ignored on the beta.

However, I'm trying to figure out how to alert the user to the existence of these extraneous values. Anu and I thought that maybe creating a new "warnings modal" may work. This modal appears when NaN's and undefineds are detected, and alerts the user to how many it found and where it found them (source genes area, target genes area, matrix area). The graph still loads, but the user is told that while the missing data may be nothing, but it could also be missing genes or missing data within the matrix that is currently being ignored.

**Comment by NAnguiano** [comment]
As a note, currently running make test alerts that 6 tests have failed. Those files were files that previously did not load properly due to either extra data or missing data, but due to the fact that those values are now completely ignored, they are not returning an error any longer.

**Comment by NAnguiano** [comment]
@anuvarsh, I've pushed the code that shows the warnings modal to the beta. There is a little basic message in the bottom left under the sliders that shows if a graph gives warnings (but not errors), and allows the user to view the warnings modal again.

**Comment by NAnguiano** [comment]
Since this issue was about investigating the error with the dCIN5GendronModel1.xlsx file, and the error has since been found and fixed, I'm going to place this under review requested.

**Comment by anuvarsh** [comment]
The failing unit tests have now been updated to match the current warning/error message framework, and all currently pass.

**Comment by kdahlquist** [comment]
Done and closing.
