### ISSUE TITLE
Make Google Analytics client more robust

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#193]
Occasionally, Google Analytics may respond with an error and no data, in a way that terminates the node application. Our GA code needs to be able to handle that.

**Comment by kdahlquist** [comment]
I don't know if this is the same issue, but how quickly should GA update the count of uploaded files?  I did the experiment of uploading a file and then closing and opening my browser to see if the count updates and the pageview counter updated, but not the file uploaded counter.

**Comment by dondi** [comment]
I’ve noticed that the turnaround is not instantaneous…give it a few minutes and reload.

**Comment by dondi** [comment]
A fix for this has been committed. It was tested by artificially simulating an erroneous Google Analytics response. With the fix, the `node` process did not terminate.

Ideally, we can see this happen with a real Google Analytics error, but only time and occasional visits to the console log will be able to confirm that.
