### ISSUE TITLE
Disable weight tooltips for unweighted networks

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#194]
I just noticed this during a student presentation today.  The unweighted networks display tooltips for edges which are all 1.000.  Should we disable this?  Let's discuss at our next design meeting during SURP.

**Comment by kdahlquist** [comment]
Answer is yes; it is useless and potentially misleading information and should not be too hard to exclude.

**Comment by kdahlquist** [comment]
Document this behavior on the website.

**Comment by NAnguiano** [comment]
Tooltips have been disabled for unweighted networks. In the documentation, it only states that tooltips appear under the section talking about weighted graphs. In the last bullet point under the section "If your adjacency matrix is contained in a worksheet entitled “network_optimized_weights” ", it states "If you hover your mouse over an edge on the graph, a tooltip will display the weight value to four significant digits." Should I explicitly state that they do not appear in unweighted graphs?

**Comment by kdahlquist** [comment]
Confirmed it on beta.  There is one other design issue we need to consider:

What should happen when someone has loaded an "network_optimized_weights" sheet but has chosen the option to display it as an unweighted network.  Should the weights appear as tooltips in this case?  I checked on beta; they currently show the (non-1) weight.

**Comment by kdahlquist** [comment]
By the way, I drafted a new release v1.12 and just listed this issue on there so that we could keep track of what is being addressed in the next release.

**Comment by dondi** [comment]
Response from the group was to preserve the tooltips even in black-and-white, as long as the data are there.
