### ISSUE TITLE
Put in News items related to starting Google Analytics

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#195]
Let's put in some retroactive News items that say:

We added Google Analytics tracking to count web page views.

We added Google Analytics tracking to count file uploads.

**Comment by NAnguiano** [comment]
Tracking to count page views was implemented September 18, 2014
Tracking to count uploads was implemented April 13, 2015.

**Comment by NAnguiano** [comment]
The news items have been added.
