### ISSUE TITLE
Add browser requirements to documentation and the about page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#198]
"GRNsight has been tested with (browser names, versions). It may not work with other browsers and versions."

(place in a distinct section called *Compatibility*, on the About page and in the *Getting Started* section of the Documentation page)

**Comment by NAnguiano** [comment]
The browser requirements have been aded to the about page and the documentation page.

**Comment by kdahlquist** [comment]
Upon reading it, I have a suggestion for changing the wording:

GRNsight has been tested with and confirmed to be working in Chrome version 43.0.2357.65 or higher and Firefox version 38.0.1 or higher. It may not work with other browsers and versions. 

On the Documentation page, please insert a paragraph break between the sentence before this one and this sentence.

**Comment by anuvarsh** [comment]
Updated the formatting error and wording on the Documentation and About pages.

**Comment by anuvarsh** [comment]
I added additional information regarding the operating systems that we have tested on.

**Comment by kdahlquist** [comment]
change spelling of OSx to OS X

**Comment by anuvarsh** [comment]
Fixed it!

**Comment by dondi** [comment]
All good, including modification date.
