### ISSUE TITLE
Update Publications page with WCBSURC conference

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#203]
We need to update the Publications page with the WCBSURC information.  Please model it after the other conferences.  Since the poster didn't change from the LMU Symposium, you can just put in the same links for it.

**Comment by anuvarsh** [comment]
WCBSURC information was added to the Publications page.

**Comment by kdahlquist** [comment]
The proper name for the conference is West Coast Biological Sciences Undergraduate Research Conference, i.e., add the word "Research".

**Comment by anuvarsh** [comment]
Fixed it!

**Comment by dondi** [comment]
Good including...date modified :)
