### ISSUE TITLE
Explore array iterator functions: map, filter, reduce

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#208]
Read up on these functions and determine whether their use will improve our test suite.

**Comment by anuvarsh** [comment]
Initially checkGeneCapitalization took in a source gene, target gene, and the input sheet and checked that the source gene was in the network.genes array exactly once, and that the target gene is not in the network.genes array at all using for loops. I refactored the function to take in a gene, a frequency, and the input sheet, so now the function just checks that the given gene is in network.genes at the given frequency (generally will be either 0 or 1) with the filter function.

**Comment by kdahlquist** [comment]
This is not a concrete task, but a stylistic piece of advice, so we are closing now.
