### ISSUE TITLE
Implement browser-side automated testing

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#209]
Some GRNsight functions cannot be tested until the graph is actually rendered by the browser (e.g., edge coloring). For this, _mocha_ is inapplicable. Possible technologies include QUnit, maybe more.

This becomes particularly compelling as the number of testable browser-side functions increases.

**Comment by kdahlquist** [comment]
A partial solution to this is covered by #326, the automated client-side test generator that @eileenchoe has written.  I'm going to label this with "backlog" and close for now.
