### ISSUE TITLE
Review the current error list messages for accuracy/correctness

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#210]
The actual content of the current error list (at this writing, located at https://github.com/dondi/GRNsight/blob/beta/server/controllers/spreadsheet-controller.js#L239) needs to be reviewed.

**Comment by kdahlquist** [comment]
Also @kdahlquist will review the appropriate wiki pages.

**Comment by kdahlquist** [comment]
I'm going to close this because I'm just not going to get to this. I'm labeling it with "backlog" to indicate I'll come back to it if I have time.
