### ISSUE TITLE
Date data type in matrix results in large network size error

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#212]
The test file adjacency-matrix-modifications/data-types/data-type-matrix-time-output.xlsx results in a network size error because the program reads 224 edges. I created a few more test files and the results were as follows:

data-type-matrix-date-output.xlsx: network size error with 15 genes and 224 edges.
data-type-matrix-date-input.xlsx: network size error with 15 genes and 225 edges.

All test files are available in the beta branch.

**Comment by dondi** [comment]
See referenced comment in issue #211 for a note on how this issue was addressed.

**Comment by dondi** [comment]
And oh yes, probably goes without saying, let’s update beta with these changes in time for final review at the 2015-06-24 meeting :)

**Comment by anuvarsh** [comment]
Reviewed this with #211. Closing.
