### ISSUE TITLE
Create a synthetic GRN that shows the range of marker and edge thicknesses

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#214]
For visual testing, it would be convenient to create a synthetic GRN file that shows the full range of markers and edge thicknesses. That way, a single file shows all of the visual possibilities for edges and markers.

Both standard- and self-regulators should be included, with mixed scenarios so that we can see how a node looks with both self-regulatory and standard incoming edges.

Having both increased and decreased regulation may be too much for a single file, so we can break this up into two files if needed.

**Comment by anuvarsh** [comment]
These sheets have been made and are available in test-files/graph-tests/all-negative-weights.xlsx and test-files/graph-tests/all-positive-weights.xlsx.

**Comment by anuvarsh** [comment]
The self-regulating only sheets are also in graph-tests and are called: all-negative-weights-self-regulating.xlsx and all-positive-weights-self-regulating.xlsx

Then there are 4 sheets called: all-negative-weights-from-same-gene.xlsx, all-negative-weights-to-same-gene.xlsx, all-positive-weights-from-same-gene.xlsx, and all-positive-weights-to-same-genes.xlsx that connect all of the genes to a central gene. 

The names of the genes signify the weight of the edges.

**Comment by dondi** [comment]
These look good; they will be useful as we further refine our edge displays.
