### ISSUE TITLE
Release v1.12 at end of SURP 2015

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#217]
Let's release v1.12 at the end of SURP to capture all of the development from the summer.  We will need to update the release notes, About, and News pages (don't forget to change the "last modified" dates).

**Comment by anuvarsh** [comment]
As a reminder, Juan's instructions for creating a release are available here: https://github.com/kdahlquist/GRNmap/wiki/How-To-Create-a-New-Release

**Comment by anuvarsh** [comment]
Completed the version release, and updated the About and News pages (including last modified dates!)

**Comment by kdahlquist** [comment]
The version numbers at the top of the Home and Beta pages need to be updated with v1.12 and v1.13, respectively.  Also, the last modified dates need to be changed on those two pages.

I'll probably have some tweaks to the release notes later, so keep this issue open for now.

**Comment by anuvarsh** [comment]
I updated the version numbers and the last modified dates.

**Comment by kdahlquist** [comment]
I have tweaked the release notes here:  https://github.com/dondi/GRNsight/releases/tag/v1.12
Please replace the text for the release notes on the about page with this (without issue numbers).

**Comment by anuvarsh** [comment]
Edits have been made, and are now live on the website.

**Comment by kdahlquist** [comment]
Can you make the hyperlink in the third bullet point under the label "this wiki page" instead of putting it at the end of the sentence?  Thanks.

**Comment by anuvarsh** [comment]
Revisions have been made, and are live on the website.

**Comment by kdahlquist** [comment]
confirmed
