### ISSUE TITLE
GRNsight server up?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#221]
Is the GRNsight server up?  I just tried the home page and beta page and it timed out.

**Comment by dondi** [comment]
I just checked; it isn't just that the server software is not running, but the machine itself is not reachable. I have notified Masao about this.

**Comment by dondi** [comment]
I have been in communication with Masao and he is aware of the problem. It appears that the machine specifically has gone offline. He is working to either restore or replace it. Meanwhile, I have put up messages on the home and beta pages indicating the outage.

**Comment by kdahlquist** [comment]
@dondi reported that:

"Finally, regarding to GRNsight server, that appears to be a specific machine failure; Masao has set up a new machine, temporarily named grnsight2.cs.lmu.edu, and I'm waiting on some recovery news from the prior server. (we mainly need configuration information for our production/beta separations---the code itself is safely on GitHub, of course) Worst-case scenario is that we will be doing some re-learning, best case is that we just transfer to prior files over."

Does this mean that the configuration information should be documented on the wiki?

**Comment by dondi** [comment]
The GRNsight server is tentatively restored on grnsight2.cs.lmu.edu. If this site proves to be stable, we will rename it as the "new" grnsight and we'll be able to close this issue.

**Comment by kdahlquist** [comment]
What is the status? The math modeling paper is going to be published online in the next week.  It would be great to have the site up since the paper might drive traffic to the site.

**Comment by dondi** [comment]
Oh sorry; to clarify, for outside purposes the site is back up—http://dondi.github.io/GRNsight and http://dondi.github.io/GRNsight/beta.html are back to normal. The finalization steps will incur very little downtime and in fact we can wait on that if we expect a surge soon.

**Comment by kdahlquist** [comment]
Maybe we should do it now to avoid downtime in the future.  Once I turn in the proofs today or Monday, it takes a week for it to come out online.


Kam D. Dahlquist, Ph.D.
Associate Professor of Biology
Loyola Marymount University
http://myweb.lmu.edu/kdahlqui



-------- Original message --------

**Comment by dondi** [comment]
OK I'll contact Masao and work on getting this fully transitioned. This has been up for about a week now and so far has been working well.

**Comment by dondi** [comment]
Restoration should now be complete. Give things a try when you have a chance to verify that things are all up OK. I directly tested both master and beta, plus checked the assorted page counts (including the ones reported on the GRNmap website).

**Comment by kdahlquist** [comment]
I've successfully loaded files on master and beta, so I am going to close this.
