### ISSUE TITLE
We've reached 1000 uploads!

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#222]
Just wanted to let everyone know that we've reached 1000 uploads!  Yesterday it was 999 and today it's 1000.  Maybe we should make a News item to that effect.

**Comment by anuvarsh** [comment]
This news item is now live on the website.

**Comment by kdahlquist** [comment]
Can you revise the wording slightly to this:
Headline text: GRNsight Reaches 1,000 Uploads
Body text: GRNsight reached a total of 1,000 file uploads on the website today.

**Comment by anuvarsh** [comment]
Revisions have been made, and are live on the website.

**Comment by kdahlquist** [comment]
confirmed
