### ISSUE TITLE
Fixes for Contact page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#224]
* The title for Dr. Dionisio and Dr. Fitzpatrick should be "Professor", not "Associate Professor"
* Dr. Dahlquist's address has changed:
 * office location is now Life Sciences Building 289
 * mail code is now "MS 8888"
 * fax number is now 310-338-5317

**Comment by anuvarsh** [comment]
Changes have been made, and are now live on the website.

**Comment by kdahlquist** [comment]
confirmed and closing
