### ISSUE TITLE
Documentation of grnsight.cs.lmu.edu setup

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#226]
The way we do production vs. beta and server vs. client on grnsight.cs.lmu.edu needs to be documented in case a new server need to be set up. A wiki page should do.

**Comment by kdahlquist** [comment]
Because of #238 and the need to give ownership of the server to @anuvarsh, @dondi needs to do this documentation :)

**Comment by dondi** [comment]
An initial version has been written up in https://github.com/dondi/GRNsight/wiki/Server-Setup …@anuvarsh and @mihirsamdarshi can perform the instructions when we “turn over” the server processes to verify the instructions and make suggestions for improving them if needed.

**Comment by dondi** [comment]
@mihirsamdarshi and possibly Eddie will walk through the documentation writeup to validate its content by testing the procedures on the grnsight.cs.lmu.edu server.

**Comment by anuvarsh** [comment]
After considering the information in the documentation write up and the issues faced during out last meeting when trying to pass off server control, it seems as if there are issues in the versions of the dependancies in the package.json file. Particularly, @mihirsamdarshi and I discovered several inconsistencies between what is documented in the [Library Requirements](https://github.com/dondi/GRNsight/wiki/Library-Requirements) wiki page and what is recorded in the package.json file (as mentioned in #254). Before the rest of the setup instructions can be tested, these discrepancies will need to be confirmed one way or the other.

**Comment by dondi** [comment]
@anuvarsh and @dondi have synced up our respective npm versions and @anuvarsh now owns the server processes on grnsight.cs.lmu.edu. We can move on to verifying [Library Requirements](https://github.com/dondi/GRNsight/wiki/Library-Requirements) versions and also addressing #254.

**Comment by dondi** [comment]
The procedures and commands that are in the document have been completed, so we can close this issue.

**Comment by kdahlquist** [comment]
@anuvarsh will update the wiki page:  https://github.com/dondi/GRNsight/wiki/Server-Setup

with what she has documented and then we can close this again.

**Comment by anuvarsh** [comment]
The wiki page has been updated.

**Comment by dondi** [comment]
Changes look good; closing.
