### ISSUE TITLE
Replace test input files with ones that display their test feature

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#227]
The current set of test files are based off of the demo files and are not necessarily specific to displaying the feature that it is testing for.  On an ongoing basis, we should replace the current set of test files with contrived ones that display something specific for that test.

For example, we have a test file that has every edge type and thickness in it.

**Comment by kdahlquist** [comment]
@anuvarsh has created an Excel spreadsheet with details about all of the test files so that @mihirsamdarshi and she can divide and conquer.  Please push the spreadsheet to the repository so all can see.

**Comment by dondi** [comment]
@anuvarsh has shown @mihirsamdarshi how to create test spreadsheets. They will move on to actually writing some tests next.

**Comment by kdahlquist** [comment]
@anuvarsh committed the first draft of the Excel spreadsheet that documents all the files.

**Comment by mihirsamdarshi** [comment]
I did 8-10 test files in my branch. I have had a busy week, but I think that I have gotten the hang of the process.

**Comment by kdahlquist** [comment]
@mihirsamdarshi is continuing to work on this on his branch.

**Comment by mihirsamdarshi** [comment]
i've finished many of the files, i plan to continue working on them, and my goal is to finish all the test files by December 20th.

**Comment by kdahlquist** [comment]
All done and closing.
