### ISSUE TITLE
Should GRNsight web site be converted to markdown?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#228]
@dondi, @NAnguiano and I forgot to ask you this at the meeting yesterday.  @NAnguiano was wondering that now she's converted GRNsight to Jekyll, should she also convert it from HTML to markdown.  This might need further discussion, but I thought I should put it down as an issue before I forgot again.

**Comment by dondi** [comment]
Having undergone a similar conversion to Jekyll for my course websites, I would recommend staying with HTML. This is still the max-flexibility option, and as long as we can handle it I think it's OK to stay with HTML.

Converting to Markdown is useful for pages that do not have specialized formatting. It is also easier to edit for non-technical folks. For pages that fit this profile, then a conversion to Markdown will work.

We can mix HTML and Markdown files, so maybe we can keep HTML for pages that need a lot of customization (master and beta pages; pages with collapsible links or custom JavaScript) but switch to Markdown for pages consisting of more conventional content.

**Comment by kdahlquist** [comment]
I'm OK with staying with HTML completely.  @NAnguiano is going to convert my personal web site to markdown for me, but I think for GRNsight, it will probably be better to not mix them, and HTML is preferred for the reasons @dondi states.  I will close this because the question is answered.
