### ISSUE TITLE
Should we include the functional versions of node/npm in the Library Requirements?

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#230]
In the [Library Requirements](https://github.com/dondi/GRNsight/wiki/Library-Requirements) wiki page, we don't list what versions of node/npm we know function with our back-end. Should we list these?

**Comment by kdahlquist** [comment]
Yes. So guess who gets to do it?

**Comment by kdahlquist** [comment]
This is related to #254.  Name the version that is on grnsight.cs.lmu.edu.  There can be a disclaimer that others will work, but we need to document at least one.

**Comment by mihirsamdarshi** [comment]
I have found and updated the version of npm required. However, in our packages.json file, we can add a bit of code alerting the user to update their version of node if their version is not up to date. More information can be found [here](https://docs.npmjs.com/files/package.json#engines) on the npm wiki.

**Comment by dondi** [comment]
This looks good to me; a warning message will be useful, after which we can close this ticket.

**Comment by dondi** [comment]
The Library Requirements wiki page has been updated with a procedure for keeping up with dependency version changes.
