### ISSUE TITLE
Create package.json for testing dependencies

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#231]
When I went to run `make test` on the beta, I kept getting the error that "node_modules" could not be found. In order to get it to work, I had to manually create a folder called node_modules in the parent directory, and npm install each dependency individually. I think that it would be beneficial for a package.json be created that would automatically create the node_modules folder and install only the necessary dependencies required for testing into the directory, similarly to how a package.json exists in the server and web-client folders.

**Comment by kdahlquist** [comment]
Is this issue closable now due to the work on #286?

**Comment by dondi** [comment]
Ah yes, #286 accomplished this. Closing.
