### ISSUE TITLE
News Flash! Bulletin of Mathematical Biology article published online!

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#232]
Our article has been published online!  Would you please make updates to the News page as follows:

* News page should have a news item for September 29, 2015 that reads:
* Headline: Article describing the sigmoidal dynamical model and penalized least squares approach used by our companion project, GRNmap, is published online in the Bulletin of Mathematical Biology (italicize the journal name and link "GRNmap" to the GRNmap publications page).
* Body text:
Dahlquist, K.D., Fitzpatrick, B.G., Camacho, E.T., Entzminger, S.D., and Wanner, N.C. (2015) Parameter Estimation for Gene Regulatory Networks from Microarray Data: Cold Shock Response in Saccharomyces cerevisiae. Bulletin of Mathematical Biology. DOI: 10.1007/s11538-015-0092-6, Epub ahead of print. (the name of the journal should be italicized)

PubMed Abstract (link that label to this URL: http://www.ncbi.nlm.nih.gov/pubmed/26420504)
View full text in HTML (link that label to this URL: http://link.springer.com/article/10.1007/s11538-015-0092-6/fulltext.html)
Download PDF (1205 KB) link that label to this URL: http://link.springer.com/content/pdf/10.1007%2Fs11538-015-0092-6.pdf
Download electronic supplementary material (65 KB) link that label to this URL: http://link.springer.com/content/esm/art:10.1007/s11538-015-0092-6/file/MediaObjects/11538_2015_92_MOESM1_ESM.zip

**Comment by mihirsamdarshi** [comment]
I updated all the news as requested, I just wanted to see if the work that I did was alright.

**Comment by kdahlquist** [comment]
This looked good.  Since this was updated, the article came out so I added the volume and page numbers to the citation.  Closing.
