### ISSUE TITLE
@anuvarsh and @Nanguiano need access to new GRNsight server

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#233]
@anuvarsh and @Nanguiano need access to new GRNsight server

**Comment by dondi** [comment]
Masao has confirmed that gaining access to the new server should be via SSH key only. Follow the procedure on this page:

https://help.github.com/articles/generating-ssh-keys/

.....for the filename, add *grnsight* or some other distinguisher; for the passphrase, enter nothing if you prefer not to have to enter a password.

Hold on to the key files and wait for further instructions.

**Comment by anuvarsh** [comment]
Created my key files. @dondi, should I go ahead and email them to you?

**Comment by dondi** [comment]
Key files should be treated like passwords, so I think it will be best if you bring them in on a flash drive sometime this week. Keeps the data off the grid :)

**Comment by kdahlquist** [comment]
As of last week @dondi had both keys and passed along the info to Masao, but we don't know the current status.

**Comment by dondi** [comment]
OK, an account has been set up for @anuvarsh. If this goes well, setting up for @NAnguiano when she’s ready will be straightforward.

On any machine from which you want to access the GRNsight server, you will need to do this:
1. Copy your key files to the `~/.ssh` directory.
2. Change permissions to allow just you: `chmod 600 <filename>`
3. Add this entry to the `~/.ssh/config` file (create it if not already there):

    Host grnsight.cs.lmu.edu
         IdentityFile ~/.ssh/<filename of your private key file>
         User <username on GRNsight server>

**Comment by anuvarsh** [comment]
@anuvarsh has successfully gained ssh access to the server. Closing.
