### ISSUE TITLE
Add tutorial links to Links web page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#235]
We should gussy up our Links page with some additional documentation:
* Three Little Circles: http://bost.ocks.org/mike/circles/, an in-depth, technical tutorial on how D3 works.
* @NAnguiano's Jekyll tutorial
* Bootstrap, getbootstrap.com

Let's just remove the section on "presentations" since it is redundant with the Publications page and is also out of date.

**Comment by mihirsamdarshi** [comment]
I added the links, wanted to see if they were ok

**Comment by kdahlquist** [comment]
This looks good.  Let's move the three little circles link under the D3 link for the sake of consistency.

**Comment by mihirsamdarshi** [comment]
done.

**Comment by kdahlquist** [comment]
confirmed and closing
