### ISSUE TITLE
Add @mihirsamdarshi to the People page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#236]
Now that @mihirsamdarshi has joined the group, we need to add him to the People page.  Put his name in alphabetical order by last name as follows:

Mihir Samdarshi (LMU Biology '19) Fall 2015 - present

We should also break out two groupings of students current and former, see how it is organized on the GRNmap People page here:  http://kdahlquist.github.io/GRNmap/people.html

Britain Southwick should go under the "former" category. All others are current.

**Comment by mihirsamdarshi** [comment]
I did this too, wanted to see if what I was doing was correct. I also had a question regarding whether Katrina is a member of the team, because I noticed that she was listed as former on the GRNmap team website.

**Comment by kdahlquist** [comment]
It's OK to add Katrina to the list of former students.  She was there as a consultant the first semester we started GRNsight.

Can you make two further tweaks?
* Indent the names of the students to the right of the headers.
* Alphabetize the student names by last name.

Thanks.

**Comment by mihirsamdarshi** [comment]
both done.

**Comment by kdahlquist** [comment]
The layout of the People page seems messed up.  The footer is appearing at the top of the page next to the picture.  Also, the font size for the student names appears to be smaller than for the other text at that level on the page.

**Comment by kdahlquist** [comment]
The CSS for the footer element should have a `clear: both` property added to it (the last line below):

     #footerNav {
         padding-top: 20px;
         list-style-type: none;
         font-size: 12px;
         text-align: center;
         clear: both;
     }

**Comment by mihirsamdarshi** [comment]
fixed.

**Comment by kdahlquist** [comment]
Page is fixed.  Closing.
