### ISSUE TITLE
GRNsight beta server error

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#238]
The GRNsight beta server failure that was noticed on Thursday afternoon 2015-10-01 has been recovered from; I displayed the demo GRNs successfully.

When looking at the console output, it turned out that the beta server did crash, with the following error (previous 18 messages included for context):
<pre>
GET /demo/weighted 200 18ms - 6.29kb
GET /demo/weighted 200 19ms - 6.29kb
GET /demo/unweighted 200 20ms - 4.51kb
GET /demo/weighted 304 20ms
GET /demo/unweighted 200 18ms - 4.51kb
POST /upload 200 9ms - 603b
POST /upload 200 17ms - 3.2kb
POST /upload 200 11ms - 780b
POST /upload 200 9ms - 603b
POST /upload 400 21ms - 777b
POST /upload 400 5ms - 777b
POST /upload 400 5ms - 1.02kb
POST /upload 400 6ms - 885b
GET /demo/weighted 200 19ms - 6.29kb
POST /upload 200 19ms - 4.04kb
POST /upload 200 19ms - 4.04kb
POST /upload 200 17ms - 1.46kb
GET /demo/unweighted 200 18ms - 4.51kb
FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)
</pre>

I don’t know if this can be replicated, but just in case, I'm recording it here.

**Comment by kdahlquist** [comment]
This is still open since we don't know the conditions under which this happened.

**Comment by kdahlquist** [comment]
@anuvarsh has found another instance of this error.  Control of the server is being transferred from @dondi to @anuvarsh so that she can restart the server.

**Comment by kdahlquist** [comment]
@mihirsamdarshi will write a script to automatically upload file after file to force this error to occur.

The possibilities are that there is a memory leak and it is a certain number of uploads causes this.

Or, there is a certain file or combination of files that is causing this.

**Comment by anuvarsh** [comment]
After writing a few more warnings for issue #242, this issue has come up again when trying to upload the sheet "extra-data-end-of-sheet-input.xlsx". I'm not certain that this exact sheet is what is causing the error, but this is the 2nd time I have gotten this error while trying to upload this sheet.

**Comment by dondi** [comment]
This has been separated into a more specific issue, #253.
