### ISSUE TITLE
Data structure design for reading expression data from GRNmap input/output sheet

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#241]
Our first task for being able to color nodes with expression data is to read the data from the GRNmap input/output workbook.

We need to design the data structure.  We will make a small test workbook with just 3-4 genes with dummy data to use in test-driven design.

**Comment by kdahlquist** [comment]
Reassigned this to @NAnguiano because she is doing this for her 402 project.  Look at the GRNmap project for small test files that can be used for this.  @kdahlquist will confirm the documentation of the new format that GRNmap is using so that there won't be further changes we have to deal with.

**Comment by NAnguiano** [comment]
@kdahlquist : Has the documentation of the new format been confirmed?

**Comment by kdahlquist** [comment]
I haven't had a chance to look at it yet, but I think it is "close enough" for you to start your work.  The relevant wiki pages are:

https://github.com/kdahlquist/GRNmap/wiki/How-to-format-the-input-file-for-GRNmap

https://github.com/kdahlquist/GRNmap/wiki/How-to-interpret-the-output-file-for-GRNmap

https://github.com/kdahlquist/GRNmap/wiki/New-Naming-Convention

**Comment by NAnguiano** [comment]
Alright, I'll start working adding this into the spreadsheet controller then

**Comment by anuvarsh** [comment]
In anticipation of the discussion we were planning to have at our next meeting regarding the data structure design, I have reviewed the previously mentioned wiki pages about GRNmap's input and output sheets.

**Comment by kdahlquist** [comment]
@eileenchoe and I met this morning to discuss this.  One conclusion we drew was that it might be best to design a data structure to read and store the entire output workbook from GRNmap, even if we are not going to use all the data right away.

**Comment by kdahlquist** [comment]
This will be the next priority for @eileenchoe after the release (#557).  @eileenchoe and @kdahlquist will probably need to meet again to document the requirements.

**Comment by dondi** [comment]
@eileenchoe and @kdahlquist will meet on Friday 1/26 to discuss the data structure, which will be a JSON extraction of a GRNmap workbook.

**Comment by kdahlquist** [comment]
Here is an example of a GRNmap output workbook: 

https://github.com/kdahlquist/DahlquistLab/blob/master/data/Spring2018/MO.LK%20Edge%20Deletion%20Data/Control%20Experiments/Missing%20Data%20beta/15-genes_28-edges_db5-MO-LK_Sigmoid_estimation_missing-values_output.xlsx

**Comment by kdahlquist** [comment]
This is the input workbook that corresponds to the input workbook.  You will see that all of the worksheets that occur in the input workbook are also in the output, and then the output has additional ones.

https://github.com/kdahlquist/DahlquistLab/blob/master/data/Spring2018/MO.LK%20Edge%20Deletion%20Data/Control%20Experiments/Missing%20Data%20beta/15-genes_28-edges_db5-MO-LK_Sigmoid_estimation_missing-values.xlsx

**Comment by eileenchoe** [comment]
There are 4 general formatting structures for sheets in a GRNmap (output) workbook:
1. Network
    - network
    - network_weights
    - network_optimized_weights
2. Expression (time series)
    - *_log2_expression
    - *_log2_optimized_expression
    - *_sigmas
3. 2-Column
    - production_rates
    - degradation_rates
    - threshold_b
    - optimized_production_rates
    - optimized_threshold_b 
4. Other
    - optimization_parameters
    - optimization_diagnostics

Note: input workbook sheets are a subset of output workbooks

Here's a first pass at a JSON structure:

```
// Example JSON extraction
var grnmap = {
    // Meta data extracted from "optimization_parameters" sheet
    "meta": {
        "expression_timepoints": [15, 30, 60],
        "simulation_timepoints": [0, 5, 10, 15, 60],
        "strain": ["wt", "dcin5", "dgln3"]
    },
    "data": {
        // Current data structure returned from spreadsheet parsing
        "network": {
            genes: [],
            links: [],
            errors: [],
            warnings: [],
            negativeWeights: [],
            positiveWeights: [],
            sheetType: "weighted"
        },
        // Additional data from spreadsheet of type "2-column" or "expression"
        "production_rates": { // Example JSON extraction of "2-column" type sheet
            "ACE2": 0.2236,
            "ASH1": 0.4332,
            "CIN5": 0.2009,
        },
        "expression": { // There are 3 types: "log2_expression", "log2_optimized_expression", and "sigmas"
            "wt_log2_expression": [ // Example JSON extraction of "log2_expression" type sheet
                {
                    id: "ACE2",
                    data: [
                      {"15": [0.6139, -1.0689, 0.1906, -0.398]},
                      {"30": [0.5827, -0.3947, -0.6264]},
                      {"60": [0.817, 0.5566, -0.4357, -1.2497]}
                    ]
                },
                {
                    id: "ASH1",
                    data: [
                      {"15": [0.97, 0.3043, -0.9904, 0.2636]},
                      {"30": [0.382, 0.4206, -0.4911, -0.1284]},
                      {"60": [0.817, 0.5566, -0.4357, -1.2497]}
                    ]
                },
            ],
            "dcln5_log2_expression": [
                {
                    id: "ACE2",
                    data: [
                      {"15": [0.6139, -1.0689, 0.1906, -0.398]},
                      {"30": [0.5827, -0.3947, -0.6264]},
                      {"60": [0.817, 0.5566, -0.4357, -1.2497]}
                    ]
                },
                {
                    id: "ASH1",
                    data: [
                    {"15": [0.97, 0.3043, -0.9904, 0.2636]},
                    {"30": [0.382, 0.4206, -0.4911, -0.1284]},
                    {"60": [0.817, 0.5566, -0.4357, -1.2497]}
                    ]
                },
            ]
        }
    }
};
```
To start, I've completed a parser for the 2-Column sheet type, since that's the simplest.

**Comment by eileenchoe** [comment]
Thinking it's best to work on DS redesign and node coloring in tandem, so that the JSON structure for expression data is most optimized for use in D3 visualization. @kdahlquist is #27 the issue I should use for node coloring?

**Comment by eileenchoe** [comment]
Looked at http://jsonapi.org/ as a possible standard for formatting JSON output

**Comment by kdahlquist** [comment]
@kdahlquist suggests spending a little time investigating if a JSON exchange format standard exists for the type of data we are using.  Here is a lead:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4152841/

**Comment by eileenchoe** [comment]
Summary of JSON data standard investigation:
- d3 itself is indifferent with regard to json formatting for data
- JSON API is a standard for formatting JSON API _responses_. After looking into it, it is not optimized for formatting data in a way optimal for vis.
- There are a few standards for microarray data:
  - [MIAME (Minimum Information About a Microarray Experiment)](https://www.ncbi.nlm.nih.gov/pubmed/11726920)
    - Suggests what type of metadata to include to ensure reproducibility of experiment, but scope of this standard is limited to what kind of data should be included, not how to format the data
  - ISA Standard
    - Again, focus is on the standard formatting of _metadata_. ISA has a [JSON format](http://isa-specs.readthedocs.io/en/latest/isajson.html)

- For the purpose of the JSON data structure design, I think the best design path is not to follow a data standard, but create a JSON extraction optimized for the end visualization / use of the specific data.
- That being said, there are plenty of suggestions for adhering to common standards for annotations /provenance for the microarray data, however it might best be tackled at the GRNmap level.
- An idea I had is to add an "Export as JSON" option in addition to SIF and GraphML
  - Cytoscape.js does this as documented [in this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4264639/) to allow users to use the JSON representation to create their own visualizations using D3 or other visualization libraries

**Comment by eileenchoe** [comment]
Almost finished with "expression worksheet" parser for sheet types `*_expression`, `*_optimized_expression`, and `_sigmas`. With `*_expression` sheets, we allow for missing data, which I am storing as `null` for now.
```
            "wt_log2_expression": {
                "time_points": [15, 15, 15, 15, 30, 30, 30, 30, 60, 60, 60, 60],
                "data": {
                    "ACE2": [0.6139, -1.0689, 0.1906, -0.398, 0.5827, null, -0.3947, -0.6264, 0.3377, 0.817, 0.5566, -0.4357, -1.2497],
                    "ASH1": [0.97, 0.3043, -0.9904, -0.2636, -0.382, 0.4206, -0.4911, -0.1284, -0.7236, -1.3477, -1.0468, -1.0978, -0.9248]
                },
                ...
            },
            "wt_log2_optimized_expression": {
                "time_points": [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
                "ACE2": [0, -0.09230572, -0.136967224, -0.154635461, -0.158266132, -0.155291879, -0.149718545, -0.143567286, -0.137779738, -0.132729405, -0.128503912, -0.125058771, -0.122296825],
                "ASH1": [0, 1.096090356, 0.500611643, -0.197656961, -0.606102207, -0.711169849, -0.668682351, -0.610959909, -0.596911867, -0.64157642, -0.74020814, -0.880880741, -1.050263345],
                ...
            },
            "wt_sigmas": {
                "time_points": [15, 30, 60],
                "ACE2": [0.731313736, 0.577122317, 0.949486235],
                "ASH1": [0.83342118, 0.436963111, 0.177775427],
                ...
            },
```

**Comment by eileenchoe** [comment]
Completed parsers for all the 3 types of sheets (metadata, expression, and 2-col) in a GRNmap input or output workbook, and integrated it with the current spreadsheet controller. This change did not break any of the other code, because I added on the new data to the current "network" object that is being output from the spreadsheet-controller. Will move on to writing unit tests for new parser before PR for this issue. @kdahlquist what's a good name to generalize the 2-column sheets  (i.e. "production_rates", "degradation_rates", "threshold_b", "optimized_production_rates", and "optimized_threshold_b")? Or, are the data in these sheets distinct and shouldn't be categorized together in the data structure?

**Comment by eileenchoe** [comment]
Completed unit tests. Coverage of `additional-sheet-parser.js` is 100%. PR for this issue is #567

**Comment by eileenchoe** [comment]
"live" on beta v.2.3.3 in the sense that you can open a GRNmap input or output workbook, and the network object printed in the console contains all the additional data from all the sheets

**Comment by kdahlquist** [comment]
I'm closing this since we've moved on from here now.  I'm assuming since the PR passed, it's good.
