### ISSUE TITLE
Experimental Biology Abstracts due November 9

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#244]
The abstracts for the Experimental Biology meeting are due Next Thursday, November 5.  The conference is being held in San Diego on April 2 (Saturday) through April 6 (Wednesday) 2016.  I would like our group to submit abstracts as follows:
* Monica, Kevin, Kevin: wet lab stuff
* @Nwilli31 , @GraceJohnson 
* @tessaam , @khorstmann, @kjacks48
* @NAnguiano , @anuvarsh , @mihirsamdarshi (GRNsight)
I am thinking that @trixr4kdz and @juansc don't want to go since it is a biology-oriented conference, but they can if they want.

Please look up the requirements for the abstracts at the web site: http://experimentalbiology.org/2016/Abstract-Submission/Call-for-Abstracts.aspx and start them on the GRNmap wiki.

Monica, Grace, and Natalie can apply to the Honors Program for funding.  Everyone else needs to apply to the College for student travel funds for a hotel room for 1 or 2 nights.  The Biology Department can cover the abstract fee ($65/abstract) and registration fee ($20/person). Hotel rooms can be shared by members of the same sex to reduce cost.  We will carpool either in a biology van or in individual cars. 

Travel form is found on this site: http://cse.lmu.edu/centerforstudentsuccess/studentravel/; UPDATE: @kdahlquist will submit this form for the group.

The undergraduate poster session is on Saturday and we will present on one other day, but we won't know which one until the abstracts are accepted.  So we'll just have to play it by ear as to which days we attend.

**Comment by anuvarsh** [comment]
Link to the wiki page: https://github.com/dondi/GRNsight/wiki/Experimental-Biology-Abstract-2016

**Comment by anuvarsh** [comment]
Added information regarding node coloring/future directions for GRNsight. 

The Experimental Biology abstract has a character limit of 3,000 and we are currently at 1753 characters. Other guidelines are outlined in the link at the bottom of the abstract wiki page.

**Comment by kdahlquist** [comment]
Abstract submitted.  Now we wait :)
