### ISSUE TITLE
grey out undo reset when sliders are locked

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#245]
Quote from issue #234 :
New site behaviors

There's been some new site behaviors added in that I wanted to note, just in case they were undesired.
1. When the user locks the sliders, the reset button also becomes greyed out. Before it was completely usable, but now the user cannot reset the sliders if they are locked. 

> We agree that this is a desired behavior.

However, I retained the ability for the user to undo a reset while the sliders are locked. Should the undo reset button be greyed out as well? It wouldn't be hard to implement.

> We think that the reset button should be greyed out since we are saying "locked" is "locked".
1. I greyed out the "undo reset" settings option when the undo reset button is disabled. I figured that it wasn't greyed out originally due to a bug, but I figured I'd note it anyways.

> Do you mean in the format menu?  We are confused.

**Comment by kdahlquist** [comment]
This has been done in the context of refactoring the code #234 , so it won't be able to be looked at until the refactoring is done.

**Comment by dondi** [comment]
This issue might be addressed as a straightforward consequence of issue #234. If it is, then fix it; if it isn’t, then don’t sweat it.

**Comment by kdahlquist** [comment]
What is the status of this issue?

**Comment by kdahlquist** [comment]
This is not a priority, but I wanted to know the status of this one so I checked beta v2.0.11.

The Undo reset button is still active when the sliders are locked.  This is not the desired behavior.  When the sliders are locked, they should not be able to be reset or undo reset.

**Comment by mihirsamdarshi** [comment]
addressed by PR #749

**Comment by kdahlquist** [comment]
I'm going to close this one because technically it is fixed in Beta v3.1.17.  However, during testing, I observed some strange interactions between the sliders, the check box, and reset/undo reset buttons.  I will try to document sets of actions in a different issue.
