### ISSUE TITLE
Scheduling research meeting for Spring 2016 

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#246]
We will need to start thinking about a mutually-agreeable time to schedule our research meetings for the Spring semester. The times that I know that we won't be meeting are the times that I am myself in class which are:

Monday 1:10-5:00
Wednesday 1:10-5:00
Thursday 4:20-6:20

If @dondi could chime in with times he is in class, that would be great.  As you are working out your class schedules, if you have choices that would put you in class at the same times as us, that is great, but I understand that there are a lot of moving parts here. We'll start the process of trying to work it out after the registration period.

I will also be giving out the independent study forms for you to turn in for next semester sometime in the next couple of weeks.

**Comment by anuvarsh** [comment]
My class schedule next semester is as following:
![image](https://cloud.githubusercontent.com/assets/8509674/11288409/9e7a0228-8ed8-11e5-985d-5a01c156a1fb.png)

**Comment by dondi** [comment]
My classes are all TR, 9:40, 11:20, and 2:40.

**Comment by mihirsamdarshi** [comment]
My class and sports schedule is:
<img width="1016" alt="screen shot 2015-11-19 at 4 16 51 pm" src="https://cloud.githubusercontent.com/assets/5462077/11288454/0837319a-8ed9-11e5-94f2-1824f6f2156d.png">

**Comment by kdahlquist** [comment]
The best time for all of us to meet in Spring 2016 is

Wednesdays from 11:30-12:30 in @dondi's office in Doolan 106.

We will see you on Wednesday, January 6 at 11:30.

**Comment by kdahlquist** [comment]
Update:

We are actually going to meet in @kdahlquist's office in LSB 289, not @dondi's office.

Meetings will still be on Wednesday from 11:30-12:30 PM, starting on Wed., January 6.
