### ISSUE TITLE
Changes to Documentation page to be in compliance with NAR requirements

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#247]
A requirement for the NAR server issue is that a sample data file be easily accessible to users so that they can confirm data formatting requirements.  Even though the demo files live on in the repository, we should provide a link on the Documentation page so that they can be easily downloaded without going to the repository.

On the Documentation page, for the sentence:

The demonstration file "Demo #1: Unweighted GRN" corresponds to the adjacency matrix shown below.

Add a hyperlink to "Demo #1: Unweighted GRN" that starts a download of the corresponding file.

Same thing for the sentence:

The demonstration file "Demo #2: Weighted GRN" corresponds to the adjacency matrix shown below.

**Comment by kdahlquist** [comment]
In addition, there is a requirement to:

The help pages must include information on how to interpret the results returned by the web server.

I will write a blurb for inclusion on the Documentation page.  Stay posted...

**Comment by anuvarsh** [comment]
Added hyperlinks to Demo Files as specified earlier.

**Comment by kdahlquist** [comment]
@anuvarsh , I'm sending you an e-mail as follows:

I started typing up some text for the documentation page in a word document.  It is attached.  Please create a section 4, below section 3 and above the privacy statement and include the text that is in the word document.  Note that there are some notes in square brackets about hyperlinks to add.

I've put placeholders for the figures in the word document, but am attaching the raw files here.  You will need to play around with laying them out, etc. so they look nice on the web page.

The text is not done yet, but I'd like you to go ahead and put this up when you get a chance.  I'll send more updates when I get a chance.

**Comment by anuvarsh** [comment]
The above changes have been made to the documentation page, and are live on the website. Reassigning for review.

**Comment by kdahlquist** [comment]
I made a bunch more changes to the documentation page; I think it's done, but I'm going to keep this open for a little longer until the NAR proposal is submitted.

@dondi, if you have time, if you could take a look at reducing the file sizes of the images so the page loads faster, that would be great, but is not critical.

**Comment by kdahlquist** [comment]
The proposal is submitted, so I'm closing this.

**Comment by dondi** [comment]
File sizes have been reduced; I also set it up so that clicking on the displayed images will load the full-size ones. Not perfect, but at least full-size remains available.
