### ISSUE TITLE
LMU Symposium Abstract

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#252]
@anuvarsh and @mihirsamdarshi should write a draft of an abstract for the LMU symposium on the GitHub wiki.  Start with a previous abstract and edit for updates and word length.  The abstracts are due 2/12, it would be great to have a draft by our meeting next wednesday, so we can edit in the following week and submit it.

**Comment by anuvarsh** [comment]
The initial draft of the new abstract is available here: https://github.com/dondi/GRNsight/wiki/LMU-Symposium-2016-Abstract. The abstract guidelines (available at http://academics.lmu.edu/symposium/guidelinesforabstracts/abstractoverview/ ) indicate a maximum of 250 words on any submitted abstract. The abstract has been cut down to 261 for now with several other potential deletions highlighted. Deletion of the last 11 words will be finalized during our meeting tomorrow.

**Comment by anuvarsh** [comment]
The abstract has been edited down to 248 words, and is now under the maximum word count.

**Comment by kdahlquist** [comment]
With the edits I just made, this is ready for submission.

**Comment by anuvarsh** [comment]
The abstract has been submitted.
