### ISSUE TITLE
extra-row-end-of-sheet-input.xlsx causes out-of-memory error on production server

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#253]
The extra-data-end-of-sheet-input.xlsx test file produces 1,048,572 warnings (2^20 - 4). On the production server, this number of warnings causes nodejs to run out of memory. We need to accommodate this edge case somehow.

**Comment by dondi** [comment]
This was originally reported as #238 before the specific cause became known.

**Comment by anuvarsh** [comment]
A unit test case has been created for this problem but it is not passing quite yet (still in red cap). 

This is the unit test error:
![image](https://cloud.githubusercontent.com/assets/8509674/13264949/625531b2-da25-11e5-934c-8f177c634f18.png)

This is what I currently have in the code:
![image](https://cloud.githubusercontent.com/assets/8509674/13264973/7e1ef2a2-da25-11e5-9c4b-ecc5313fc491.png)


When I looked at warningsCount in the console, I noticed that it is returning the correct number of warnings, so my best guess is that there is something wrong with pushing the error into the error array or something along those lines.

**Comment by dondi** [comment]
It looks like this can be managed in a reasonable way with the benefit of making the code overall more robust. I would first define this function:

    var addMessageToArray = function (messageArray, message) {
        messageArray.push(message);
    }

This is a helper function that both warnings and errors would now use:

    var addWarning = function (message) {
        addMessageToArray(network.warnings, message);
    };

    var addError = function (message) {
        addMessageToArray(network.errors, message);
    };

Once these functions are in, a search-and-replace can be conducted such that:

    network.warnings.push -----> addWarning
    network.errors.push -----> addError

(note how the argument remains the same, which is why we can search-and-replace)

Once this change has been made, run the test suite; observe how we have not changed any actual behaviors so the test suite will assure us whether something was broken.

After verifying that this change is successful, you can now modify the `addMessageToArray` function so that it performs the count check.

**Comment by anuvarsh** [comment]
I completed this a few days ago and found that the unit tests are not passing, as we expected. 21 unit tests for errors and 16 unit tests for warnings are not recognizing "network" as an object (image below). I found that when I only replaced network.errors.push with addError, 2 unit tests were failing (both were error unit tests). When only network.warnings.push was replaced with addWarning, 35 unit tests failed but they were an assortment of both error unit tests and warning unit tests.

![image](https://cloud.githubusercontent.com/assets/8509674/13627989/5e939366-e583-11e5-8867-8d8e40a944cc.png)

Both instances of missingNetworkError's are resulting in failing unit tests and many but not all instances of noErrors are are resulting in failing unit tests. Some but not all instances of missingTargetWarning, invalidDataWarning, and noWarnings are resulting in failing unit tests as well. 

I also found that when I replaced `network.warnings.push` with `addMessageToArray(network.warnings, message)` and `network.errors.push` with `addMessageToArray(network.errors, message)`, no unit tests failed. 

This is the code I added:
![image](https://cloud.githubusercontent.com/assets/8509674/13628373/7b2497a2-e586-11e5-9bd9-6b4c9441d2ce.png)

**Comment by anuvarsh** [comment]
I pushed the code with both network.warnings.push and network.errors.push replaced with the corresponding function to beta for ease of discussion tomorrow.

**Comment by anuvarsh** [comment]
The reason the `addWarning` and `addError` functions were not working is because they were calling the `network` array before it was defined. Simply adding `network` as a parameter to those functions fixed the problem. All unit tests are passing now.

Updated code:
![image](https://cloud.githubusercontent.com/assets/8509674/13648936/1b573f22-e5f0-11e5-9214-da2c25778a07.png)
