### ISSUE TITLE
NPM package list needs to be updated

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#254]
The existing package list that used by `npm install` when setting up GRNsight is missing `moment`. This should be added to avoid needing to do an individual manual install.

**Comment by dondi** [comment]
We have discovered that other package versions may need to be audited as well, such as node-xlsx.

**Comment by anuvarsh** [comment]
@mihirsamdarshi noticed some other discrepancies between the versions listed in the Library Requirements wiki page and the versions on the package.json file. In addition, I noticed that the start script in package.json was `node app.js` even though we are currently using `nodejs app.js`.

**Comment by mihirsamdarshi** [comment]
I was wondering whether the googleapis package, which is currently at version 2.1.7 is ok to be using with beta, because packages.json lists it as "^1.1.5"  If I'm not mistaken, caret means that GRNsight does not support the next major release of the googleapis package. Is there a way I can check the package independently, because the documentation seems inconsistent?

**Comment by dondi** [comment]
You can use `npm list` or `npm list -g` to see what you have installed in a particular */node_modules* directory (with `-g` listing the globally-installed modules):

http://stackoverflow.com/questions/10972176/find-the-version-of-an-installed-npm-package

Might be useful to compare what `npm list` gives you on your respective installations. The one that I have on grnsight.cs.lmu.edu (i.e., the one that is currently running) is showing `node-xlsx` at version `0.4.0`, as specified by the documentation. You can use `npm list` to see what you have.

**Comment by dondi** [comment]
This is issue has been adjusted as the general "version audit" issue. A new item is to contextualize the different dependencies because not every context needs all dependencies (e.g., mocha et al is only needed for developer installations where unit tests are being run; googleapis is only needed by server for interacting with Google Analytics, etc.).

@mihirsamdarshi and @cazinge can serve as initial verifiers of a "clean room" installation based on the work in this issue.

**Comment by kdahlquist** [comment]
Wiki is now up-to-date.
