### ISSUE TITLE
value-replaced–w-spaces-net-only-input.xlsx causes TypeError

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#255]
When uploading `value-replaced–w-spaces-net-only-input.xlsx` onto the beta site, an Uncaught TypeError appears in the console:
![image](https://cloud.githubusercontent.com/assets/8509674/12876245/c4db4df0-cdb2-11e5-85f3-773da18bc653.png)
The server does not crash, but the graph does not appear. Graph statistics are still reported at the top right corner of the window. The unit test for this file is passing, which indicates a client side issue that is not being caught via unit tests in our current testing framework. This error was replicated multiple times.

**Comment by kdahlquist** [comment]
This should get kicked back to the user as an error so that they can fix it.

**Comment by dondi** [comment]
Still open because it is a web-client issue.

**Comment by anuvarsh** [comment]
Instead of checking this on the web-client side, we will do a type check in the server to make sure that all of the weights are numbers.

**Comment by dondi** [comment]
@anuvarsh has converted this issue from a warning to an error, thus preventing the spreadsheet from fully loading and displaying an error. This results in prior warnings to now also become errors, which we have concluded is the better way to go anyway. (i.e., prior behavior was too forgiving)

**Comment by anuvarsh** [comment]
Though the code is in place and I have manually confirmed that the error is functioning, the unit test code needs to be revisited as it is not currently passing.

**Comment by anuvarsh** [comment]
Slight edits were made so that the unit tests are now running, however it seems as if data-type-header-date-input.xlsx has a different number of errors than it's corresponding output file. This will require some digging.

**Comment by anuvarsh** [comment]
This was fixed last week in the graph-statistics branch. Unit tests associated with this problem are passing.
