### ISSUE TITLE
Investigate libraries that would give us graph properties

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#256]
I am interested in investigating if there are any libraries out there that we can easily adopt/adapt to give us some graph properties of the loaded graph "for free".

Currently, we display the number of nodes and edges.  We could also display the following graph properties:
* diameter: longest of the shortest path lengths between pairs of nodes
* vertex (node) connectivity: minimum number of nodes that need to be removed to disconnect remaining nodes from each other
* edge connectivity: minimum number of nodes that need to be removed to disconnect the remaining nodes from each other
* global clustering coefficient: measure of degree to which nodes in a graph tend to cluster together
* betweenness centrality (for individual nodes): number of shortest paths from all vertices to all others that pass through that node (this could be computed for both the unweighted and weighted graphs)
* degree distribution, in-degree/out-degree bar chart; it seems that there would be many solutions for making the bar chart if we could compute the data properly from the adjacency matrix.

I've tried looking myself and cytoscape.js is one possibility, but it is not clear to me from just their web page, which, if any of the above it can compute.

jsPlumb Toolkit is another possibility.  It seems like it can do some of the things we want, but it has both an open source "community" version and a commercial version.  I don't know enough to tell whether we could effectively use the open source version for what we need.

**Comment by kdahlquist** [comment]
forgot to provide link to jsPlumb: https://jsplumbtoolkit.com/docs/toolkit/graph.html

**Comment by kdahlquist** [comment]
Another feature would be a byproduct of this would be a converter that converts the adjacency matrix to a pairwise interactions.

As a milestone for next week, try loading each of these libraries and mess around with them (run the tests?).

**Comment by dondi** [comment]
@mihirsamdarshi can get started on this while @anuvarsh is wrapping up the errors/warnings infrastructure. The general process here would be:

- Visit the various options listed by @kdahlquist here
- Determine whether the package runs on the server (node) or the browser, or both
- Try out the packages one by one, to get the feel for how they are used
- There is a high likelihood that some kind of conversion will be needed, so a converter function will be an expected part of this work

While in this experimental phase, we just need to see what it takes to compute some subset of the properties listed above. When we get a better feel for the various libraries, we can make a final decision on what to use and how to integrate the graph properties into the display.

**Comment by dondi** [comment]
@mihirsamdarshi has installed them locally and is halfway through putting together some tests to take them through their paces.

**Comment by dondi** [comment]
Two aspects here:
- One is from the use case perspective. Anecdote from GRNmap group regarding an observation with number of nodes vs. edges.
- @mihirsamdarshi will start a branch for the graph work. We can list the graph modules that we are testing in the Node.js requirements.
- @mihirsamdarshi and @anuvarsh and possibly @dondi can meet to investigate how we might inject these libraries into the GRNsight workflow. Likely approach, because these are node, is for the server side to add new properties to the graph object that returned by the GRNsight server upon upload. Then, the web-client (upload.js) can transfer those values to some predetermined location on the GRNsight webapp.

Current location of node and edge count display is here:

https://github.com/dondi/GRNsight/blob/master/web-client/public/js/upload.js#L33

**Comment by dondi** [comment]
Let's try to get enough done so we have something to discuss at the April 6th meeting.

**Comment by dondi** [comment]
Very initial test is verifying proper installation. This can be done through a unit test that `require`s the pertinent library then asserts that it is present.

If there is some need to do more work with the library(ies) prior to integration with the GRNsight server code, these can be done as unit tests as well.

Comparison of graph libraries can potentially be done solely via these unit tests.

**Comment by anuvarsh** [comment]
Cytoscape.js's graph statistics algorithms seem to only directly hit about 1/2 of the graph statistics we were looking for (as listed by Dahlquist in the top comment). The statistics not included are: node and edge connectivity, longest path, global clustering coefficient, and degree distribution. There are functions that we can combine/manipulate to get the information we want for some graph stats, but even then we may end writing the algorithms on our own. 

In general, it is difficult to find graph theory libraries in JavaScript that are able to handle all of those graph stats. Several packages exist in languages including Python, R, C, C++, and .NET (as expected). An issue with using one of those packages is that we would have to implement a new testing suite compatible with Python (or whichever language library we use for calculating graph statistics). 

Currently, we are working on testing the few stats algorithms available via Cytoscape.js on a demo spreadsheet and are searching for other libraries that may fill in the holes.

**Comment by kdahlquist** [comment]
Was jsPlumb a bust then?

**Comment by anuvarsh** [comment]
Yes, jsPlumb had fewer and more simple statistics than Cytoscape

**Comment by dondi** [comment]
I looked at this with @mihirsamdarshi on Tuesday afternoon and I gave some pointers on how to convert our graph representation into the format that Cytoscape expects. It looks pretty straightforward and @mihirsamdarshi thinks he will be able to give it a shot. We can review this at the meeting Wednesday.

**Comment by anuvarsh** [comment]
We started up graph-library-tests.js which will contain the code that @dondi referred to above. The `genes` array of the parsed sheet will become the `node` data in the Cytoscape graph, while the `links` array will become the edges, where `source` and `target` need to be converted from the array index in the parsed `genes` array into the `name` property of the referenced gene.

**Comment by mihirsamdarshi** [comment]
@dondi We are having trouble with the cytoscape library showing up in our test file. [Our code](https://www.dropbox.com/s/5lo6cpxwviiv4uq/Screen%20Shot%202016-04-10%20at%2011.59.54%20AM.png?dl=0) should be correct and follows the [documentation](http://js.cytoscape.org/#getting-started/including-cytoscape.js) on the website to correctly include it. Our console.log in the code shows up false every time we run make test.

**Comment by dondi** [comment]
The `console.log` statement that you have will log the value of `cy == true`. But `cy` is supposed to be the Cytoscape library—highly doubtful that this is merely `true`. Try doing `console.log(cy)` instead and tell me what you get.

**Comment by mihirsamdarshi** [comment]
doing `console.log(cy)` gave me `false`

**Comment by dondi** [comment]
`false` means it’s not installed. Try `npm install`ing it again, or if you are sure that it should be installed, check the location of your node modules to see if the files are there.

**Comment by mihirsamdarshi** [comment]
cytoscape is there, and all the files are present but I'm still getting `false` on the Terminal

**Comment by mihirsamdarshi** [comment]
Yeah, the files were missing for some reason, I deleted the Cytoscape folder and reinstalled it.

**Comment by dondi** [comment]
Ah—so not false anymore?

**Comment by kdahlquist** [comment]
cytoscape.js has been successfully installed.  closing this and opening new issue for exploring what cytoscape can give us
