### ISSUE TITLE
LMU Symposium 2016 Poster

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#257]
We want to have an updated version of our poster by March 9th to leave time for review and edits.

**Comment by anuvarsh** [comment]
An updated version of the poster can be found below. Information was updated or confirmed to be accurate except the Google Analytics graph. Currently, the old graph is outlined with a red box to indicate it must be replaced. I had trouble logging into the GA account so could not do it in advance. Other GA statistics were updated and reflect the data currently presented on the website.

[Varshneya_Samdarshi_LMU_Symposium_2016.pptx](https://github.com/dondi/GRNsight/files/164604/Varshneya_Samdarshi_LMU_Symposium_2016.pptx)

**Comment by dondi** [comment]
The task itself is done and the final copy is linked above; however @anuvarsh has the physical version and she was wondering what to do with it.
