### ISSUE TITLE
Add News item and upload work(s) to Publications for LMU Symposium and Experimental Biology 2016

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#259]
Create a news item for the LMU Symposium 2016. The program is linkable, and can be found here: http://academics.lmu.edu/media/lmuacademics/undergraduateresearchsymposium/documents/ei8ht_Symposium_Long_Program_16_Secured.pdf

**Comment by anuvarsh** [comment]
These have been added to the code. @kdahlquist, is there a link to the poster on SlideShare as of now? Also, the changes have not been pushed because jekyll needed me to update some of the dependencies and one of the dependencies (nokogiri) is taking an impressively long time to install.

**Comment by anuvarsh** [comment]
Will link directly to the powerpoint that is committed in beta instead of putting up the SlideShare.

**Comment by anuvarsh** [comment]
The link has been updated.

**Comment by kdahlquist** [comment]
I made a bunch of changes to both the Publications and News pages, going through and fixing phrasing, links, formatting, etc. I uploaded the poster and slides to SlideShare and linked to them.  I made all of these changes to the html files on the gh-pages branch, I hope that I didn't mess something up for Jekyll.
