### ISSUE TITLE
Stress test for cytoscape.js: unit test with maxed out nodes and edges

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#261]
Now that we've finished the exploration phase, we want to do a "stress" test for cytoscape.js where we create a unit test with an input file with maxed out nodes (75) and edges (150) and a smaller one with nodes fully connected to other nodes.

**Comment by anuvarsh** [comment]
Stress tests have been created for 75-genes-150-edges, 10-genes-max-edges, and 12-genes-max-edges and all of them are passing with ease.
