### ISSUE TITLE
Write the graph report function for cytoscape.js

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#262]
Write the function that calculates the data and produces the report object for the graph properties.

Shortest path to every other node
- a matrix (note that there should be 1's in every place there is an 1 in the adjacency matrix, 0 where there is no possible connection, and an integer for all the other path lengths (note fun things for later here: https://bost.ocks.org/mike/miserables/).

Betweenness centrality
- a list of each node and the value

Once we have the report, then we can code the display and export of the data.

**Comment by kdahlquist** [comment]
1. Refactor the converter function:  take it out of the test code and put it in production code.
2. When converter function is part of code, then work on the reporter function.

**Comment by kdahlquist** [comment]
@anuvarsh did in fact write the graph report function, but she has technical debt and needs to write the test now.  Next time we will do TDD in the right order! :)

**Comment by kdahlquist** [comment]
Because we already wrote a converter from cytoscape to GRNsight, we can make this an option for the user to import their file that way.

**Comment by kdahlquist** [comment]
* @dondi has it running locally.  
* We need to validate the results with answers computed independently.
* Need to get ownership of the servers back from @anuvarsh 
* Once results are verified, then merge branches and release to beta (increment version to 2.1)

**Comment by kdahlquist** [comment]
We need to figure out what is the right shortest path value for a auto-regulatory edge.  Right now it is returning 0, but it seems that it should be 1 and that nodes that are not self-regulatory would be 0.

**Comment by anuvarsh** [comment]
Anything I need to do to pass ownership of the servers?

**Comment by kdahlquist** [comment]
Based on the data @dondi sent me, the first thing I notice is that the orientation of the matrix for shortest path is transposed from how we expect the imported data, i.e., the regulators are the columns and the targets the rows.  It makes sense that we should transpose our report to conform to our expected input data format.

**Comment by kdahlquist** [comment]
I verified the shortest path lengths for the demo 3 file.  The demo 1 is harder because it has 50 edges and it will take me longer.

**Comment by kdahlquist** [comment]
We are downgrading this for the time being, but we are going to deploy the latest beta code on the web in the meantime.

**Comment by dondi** [comment]
As noted in #289 it turns out that the branch on which this work was done came from `beta` and not `master` and thus will need more work before it can be merged back.

**Comment by kdahlquist** [comment]
Does this mean that we won't deploy the beta code?

**Comment by kdahlquist** [comment]
As discussed at our meeting, we will deploy beta.  As discussed in issue #289, we will perhaps pull out code from the graph-statistics branch separately into master after some of the other more pressing issues are resolved.

**Comment by kdahlquist** [comment]
I know we don't want to spend a lot of time on this, but I have some immediate suggestions that, I think, would greatly clarify the interface:

* There is now a left-right scroll (both on Firefox and Chrome) that is kind of annoying because it's not scrolling very far and it doesn't seem to need to be there (at least until the graph statistics are opened).  I hope we can get rid of it.
* The up/down scroll currently hides the link to Graph statistics.  So there is no obvious indication to the user that they could scroll down to get more information.  Can it open far enough to show the Graph Statistics link?
* The Graph Statistics link itself is not obvious that it is a link.  It seems that it should say something like "Click here to display graph statistics" or some such.  I also would be OK with it just automatically opening the graph statistics portion.
* Can we limit the decimal points on the betweenness centrality to 2?

You'll see I put some e-mails out asking what the proper shortest path is between self-referential nodes.

**Comment by kdahlquist** [comment]
Is there a way to "comment out" the graph statistics code until we are ready to deal with it?  It's not a high priority right now and there are known bugs with it.  Thanks.

**Comment by NAnguiano** [comment]
The graph statistics code has been commented out for now.

**Comment by kdahlquist** [comment]
Backlogging because we are putting a freeze on new features for now.  Can re-open in future when we are ready to tackle graph statistics again.
