### ISSUE TITLE
Fall 2016 meeting schedule

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#265]
Tentatively, Mondays at 4:00 works for @dondi , @kdahlquist, @mihirsamdarshi , @anuvarsh  for the Fall 2016 semester.

**Comment by kdahlquist** [comment]
Need to investigate if there is a better time that will fit with @dondi's schedule.

**Comment by kdahlquist** [comment]
It looks like Mondays at 3:45 is going to be a better fit.  Let's all meet in @kdahlquist's office on Monday, 8/29 at 3:45 PM for our first meeting of the semester.

**Comment by NAnguiano** [comment]
I'll be most likely breaking my 4-hour time into 2 2-hour timeslots so I can meet with both Anu and Mihir separately since it doesn't look like we all have a time that overlaps. I can meet on Monday after 11:10am and Tuesday/Thursday after 12:50pm. @anuvarsh @mihirsamdarshi What times would work for you?

**Comment by anuvarsh** [comment]
I will be coming on Mondays after 12:30pm. Because of Labor day, next week I will come in on Tuesday and Thursday for 2 hours each day.

**Comment by kdahlquist** [comment]
Reminder to @mihirsamdarshi to schedule your research time.  It looks like @NAnguiano and @anuvarsh can both work on Mondays after 12:30--are you also available at that time?

**Comment by mihirsamdarshi** [comment]
I'm likely going to come in Mondays after 2 pm, and if I need extra time, Wednesdays and Thursdays after 1:30.

**Comment by NAnguiano** [comment]
Ok, I'll come in at 12:30 on Monday. Does the meeting count as an additional hour, or do you want all coding time to occur outside of the main GRNsight meeting? 12:30 to 4:30 would be 4 hours, but the meeting takes an hour of that. If not, I'll stay until 5:30.

**Comment by kdahlquist** [comment]
There's  some  flexibility, but ideally there would be 4 hours of coding outside of the meeting.

**Comment by kdahlquist** [comment]
@dondi , will you add @yshin4 to the GRNsight project?  @anuvarsh will coordinate with her to meet up and onboard the project.

**Comment by dondi** [comment]
OK, invitation sent.

**Comment by anuvarsh** [comment]
@yshin4 and I will meet on Monday around 1pm to walk through the code and introduce her to the project.

**Comment by kdahlquist** [comment]
Having settled all the team meeting times, I'm going to close this now.
