### ISSUE TITLE
Register persistent URL for GRNsight at BioWeb.me?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#266]
http://www.bioweb.me/ is a service for providing short, persistent URLs for web services.

Should we register with them or do you think that http://dondi.github.io/GRNsight/ will be good enough for the long term?

**Comment by dondi** [comment]
Sounds like a good idea; it would at least clean up the URL so that `dondi` isn't in it (identifies it more with the group). Plus if we move our work to `lmu-bioinformatics` then this shorter URL will not need to change.

So we would go to http://www.bioweb.me/GRNsight, right?

**Comment by kdahlquist** [comment]
Yes, that would be the URL.  Another option would be to just register www.GRNsight.org as a domain name, which would be shorter and simpler, but incur a fee.

A tiny part of me worries about what happens if bioweb.me goes away.

**Comment by kdahlquist** [comment]
As per the discussion between @dondi and @kdahlquist on 5/17, we decided against using bioweb.me because:
1. it is still labeled beta with a copyright notice from 2011, so it is unclear whether this is actually going to be a stable and persistent service
2. we decided against getting our own domain because we have to pay for it and register with a home address
