### ISSUE TITLE
Bug: test failure due to missing file: value-replaced­w-spaces-net-only-input.xlsx

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#272]
One of the reviewers of our BOSC abstract noted that one of the tests failed due to a missing file:

Error: ENOENT: no such file or directory, open 'test-files/adjacency-matrix-modifications/value-replaced­w-spaces-net-only-input.xlsx'

Even though the file seems to be there, the problem arises from a long dash (before the w-spaces) which is represented differently in the Mac file system.

**Comment by dondi** [comment]
The filename has been changed (along with the equivalent name in the test code). As a “hot fix,” the change was made and validated directly in `master` then merged with `beta`. 134 tests passing in `master`. 144 tests passing and 17 failing in `beta`. (the failures were already there beforehand)

**Comment by dondi** [comment]
(just to follow procedure I have added the `review requested` label to this issue, although I don’t think @kdahlquist’s workstations are configured to run the test suite—we can just close if this is enough)

**Comment by kdahlquist** [comment]
I'm not configured to run the test suite, so I'll close this.  In the future, you can assign me "review requested" when it is something that is user verifiable (web site, functionality that a user can see).
