### ISSUE TITLE
LMU.BUILD site for GRNsight (and map)

### ISSUE THREAD

**Issue by bengfitzpatrick** [dondi/GRNsight#276]
I saw the back-and-forth about bioweb.me, and it occurred to me we may be able to do something like

GRNsight.lmu.build

if ITS does the build thing right.  I asked Michelle Yeung about the possibility of research groups having a shared website, and she said she'd look into it.  If you think it's worthwhile, ping Michelle.  maybe enough squeaky wheels will get some grease.

**Comment by kdahlquist** [comment]
I saw the notice about build.  It doesn't solve the problem of the length of the URL; it's still approximately as long as the github one.  I'm also not thrilled about having no control over whether ITS decides to support it in the future (e.g. Lionshare).  I think github has a better chance of being persistent as a URL.

**Comment by bengfitzpatrick** [comment]
that's fine with me. ITS has a poor record of persistence.
