### ISSUE TITLE
Create collapsible sections for Publications page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#279]
I'd like to have collapsible sections on the Publications page like we did at GRNmap:  http://kdahlquist.github.io/GRNmap/publications.html

It should look like the GRNmap page and have the sections in the same order:  Papers, Presentations, Posters

As soon as PeerJ CS puts our manuscript up on the preprint server, we can population the Papers section with a reference to that.

**Comment by mihirsamdarshi** [comment]
I could do this. It seems easy enough.

**Comment by kdahlquist** [comment]
@mihirsamdarshi, did you mean sometime soon or in the Fall.  I'd like to take care of this soon because I want to put up the information about our preprint.

**Comment by kdahlquist** [comment]
Hey--just noticed that we can now assign multiple people to an issue!

**Comment by mihirsamdarshi** [comment]
I actually did this this morning, I'll commit as soon as I get a wifi connection on my laptop.

**Comment by kdahlquist** [comment]
I saw @mihirsamdarshi committed the collapsible sections, can you make one for Papers, too and put it at the top of the page?  Could you put Presentations in the middle and Posters at the bottom?  Thanks.

**Comment by dondi** [comment]
Shall I go ahead and add the PeerJ paper to the new Papers section, or wait until we are past the pre-print stage?

**Comment by dondi** [comment]
Section and placeholder link added.

**Comment by kdahlquist** [comment]
Please add it.  Thanks.

**Comment by dondi** [comment]
OK, it's in. I used the text that they recommended except names are spelled out to match the other entries.

**Comment by kdahlquist** [comment]
Can we reverse the order of the poster and presentation sections and default presentations and posters to closed?

**Comment by kdahlquist** [comment]
I'd like to format the section on the paper like on the GRNmap page here:
http://kdahlquist.github.io/GRNmap/publications.html

I'd try to do it myself, but I'm a little nervous about screwing up the formatting.

**Comment by dondi** [comment]
OK, the above two changes have been made. The format links are different due to the way PeerJ formats the paper; we can make adjustments to whatever labeling is clearest, of course.

**Comment by kdahlquist** [comment]
Confirmed and closing.
