### ISSUE TITLE
Export data to cytoscape sif and graphml format

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#287]
This has been separated from issue #59 because image export is a different issue than data export.

Reviewer 1 comment (#278):

"As it does not accept a standard input file type, the output of any other network analysis package requires conversion in to the matrix format required here. Similarly, the tool provides no export function (the option in the File menu remained stubbornly greyed out) and so I can’t take a network from GRNsight and utilise it elsewhere. I also can’t use GRNsight to convert the GRNmap format to something I might like to use elsewhere.

The authors refer to future features coming in version 2 (lines 323-329). I encourage them to consider implementing at least one standard filetype for displaying graph data within their tool. Be it sif, graphml or even gml, it would significantly increase the utility of the tool as it currently exists."

We need to look into import/export of adjacency matrix in sif, graphml, or gml format.

**Comment by kdahlquist** [comment]
Another format to investigate that was mentioned by a BOSC reviewer is MIMIx.

**Comment by kdahlquist** [comment]
Notes on BioTapestry:  http://www.biotapestry.org/
* written in Java
* latest version 7.0.0, released 9/22/14
* locally installable executable
* BioTapestry Viewer runs in a web browser as of version 7.0.0
* It supports import of 
    * root network from SIF
        * SIF is "simple interaction file", see http://wiki.cytoscape.org/Cytoscape_User_Manual/Network_Formats
        * space-delimited file (except when you want to use space characters, then you should use tab-delimited)
        * Lines in the SIF file specify a source node, a relationship type (or edge type), and one or more target nodes: 
        * nodeA <relationship type> nodeB
        * nodeD <relationship type> nodeE nodeF nodeB
        * where <relationship type> is a two letter code, of which we would use "pd" for protein -> DNA
    * full model hierarchy from CSV

**Comment by kdahlquist** [comment]
I have created a .sif version of the 21-genes_31-edges_Schade-data_input.xlsx demo file that loads in BioTapestry
[21-genes_31-edges_Schade-data_input.sif.zip](https://github.com/dondi/GRNsight/files/376894/21-genes_31-edges_Schade-data_input.sif.zip)
![biotapestry_21-gene_31-edges_schade-data_input sif](https://cloud.githubusercontent.com/assets/6463867/17037682/e915d8be-4f46-11e6-9924-d9f406cdbb4b.png)

**Comment by kdahlquist** [comment]
SIF format can only be used to export unweighted networks (it does not support attributes like weights).  Cytoscape can read SIF (as well as BioTapestry, in previous comment).

**Comment by kdahlquist** [comment]
Notes on yED:  http://www.yworks.com/products/yed
* Stand-alone Java Swing program, requires Java 1.8
* current version is 3.16
* not specific to GRNs or biology (e.g., can be used for UML diagrams)
* File formats that can be imported:
    *  ?, an XML format which supports arbitrary, user-defined element properties (this was blank on the web site, but might be GraphML)
    * Excel® XLS spreadsheets, which can be easily imported using our wizard for comfortably specifying matrix and list-like annotated diagram data. Custom properties can be imported, too.
    * GEDCOM, which contains genealogical information
    * GML, a popular text-based diagram file format
    * arbitrary XML run through an XSLT stylesheet that transforms the input into valid GraphML. 
    * Predefined stylesheets for Ant build scripts, the OWL Web Ontology Language, and others are included.
* free, but not open source
* So I was able to import the demo file 21-genes_31-edges_Schade-data_input.xlsx directly into yED using their Excel import wizard.  See below:
![yed_21-gene_31-edges_schade-data_input-xlsx](https://cloud.githubusercontent.com/assets/6463867/17040804/b28f850a-4f56-11e6-8902-39dd815fb442.png)
* However, the regulators/targets relationship is reversed from what we default to, so I have to transform the "network" sheet to get the directed edges to have the correct directionality.

**Comment by kdahlquist** [comment]
* GML format is described here:  http://www.fim.uni-passau.de/index.php?id=17297&L=1
    * it can be read by Cytoscape and yED
* GraphML format is described here: http://graphml.graphdrawing.org/
    * it can be read by yED

**Comment by dondi** [comment]
Initial design decisions have been made for this functionality, with a SIF export function implemented for non-weighted graphs. Key design decisions are:
- Perform all import/export work on the server side (facilitates unit tests; decouples import/export functionality from web client)
- Define routes that accept `POST` requests with the GRNsight-formatted JSON network to export in the body; the routes then call the import/export function and return the converted result
- Invoke the routes from the web client

**Comment by kdahlquist** [comment]
http://pynetconv.sourceforge.net/ PyNetConv is a python program that can convert cytoscape sif to gml.

I've been searching for additional documentation about SIF format and am puzzled by two things:
* the default is to use a space character as a delimiter, but of course this is a problem if there is a space character in the gene IDs/labels.  So, in this case one uses a tab delimiter instead.  Why not just use tab to begin with and not have two options?  Which did you implement?
* Cytoscape seems to define a certain number of relationship types (http://wiki.cytoscape.org/Cytoscape_User_Manual/Network_Formats), while Pathway Commons(http://www.pathwaycommons.org/pc2/)  uses a different set (and based on my experiments with BioTapestry, it uses a third set).  However, I can only find documentation for SIF through Cytoscape or Pathway Commons.

**Comment by kdahlquist** [comment]
Here is my exploration of Cytoscape for an unweighted network.

Version 3.4.0 (Windows 64-bit)

* Launch Cytoscape
* In "Session" Start-up window, select button "From Network File" button and select the 21-genes_31-edges_Schade-data_input.sif file.
![21-gene_31-edge_schade-data_input_cytoscape-default-view](https://cloud.githubusercontent.com/assets/6463867/17194465/00f5af70-540d-11e6-9076-b9047163f84e.png)
* to see directed edges, go to "style" tab
* click default dropdown
* choose one of three styles that has directed edges:  curved, directed, or marquee
    * directed is the best choice, marquee is animated
![21-gene_31-edge_schade-data_input_cytoscape-directed-view](https://cloud.githubusercontent.com/assets/6463867/17194579/90cd1e4e-540d-11e6-8181-87f206bc599e.png)
* On the node and edge tabs, can set properties.
![21-gene_31-edge_schade-data_input_cytoscape-directed-view-black](https://cloud.githubusercontent.com/assets/6463867/17194704/36b2a158-540e-11e6-8290-d588ca6b792a.png)
* Played with layouts, has yFiles layouts, which I'm pretty sure is the same company as yED.  The best was the yFiles Hierarchic
![21-gene_31-edge_schade-data_input_cytoscape-directed-view-black-hierarchic](https://cloud.githubusercontent.com/assets/6463867/17194811/ff2e1a18-540e-11e6-809e-3f4637e50682.png)

**Comment by kdahlquist** [comment]
OK, here is my exploration of a weighted network in Cytoscape.

I made a .sif file where the relationship type was the weight itself.  This then labeled the edges with the weights.
![21-gene_31-edges_schade-data_estimation_output_cytoscape-edge-weight](https://cloud.githubusercontent.com/assets/6463867/17195651/02c6c828-5414-11e6-8842-9014e393ecd6.png)

I should be able to set edge colors and widths, but I need a little more time to figure it out.

**Comment by kdahlquist** [comment]
Latest Cytoscape user manual v3.4.0: http://manual.cytoscape.org/en/3.4.0/index.html

**Comment by kdahlquist** [comment]
So, it turns out that the stand-alone Cytoscape v3.4.0 can directly import json from cytoscape.js (and export json, too.)
[21-genes_31-edges_Schade-data_estimation_output_weights_json.zip](https://github.com/dondi/GRNsight/files/387371/21-genes_31-edges_Schade-data_estimation_output_weights_json.zip)

I need a break from this right now.  From what I've seen so far we can leave the relationship type for the unweighted network as "pd".  For the weighted network, if we use the actual weight values as the relationship type, they will automatically display on the edges in Cytoscape.  I just don't know whether they need to be specified differently so they can be used as ways to change the color or width of the edges.

**Comment by dondi** [comment]
The first export variant, export to SIF, has been implemented and has replaced the `graph-statistics` branch on the [Beta page](http://dondi.github.io/GRNsight/beta.html). This beta version is set to 1.15. I will log my proposed version roadmap (which is a touch more complicated than usual due to the concurrent development threads that are going on) in #293 right after I finish this comment.

Placeholder menus have been applied for import, export data, and export image, but for now only _Export Data > To SIF_ will work. Once a GRN has been loaded into the application, this menu item will activate. When selected (and if functional), the menu item will then trigger a download that deposits the SIF export to the user's Downloads folder.

While this full-cycle functionality is under review, I will continue with implementation of import/export for the remaining intended formats.

**Comment by dondi** [comment]
Export to GraphML is now available on the beta 1.15 deployment. Workflow is identical to SIF export, except that the resulting file ends in _.graphml_. I used http://graphml.graphdrawing.org/primer/graphml-primer.html as my main reference for putting together the exported data.

**Comment by kdahlquist** [comment]
We are not going to export data in GML format so that we can focus on other issues.  Although @dondi notes that the export would be easier than the import if we ever wanted to do it.

**Comment by dondi** [comment]
GML menu items have been removed from the deployed beta v1.15 (I guess this note applies to #288 too).

**Comment by kdahlquist** [comment]
I am closing this now because basic functionality has been implemented and discussion has moved to #309 and #314.
