### ISSUE TITLE
Consider hiding menu items that are not implemented yet

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#302]
I want us to talk about completely hiding menu items that are not implemented yet.  If they are greyed out, but present, the user is "teased" that they might be usable even though the feature has not been implemented (as happened with one of our reviewers.)  By completely hiding them, we don't set up an expectation in the user's mind that there is some condition which "unlocks" the menu item.

Menu items affected:

* File > Export Image
* Edit > Undo
* Edit > Redo
* Format > Lock Nodes
* The entire Data menu

**Comment by dondi** [comment]
OK, this can be done anytime before we merge to master.

**Comment by dondi** [comment]
This turned out to be pretty straightforward so I went ahead and did this.

**Comment by kdahlquist** [comment]
Looking good!  Closing.
