### ISSUE TITLE
Is upload counter counting import of other filetypes?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#303]
It just occurred to me to ask whether the upload counter is counting these new filetypes we are importing (SIF, GraphML, GML)?

**Comment by dondi** [comment]
That crossed my mind too. It is easy to add if we preserve the same path. Will that be sufficient? Or should we differentiate the type of upload/export?

**Comment by kdahlquist** [comment]
I don't think we need to differentiate if we just want to get the count of how many files are uploaded.  If we want to use this information to judge how popular the different file types are, I guess it might be useful, but do we care?

**Comment by dondi** [comment]
OK, making the counter code execute for both Open and Import turned out to be pretty straightforward, so I've made the change. This is live in beta 1.15.

**Comment by kdahlquist** [comment]
Sounds good.  This is a little difficult for me to test.  I've done one import and will watch the counter to see if it ticks over from 1569 to 1570, but it's not the best test if there's another user out there uploading files.  I also don't quite know how long it will take for Google Analytics to catch up.  Is this something we can observe directly on the Google Analytics dashboard?

**Comment by dondi** [comment]
I recall that there was a "live feed" version of the analytics display. It was somewhere on the sidebar. If that view is active, then you can see changes as they happen. Not sure if it's still there though; we can look later.

**Comment by kdahlquist** [comment]
We looked at the realtime dashboard and did not see anything for Beta import or Master open from @kdahlquist's computer.  However, it works for @dondi's computer.  This may have something to do with anti-malware software that @kdahlquist has installed.

There is still a delay for the counter to refresh, but we will monitor this.

**Comment by kdahlquist** [comment]
The counter refreshed by the end of our meeting, so closing this.
