### ISSUE TITLE
User tests of SIF import: newline bug

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#305]
Breaking this out from #288 as the issues will likely be different for different formats.

So, I did the obvious, which is export our four demo files to .sif using our GRNsight export function and then re-import them with the GRNsight import function.

As expected, no problems.

However, when exploring #301, I modified the demo 2 file in Excel to enable it to import into Cytoscape, but it is now broken for import into GRNsight.  It turns out that opening the exported SIF file for a weighted network and doing Save As text, tab-delimited in Excel breaks it for import into GRNsight.  What happens is that the nodes load, but no edges appear (the edge count is also 0).  I'm not sure what is happening under the hood and I'm attaching one such broken file.

Interestingly, one can do this same set of actions for an unweighted sif file and it's fine.
[Demo #2_ Weighted GRN (21 genes, 50 edges, Dahlquist Lab unpublished data)_resave.zip](https://github.com/dondi/GRNsight/files/394864/Demo.2_.Weighted.GRN.21.genes.50.edges.Dahlquist.Lab.unpublished.data._resave.zip)

**Comment by dondi** [comment]
Agreed, that is puzzling. I opened the file and did not see anything untoward. I did notice that the linebreaks were of the `\r\n` variety, but then if those were the problem, the unweighted sif file should have had issues as well. This will require some additional digging.

**Comment by kdahlquist** [comment]
Yeah.  I guess I can try making a weighted sif file in Excel, "from scratch" and see what happens.

The unweighted and weighted versions differ in the relationship type being "pd", versus a real number.  I thought that datatype encoding might be the issue, but that should be stripped out when saving as .txt.

**Comment by kdahlquist** [comment]
OK, yeah, if I type a small weighted network from scratch in Excel and save as text, tab-delimited, it is broken in the way described above.  So it's something in the way that Excel is saving the file that's doing it.

**Comment by dondi** [comment]
Oddly enough, it did seem to be the different newline convention which prevented proper importing. I modified the SIF importer to handle all newline conventions properly, and when that change was made, the file attached above then imported correctly.

This change has been made live on the beta 1.15 page.

**Comment by kdahlquist** [comment]
This is fixed.  I am going to close this one off and open new issues for anything else I find in testing to keep this granular.
