### ISSUE TITLE
File > Reload does not work with imported files

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#306]
So, File > Reload does not work with an imported SIF file (and presumably with the other imported formats.

We either need to enable Reload to work with imported files or grey this option out when the graph displayed has been imported (preferably the former of the two options).

**Comment by dondi** [comment]
OK, that was one of my pending questions also, whether Reload should apply to imports as well as open (the higher-level question being, is "Import" pretty much identical to an "Open" in terms of behavior, differing only with the file format used; and so far the answer appears to be "yes"). Some additional code is involved but I have a general idea on how to implement this if indeed that is the preference.

Also, if the general idea is that Open and Import are behaviorally the same, then I can approach future issues of functionality in a similar way.

**Comment by kdahlquist** [comment]
Yes, I think that Open and Import are behaviorally the same; we are calling them different things to distinguish that there is a GRNsight "native" file format, whereas the other file formats are not.  We might end up with some features that would not apply to the imported files, but I think the default is to treat them the same.

**Comment by dondi** [comment]
This change has been made and is available on the beta 1.15 page.

**Comment by kdahlquist** [comment]
Confirmed fixed and closing.
