### ISSUE TITLE
Specification of file format for SIF export and import

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#309]
So, I've been looking into more details about SIF format and weighted edges.  

It turns out that Cytoscape considers SIF just a specification of the network connections and to not provide any information about attributes, such as weights for edges.  According to their documentation, edge weights would be provided in an ancillary file, a data table, which (I think) is what is needed to actually color edges or adjust their thicknesses based on the weight values.

As we have already noted, the relationship type is somewhat ill-defined, which is why we can stuff the weight values in there and not have anything break.  The advantage of doing that is that Cytoscape will automatically label the edges with the weight values that way.  However, I guess I'm a little uncomfortable with it because that relationship type is usually defined as a text string (pd, pos, neg, etc.).  In fact, when I draw a new network in Cytoscape and then export it to SIF, the relationship type is set to "interacts with".

So I'm torn between leaving what we have done alone or saying we should modify it, which would mean a necessary loss of information.  We could do "pos"/"neg" or just export all networks as unweighted networks with "pd".

Thoughts?

**Comment by dondi** [comment]
Ah, I didn't realize that the numbers in the second column were not actually read as weights after all. It seems like SIF is not designed to handle weighted edges at all, and if that is true then I wouldn't feel obligated to export SIFs as weighted.

So if we take that off the table, it sounds like the priority becomes whatever has best interoperability with Cytoscape.

Anyway, those are my initial reactions. Might need more discussion.

**Comment by kdahlquist** [comment]
After sleeping on it, I think we should definitely *not* use the weights as the relationship type, which leaves us with two options:
1. export using "pd" for both unweighted and weighted networks, with, a warning to the user that weight data will be lost.
2. export using "pos" and "neg" for positive and negative weight values, respectively.  This could also generate a warning to the user that the weights will be converted.  The advantage of this one is that we retain a little of the information and it can be imported into BioTapestry.

I'm torn between these two options; I feel like we need a third opinion about this.

**Comment by kdahlquist** [comment]
I have another thought for discussion.

The GRNmap team sometimes has need to convert the adjacency matrix to a list of pairwise interactions.  Our export to SIF format gets us partway there, but has the annoying feature of concatenating the target nodes instead of being a true list of binary interactions.  

If the list of binary interactions can be a valid SIF format, then maybe we should do it that way and kill two birds with one stone.  I'll have to run some tests on that.

I think we already talked about exporting to GRNsight .xlxs format is a little more complicated due to writing out an Excel file, but could we write out the adjacency matrix as a tab-delimited text file or .csv?  That would gain us conversion in the other direction, which could be useful (but beyond the scope for our deadline next week.)

**Comment by kdahlquist** [comment]
I talked to Carl about options 1 and 2 for exporting either only unweighted networks or networks with pos/neg/neu as the relationship type.

He voted for exporting weighted networks with interaction types of pos/neg/neu where neu is determined by the edges that we call grey (5% either side of zero).

Of course, we could also give the user the option to export as unweighted or weighted (pos/neg/neu) or with the actual weight values, for that matter.  Ugh.  This is so complicated.

In our discussion, the issue got raised as to what we will expect as to SIF format for weighted networks.  I.e., if we allow pos/neg/neu, how will GRNsight interpret that?  It seems that we would need additional coding to make pink, blue, and grey edges based on those text descriptions.

So, now I'm coming back around to allowing the numerical weight values in the import/export of SIF as being more useful.  Double ugh.

I'm going to think about other things for a while and come back to this later.

**Comment by kdahlquist** [comment]
OK. OK.  I think I've got it in terms of the specification that will be useful to both the GRNmap team and outside users of GRNsight.

1. For SIF export:
    * I want us to export the data in a "pure binary" format, by which I mean that each source-->target relationship gets one line in the file, instead of listing each source once and having the targets on the same line separated by tabs.  I know that this is a change from what you have already coded, but I think it is better in that it is more useful to us than the way it is now and Cytoscape and BioTapestry will still read it (I've confirmed this by testing).  We do not need to list source genes with no targets separately  (and we will need to fix the bug in GRNsight where it can't read such a file properly #301).
    * For unweighted networks, the relationship type will still be "pd".
    * For weighted networks, I think we need to offer the user two choices:
        1.  Export as unweighted network with relationship type "pd"
        2.  Export as weighted network with the numerical values of the weight parameters as the relationship type.  I know that I initiated this discussion about getting rid of this, but after further reflection, I think we should do what we think is useful to us.  It seems silly to get rid of the weight information.  The advantage to us is that we can use this to transform a file from matrix to binary relationship easily so that we can do something else with it.  If the user doesn't like it and wants to further edit the file (to pos/neg/neu), they can do so themselves pretty easily and we don't then have to make any programmatic decisions in that way.
2. For SIF import
   * This needs to be a little more flexible to accept a few different flavors of possible files that will be presented to us.
    * For unweighted networks:
        1. We need to be able to import the SIF format that we are exporting, i.e., a list of pairwise interactions.  We need to properly interpret the file if targetless genes are either included or not included in the list (#301).
        2. We need to be able to import the SIF format where each source node is only listed once, followed by a relationship type and a tab-delimited list of target genes.
        3.  Now, what are we going to do if we receive a space-delimited file?  We already decided that our export is going to do tab-delimited and dispense with any potential problems that way.  But what if we receive a space-delimited file?  In the Cytoscape help, there is a line that says if your file is not parsing properly because you have space characters in a node label, try saving it as tab-delimited.  So, should we just ignore this case and say something in the documentation?  or should we try to handle it?
        4. For unweighted networks, I think we can just ignore what the relationship type text string actually says.  For example, I don't think that we should enforce "pd".  It seems like this text string can be lots of different things, depending on the program, and although we intend GRNsight to visualize GRNs, it is really agnostic as to what type of network it is.  The only hiccup with this would be a case where a source-->target relationship is listed twice on two lines with two different relationship types.  We would just ignore the second (or third, etc.) instance, with or without a warning to the user.
    * For weighted networks:
        1.  Items a, b, and c above are still applicable.
        2.  I think it's safe to say that we can only effectively display weighted networks if the numerical weight value is given as the "relationship type".  I think it is too much for us to be in the business of interpreting text descriptions of weights.
        3.  How is GRNsight deciding whether it is being presented with an unweighted or weighted network?  Is it by finding numbers as the relationship type?  Do we want to signal to the user that there are these two types by having two submenu options to import a weighted or unweighted SIF?  Or are we going to stick with the automatic detection?
        4.  Our preferences option to display a weighted network as an unweighted network should still apply to SIF import (and for that matter GraphML import).
        5.  The issue that you mentioned with regards to GraphML about what happens when not all interactions have weights could potentially occur with weighted SIF files, too.  In both cases, I think a warning to the user something like this applies:  "GRNsight has detected that one or more edges in your network are missing numerical weight values.  Because the algorithm GRNsight uses for determining the arrowhead type and the color and thickness of the edges requires numerical weight values, your graph will display as an unweighted graph with black edges and pointed arrowheads.  If you want to display the network as a weighted graph, please modify your input file to include weight values for all edges."

With @dondi's approval, I think that is it in terms of specifying what should happen.  Implementing this and dealing with #301 should wrap it up for SIF import/export.  Of course, there will be further testing after these changes, but I think I'm clear now as to what behavior I'm expecting.  I'm changing the name of this issue and further discussion of SIF should be on this issue instead of #287 and #288.

**Comment by dondi** [comment]
OK, I'll take that as the authoritative spec for SIF import/export. The export options will add some work in terms of the UI; I’ll see what design can be done that balances effort and usability.

I’ll update when something is available online.

**Comment by dondi** [comment]
As a result of the work done in #301, the first two bullets and item (b) of the third bullet for the SIF export spec have been implemented. The option to export a weighted network as unweighted is the sole item that remains; this one requires additional coding in the UI to present the user with that choice, then relay that to the server, when the current network is weighted.

I will continue with this spec now so that we can close out the SIF import/export task completely. More updates as they get implemented.

**Comment by dondi** [comment]
I spotted a couple of questions in the SIF spec so figured I'll answer them here:

> Now, what are we going to do if we receive a space-delimited file?  We already decided that our export is going to do tab-delimited and dispense with any potential problems that way.  But what if we receive a space-delimited file?  In the Cytoscape help, there is a line that says if your file is not parsing properly because you have space characters in a node label, try saving it as tab-delimited.  So, should we just ignore this case and say something in the documentation?  or should we try to handle it?

Accepting a space-delimited file is more complicated precisely because of that possibility that nodes have spaces in their names. Even without spaces, parsing with spaces is still a touch more complex than parsing with tabs. This feels like something where the extra effort does not align with the benefit. It seems that documentation similar to Cytoscape’s, where we advise users to re-save space-delimited SIF files as tab-delimited (just unconditionally this time, independent of whether nodes have spaces in their names).

> How is GRNsight deciding whether it is being presented with an unweighted or weighted network?  Is it by finding numbers as the relationship type?  Do we want to signal to the user that there are these two types by having two submenu options to import a weighted or unweighted SIF?  Or are we going to stick with the automatic detection?

Yes, the SIF importer pre-scans all of the SIF edges to see if all relationship values parse as numbers. If this is the case, then the graph is imported as weighted. If even one relationship value does not parse as a number, the import switches to unweighted.

Separating the weighted and unweighted SIF export options mainly has the benefit of giving the user the explicit choice of importing a weighted SIF as unweighted. However, the preference for "Default to black edges..." takes care of this anyway. Importing an unweighted SIF as weighted will have no effect, and if the warning is implemented, that’s what the user will see anyway. So given this, I'm inclined to stick with automatic detection, with the added warning if not all edges have weights.

**Comment by dondi** [comment]
The specification given a few comments above should be fully implemented now (as far as I can tell). Please see notes in #283 on how I chose to present the Export-as-Unweighted vs. Export-as-Weighted option when exporting a weighted network. Unit tests were modified or added in order to reflect the spec.

**Comment by kdahlquist** [comment]
Here are my initial observations:

Now that we have the option to export as weighted or unweighted, I think we need to append something to the filename for the user:
* Unweighted to unweighted:  leave as is
* Weighted to unweighted: append "_unweighted" to the filename
* Weighted to weighted:  I'm torn, we could either leave it alone or append "_weighted" to the filename

Currently, the exported SIF files still have lines with source nodes that have no targets.  I want us to leave those out as the default behavior of GRNsight.  You'll see that the sample export files I put in the Documentation are that way.

**Comment by dondi** [comment]
Ah OK, yes I missed that one. But I just realized, if that node has no targets and is also never targeted (i.e., it is completely disconnected), exporting in this way will lose that node. Just want to make sure that this is the intent for nodes such as those.

**Comment by dondi** [comment]
As for the file names, yes I can put that up. Need to think about weighted-to-weighted too.

**Comment by kdahlquist** [comment]
Oh.  I didn't think of that use case.  You're right, we need to leave it the way it is.  We don't want to lose information.  I will make the change in the documentation.  Good catch.

**Comment by dondi** [comment]
I went ahead and chose "leave it alone" when exporting weighted to weighted. Two points influenced this:
- This follows the pattern that we preserve the filename if the original data has not changed type.
- Users might already have something in their naming scheme that signifies a weighted graph to them (like for GRNmap, it is the output files that are weighted), so appending `_weighted` when the original filename might have something already indicating that would be redundant.
The filename logic applies to all exports, so this behavior also happens with GraphML exports.

**Comment by kdahlquist** [comment]
OK, I'm good with that decision.  I've verified that the filename appends in the specified cases, so I think we're done with this issue!  I need to catch up a bit with the documentation, but that is a separate issue #283.
