### ISSUE TITLE
GRNsight-exported GraphML imported into Cytoscape

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#311]
GRNsight-exported GraphML imported into Cytoscape
* seems relatively OK, but have weird bar or hyphen as label on edges

more later...

**Comment by kdahlquist** [comment]
So, figuring this out is obviously related to issue #312, but I'll put notes on this specifically here.

So first the good news:
* The graph displays
* The nodes are labeled correctly (implying that Cytoscape is correctly interpreting the node ID and using it as the Cytoscape name).
* The edge connections are correct.

The "bad" news:
* The relationship type (in the parlance of SIF) is not coming through, which is causing the weird hyphen that is displaying as an edge label as noted in the previous comment to this issue.
    * So, we are not specifying any relationship type in the GraphML we output, which, I think, is why Cytoscape is subsituting a hyphen there (the equivalent of N/A).

The fix (which I have done manually in firstObject)
* Add the key

        <key attr.name="interaction" attr.type="string" for="edge" id="interaction"/>

* Then add to each edge tag

         <data key="interaction">pd</data>

* We already decided to use the relationship type "pd" for SIF and we can use it again here.
* One more thing to add to make our GraphML import into Cytoscape and look like a native-drawn Cytoscape network

       <key attr.name="name" attr.type="string" for="edge" id="name"/>

and

for each edge tag

               <data key="name">ACE2 (pd) YOX1</data>

where "ACE2 (pd) YOX1" is an example of source ID open parens interaction type close parens target ID

Doing this populates the edge table in Cytoscape like it would look like if you did it manually.

Note that we can correctly use the for="edge" even though Cytoscape's own export does not.  It does read it in correctly even though it does not export it correctly.

I'm attaching a sample file that works for Cytoscape.  Note that this is a weighted file, an unweighted one would look the same, except without and edge-value (or what we are going to change to weight).  

[7-genes_10-edges_test_weighted-to-weighted_modified.zip](https://github.com/dondi/GRNsight/files/404728/7-genes_10-edges_test_weighted-to-weighted_modified.zip)

**Comment by dondi** [comment]
OK, this has been implemented. In addition to revising the export unit tests to reflect these changes, I manually imported some GRNsight exports into Cytoscape, and saw the expected data in the Edge Table. This should be on the current deployed beta now.

**Comment by kdahlquist** [comment]
Haven't had a chance to review this yet.  I will get to it tomorrow.

**Comment by kdahlquist** [comment]
I have confirmed that the requested changes are working.  Closing now.
