### ISSUE TITLE
Release notes for v1.18

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#313]
I think we should start working on some release notes for v1.16 so we can keep track of what features and issues are related to the release.

* Implemented import of network data from SIF (*.sif) format #287, #301, #305, #306, #309
* Implemented export of network data to SIF (*.sif) format #288, #301, #309
* Implemented import of network data from GraphML (*.graphml) format #287, #306, #312, #314, #321 *
* Implemented export of network data to GraphML (*.graphml) format #288, #310, #311, #314
* Menu items for features that are not yet implemented are hidden #302 
* The true filenames of the demo files now display in the menu bar #308
* Fixed bug where weights were not displaying upon edge mouseover by new implementation of the feature #284

**Comment by dondi** [comment]
With the import/export issues closing out, looks like we are close to releasing 1.16 and merging `import-export` into `master`? That will then leave us with mouseover as beta 1.17/release 1.18.

**Comment by kdahlquist** [comment]
Now that I can directly look at a yED-exported GraphML file #310, I want to see how close we might be to fixing this via the kitchen sink approach.

I want to catch up on the documentation #283 before doing an official release.  I haven't written any of the section on formatting a GraphML file for import yet.

But, in principal, yes, what you suggest seems like  a good game plan.

**Comment by kdahlquist** [comment]
We will release v1.18 #323 without an intermediate v1.16.

**Comment by kdahlquist** [comment]
Hey--this can be closed!
