### ISSUE TITLE
Modifications to demo files #3 and #4 to be consistent with manuscript

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#315]
I  made some minor modifications to demo files 3 and 4 to make the screenshots that are in the manuscript.  The modifications were:
* change cell A1 to read "cols regulators/rows targets"
* alphabatize the rows and columns of the adjacency matrix
* restrict the weight values to 4 decimal places for the weighted network

I want to substitute these files for the ones that we are currently using.  Is that as straightforward as replacing them in the repository or does it have downstream affects because they are not actually being directly read for demo display?

I want to also swap out the examples used in the Documentation page for the same ones that are in the paper so that the images are consistent.

I'm preparing additional files/images for the documentation of the SIF format and want the example of which file I'm using to be consistent throughout.  It's easier to use 3 and 4 because its a smaller network than 1 and 2.

**Comment by dondi** [comment]
The files should be processed no differently from a regular "Open," so if it opens up fine, then dropping it on top of the existing demo file should be OK. We can always back out the commit if there's something off, but I don't expect it.

**Comment by kdahlquist** [comment]
So, which branch should I commit this to?  The documentation itself is being committed to gh-pages, but should the demo files go to the import-export branch?

**Comment by dondi** [comment]
Yes, let’s do `import-export`. That way, on the next iteration, the updated demo files can be tested and verified with the same build.

**Comment by kdahlquist** [comment]
OK.  I'll get to this a little later--don't want to lose my train of thought right now...

**Comment by dondi** [comment]
The updated demo files work for me on the newly-deployed beta site.

**Comment by kdahlquist** [comment]
I didn't actually upload them on Friday because I ran out of time.  I had uploaded the .sif files, not the .xlsx before I left for the day.

However, they are uploaded now on the import-export branch.

**Comment by dondi** [comment]
Ah it must have been the .sif's that I saw come in then. OK, I can try this out.

**Comment by dondi** [comment]
OK the files are up on beta and there don’t appear to be any issues with the change-up.

**Comment by kdahlquist** [comment]
It looks OK to me, too, but I can't see "under the hood".  I'll close this one; I still have a little to catch up on with regards to the changeovers on documentation, but that's another issue #283.
