### ISSUE TITLE
Redo Figure 4 to be consistent with new beta UI

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#322]
Now that we've hidden the data menu, we should probably redo the screenshot for Figure 4 to reflect this.

If we end up with buttons on the page that control display of the edge weights, that would be another reason to redo the screenshot.  #284, #285.

**Comment by dondi** [comment]
This has been pushed to the _figures_ folder under PeerJ.

**Comment by kdahlquist** [comment]
A couple of comments:
1. I would rather that this new version not replace the previous one in the repository.  I would like there to be an easily accessible record of what was originally submitted (v1).  I started a new folder for revisions so that the revised version would be separate from the original submitted version, can you put the revised figure 4 there and restore the originally submitted version to the figures folder?  
2.  The original figure showed the network in its state after the force layout without manual manipulation.  Can we have another version like that instead of showing the layout manually manipulated?

**Comment by kdahlquist** [comment]
I guess the same comment applies to Table 1 as well with regards to preserving the submitted version.

**Comment by dondi** [comment]
OK, the prior files have been restored and the new versions are in the _revisions/_ folder under the same filenames. The version with no manual manipulation has the same filename but with _-auto_ appended to it.

**Comment by kdahlquist** [comment]
Thanks.  I'm going to close this one.
