### ISSUE TITLE
Revisiting semantic versioning

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#324]
I had a thought that we should be in the habit of using all three numbers for semantic versioning so that we won't forget the third number in the future when releasing (so npm and biojs can be updated).a

That means that we should add the third number to the beta as in 1.19.0 or 1.19.1.

The advantage to this is that we can update the third number on beta as new versions are made live for testing and we won't have the version gaps that we just did moving from 1.12 to 1.18.1.

Thoughts?

**Comment by dondi** [comment]
True, that use of minor versions to track betas-in-progress will be useful. Using all three numbers when called for is no problem. It just looks redundant when the trailing values are zeroes.

**Comment by kdahlquist** [comment]
Yes, but I think consistency (and aiding our memory) trumps redundancy in this case.

**Comment by kdahlquist** [comment]
If we bump the beta to 1.19.1, then I think we can close this with the understanding that we will always use three numbers in the future.

**Comment by kdahlquist** [comment]
There are three package.json files that need to be updated.  @dondi can edit those in beta.

**Comment by dondi** [comment]
Beta version number has been set to 1.19.1 in the package.json files and the website.

**Comment by kdahlquist** [comment]
Confirmed (at least what I can see) and closing.
