### ISSUE TITLE
Consider adding Code of Conduct to GRNsight

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#325]
We should consider adding a Code of Conduct to the GRNsight project.  Let's discuss this at an early face-to-face meeting this semester.

See:  http://contributor-covenant.org/

**Comment by kdahlquist** [comment]
Everyone should read and at our next meeting we will vote to adopt this.

**Comment by NAnguiano** [comment]
I've read over the Code of Conduct and think it would be a great addition to GRNsight.

**Comment by anuvarsh** [comment]
I've read over the Code of Conduct, and absolutely agree to add it to GRNsight.

**Comment by mihirsamdarshi** [comment]
I agree that it would be a good add.

**Comment by kdahlquist** [comment]
I'll proceed with adjusting the language and adding it to the project.

**Comment by yshin4** [comment]
I've read and agree.

**Comment by kdahlquist** [comment]
The code of conduct has been added.  I think we need to reference it on the About page.

Lets rearrange the collapsible sections and add a new one called "Code of Conduct".  The order of the sections should be:
* Availability
* Compatibility
* Release Notes
* Funding
* Privacy
* Code of Conduct

The Code of Conduct needs to be a new collapsible section.  The text inside the section should read:

This project has been released with a Contributor Code of Conduct. Participants in this project have agreed to abide by its terms.  The full Code of Conduct can be read [here](https://github.com/dondi/GRNsight/blob/master/CODE_OF_CONDUCT.md).

I am assigning the task of updating the About page to @yshin4.

**Comment by yshin4** [comment]
@kdahlquist  Do you want 'privacy statement' to be changed to Privacy?
Was wondering if that was a change you wanted to make as well or just a typo.

**Comment by kdahlquist** [comment]
Good catch, it was a typo.  I'll revise the comment above about it.

**Comment by yshin4** [comment]
@kdahlquist  Please review.

**Comment by kdahlquist** [comment]
confirmed and closing
