### ISSUE TITLE
Add Jen to People page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#328]
@yshin4, one of your first tasks will be to add your name to the People page on the website here:  http://dondi.github.io/GRNsight/people.html

Please follow the format of what you see there.

Please also move Nicole back to the Current Students list.

Finally, don't forget to update the last modified date.

@anuvarsh can show you how to do this on Monday when you meet if you have questions.

**Comment by yshin4** [comment]
Done.

**Comment by kdahlquist** [comment]
@yshin4, in the future our process is to mark something with the label "review requested" when you are finished and to reassign it to either me or @dondi for review.  We then close issues at the meeting.  See you next week!

**Comment by yshin4** [comment]
Sorry about that! Will do so next time.
