### ISSUE TITLE
Journal club by @NAnguiano on Monday, 9/26, 3:00PM, LSB 118

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#331]
As part of her BIOL 367T independent study, @NAnguiano needs to give a journal club presentation.  We are scheduling this for Monday, September 26 at 3:00PM in the first floor conference room of the LSB, room 118.  I would like all GRNsight and GRNmap team members to attend, if you are available.

She will be presenting a paper relevant to both groups:

[Jacomy, M., Venturini, T., Heymann, S., & Bastian, M. (2014). ForceAtlas2, a continuous graph layout algorithm for handy network visualization designed for the Gephi software. PloS one, 9(6), e98679.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0098679)

**Comment by NAnguiano** [comment]
The presentation has been done as of last week.
