### ISSUE TITLE
Reduce white space one either side of gene label

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#333]
I've noticed this a few times now, but I think we need to reduce the white space on either side of the label in a node rectangle.  As the labels get wider, the white space does as well and it's using up too much real estate.  This is related to another issue #318.

**Comment by yshin4** [comment]
Reduced white spaces for Nodes. Waiting for it to get applied.

**Comment by kdahlquist** [comment]
It looks like this is now live on beta.  It looks good for the short node names we use for the demo files, but note that if you use a really long gene name (up to the 12 characters we allow), the white space gets bigger proportionally to the label, so for large labels, the white space is still too large.  It would be nice if it was a fixed width, no matter how long the label, but I don't know how easy that would be to implement.

This still remains a low priority issue for now.

**Comment by kdahlquist** [comment]
Moving this up to priority 0 and assigning to @yshin4.  The fix she previously implemented reduced the white space, but the problem is that it still gets proportionally longer as the label gets longer.  The white space needs to be a fixed length (and narrow) as the label gets longer.

This is related to issue #318, which is getting a priority 0.5 to be handled next (or maybe in tandem if the two issues are tied up with each other).

**Comment by yshin4** [comment]
After looking for a way to figure out a better formula and trying things out on different sized gene name nodes, settled on a formula for now. The white space is reduced and the letter doesn't go out of the node, but does not have equal spaces before and after the gene names for different sized nodes.

Talk to @NAnguiano and decided that @yshin4 will look more in to the svg part of the node data and figure how to acquire word width other than using the length of the gene name.

**Comment by yshin4** [comment]
This is for myself, where I can take a look when I get back to work: http://stackoverflow.com/questions/118241/calculate-text-width-with-javascript

var element = document.getElementById ("mytext");
var width = element.clientWidth;
var height = element.clientHeight;

Trying to look for the 'width' of the text in the node. Inspecting seems to show the width but don't know how to get that data yet.

**Comment by yshin4** [comment]
http://stackoverflow.com/questions/1636842/svg-get-text-element-width

**Comment by dondi** [comment]
This looks like a good lead; carry on :ok_hand:

**Comment by yshin4** [comment]
I am trying to use 
var bbox = textElement.getBBox();
var width = bbox.width;
to get the width of the text, but I don't know what SVG version we have and apparently it only works for 1.1 and above. Once I can accessthe width of the text element I will be able to modify the box accordingly.

**Comment by yshin4** [comment]
Trying to find the way to acquire text element's width that can be seen from inspecting the graph on site. However, because we use existing node data to create the graph through svg, I dont think I have a div to access for the text element. I tried to use the BBox() but our svg is 0.1.0 while using BBox I need svg 1.1. Will research more to get html elements (text width) directly.

**Comment by yshin4** [comment]
@dondi helped me out with the svg issues I was having. Now I am able to access the text width per node data and set the dx accordingly. In addition, I can fix the size of the rectangle for the node without using getNodeWidth function (which used number of characters of the gene and magic numbers to set the value) , by using the same method I used to get text width. Now I have to modify the numbers accordingly so there is enough white space on both left and right sides of the text within the rect box.

**Comment by yshin4** [comment]
As written for pull request: 

Reduced white space and my test file looked like below which clearly contains some edge issues.

![image](https://cloud.githubusercontent.com/assets/16246811/24820513/485b5adc-1b9e-11e7-97cf-dda365b627a4.png)

I adjusted all previous code that returned proportional values using character length so that the nodes have fixed length of white space in addition to the text width. Now, it looks like the image below.

![image](https://cloud.githubusercontent.com/assets/16246811/24820592/b85d18e8-1b9e-11e7-8e1e-a2d8bc3f3834.png)

I checked the demo files as well and they seemed to be fine to me but please tell me when anyone sees something wrong with the nodes.

**Comment by yshin4** [comment]
@kdahlquist 

Please review and kindly tell me if there are any changes you would like me to make.

**Comment by kdahlquist** [comment]
@yshin4, final review has to take place when the functionality is live on beta.

I've been thinking about it and I think there needs to be a minimum box size that is larger than the skinny ones that now occur when using a single letter (or 2) for the node label.  Looking at the screenshot above, it seems like the width of four w's is the right size for a minimum. [wwww]

I.e., if the width is going to turn out to be smaller than [wwww], then size it to the size of four w's.

**Comment by yshin4** [comment]
Will be working on this right now, @kdahlquist thank you so much for the excel files!

**Comment by yshin4** [comment]
![image](https://cloud.githubusercontent.com/assets/16246811/25160881/8ed74dd6-246d-11e7-8e18-1224c676a208.png)

Added requested edition. Will be working on arrowhead sizes and request for merge.

**Comment by kdahlquist** [comment]
The widths are looking good.  Obviously, the self-referential arrows still need a little work.

**Comment by kdahlquist** [comment]
I looked at this live on beta v2.0.5 and it looks good.  Since the self-referential arrows have their own issue #318, I'm closing this one.  Nice work @yshin4!
