### ISSUE TITLE
npm packages not currently on package.json

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#334]
@NAnguiano and @anuvarsh discovered that the following libraries are not currently on the package.json and will need to be added:

* cytoscape
* xmlbuilder 
* xml2js

We will also need to confirm with @yshin4 that these are the only libraries she needed to npm install individually when she set up the GRNsight repo on her machine.

**Comment by kdahlquist** [comment]
`npm install --save` will both perform the install and modify a package.json file if it finds one.

@yshin4 will post error she gets with npm install, and with jekyll

**Comment by kdahlquist** [comment]
@yshin4 should do the dev version of npm install.

**Comment by yshin4** [comment]
Met up with @NAnguiano today to discuss & fix npm install issues.
Discovered that my node_modules file had way for files than @NAnguiano 's node_modules file.
Tried both Node 6.7 and 4.6 but got errors for both so seems to be not a Node problem.
For npm install -g --dev I got multiple errors and warnings which seemed to be repeating itself.


![k-20160928-444006](https://cloud.githubusercontent.com/assets/16246811/18928696/094799be-8576-11e6-9482-5991f14e654a.png)

**Comment by yshin4** [comment]
I think we need @dondi 's assistance for this problem.

**Comment by dondi** [comment]
OK, find me in the office or lab sometime and we can work on this.

But in general when things get messy like this I typically just blow away the existing `node_modules` directory then start over. I would stay away from the `-g` ("global") argument and in fact if you’ve been using that, I suggest looking up where the global libraries are stored then erasing those also. That way things are clean and you have a node setup that varies without overlap across project locations.

**Comment by dondi** [comment]
The only "downside" (if one might even consider it to be that) of the "no `-g`" approach is that you might have multiple copies of the same library in different locations on your computer. However, short of the extra space, sometimes even this is not a disadvantage because some projects might require different _versions_ of the same package, so you would need multiple copies anyway.

**Comment by anuvarsh** [comment]
@NAnguiano and I were getting different results when running make test on the same commit. I deleted my node_modules and tried to npm install them all back, but I am getting a Segmentation Fault: 11. I also tried individually installing each of the dependencies according to what @NAnguiano had but I still received the same error.

This is particularly interesting because @yshin4 was getting the same error last week when trying to run GRNsight locally after running npm install. 

![image](https://cloud.githubusercontent.com/assets/8509674/19052931/9a63b6f8-896d-11e6-952d-5f812e7a7317.png)

Not super sure how to proceed/what to try next.

**Comment by yshin4** [comment]
Tried npm install in server and web client and found out package is missing
moment in addition to xmlbuilder and xml2js which already has been addressed.

**Comment by kdahlquist** [comment]
@kdahlquist says make sure that the wiki documentation is up to date and that there is a protocol for how to use npm install for newbies that come to the project after you have all graduated.

**Comment by kdahlquist** [comment]
@dondi says:  target case: fresh clone, npm install, that's it.

**Comment by anuvarsh** [comment]
In order to fix this problem, @anuvarsh had to delete all node_modules at a global and local level, reinstall node, and then try npm installing everything onto a fresh clone of GRNsight.

**Comment by kdahlquist** [comment]
@anuvarsh has a "virgin" bio department laptop for @yshin4 to use, if needed.  @anuvarsh will get with @yshin4 tomorrow (Tuesday) and see if they can get her up and running; if not, use the department laptop.

**Comment by yshin4** [comment]
Tried completely deleting Nodejs and wiped the repo out and recloned/redownloaded both.
npm install was successful but installed more files in node_modules than it should have. 
make test gave me an error. 

![k-20161004-422905](https://cloud.githubusercontent.com/assets/16246811/19087929/ba92d6dc-8a28-11e6-9a44-08493ed02718.png)
![k-20161004-423120](https://cloud.githubusercontent.com/assets/16246811/19087928/ba90165e-8a28-11e6-8134-499be310c087.png)

Currently installed gitbash/Nodejs6.7/make on department laptop and cloned grnsight repo.
However cmd/gitbash does not recognize make even though i downloaded the same files which worked on my laptop. I tried rebooting and reinstalling but it still didn't work.

**Comment by kdahlquist** [comment]
@yshin4 and @dondi, please find a time when the two of you can sit down and work this out sometime this week, so that @yshin4 can get past this hump and work with the group at their normal meeting time on Monday.  Thanks.

**Comment by yshin4** [comment]
@dondi, can i visit you at 1 today if you don't have any other appointments? I was going to go tomorrow but my 12:40-2:10 class got canceled today so I'm free during your office hours.

**Comment by dondi** [comment]
Sorry just saw this—yes I should be available but a little later. Had to go grab some food. How late will you be around?

**Comment by dondi** [comment]
@yshin4 is now unstuck, and with it comes an adjustment to the test command.

The blocking issue, which actually remains unresolved, is the `make` command on these machines. It is rejecting the scripted `mocha` command that is supposed to run.

@dondi ran the `mocha` command directly and everything worked (once the needed installs were added).

To circumvent `make`, @dondi has added the test command to _package.json_ instead. With this addition, we no longer need make. Instead, developers can type:

    npm test

And this will do what `make test` used to do (and still does, when `make` is functioning).

This change was pushed to `beta` but can eventually find its way to `master`.

**Comment by kdahlquist** [comment]
Need two more for both server and client package.json:
* express
* stylus

Please update and mark as review requested.

**Comment by kdahlquist** [comment]
This was tested on Anu's newly wiped hard drive--closing!
