### ISSUE TITLE
Beta is giving 502 (Bad Gateway) on demos and uploads

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#337]
![image](https://cloud.githubusercontent.com/assets/8509674/19056542/b53c72a6-897e-11e6-8147-52db66f28a91.png)

See above

**Comment by NAnguiano** [comment]
Beta initially had an out of memory error and had gone down. We should create a test that tests a file that would cause it to go out of memory and ensure that the server doesn't go down.

**Comment by kdahlquist** [comment]
Should this issue be closed and a new one opened with the task @NAnguiano suggested in the previous comment?

**Comment by dondi** [comment]
Agreed, and done.
