### ISSUE TITLE
Improve server-side logging to capture the filename that crashes it

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#341]
From #340, the only issue is that if the out-of-memory error is caused by something else.  We don't have a sophisticated enough log on the server side that records the file that was being uploaded right when it died.

**Comment by kdahlquist** [comment]
Is this something easy to address that either @igreen1  or @luluriffic could tackle?

**Comment by dondi** [comment]
Seemed to have been reopened but then again not observed further in the past few years
