### ISSUE TITLE
Create a warning for Cytoscape Graph Statistics Report Failure

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#343]
Whenever there is a special character in a file, cytoscape throws an error and graph statistics are not calculated. Right now, there is only a console.log that indicates that graph statistics failed to complete, but a proper warning should probably be created.

As far as I can tell, graph statistics are only not calculated in the event of a special character in a node name.

**Comment by kdahlquist** [comment]
For clarification, the graph still displays, but it's just the graph statistics that aren't calculated?

What special characters are involved?  All of them? or are "-" and/or "_" exempt?

**Comment by NAnguiano** [comment]
Yes. The graph displays properly, but the graph statistics aren't calculated. The special characters that throw errors seem to be everything but "-" and "_".

**Comment by kdahlquist** [comment]
What is the status of this issue? I think we might have implemented tests checking for all special characters?

**Comment by NAnguiano** [comment]
It looks like the issue has been resolved. Running the tests with the graph statistics code re-enabled no longer causes errors.

**Comment by kdahlquist** [comment]
Someone else needs to test this to make sure there are no errors and then we can close.

**Comment by yshin4** [comment]
Verified this did not print out any errors and going to close this one.
