### ISSUE TITLE
Make bounding box/zoom/scrolling/size toggle-able

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#345]
To make design decisions for issue #159, @NAnguiano will make toggle switches independently for the following:
1. Size of box
2. zoom
3. scrolling
4. box constrains layout or "infinite" box

Once we can turn them on and off independently we can see what combinations of things do what and make further decisions.

Make check boxes on the UI so we can do live testing.

Bootstrap has default values for sizes:
XS
S
M
L
XL
based solely on width, then we can set height based on aspect ratio, like 16:9 to start.

**Comment by kdahlquist** [comment]
Also, see notes on #159.

**Comment by kdahlquist** [comment]
@NAnguiano has made some switches for the bounding box size, but reload isn't working #347 .  Want to reload the graph when box gets smaller.

When working on zooming, realized that D3 has moved on to version 4 and we're using version 3.  We will *NOT* upgrade to version 4 at this time.

Scrolling is implemented but is buggy when the screen has scroll bars, too.

Has not worked on infinite vs finite box.

**Comment by NAnguiano** [comment]
Reload has been fixed, and the graph now reloads when the box size is changed. Scrolling also works now.

I can't seem to get zoom to do anything, so that's still in progress. After that will be working on the infinite/finite box.

**Comment by NAnguiano** [comment]
Got zoom working. It's just as a simple set of buttons currently, but the functionality should be able to work with any interface with relative ease. Moving onto infinite vs finite boundbox now.

**Comment by kdahlquist** [comment]
@NAnguiano still needs to implement finite vs infinite bounding box, but this got punted to next semester due to 401 considerations.

**Comment by kdahlquist** [comment]
@NAnguiano will begin work on the finite vs infinite bounding box.

**Comment by NAnguiano** [comment]
I got an initial version for this working, but I want to talk to @dondi about the implementation of it. Instead of an "infinite" box, I'm using one that's very large, then removing the scrollbars on the side so that it appears to just be an infinitely scrollable space. I can't seem to get the scrollbars to come back once you've chosen the infinite option, so I'm currently trying to work in a fix for that. I also am not sure that the scrollbar removal works on Firefox.

**Comment by NAnguiano** [comment]
I can confirm that the solution does not work on Firefox. Also, on Chrome, the scrollbars do come back but in the completely wrong spot. @yshin4 and I are investigating.

**Comment by NAnguiano** [comment]
We have gotten the scrollbars to reappear in the right spot after going from infinite to a finite bounding box in chrome.

**Comment by NAnguiano** [comment]
The scrollbars are now working in firefox.

**Comment by NAnguiano** [comment]
It seems like the current solution may have put tiny scrollbars in when the smaller sizes are chosen. Not sure why this is, but we'll look into it.

**Comment by kdahlquist** [comment]
Finally, as promised, some examples of putting the zoom/scroll buttons within graph window:

1. http://biojs.io/d/biojs-pcviz (example embedded on page)

2. See this page for example: http://www.ebi.ac.uk/ols/ontologies/efo/terms/graph?iri=http://www.ebi.ac.uk/efo/EFO_0000400.  See this page for biojs registry entry: http://biojs.io/d/ols-graphview

**Comment by kdahlquist** [comment]
As I noted on another issue, I'm not sure that I'm looking at the latest version on beta, but I'll note that there is a difference between the bounding box display in the browser window and (for the lack of a better term, I'll use the GenMAPP term) the drafting board.  It's not making sense for me to see "infinite" as a choice listed after very small, small, etc.

**Comment by kdahlquist** [comment]
1. GRNsight web app should set its initial drafting board and viewport size to the best fit (among our three fixed sizes) based on the current iframe dimensions and zoom factor (scale is at 1). I.e., world starts with drafting board and viewport aligned.  Note that the viewport does not change after this point.
    * small is for 13-15 " laptop size
    * medium is for best fit on @kdahlquist's screen (~24" monitor)
    * large is larger than that
2. If the user has set a _hard_ drafting board, then we are done--i.e., the nodes will bump up against the boundary and that's OK (current GRNsight behavior)
3. If the user has set a _adaptive_drafting board, then when the user loads a GRN, @NAnguiano will implement an algorithm that detects when nodes hit the edge of the drafting board and will expand it gradually.
4. Zoom is a separate multiplier that is applied to the entire drafting board once its size is set (control is slider with a bar at 100%)
5. Through all of this, viewport remains constant, scrolling is the same as translating the viewport's origin and zooming is changing the scale factor applied to the drafting board.

**Comment by NAnguiano** [comment]
All of the issues that were created based on the comment above (Issues #395, #396, #397, #398, and #399) have been filled in with the relevant portions of the comment.

**Comment by kdahlquist** [comment]
Closing this one since the issues for the subtasks have been opened.
