### ISSUE TITLE
Scheduling Research next semester

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#350]
It's time to start thinking about scheduling research next semester, both our team meetings and the 4-hour time slots that you will work.

I don't quite have information about what time we will be able to schedule our research meeting, but I can tell you when it will _not_ be:
Monday 1:10-5:00 (@kdahlquist teaching)
Tuesday 9:40-10:55 (@kdahlquist, @dondi teaching)
Tuesday 11:30-12:30 (@kdahlquist department meetings on alternate weeks)
Tuesday  4:20-5:35 (@dondi teaching)
Wednesday 1:10-5:00 (@kdahlquist teaching)
Thursday 9:40-10:55 (@kdahlquist, @dondi teaching)
Thursday  4:20-5:35 (@dondi teaching)

I will be scheduling my wet lab students from 1:00-5:00 on Thursday afternoons.  This doesn't preclude a meeting during that time, but it may mean that I will have to drop out of the meetings from time to time if we have an intense experiment going on in the lab.

As you plan your schedules, it would be a good idea to try and coordinate with each other so that you can find a common time to do the coding work when you all can meet together (as a foursome, or at least in pairs).

**Comment by anuvarsh** [comment]
http://when2meet.com/?5902968-mhsPe

@yshin4, @NAnguiano, @mihirsamdarshi, and I put in (or are putting in) our availability for next semester into this calendar so we can see what times we are all free.

**Comment by NAnguiano** [comment]
Right now, it looks like a set meeting time from 3-4pm on Tuesdays will work for all of us. Otherwise, our schedules are pretty different from one anothers.
Anu and I will be meeting from 4-8 on Wednesdays, and Jen and I will be working from 6-8 on Tuesday. 

Once Mihir can fill out the when2meet, I'll have a bit more of an idea on when we can meet.

**Comment by anuvarsh** [comment]
It seems as if all of us are available on Thursdays from 3-4pm. Still waiting on @ebachoura to finish registering/ updating the When-To-Meet so we can confirm this as a meeting time.

**Comment by ebachoura** [comment]
Just finished registering and I put in my available times.

**Comment by NAnguiano** [comment]
Looks like we can all make it Thursday 3-4pm! 👍

**Comment by dondi** [comment]
Greetings—I just reviewed the schedule and it turns out that Dr. Dorin’s course which we lined up with a free slot of mine, in case he needs to return to medical leave, is the TR 2:40-4:10pm slot. So it is true that 3-4pm is free for me for now, but it is not guaranteed. Judging from the when2meet, it looks like the only available time though, so we may just have to roll the dice on this one.

**Comment by kdahlquist** [comment]
It is likely that @dondi will at least be able to make it at the beginning of the semester.  We'll figure something out if things change.

For now, we'll say Thursdays 3:00-4:00 for the GRNsight meeting in Spring 2016.  I'll leave this open now; we can close it at our first meeting in January.

**Comment by kdahlquist** [comment]
Based on a previous comment from @NAnguiano, she @anuvarsh and @yshin4 have figured out when their work sessions will be.  Have @mihirsamdarshi, @ebachoura, and @eileenchoe set their times?  Ideally, each new person will be working with a veteran to facilitate the onboarding process.

Remember, the commitment is 4 hours per week of work, ideally in one chunk.

**Comment by eileenchoe** [comment]
I am available on the Wednesday 4-8PM block when @anuvarsh and @NAnguiano are scheduled to work.

**Comment by mihirsamdarshi** [comment]
I am available from 4-8 on Wednesday too

**Comment by ebachoura** [comment]
I am also available from 4-8 on Wednesdays

**Comment by dondi** [comment]
Just posting here what I’ve already relayed to @kdahlquist, which is that some last-minute CMSI schedule changes (not yet in PROWL) will now have me teaching in the 2:40-4:10pm slot. The later slot does open up but I don’t think everyone will be available then. So we’re back to picking an open time, and this time we might not be able to capture everyone.

**Comment by kdahlquist** [comment]
Happy New Year!

I've conferred with @dondi about scheduling meetings for the Spring semester since he is teaching during the Thursday 3:00 time slot that we all originally agreed upon.  We will alternate this Thursday time slot with Wednesdays at 4:20.  Unfortunately @yshin4 can't make the Wednesday slot (sorry) but it was the only viable alternative.  Since @yshin4 and @NAnguiano are meeting on Tuesdays, hopefully information can be transmitted that way.

The first meeting will be on Thursday 1/12 at 3:00 led by @kdahlquist.  The rest of the meetings for the semester will then be:
Wed 1/18, 4:20 (@dondi)
Thurs 1/26, 3:00 (@kdahlquist)
Wed 2/1, 4:20
Thurs 2/9, 3:00
Wed 2/15, 4:20
Thurs 2/23, 3:00
Wed 3/1, 4:20
Thurs 3/16, 3:00
Wed 3/22, 4:20
Thurs 3/30, 3:00
Wed 4/5, 4:20
Thurs 4/20, 3:00
Wed 4/26, 4:20

I am working on getting a conference room reservation and will update when that is confirmed.

**Comment by kdahlquist** [comment]
All meetings, both the Wednesday and Thursday, will take place in LSB 331, which is the conference room on the third floor on the North side of the building.

Again, the first meeting will be on Thursday the  12th at 3:00.

See you there!

**Comment by kdahlquist** [comment]
Reminder to write down all the meeting times for the semester.
