### ISSUE TITLE
TriBeta Holiday Ornament Contest

### ISSUE THREAD

**Issue by Nwilli31** [dondi/GRNsight#352]
TriBeta is having a holiday ornament contest. BIO 1 & 2 sections, upper-division labs, and research labs are invited to submit one. The ornament is due **Monday, Nov. 28** to **John Kaufman in LSB 101**
Winners will be chosen based on:
1) Most beautiful ornament, 2) Funniest ornament, and 3) Best Bio-themed ornament

Prize: Donut Part for winning classes (week of 12/5)
Winners announced at TriBeta Cookie Decorating Party, Fri. 12/2 from 4 - 6 pm (LSB Terrace, 2nd floor)

The entire Dahlquist lab (GRNmap, GRNsight, and wet lab) will be submitting one ornament. See [GRNmap #287](https://github.com/kdahlquist/GRNmap/issues/287) for GRNmap thread.

Please suggest ideas here! Creativity knows no limits - no idea is a stupid idea.

**Comment by anuvarsh** [comment]
Mihir and I were thinking Kanye wearing GRNsight glasses. We should add other things from other parts of the lab as well.

**Comment by kdahlquist** [comment]
@khorstmann decorated the ornament--thanks!
