### ISSUE TITLE
LMU Symposium Saturday, March 25

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#358]
Abstract deadline is: Feb. 10

**Comment by kdahlquist** [comment]
Elevating this because we need to draft abstract(s) for review at next week's meeting.

**Comment by NAnguiano** [comment]
Abstracts are due 2/10 at 5:00PM.

**Comment by kdahlquist** [comment]
We decided that @anuvarsh is going to give a talk and that @NAnguiano , @mihirsamdarshi , and @yshin4 are going to give a joint poster.  @ebachoura and @eileenchoe will help with the poster, but are acting in a supporting role.

Abstracts should be drafted on the wiki for first pass review by @dondi at next Wednesday's meeting and final review in two weeks at the Thursday meeting.

**Comment by kdahlquist** [comment]
Upon rethinking this, I think that @anuvarsh and @NAnguiano will give a joint talk as graduating seniors and that @mihirsamdarshi , @yshin4 , @ebachoura and @eileenchoe will give a joint poster more focused on the testing optimization (and documentation).  So @ebachoura and @eileenchoe are not "off the hook".

**Comment by eileenchoe** [comment]
@mihirsamdarshi @yshin4 @ebachoura 
Here's the link to the working draft of the poster abstract:
https://docs.google.com/document/d/1rRosoxRNf9BXapgDyEFFTKiWqVEYZcHCxSXhaCdgDNQ/edit

**Comment by eileenchoe** [comment]
@yshin4 and @eileenchoe completed a draft of the abstract. @mihirsamdarshi and @ebachoura please review

**Comment by kdahlquist** [comment]
Please move the abstract over to the GRNsight wiki.

Please come up with a title, as well.

It seems a little odd to define GRNmap _after_ mentioning the Excel workbook.  Instead of mentioning GRNmap, it might be better to simply define the input type as an Excel workbook containing an adjacency matrix.  Introduce that first, then say that GraphML and SIF formats were added, then say that the tests were refactored into semantic and syntactic.  Some motivation why adding the GraphML and SIF formats is important would be useful as well.

**Comment by kdahlquist** [comment]
For @NAnguiano  and @anuvarsh's abstract, I'm going to challenge you to rethink and dramatically modify the abstract.  What you have is basically the standard one we've been using for the last year.  I want you to specifically talk about your new features and why they are important, which means that you will need to cut down on the background from previous versions.  You also need a title!

**Comment by eileenchoe** [comment]
Wiki for abstract created [here](https://github.com/dondi/GRNsight/wiki/LMU-Symposium-2017-Abstract:-%5BTitle%5D)

**Comment by kdahlquist** [comment]
updated link for abstract submission: http://mylmu.co1.qualtrics.com/SE/?SID=SV_4Sjyc2MtNPJgDpH

**Comment by kdahlquist** [comment]
I don't see any updates to the abstracts since I last looked.  @mihirsamdarshi et al. need a title and more emphasis on the semantic/syntactic tests and the addition of new GraphML and SIF formats.

It would be great to be able to see revised versions ahead of Thursday's meeting so that we only have minor tweaks left at that point.

**Comment by NAnguiano** [comment]
@kdahlquist, @anuvarsh and I rewrote the abstract. We are 11 words over the word limit and both of us are stumped on what to take out.

**Comment by kdahlquist** [comment]
I reveiwed @NAnguiano and @anuvarsh 's abstract and got it to 248 words by consolidating what they said about new features and removing references to "beta".  I know @dondi has a packed day today, but if he could review and sign off soon, I think it's ready to submit.

**Comment by kdahlquist** [comment]
The second abstract is now ready for review by @dondi.  Once he signs off, the abstracts can be submitted.

**Comment by dondi** [comment]
I hereby sign off…sorry for the delay.

**Comment by kdahlquist** [comment]
OK, ready to submit!  The deadline is 5:00 today, but better to get them in sooner if possible in case of computer glitches.

**Comment by NAnguiano** [comment]
@anuvarsh and I have submitted our abstracts.

**Comment by eileenchoe** [comment]
poster abstract submitted as well

**Comment by kdahlquist** [comment]
I'm dropping the priority on this one for now.  Two weeks before the symposium (Saturday, March 25), the first draft of the poster will be due at the meeting (Thursday, March 16) and the first practice talk by @NAnguiano and @anuvarsh will be given, with revised drafts due at the meeting the following week (Wed, 3/22). 

I should also note that you are expected to attend the symposium for the entire day, not just your session.  It is courteous to go to listen to the talks/posters in the sessions besides yours.  

We will be scheduling a group picture at some point during the day so we can get a shot of the joint wet lab, GRNmap and GRNsight groups.

**Comment by anuvarsh** [comment]
The most recent draft of my and @NAnguiano's presentation has been pushed to documents>presentations in master. I believe @eileenchoe also pushed her, @mihirsamdarshi, and @ebachoura's poster to master today as well. 

Looking forward to presenting and getting some feedback tomorrow!

**Comment by kdahlquist** [comment]
OK, retrieving now to look at in advance of the meeting.  I was confused at first because you named your file with 201603 instead of 201703!

**Comment by anuvarsh** [comment]
Oops! Hahaha, thank you for catching the typo!

**Comment by kdahlquist** [comment]
@mihirsamdarshi , @yshin4 , @ebachoura , @eileenchoe: no one has picked up the comments I made on your poster draft.  They are pinned to the bulletin board outside my office door.  There is not unlimited time in which to work on this.  I need to see another draft and the final version needs to get into the queue for printing soon.  Please let me know when I can expect to see another draft of the poster, based on the comments.

**Comment by eileenchoe** [comment]
Just picked up the poster draft with comments, and reviewed changes with @kdahlquist. Will have the final draft ready by the end of work session tomorrow at 8PM.

**Comment by eileenchoe** [comment]
Final poster draft uploaded to documents/posters. @kdahlquist please review the "Why GRNsight" section specifically. Added this section per our discussion.

**Comment by kdahlquist** [comment]
I reviewed the new version of the poster and made minor changes to that section (title, a little rearrangement of bullets). I also did a little clean up throughout with line breaks, periods, capitalization and adding references.  The new version is pushed to the repo and I will be submitting it to John to be printed.  You'll be cc'd on that message; you will receive an e-mail when the poster is ready to pick up.

I haven't had a chance to look at @anuvarsh / @NAnguiano 's slides yet.  I will do so before their second practice run at 3:00 Thursday.

**Comment by kdahlquist** [comment]
Good work on Saturday, everyone!

@anuvarsh, will you please make sure that the final version of your talk is in the repository?  The final poster version is already there.

I'm going to close this and remind everyone to please return to the tasks/issues you were working on pre-symposium prep for this week and I'll see you on Thursday for the GRNsight meeting.

I will begin another issue for updates to the website.
