### ISSUE TITLE
Southern California Conference for Systems Biology

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#360]
@mihirsamdarshi can you make the conference on thr 28th?  I need to know ASAP so I can work out the registrations.

@anuvarsh and @mihirsamdarshi need to work on an abstract (due Friday the 20th).  Do it on the wiki and let us know when it is ready for review.

**Comment by anuvarsh** [comment]
I don't see any word count limits on the website. I will assume there isn't a hard cutoff and edit our most recent abstract accordingly.

**Comment by mihirsamdarshi** [comment]
I can make it.

**Comment by anuvarsh** [comment]
The newest version of the abstract can be found here: https://github.com/dondi/GRNsight/wiki/Systems-Biology-Conference-2017-Abstract

Should I add a sentence or two about the zoom function and the bounding box even though the user interface isn't complete yet?

**Comment by kdahlquist** [comment]
Abstract guidelines are here:  http://ccbs.uci.edu/scsbc2017registration

limit of 250 words

Yes, talk about the new features as beta if there's room.

**Comment by anuvarsh** [comment]
Updated the abstract to fit within the word count and added information about the bounding box.

**Comment by kdahlquist** [comment]
I just made some revisions to the abstract and re-ordered the author list.

There needs to be a title.

The conference wants a Word document with the following formatting:

Guidelines: font size- 11 pt. font type – Arial, text box size – 7 3/8" (19cm width) x 4 ½" (11.5cm height) (one half of an 8 ½ x 11 page) Word format (.doc), although pdf documents will be accepted. Insure all fonts are embedded with the text. Please provide the list of authors with the presenting author indicated by an asterisk (*) next to their name. Separate each author by a comma.

Please generate the Word document and add it to the repository on the master branch under "documents" adding a new directory for "abstracts" and naming it "Varshneya_Samdarshi_Southern-California-Systems-Biology_2017_abstract"

I'll do a final review before submitting it.

**Comment by anuvarsh** [comment]
Added the correctly formatted abstract to the master branch in GRNsight>documents>abstracts.

**Comment by kdahlquist** [comment]
Made minor formatting changes and submitted abstract.  Now on to making the poster!

**Comment by kdahlquist** [comment]
@mihirsamdarshi lost his changes to the poster due to a merge conflict where GitHub chose the old version.  All changes were lost (nobody had a copy of the changed version).  A good practice might be to save a copy of documents/code somewhere else on your hard drive before pushing/pulling.  @anuvarsh and @mihirsamdarshi will get the poster to @kdahlquist by noon on Friday (sooner if possible).

**Comment by kdahlquist** [comment]
_Correct_ poster is printed.  I'll bring it tomorrow with the others.

**Comment by kdahlquist** [comment]
Nika and Natalie are driving. See you at 7am.

**Comment by kdahlquist** [comment]
We need to make a news item about our attendance at the conference, and update the Publications page.  There is a mistake on the poster regarding semantic and syntactic testing that I would like @mihirsamdarshi to fix before I upload the poster to slideshare.

**Comment by anuvarsh** [comment]
I already made the necessary updates to the poster according to our conversation during the meeting yesterday. It's currently pushed to master. If @mihirsamdarshi or anyone else on the current testing team could take a look and sign off, it should be ready to upload to slideshare.

**Comment by kdahlquist** [comment]
Assigned this one to myself for upload to Slideshare, updates to publication and news pages.

**Comment by kdahlquist** [comment]
OK, now closing this one since opened #418.
