### ISSUE TITLE
Add "syntactic" tests for SIF format

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#362]
Need to add more tests for SIF format input files.  @ebachoura and @eileenchoe can either split SIF and graphml or both work on both.  Discuss with @dondi this week.

**Comment by dondi** [comment]
@dondi gave the group an overview/tour of the existing code and pointed out where syntactic errors can be detected then reported. @ebachoura and @eileenchoe will take a look at the code and decide how to tackle this.

**Comment by dondi** [comment]
(the above note also covers #363)

**Comment by eileenchoe** [comment]
Decided that I will focus on SIF tests while @ebachoura will focus on GraphML tests #363 for now. Ran some initial tests using existing SIF files in test-files to understand code structure of the importer.

**Comment by kdahlquist** [comment]
Here's how to approach this one:
1. Read the documentation on the Documentation page of the website to fully understand the specification for this format in GRNsight (which is slightly more specific than the general specification for this format).
2. Look in the test suite to see what tests are already there from @dondi's initial implementation
3. Enumerate the cases for which we don't have test coverage, looking at the cases for the Excel format may be helpful here.  Perhaps we could have a meeting with just @kdahlquist, @eileenchoe, and @ebachoura to go over likely edge cases to look for.  The errors and warnings glossaries on the wiki will also be helpful; it would be a good place to add any new cases.
4. Then write the tests.

**Comment by dondi** [comment]
@eileenchoe has successfully implemented one syntactic warning and will just keep proceeding with more. At the meeting, @dondi showed her how she can include unit tests for this in the codebase.

**Comment by kdahlquist** [comment]
Warnings that have already been written are now showing up in the warnings box on GRNsight when use uploads bad file.

**Comment by eileenchoe** [comment]
@kdahlquist here are times that I am available this week to meet about this issue. I'm hoping we can meet before my research block on Wednesday, so I can get a significant amount of work done for this issue this week.
- Mon 11:20AM - 12:30PM,  2:20PM-4:20PM
- Tues 4:10PM-5:30PM 
- Thurs 8:30AM - 9:30AM, 4:10PM-5:30PM

**Comment by kdahlquist** [comment]
@eileenchoe, I can do Tuesday, 4:10-5:15.  Please come meet me in my office, LSB 289.

**Comment by eileenchoe** [comment]
@kdahlquist Great, see you then.

**Comment by kdahlquist** [comment]
@eileenchoe and @kdahlquist met to talk about tests for SIF.

The types of tests that are going to be most relevant for SIF are ones that involve missing data or stray data outside the confines of the data matrix.

Missing data:
* Cell A1 missing
* Cell A1 present, but Cell A2 is missing, but Cell A3 is present
* Corners
* First row, second row
* First column, second column, third column in the three column format
* Missing cell in first column, second column, third column

Stray data
* stray data to the right of the data matrix (skipping columns) and to the bottom (skipping rows)

The other unique feature of SIF si the interaction type:
* question: should we have a strict interpretation of "pd" so that it and only it can be present in a valid file or should we allow any text string in there (including strings that don't match each other).  If we allow any string do we want to inform the user if the strings are different?  Tentatively, we are going to allow any string of any length.

This should be run by @dondi and @anuvarsh to see if we are missing any obvious cases.  This is more similar to what had to be done for Excel than graphml.

**Comment by dondi** [comment]
@dondi took a look at the list and it looks OK. Meanwhile @eileenchoe has started looking at the cases and has found some situations that are already "handled" by the current implementation. She will ask @kdahlquist whether such cases can stay this way, or if the code should explicitly flag an error that notifies the user of the issue.

[This link](http://www.cbmc.it/fastcent/doc/SifFormat.htm) may be helpful, providing a specification of sorts for SIF, to the degree that it has been specified.

**Comment by eileenchoe** [comment]
Conclusion reached with @kdahlquist that a strict interpretation of "pd" should be required for unweighted networks. This is due to the fact that for SIF files in the "multi-column" format, if the relationship type is missing, the value of the target shifts into the "relationship" slot.

**Comment by eileenchoe** [comment]
Worked with @dondi to enable the error modal for SIF and GraphML importers. @ebachoura please review changes on my fork and confirm that it works for your GraphML tests. Additionally, updated the error message when the user tries to upload a SIF or GraphML file under "Open" to include information to redirect the user to use the "Importer" if they actually intended to upload a SIF or GraphML file.

**Comment by eileenchoe** [comment]
Bug found in the Error Modal for SIF files. Clicking the "Select New File" button from the error modal opens an upload box which only accepts the XML file extension, when it should only accept the .sif extension. Can't pinpoint where the error occurs in the code, but will add this to tasks for the week.

**Comment by eileenchoe** [comment]
Completed all syntactic tests and corresponding unit tests as enumerated above this week. Additional discussion at the meeting yesterday brought up a few additional edge cases for the SIF importer (single node, file with no data, file with no data but tabs) which will require some additional time to handle and test. When complete, I will work on updating the documentation to reflect new SIF requirements on beta version (to be again updated when the version of GRNsight is released).

**Comment by eileenchoe** [comment]
Worked with @NAnguiano to solve the bug mentioned regarding routing SIF, GraphML, and Excel to its appropriate file uploader when the user selects "Select New File" from the error modal.

**Comment by eileenchoe** [comment]
Pull request merged by @NAnguiano in #432

**Comment by kdahlquist** [comment]
@eileenchoe, I see that I've been assigned to this with a review requested label.  Does this mean that this is more or less done?

I see there is a "sif-syntactic-test-files" directory inside "test-files".  Is this the only place I should look to find test files for me to check?

**Comment by eileenchoe** [comment]
@kdahlquist yes, this issue is complete and has been merged. Summary of changes are in PR #432. The unit test added are in import-sif-tests.js

**Comment by kdahlquist** [comment]
I went through the "sif-syntactic-test-files" directory and tried out all the files there on beta v2.0.9.

The "correct" files loaded and the others all errored out.  However, certain files triggered redundant error messages in the error modal window.  Somehow I think we deal with this somehow so that the error message only shows up once?

The ones that trigger this are the "multi-column" variety of:
* column-1-missing.sif
* column-2-missing.sif

Also, I noticed that if I triggered the error, clicked on select new file and then chose one that did load, part of the window was still greyed out.

The "stray-data-bottom.sif" and "stray-data-right.sif" files in the three column format appear to both actually be instances of "stray-data-right".  So I modified the "stray-data-bottom" and I think I crashed beta.  Here is the file that did it:

[stray-data-bottom.zip](https://github.com/dondi/GRNsight/files/940561/stray-data-bottom.zip)


In these two folders, I don't see any examples of these test files for weighted networks.  Do they exist somewhere else?  It seems that all of these need to be repeated for weighted networks.

**Comment by kdahlquist** [comment]
@eileenchoe, I labeled this "for next release" because we want to merge all of your current completed tests into the next release.  Since you guys fixed the error that crashed the server, this is already in a good enough state for the release.  Get to the issues I reported above if you have time.  We can come back to this one in the summer.  There are other bugs in the critical path that need to take priority over working on this.

**Comment by eileenchoe** [comment]
Updated the documentation to reflect our new strict interpretation of the relationship type for weighted networks (must be "pd"). As @kdahlquist suggested, changes are commented out for now, then should be uncommented upon v2 release #422

**Comment by kdahlquist** [comment]
De-labeling this "for next release" since current work has reached a stopping point.  We'll pick this one up later.

**Comment by eileenchoe** [comment]
Finished generating the equivalent test files for weighted network and working through checking if the correct warnings and errors are being generated. 

An issue that has come up a few times now are errors that the semantic checker are detecting, which are direct results of syntactic errors. For instance, for this sif file (where the entire column 1 is missing), this is the output of the errors modal:

<img width="116" alt="screen shot 2017-05-16 at 11 33 20 am" src="https://cloud.githubusercontent.com/assets/16827883/26122198/83d51f98-3a2b-11e7-8e2f-050fc65708e8.png">
 
<img width="581" alt="screen shot 2017-05-16 at 11 30 40 am" src="https://cloud.githubusercontent.com/assets/16827883/26122196/81bdbc24-3a2b-11e7-8478-9e6cec936adc.png">

As a result of the syntactic error, the relationship type is "shifted" to the source gene column. The semantic checker is blind to this fact, and incorrectly generates the warning that the source gene has a semantic error of an invalid character (the decimal point in the weighted relationship). I guess the question to this point is what the relationship should be between the syntactic and semantic checker. At this point, we are running the input through the syntactic checker, then the semantic checker, and aggregating the warnings and errors generated from both the checkers into the warnings/errors modal. I'm wondering if we should explicitly differentiate where the source of the warnings or errors are and whether this would help the user. Or, if we consider syntactic errors of a higher priority to the user, should we not run the network through the semantic checker if a syntactic warning or error is detected? This would sidestep the specific issue above.

**Comment by kdahlquist** [comment]
There is always a tradeoff between simplifying something on the one hand and providing maximum info to the user.  In this case, I think I would be OK with the situation where GRNsight encounters a syntactic error and doesn't bother to run semantic and returns the error to the user at that point.

This might mean that the user does multiple rounds of fixing their file, but it's probably better that the error message isn't confusing.

**Comment by dondi** [comment]
Agreed, this is actually in line with traditional compiler designs where compilation aborts when syntactic errors are encountered and semantic analysis does not take place until the syntax checks out fully. We wouldn’t be shirking any usability conventions by waiting for the syntax to be cleaned up before going deeper into the data.

**Comment by eileenchoe** [comment]
Great that makes sense. So semantic checker is now bypassed for the SIF and GraphML importers if a syntactic error is detected. For the spreadsheet controller, since the network is returned as soon as an error is detected, no changes needed to be done to make this change for Excel spreadsheets.

**Comment by eileenchoe** [comment]
Finished testing the rest of the weighted versions of my syntactic tests, as well as fixed the bug where the same error message was being shown multiple times in the error modal. Is there anything more to do on this issue?

**Comment by dondi** [comment]
Is there a pull request for this issue or is this part of getting the latest merged beta up and running?

**Comment by eileenchoe** [comment]
Working on making a pull request right now to close out this issue and #428. This one has the patches to get beta running!

**Comment by kdahlquist** [comment]
I don't think there's anything left--if @eileenchoe has reviewed the syntactic tests for Excel and made sure that she's covered the equivalent, that should be it.

**Comment by kdahlquist** [comment]
I tested all the new test files in the beta branch and they all give errors as expected.  Closing this now.
