### ISSUE TITLE
Clicking Print opens print dialogue twice

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#365]
When you hit print, if you exit out of the print dialogue, it opens again right after.

Also, the print image is completely broken, so I think some redoing of the print css is in order.

Note: this is only on beta.

**Comment by kdahlquist** [comment]
I think this is an issue for Chrome, but not Firefox.  Lowering the priority for now.

**Comment by johnllopez616** [comment]
I _believe_ I fixed this. There were two identical functions designed to print, all I had to do was remove one of them.

**Comment by kdahlquist** [comment]
This appears fixed in beta v3.0.9, so I'm closing.  The other issue with printing noted by @NAnguiano above should be written up as a separate issue.
