### ISSUE TITLE
402: Project Proposal Due 1/23

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#366]
Information from [here](http://myweb.lmu.edu/bjohnson/cmsi402web2/proposal.html).

- [x] Presentation
- [x] Project Proposal Document

The Proposal Presentation should contain the following slides in this order:
- Title slide with the project name, your name, and the date, and maybe a cool graphic
- Project Description, containing top-level explanation of your application, along with the target audience for the application.
- Justification slide, presenting reasons why this is an acceptable semester project; this could contain reasons why your classmates will be interested, interesting algorithms or computational implementations that you'll be including, and so on.
- User's point of view; this should present facets of the user experience, such as application operations (buttons, menus, etc.). If doing a game, be sure to clearly state the way the game ends -- what is the outcome?
- Operations Description, describing generally how the application will work; this should include any project segmentation, such as clients, servers, and support software.
- Technologies with brief descriptions of all technologies you'll be using, including the programming language, any IDE or other tools you'll use, and any libraries required. Don't forget to mention if there are any licensing issues.
- If there is any other information you want to present, put the slide(s) for it here.
- Preliminary development schedule, including the major milestones for your project as you see them this early in the semester.
- "Questions" slide

The Project Proposal document which goes in section 3.0 of the SDF will itself consist of two parts or subsections, the first being a verbal description of the project, and the second being a justification of the project. The total length should be about 500 words.
- The verbal description must provide a high-level overview of the project, compare it to any software programs already in existence (if applicable), list its most important features, and mention the hardware and software it requires. The description must also indicate who the end user of your application would be, and, if relevant, how it would be maintained.
- The justification section should explain why your choice of project is appropriate for this class.

 The following criteria will be used as a guide for evaluating the appropriateness of the project, and should be considered when writing the justification section:
1. Applies and demonstrates what you have learned in your other classes
2. Gives you the opportunity to extend what you have learned in other classes
3. Technical difficulty is appropriate (not too easy, but not too hard either)
4. One semester is a reasonable amount of time to develop the project
5. You possess the tools and skills required to complete the project
6. Project is interesting to you, your classmates, and the instructor

**Comment by NAnguiano** [comment]
Done.

**Comment by kdahlquist** [comment]
I know that you prepared these documents for BJ, but I also want to comment on them.  Can we use the convention of adding "review requested" and assigning them to @kdahlquist as we do for the other issues?

First some mechanics:

What does "SDF" mean?  Google failed me on that one.

I want to change the naming of the directories and files slightly with a view to the fact that there will likely be future 402 projects.

So, would @NAnguiano please move her files into a directory as follows:

documents > CMSI_402 > spring_2017 > SDF

Assuming that it makes sense to have a "SDF" folder once you tell me what that means. Otherwise, it might just make sense to put the documents in the spring_2017 directory.

Then the PowerPoint should be named "Anguiano_CMSI402_Spring2017_project-proposal-presentation.pptx"

The Word document should be named "Anguiano_CMSI402_Spring2017_project-proposal.docx"

Any further documents should follow a similar convention so we can avoid having to rename things later (as we also did with Britain's 402 documents).

Substantively, I want to review your development schedule in terms of priorities and scope at the meeting on Thursday 1/26.

**Comment by bjohnson05** [comment]
The acronym "SDF" means, by turns, either "Software Development File" or "Software Development Folder".  It's an industry term that is used for the collected documentation, generated as part of developing a software project.
I hope that helps!

**Comment by kdahlquist** [comment]
Ah, thanks @bjohnson05.  In that case, the directory structure should be:

documents > SDF > CMSI_402 > spring_2017

assuming that all the documents generated for CMSI 402 would qualify as SDF documents.

**Comment by NAnguiano** [comment]
The documents have been moved and renamed. I wasn't sure whether you wanted to keep the review requested notation for 402, but now that I know, I will do that in the future.

**Comment by kdahlquist** [comment]
I'll leave this open pending the meeting between @NAnguiano and @kdahlquist Friday at 10:00 AM where we will discuss the feature set for the 402.

**Comment by kdahlquist** [comment]
@NAnguiano and @kdahlquist met to discuss the 402 Project proposal on Friday morning.
Here is what she put in her PowerPoint submitted to @bjohnson05:

* Website Redesign (emphasis on fixing kludgy stuff and UI design for new features)
* <s>Node Coloring</s>
* Alternate Graph Layouts, especially hierarchical
* Graph Optimization (rows vs. columns)
* <s>User Login</s> + Graph Saving (data, image, session)
* <s>Optimizations/ES6 Conversion</s> as per #383, we will not upgrade any library versions this semester.

**Comment by kdahlquist** [comment]
Just to reiterate what @NAnguiano and I talked about, her priorities for the semester are, in order:
1. finish up the bounding box size, zoom, and scroll functions and the UI changes needed for the controls #345 
2. get hierarchical layout functioning #290 
3. graph optimization (under the hood traversing data rows vs. columns) she needs to create an issue for this/website optimization (fixing kludgy stuff, _maybe_ revisiting layout/design)
4. She has had user reports that they want to return to their session with their layout saved.  There are three levels of export, saving data (which we can do with conversion to SIF/graphml and which we will need to do when implementing graph stats), saving image #59 (we want to export the SVG or other vector format), and saving the session data (state of the layout and parameters). An issue needs to be written for the latter.

When dividing the work with @yshin4 this semester, @yshin4 will focus on dealing with reported bugs that have to do with the graph layout, e.g., #355, #333, #318, and others, while @NAnguiano will focus on coding new functionality (as per 402 requirements).

@NAnguiano and @kdahlquist will meet on Fridays at 10 AM to specifically discuss 402 progress.
