### ISSUE TITLE
598-04: Title and annotated bibliography

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#367]
The function of the title is to identify the main result or take-home message of the report. It should be as specific as possible and name the organism. It can be a phrase or a sentence.
The annotated bibliography is a list of a minimum of 10-15 primary research articles.
Each should have a properly formatted citation (in the APA format).
Each should have 2-3 sentences as to why the article relates to the research project.
A minimum of 5 of the references from this bibliography will be discussed in the Introduction to the report.

**Comment by anuvarsh** [comment]
Annotated bibliography and draft of title has been submitted.

**Comment by kdahlquist** [comment]
I sent @anuvarsh an e-mail acknowledgment that the annotated bibliography has been received, but it just now occurred to me that we could be using the repository for this.

I created a directory under "documents" on the master branch called "reports".  Please put your annotated bib there so we can keep it under version control.  I could deposit it, but it makes more sense for you to do so, since you are the author.

As I mentioned in my e-mail, the citations need doi numbers.  Google Scholar doesn't provide them, unfortunately, in their automatically generated citation format.  You will have to look them up.

Also, you should number your pages.  Be in the habit of doing that whenever you create a new document.

My goal is to give you more substantive feedback by our GRNsight meeting next Thursday.

**Comment by anuvarsh** [comment]
I emailed in the updated version of the annotated bibliography on Friday, and uploaded the file into the documents>reports directory. 

I was looking it over earlier today and realized that I added the doi's but I forgot the page numbers. The corrected version of the document is uploaded to the master branch now.

**Comment by kdahlquist** [comment]
Here are my comments on your Annnotated Bibliography.

First, mechanics:
* I like the title, but "web app" is a little too informal.  Please spell out "application"
* Your hanging indent is a little large at 1 inch.  It should only be 1/4 inch.
* For the Breitkreutz article, I think your DOI is referencing the preprint, please double-check that it is the correct DOI for the final published article.

Substantive comments:
* I'm not sure the DeRisi article is the right one for connecting microarrays to GRNsight.  [This review article]http://www.nature.com/ng/journal/v21/n1s/full/ng0199supp_33.html) might be better for talking about microarrays, or there might be something more recent/relevant.  Let's talk about this one.
* I was not aware of the Longabaugh, MacNeil, Mugridge, Pastrello, or Rafique articles and am looking forward to your analysis.  Would you recommend these for a journal club for the GRNsight team?
* Overall, I think this is a good list.  Once the mechanical changes noted above have been commited, you can close this issue.

**Comment by kdahlquist** [comment]
I forgot to mention that "visualisation" is not misspelled--it is the British spelling and the journal that article was published in is from there.

**Comment by anuvarsh** [comment]
Oop! My mistake about the British spelling. I edited the bibliography accordingly. 

The mentioned mechanical edits have been made and uploaded. 

In regards to the DeRisi article vs. the Brown review article-- I agree that the Brown article is a better source for the type of information I was hoping to get out of the DeRisi article. I'll go ahead and add the Brown article to the annotated bibliography in addition to the DeRisi article that is already there. 

In regards to having journal club for other cited articles-- The MacNeil article was especially interesting for me. The GRNsight team would benefit from reading this paper and understanding the different ways that GRNs are analyzed for the sake of understanding our users, but I also believe that a similar result could be achieved by talking to the analysis team and understanding their process/ what they look for when they analyze a GRN.

**Comment by anuvarsh** [comment]
The Brown article has been added to the annotated bibliography and pushed into master.

**Comment by kdahlquist** [comment]
@anuvarsh, I think this is closable now, is it?  If so, please close.

**Comment by anuvarsh** [comment]
Yes, I made the corrections mentioned above so this issue is done. Closing.
