### ISSUE TITLE
598-04: Outline

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#368]
Outline of all sections of the report
Include a list of figures and tables
No set length; it needs to be long enough to be inclusive of all results from your body of work in the Dahlquist Lab

Due: 5:00 PM on Friday, February 3 (end of Week 4)

**Comment by anuvarsh** [comment]
Outline was submitted and pushed to master on Friday. After @kdahlquist and I have the opportunity to talk about any revisions I should make, I will go ahead and close this issue.

**Comment by kdahlquist** [comment]
@kdahlquist and @anuvarsh need to schedule a meeting to discuss.  I'm free on Tuesday from 11:00 to 5:00, Thursday 11:00-2:30 or Friday 11:30-1:00.  Hopefully one of those times works for you.

**Comment by anuvarsh** [comment]
I am available at 3pm on Tuesday.

**Comment by kdahlquist** [comment]
OK.  See you then!

**Comment by kdahlquist** [comment]
Feedback was given at the Tuesday meeting.  There's no need to update the outline document; just proceed with the writing.
