### ISSUE TITLE
598-04: Introduction

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#369]
The introduction should tell a story and should provide all of the background information necessary for the reader to understand the project. The outline of a good introduction is shown at the left.
A critical review of a minimum of 5 references from the annotated bibliography must be performed in the introduction.
Minimum length of 4-7 pages
In text citations must be used (minimum of 2 per paragraph), and a properly formatted References section must also be included

Due: 5:00 PM on Friday, February 24 (end of Week 7)

**Comment by kdahlquist** [comment]
Got your attachment.  Now that you are into the writing, you need to have a References section with all of your cited references in it, not just the in text citations, for all the drafts you turn in.

Friday would be best for me to meet.  I'm available 9:00-10:00, 11:15-1:00, or 3:30-5:00.

**Comment by kdahlquist** [comment]
@anuvarsh varsh--I'm also available 10-11 on Friday since @NAnguiano and I have cancelled our Friday meeting.  Please let me know what works for you so I can put you in my calendar.

**Comment by anuvarsh** [comment]
Sorry for the delayed response. Friday at 4pm is best for me.

**Comment by kdahlquist** [comment]
Confirmed--see you then!

**Comment by anuvarsh** [comment]
Because this assignment was already submitted, @kdahlquist and I already had our meeting about the Introduction, I'll go ahead and close this task.
