### ISSUE TITLE
598-04: Materials & Methods and Results

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#370]
No set page length; it needs to be long enough to cover all of the research results from your body of work in the Dahlquist Lab.
Enough information must be provided in the methods for a practitioner in the field to reproduce all of the results
All figures and tables must be included, numbered sequentially in the order they appear in the text, with descriptive legends that give a key to all labels and abbreviations.
The results section includes a narrative description of all figures and tables along with analysis of results that includes detailed explanation of the evidence
In text citations must be used, and a properly formatted References section must also be included.

Due: 5:00 PM on Friday, March 17 (end of Week 9)

**Comment by anuvarsh** [comment]
An extension has been granted, so this assignment is now due on Friday, March 24th (end of Week 10).

@dondi, I am working on my figures/tables and I am having difficulty getting test coverage statistics. Do you by chance remember how to run Istanbul with our set-up of Mocha to get those numbers?

**Comment by anuvarsh** [comment]
The MM/Results section has been uploaded to the master branch under documentation>reports, and has been emailed to @kdahlquist.

**Comment by kdahlquist** [comment]
@anuvarsh, we need to set up a time to meet and discuss.  Since advising is starting for me, it would be best if you stopped by my office and signed up on the sign-up sheet.  I just need 24-hours notice.

**Comment by anuvarsh** [comment]
@kdahlquist, sounds good. Should I wait for later next week so we can discuss this section and the Discussion section together, or would you prefer we talk about them separately?

**Comment by kdahlquist** [comment]
Supplanted by #372.
