### ISSUE TITLE
598-04: Discussion

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#371]
Research results must be discussed in terms of their significance, relevant literature, and future directions; write a concluding paragraph that summarizes the entire work
Minimum length of 4-7 pages
In text citations must be used, and a properly formatted References section must also be included.

Due: 5:00 PM on Thursday, March 30 (end of Week 11)

**Comment by anuvarsh** [comment]
First draft of discussion has been pushed to master!

**Comment by kdahlquist** [comment]
As per your previous comment on #370, should just go ahead and meet next week and talk about both the M&M, results, and discussion.  @anuvarsh, stop by my office to sign up for a time slot; I'm doing advising, so you'll need to fit yourself in between advising appointments.

**Comment by kdahlquist** [comment]
Supplanted by #372
