### ISSUE TITLE
598-04: Second draft of complete report

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#372]
All sections, including: Abstract, Introduction, Materials & Methods, Results, Discussion, Acknowledgments, References

Due: 5:00 PM on Monday, April 17 (beginning of Week 14)

**Comment by kdahlquist** [comment]
@anuvarsh--let's set up a time to meet.  I'm free most of Tuesday after 11:00.  Sign up for an appointment or respond to this comment.

**Comment by kdahlquist** [comment]
The rest of your draft is ready to pick up from my bulletin board.  Closing this now.
