### ISSUE TITLE
598-04: Final draft of complete report

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#373]
All sections, including: Abstract, Introduction, Materials & Methods, Results, Discussion, Acknowledgments, References
Both a hard copy and electronic copy of the report must be submitted to Dr. Dahlquist by the deadline.

Due: 5:00 PM on Friday, April 28 (end of Week 15, last day of classes)

**Comment by kdahlquist** [comment]
I'm sure @anuvarsh is glad to see this one closed!
