### ISSUE TITLE
Investigate Codecov for automated code coverage analytics

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#374]
As recommended by the 10 Simple Rules article #356, [Codecov](https://codecov.io/) does automated code coverage analytics.  We used Istanbul to generate the report in our PeerJ Computer Science paper, but this might be better.

**Comment by kdahlquist** [comment]
@eileenchoe will take this on to start off the semester. This capability falls under _continuous integration_. Travis is a good initial lead; it is a popular CI choice for open-source GitHub projects.

**Comment by eileenchoe** [comment]
@dondi the issue for CI is actually #248, I assigned that to myself. I can also take a look at this one, as it's also in the effort of devops improvements.

**Comment by dondi** [comment]
OK, great, thanks for the correction. Yes, let's do #248 first and certainly this one can then follow if that one is done. To keep things clean I will make this one a priority 0.5.

**Comment by eileenchoe** [comment]
[Coveralls](https://coveralls.io/ ) has nice integration capabilities with Travis CI, and I set it up to use Istanbul. Coveralls does code coverage analytics and also produces another cool badge for the readme: [![Coverage Status](https://coveralls.io/repos/github/eileenchoe/GRNsight/badge.svg?branch=beta)](https://coveralls.io/github/eileenchoe/GRNsight?branch=beta)

**Comment by kdahlquist** [comment]
Bumping up the priority since @eileenchoe seems to have already covered this.  I'm thinking that this can be closed at the meeting?

**Comment by dondi** [comment]
Yes this has also be done and is a candidate for closure at the meeting. I was thinking that we can make a baby release so that the changes made to beta relating to devops can also be reflected in master. This can be discussed at our meeting.

**Comment by kdahlquist** [comment]
I think it's a good idea to do a release because the bug with the normalization is quite serious and it would be good to see the fix reflected on master.

**Comment by kdahlquist** [comment]
we are using travis --> coveralls --> instanbul instead of codecov.
