### ISSUE TITLE
Set up Zenodo so we have a DOI for GRNsight software

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#375]
From the Ten Simple Rules article (#356), we can use Zenodo to create a DOI for the GRNsight software itself.

Instructions are here:  https://guides.github.com/activities/citable-code/

This service is integrated with GitHub and creates archives of releases with citable DOI's, which would then be referenced in our CITATION.md file and on our website.

I'm assigning to @dondi as the owner of this repository--after he checks it out, I'll enable it for GRNmap (and XMLPipeDB, too, actually...)

**Comment by dondi** [comment]
This has been set up for GRNsight (the sign that this is done can be seen in Settings > Webhooks, showing that Zenodo is connected).

It turns out that DOIs are connected to releases (in hindsight, it makes sense—one would want to cite a _specific snapshot_ of a repository, not a moving target). When we create our next release of GRNsight, we will be able to create a DOI.

**Comment by kdahlquist** [comment]
Cool.  Was it easy?  It would be great to set this up for GRNmap ahead of the 0% release...

**Comment by dondi** [comment]
Yes, pretty easy. They let you login with your GitHub credentials. You just need to authorize the service to access certain aspects of the repository (all read-only). Then you "turn on" Zenodo for that repository.

**Comment by kdahlquist** [comment]
Are we done with this issue then?  It's supposed to work automatically the next time we do a release?

**Comment by dondi** [comment]
Oh right, that's true. At first I was thinking of closing this when a DOI actually shows up, but in terms of setup then yes, it's done. Closing now.

**Comment by kdahlquist** [comment]
I "flipped the switch" for GRNmap and XMLPipeDB, so those are waiting for their next release as well.

**Comment by dondi** [comment]
👍
