### ISSUE TITLE
@ebachoura and @eileenchoe need to schedule safety training with @kdahlquist

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#377]
@ebachoura and @eileenchoe need to schedule safety training with @kdahlquist so that the lab authorization form can be turned in.

**Comment by eileenchoe** [comment]
Suggesting meeting at 3:00PM next Thursday. @ebachoura does this time work for you?

**Comment by ebachoura** [comment]
Yes that works for me

**Comment by eileenchoe** [comment]
@kdahlquist can you confirm safety training for tomorrow (2/2) at 3PM?

**Comment by kdahlquist** [comment]
Confirmed--see you tomorrow in LSB 263 (my research lab, across the hall and around the corner from my office.)

**Comment by eileenchoe** [comment]
@kdahlquist can we move this up to 2:20PM today? @ebachoura can also make it at this earlier time.

**Comment by kdahlquist** [comment]
Yes.

**Comment by kdahlquist** [comment]
Completed and lab authorization form submitted.
