### ISSUE TITLE
402: Requirements Specification Document

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#378]
Information [here](http://myweb.lmu.edu/bjohnson/cmsi402web2/requirem.html).

Due 2/6.

**Comment by kdahlquist** [comment]
Since this was due 2/6 according to the last comment by @NAnguiano, shouldn't it be uploaded to the repo for review?

**Comment by kdahlquist** [comment]
@NAnguiano, I think I commented on this document.  Did updates get uploaded to the repo?  I want to keep on task with the documentation required for your 402 and close issues when appropriate, as well.
