### ISSUE TITLE
402: Software Development Plan or Software Design Description

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#379]
One of either the [Software Development Plan](http://myweb.lmu.edu/bjohnson/cmsi402web2/sdevplan.html) or [Software Design Description](http://myweb.lmu.edu/bjohnson/cmsi402web2/sddesign.html). 

Due 3/6.

**Comment by kdahlquist** [comment]
I reviewed the software development plan that @NAnguiano uploaded to the repo and made comments and small edits in track changes mode.

My main questions include whether the requirements specification has been updated as we discussed and when is the date of your next presentation and final presentation.

Let's keep the CMSI402 issues updated as well as the actual development issues.
