### ISSUE TITLE
Use forks and pull requests to avoid losing work due to merge conflicts

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#382]
As mentioned with regard to #360, @mihirsamdarshi lost changes he made to the poster due to a merge conflict when pushing where GitHub chose the older version.

Given the larger size of the group and the complexity of the different development threads, I think it is time to implement the practice of forking the code onto your own repository and to manage code updates through pull requests.  The GRNmap group is regularly doing this as part of their workflow and it seems to be working nicely.

@dondi will you please discuss at the Wednesday meeting?

**Comment by dondi** [comment]
Here’s the new procedure/structure for our current approach:

1. Let’s have one more `beta` merge first. Everyone get to a clean (can be unfinished) state, with tests passing and no fatal errors, then all merge into `beta`.
1. After this merge, each distinct task should now be in its own fork. Right now this would be zooming/scrolling; display weights; syntactic error checking. (future forks: edge weight normalization; possible splitting of syntactic error checking based on file format)
1. From this point on, the workflow should be:
    * When starting a work session, merge `beta` into your fork (instructions: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/)
    * Work. Commit. Test. Rinse. Repeat. (work session can end here)
    * Upon reaching a good state (can be unfinished, but tests must pass and GRNsight app runs without fatal errors), merge into `beta`
    * Clone `beta` and run tests again to make sure that there are no merge-specific breakages
1. Using this approach, we can still use `beta` as our testing site. e.g., If someone thinks their fork is ready for review, they would merge with `beta` then refresh the `beta` site (coordinate with @anuvarsh on this) and then review can take place.
1. When a fork is completely finished, a final merge can take place and the fork can be deleted.
1. When enough forks are finished and we do a release, we will merge `beta` into `master`.

**Comment by dondi** [comment]
Once this issue has been sufficiently discussed and settled, let's have everyone explicitly sign off on this, then we can close the issue:
- [ ] @kdahlquist 
- [ ] @NAnguiano 
- [ ] @anuvarsh 
- [ ] @mihirsamdarshi 
- [ ] @eileenchoe 
- [ ] @ebachoura 
- [ ] @yshin4

**Comment by kdahlquist** [comment]
I am thinking that getting everyone on the same versions of the libraries is a necessary step 0 for this (#383), otherwise, this looks good to me.

**Comment by dondi** [comment]
Agreed—I’ve revised the comment.

**Comment by kdahlquist** [comment]
Having just updated the gh-pages branch, I note that there are currently three functional branches besides master:
- beta
- issue204
- testFixes

Do we need to merge (and/or delete) issue204 and testFixes so that everyone is on the same page?

**Comment by dondi** [comment]
@dondi deleted the obsolete branches from GRNsight; the hypothesis is that one or more team members has been unintentionally pushing their local branches back. With our switch to forks, we don't expect this to happen again because pull requests force a specific branch to be chosen. Will close this issue for now and we will monitor the branch list to see if they come back.
