### ISSUE TITLE
Update package.json file so that versions are fixed, not "latest"

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#383]
@NAnguiano noticed that the package.json file was set to download the "latest" version of some libraries, not a fixed version number.  She is changing this right now, so it should be exactly what is on the wiki: https://github.com/dondi/GRNsight/wiki/Library-Requirements

**Comment by kdahlquist** [comment]
Upon inspection, @NAnguiano sees that what is on the wiki (updated by @ebachoura and @eileenchoe ) are not the same as what she is using, they are later versions.

Since @ebachoura and @eileenchoe have not done much coding yet, we are not sure whether the newer versions break anything, so to be safe, @NAnguiano is going to record on the wiki the versions that she is using and change the package.json accordingly.

This means that @ebachoura and @eileenchoe will need to redo their installations.

All other team members should double check that everyone is using the same set of versions of everything.

@kdahlquist and @NAnguiano have discussed that we do not want to upgrade any libraries this semester if we can possibly help it.  We want to focus on other features.  Any new refactoring due to version upgrades needs to occur in the summer or start in the Fall semester.

**Comment by kdahlquist** [comment]
Is it possible that library versions have different numbers for Mac, Windows, Linux, please double-check.

**Comment by dondi** [comment]
This is the very first task for the week of 2/1:
- Wipe out ("clean room") all existing node_modules installations on everyone's dev rigs.
- Do an `npm install` with testing in order to reach consensus on fixed version numbers for every GRNsight dependency
- Update _package.json_ files and wiki documentation with these version numbers
- Look at the `npm install-dev` variant also
Ideally this can be settled at the 2/1 work session with results reported to @kdahlquist on the 2/2 meeting.

**Comment by NAnguiano** [comment]
I updated the package.json versions to be fixed. @anuvarsh, @ebachoura, @eileenchoe, and myself have all tested to make sure everything runs and have had success.

**Comment by kdahlquist** [comment]
Is the wiki now up-to-date with package.json?  Let's have @yshin4 and @mihirsamdarshi sign off on this as well before closing.  Reassigning to them and @dondi for review.

**Comment by yshin4** [comment]
I deleted my node modules and reinstalled npm install. I got the same versions as @NAnguiano and checked that everything runs without error.

**Comment by ebachoura** [comment]
I just finished updating the wiki. Versions and release dates are up to date with the ones that are now static in the package.json.

**Comment by dondi** [comment]
This looks good to me; just waiting on @mihirsamdarshi

**Comment by mihirsamdarshi** [comment]
Everything is good on my end

**Comment by kdahlquist** [comment]
OK, closing.

**Comment by kdahlquist** [comment]
Didn't actually hit the close button last time, trying again :)
