### ISSUE TITLE
Feedback from Southern California Conference of Systems Biology

### ISSUE THREAD

**Issue by anuvarsh** [dondi/GRNsight#385]
During the poster session, GRNsight got some feedback/feature requests from potential users. The most interesting recommendations included:

* Implement a feature that allows users to upload 2 different matrices and highlight the differences between them
* Create a "grid snap" option where nodes would line up to a potentially optimal layout (perhaps use graph statistics to decide where each node should be relative to each other - mentioned BioTapestry's layout)
* Make nodes clickable and connect them to some sort of informative database

People seemed to appreciate the aesthetic of the networks in comparison to the networks produced by Cytoscape. Someone also mentioned that they didn't love the font size and wondered if they could customize it/make it smaller.

**Comment by kdahlquist** [comment]
Out of the three suggestions, "snap to grid" is #44 and connecting to a database is #60 (which got closed and assigned the label "backlog").  Viewing two networks side by side would be nice (and only reasonable if they were smallish), but highlighting the differences is likely to be non-trivial.

Food for thought for setting the next priorities.

**Comment by kdahlquist** [comment]
We now have grid layout and will have gene pages soon.  We haven't tackled comparing two different graphs.  I'll log that as a separate issue and close this one.
