### ISSUE TITLE
Create "How to cite GRNsight" section on About page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#387]
We need a section on "How to cite GRNsight" on the About page.

It should go in between the "Release Notes" and "Funding" sections.

For now it should say:

If you use GRNsight in your work, please cite:

Dahlquist, K.D., Dionisio, J.D.N., Fitzpatrick, B.G., Anguiano, N.A., Varshneya, A., Southwick, B.J., Samdarshi, M. (2016) GRNsight: a web application and service for visualizing models of small- to medium-scale gene regulatory networks. PeerJ Computer Science 2:e85. [https://doi.org/10.7717/peerj-cs.85](DOI: 10.7717/peerj-cs.85).

As we do releases, we will provide additional DOI numbers for the new releases.

**Comment by ebachoura** [comment]
I went ahead and added this section.

**Comment by yshin4** [comment]
@kdahlquist eddie finished this task the issue is waiting for review now.

**Comment by kdahlquist** [comment]
@ebachoura: when you add the "review requested" label, make sure you assign the issue to the person whom you want to review it (in this case, @kdahlquist).

* Don't forget to update the "last modified" date when you update a web page; it must be done manually.
* I made a couple of slight edits, including making a hyperlink for the DOI (you just copied the markdown version).

It's all done, so I'm closing.
