### ISSUE TITLE
@kdahlquist, @dondi, @NAguiano need to schedule a meeting

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#389]
@NAnguiano and @kdahlquist discussed this morning that she and @dondi need to schedule a meeting to discuss 402 stuff.  We also said that the three of us need to schedule a meeting now that size/scroll/zoom functionality is implemented to make design decisions.  It would be easiest if the three of us could meet at the same time to review.  Once the server issue #388, has been worked out and @NAnguiano can display her work on the beta server and I can review, we should have the meeting.

Reviewing our course schedules, one possible time would be a Monday morning.  I have a meeting from 10-11, but could do 9-10, or sometime between 11 and 1 (then I'm off to class).  Assuming that we can schedule a Monday meeting, shall we try for Feb 13?

**Comment by dondi** [comment]
9-10am on February 13 works for me (I then have a 10:15am meeting in UHall), or after that meeting, say 11:45am to 1pm, will also work.

**Comment by kdahlquist** [comment]
Let's go for the later time at 11:45.  I sometimes have trouble getting here by exactly 9 in the morning.  Let's meet in my office, LSB 289.

**Comment by NAnguiano** [comment]
11:45 on Feb 13 works for me.

**Comment by kdahlquist** [comment]
OK, confirmed 11:45 on Feb 13.  I'll leave this open until the meeting as a reminder.

**Comment by dondi** [comment]
Acknowledged; I’ve placed it in my calendar.

**Comment by kdahlquist** [comment]
done.
