### ISSUE TITLE
Semantic versioning in light of more frequent changes to beta

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#393]
I think we need to think about our semantic versioning scheme in light of the more frequent updates to beta enabled by #388.  I think that we should be agreed that we are working on version 2 at this point and that our next release will be v2 something.  I think that updates to beta should increment the patch number, like v2.0.1.  This will give us something besides the last modified date to go on when the beta server is updated.

Thoughts, @dondi?

**Comment by kdahlquist** [comment]
This is now implemented as described in issue #404.

**Comment by dondi** [comment]
This was indeed resolved during the the 2/27 meeting with @NAnguiano; checking off the task list now.
