### ISSUE TITLE
Implement automatic discovery of initial drafting board and viewport size

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#395]
GRNsight web app should set its initial drafting board and viewport size to the best fit (among our three fixed sizes - Issue #397) based on the current iframe dimensions and zoom factor (scale is at 1). I.e., world starts with drafting board and viewport aligned. The iFrame should determine its size based on the amount of available space on the user's screen.

 Note that the viewport does not change after this point.

**Comment by kdahlquist** [comment]
I just wanted to note that if the _automatic_ part of the automatic discovery gets us bogged down, I would be OK with it not being automatic and moving on to the meat of the functionality.  I can imagine that this might be browser-dependent and get hairy.

**Comment by NAnguiano** [comment]
Looking at this, it looks like the web page and the iFrame are going to need to be able to communicate with each other in order for this to become automatic. They can't right now, but I'm working on getting this... well, working. 

I'm going off of this example on stackoverflow currently. 
http://stackoverflow.com/questions/9153445/how-to-communicate-between-iframe-and-the-parent-site

**Comment by NAnguiano** [comment]
@dondi pointed out that I was probably overthinking this.

He was right.

This is now working properly. I've made a few changes to the CSS of the beta page so that it looks better when viewing the automatic sizing. The most notable change is that I significantly increased the height of the iframe. This allows for even the largest size to be viewable in one piece without vertical scrolling. I would like to make it so that the containing div expands to the height of its iframe's content, but I can't seem to figure out how to do that at this time. This is a temporary workaround.

**Comment by kdahlquist** [comment]
Note that on @kdahlquist's laptop, using Firefox at 100%, it chose "medium" and not "small" as expected.

**Comment by NAnguiano** [comment]
This is working with my current method, but the method I'm using isn't the best. I'll be switching it to use [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries), which [Bootstrap](https://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints) also uses.

When it comes to expanding the div to be the height of the iFrame, I'll use the [iframe resizer](https://github.com/davidjbradshaw/iframe-resizer).

**Comment by NAnguiano** [comment]
Ok. I switched this to using media queries. I also fixed the issue that was causing it to choose medium instead of small.

**Comment by kdahlquist** [comment]
So it now correctly chooses small on my laptop (sorry, I'm not in my office to check the medium).  However, the right edge of the bounding box/viewport is not showing (no grey line) and the nodes are disappearing off the right edge.  The scrollbar on the right is my browser scrollbar (Firefox v.51.0.1 32-bit).

![image](https://cloud.githubusercontent.com/assets/6463867/23472531/f9c5c780-fe61-11e6-9ffe-7494382a2ed3.png)

Now the length and width are little too large for my laptop screen.

It occurred to me that the medium size could be checked on the monitors in Seaver 120; they are approximately the same size as my office monitor.

**Comment by kdahlquist** [comment]
The medium setting was automatically discovered for my office monitor and the viewport size for this setting is great--no changes needed.

**Comment by kdahlquist** [comment]
Labeling this "review requested" and assigning to me.

**Comment by NAnguiano** [comment]
For some reason, the bounding box continues to resize itself after initially being detected. I think it's because of the @media tags.
Unfortunately, the bounding box only appears to resize - it doesn't actually change the drawable area at all. I'm not sure how to handle this, but I think the best way is to find a way to prevent automatic detection after the initial size is chosen.

**Comment by kdahlquist** [comment]
Automatic detection of "small" for my laptop occurs with Firefox v52.0.2 (32-bit) and Chrome Version Version 57.0.2987.110.  I'll have to check the medium back in the office tomorrow.  Did we find a screen with which to check large?

As for @NAnguiano's last comment, I'm not even sure how I would know that.  Your solution sounds reasonable.

**Comment by NAnguiano** [comment]
Fixed the continued resizing problem on my fork.

**Comment by kdahlquist** [comment]
I've been able to test both small and medium, but have yet to find a monitor on which to test large.  Any suggestions?  I tried the large conference room monitors, but because of the way they are scaling the screen, they actually turn up as "medium".  I don't want to close this until I can find a native "large" monitor, if it exists.

**Comment by mihirsamdarshi** [comment]
As I recently have been doing a lot of front end work, I believe our current viewport sizes are off, and that true values for small, medium, and large should probably be a lot less. The current "large" size would be only supported on 4K monitors which aren't ubiquitous yet and don't necessarily display in native 4k (case in point, the iMac, which displays everything scaled up). I believe the values should be closer to 600, 800, and 1024 pixels, which are considered standards for tablet, mid-point, and desktop browser sizes.

**Comment by kdahlquist** [comment]
I don't agree with the assessment of "small" and "medium".  Those two sizes were optimized for a laptop and ~24" desktop monitor (i.e., my laptop and my desktop monitor).  The intention was to maximize the menu bar/bounding box to fit the visible area on the monitor so that the the graphs could be as large as possible given the constraints.  These two sizes work really well for me right now.

We don't actually intend for GRNsight to be used on a tablet right now.  This could be something we consider for the future, but it is not our focus right now.  

I haven't been able to actually find a monitor that would automatically cause the "large" size to be chosen, so I don't have any perspective on that.  But that size was meant to be for a monitor larger than the standard 24".

As discussed in issue #411, we have asked @NAnguiano to add a feature to "fit viewport to browser window" which would lock the lower right corner of the bounding box to the browser window so that it would always be resized with the window.  When implemented, this feature will probably be more useful than the small, medium, and large size selection anyway.

I'm guessing you made this comment because the size is not working for you on your development machine.  In what direction is it off?

**Comment by NAnguiano** [comment]
I think I see what @mihirsamdarshi is saying. I just tested it on a 32ish" 1440p monitor and it does fall very slightly short of the size necessary to trigger the "large" size selection. I think the best solution is to simply reduce the max size required to trigger the selection of the large size. At this point, I'm pleased with the point at which small and medium are chosen, but I do think the requirement for large is, well, too large. I'll reduce it by about 100px and that should allow it to show up on my large monitor.

**Comment by kdahlquist** [comment]
Got it--sounds good.  Is there a monitor this size in the Keck lab or somewhere on campus where I can see with my own eyes?

**Comment by NAnguiano** [comment]
The viewport size change is up on beta. I'll check tomorrow to see if the monitors in the Keck lab are of the right size. For now, I'll check it at home on my monitor to make sure it is working as expected.

**Comment by kdahlquist** [comment]
I'll take @eileenchoe 's independent verification of the correct automatic selection of large viewport as noted in PR #448 as good enough for me.  Closing!
