### ISSUE TITLE
Implement preference to change viewport size between small, medium, large

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#397]
There will be three size options: 

- small is for 13-15 " laptop size
- medium is for best fit on @kdahlquist's screen (~24" monitor)
- large is larger than that

**Comment by kdahlquist** [comment]
Medium, according to @kdahlquist's screen using Firefox:

Current beta is 14.5 inches wide, should go to 15 inches.
Current beta is 8.25 inches wide, should go to 9 inches.

**Comment by kdahlquist** [comment]
small is a little too big.  The height is OK, but the width needs to shrink by 1/2 inch.

**Comment by kdahlquist** [comment]
We noted at our meeting that final tweaks to the sizes will be made after UI changes are made.  So, make these changes now and we'll revisit it later.

**Comment by NAnguiano** [comment]
I tweaked the sizes as requested.

**Comment by kdahlquist** [comment]
I can't check the sizes specifically right now, but I can verify that choosing the radio buttons changes the size.  I also note that changing the size causes a reload, which is something we don't want to have happen.

**Comment by NAnguiano** [comment]
It does currently trigger a reload. This should be fixed once I get the adaptive drafting board fully implemented (#398), as at that point the code will allow for the graph to change size without reloading. Until I get that completed, a reload will be required. Without a reload, the svg doesn't see the new size of the drafting board, and will continue to operate as if the size had not changed.

**Comment by NAnguiano** [comment]
The reloading issue is fixed on my fork.

**Comment by kdahlquist** [comment]
Making this a review requested and assigning to me.  Since this is related to #399, #396, #398, as soon as pull request #415 has been taken care of and @NAnguiano can make this live on beta, I will review them as a batch and close.

**Comment by kdahlquist** [comment]
I am going to close this one since the buttons are there and they do indeed switch the viewport between small, medium, and large.

I think we need to fully explore all the interactions between choosing viewport size and allowing adaptive vs. fixed drafting board size, but let's open specific issues for that as they arise.
