### ISSUE TITLE
Implement adaptive drafting board resizing algorithm

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#398]
If the user has selected an adaptive drafting board (Issue #396), an algorithm needs to detect when nodes hit the edge of the drafting board and expand it gradually.

**Comment by NAnguiano** [comment]
Here's an example related to resizeable force graph layouts. It should be a good place to start.
https://bl.ocks.org/mbostock/3355967

**Comment by NAnguiano** [comment]
This is done on my fork.

**Comment by kdahlquist** [comment]
Labeling this one with "review requested" and assigning myself.  Will close after pull request #415 is accepted and the functionality is live on beta.

**Comment by kdahlquist** [comment]
I've selected the radio button for adaptive and loaded a graph on both Firefox and Chrome that goes beyond the viewport.  I can't really think of any other way for a user to test this.  Any bugs detected in the future will be reported on other issues, so closing this one.

Good work!
