### ISSUE TITLE
Update Server to Ubuntu Xenial Xerus

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#407]
Our version of Ubuntu (14.04) only supports node version 0.10.25. The next version, Xenial, supports up to node version 4.2.6. 

Fun Fact, did you know that a [xerus](https://en.wikipedia.org/wiki/African_ground_squirrel) is a genus of ground squirrels? 

![Ground Squirrel](https://i.ytimg.com/vi/K2BIq4T0kxo/hqdefault.jpg)
[Source](https://www.youtube.com/watch?v=K2BIq4T0kxo&ab_channel=tomb0171)

**Comment by dondi** [comment]
Operating system upgrade complete; the server rebooted successfully so I will close this issue on that note. Follow-ups specific to GRNsight will be noted in #205.
