### ISSUE TITLE
Semantic Checker Throws Errors On Loading a Graph

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#408]
I didn't see any issue that this would fit into, so I'm just making a new one. 

The semantic checker is having some issues right now and currently will not run on the beta server in its current state. When I went to refresh the beta server this morning, the semantic checker crashed the server. @dondi and I hotfixed a few random issues that were found, but upon loading a file, this happened:
![screen shot 2017-02-27 at 6 39 51 pm](https://cloud.githubusercontent.com/assets/6444156/23389326/35487de4-fd1c-11e6-9b4e-665e7b9cf21c.png)

I haven't tracked down why this is occurring, nor whether or not it will occur when SIF and GraphML are added to the check, as per issue #386. 

As a result, the semantic checker is currently turned off on beta. 

Another random note:
The version of node being run on the beta server is extremely old: 0.10. @dondi is going to upgrade it eventually (issue #407), but for now, there's many things that simply just don't work when they're pushed to the server. Most notably, `for of` (ex: `for (var potato of potatoArray) {`), will not work on the current version. This would not show up in testing, and @dondi and I were not aware of it until now. If you're using `for of`, it's safest to remove it for now or replace it with `for in`, as it will cause the server to crash when a file is run.

**Comment by kdahlquist** [comment]
@NAnguiano, is your "random note" above related to this new issue or is it something separate?  If it is separate, please make a new issue for it so that it doesn't get buried.  Thanks.

**Comment by NAnguiano** [comment]
It's related insofar that it was significantly contributing to the initial problems we had getting beta running. I'll make a new issue for it anyways though, since it is separate overall.

**Comment by yshin4** [comment]
Changed for of loop, which was causing the problem, into a traditional for loop. Also fixed the typo in the semantic checker. @NAnguiano and @yshin4 can confirm that the demo server is running without the problems proposed above. All the errors passed the test as well.

**Comment by kdahlquist** [comment]
I verified that v2.0.2 is running on the beta page this morning.  If that's all I need to do to check this one, it's ready for closing.  If there's something else I should do, let me know, otherwise go ahead and close this one.

**Comment by NAnguiano** [comment]
Alright. Going ahead and closing this one then!
