### ISSUE TITLE
Why would running both node processes simultaneously cause no graphs to load? (npm start)

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#414]
@dondi 
I was trying to find a way that enables the developers to only run "npm start" in a single place rather than needing to open two terminals (or terminal tabs), cding one into web-client and the other into server, and then running node app.js in both places.

I found two npm options: concurrently and parallelshell, both of which do pretty much the same thing and allow for the user to run two node processes at once. However... Both of them prevent any graphs from being able to load. It seems like the xlsx.parse step of the spreadsheet controller just fails to complete. Running them separately the normal way works just fine, but together they don't. 

Any ideas?

**Comment by NAnguiano** [comment]
I figured out what was happening. It has nothing to do with them being run concurrently - Instead, it's due to the paths on the demo files. Because the paths are hardcoded, when the server is run from the parent directory, all of the paths are wrong. As a result, it's trying to grab a graph that doesn't exist. Fixing that seems to have fixed the problem.

As a result though, the old method of going into both places now doesn't work. For me, it's more convenient to just run `npm start` than it is to do it the old way. I've also integrated nodemon so that I never need to reload the server when a file is changed - nodemon just reloads it automatically. For now, this is something I'll just keep locally. 

Closing this up.

**Comment by kdahlquist** [comment]
@NAnguiano, would you please update the documentation page on the wiki with what you have discovered here.  https://github.com/dondi/GRNsight/wiki/Running-the-Applications

One @NAnguiano has updated the documentation, would everyone on the team please acknowledge on this check list that he/she is able to run it this way:

- [ ] @mihirsamdarshi 
- [ ] @anuvarsh 
- [ ] @ebachoura 
- [ ] @eileenchoe 
- [ ] @yshin4

**Comment by NAnguiano** [comment]
@everyone (why isn't this a thing you can do?), right now this is just on my fork. Everyone can test it on my fork if they want to see how it works. Just load it up, `npm install`, then run `npm start` and prepare to be amazed. 

The implications of doing this extend a little further than just changing the way that the apps are launched. Namely, the beta server (and master, once they are merged) would need to be reconfigured so that the new paths to the demo files are recognized. This wouldn't change much - it would just be a slight change to each of the existing commands, as well as a change in the directory that the commands are run. When the pull request is accepted, I'll make the new commands in the screens and ensure everything works. 

I'll pull request this soon. Once this is in beta, everyone will need to make sure to npm install so that they can get some new dependencies and be able to run `npm start`.

**Comment by kdahlquist** [comment]
I see a lot of check boxes on a previous comment to this issue that are empty.  Would @anuvarsh , @mihirsamdarshi , @eileenchoe , @ebachoura , and @yshin4 please check the box if you've completed this.  I have some vague idea that everyone has except for @yshin4.  I want to be able to close this at the meeting on Thursday.

**Comment by yshin4** [comment]
Met up with @NAnguiano today and found out it was working without errors, for some magical reason. Npm start now runs on my laptop as well.

**Comment by NAnguiano** [comment]
@yshin4 , I think I know why we got it working. @ebachoura had the same issue you had before today. What solved it was running npm start from the windows command prompt rather than git bash. I'm pretty sure that for whatever reason, you need to use the command prompt for npm start, not git bash.

**Comment by yshin4** [comment]
@NAnguiano  omg, you're right! Okay, I'll put that into my practice!

**Comment by kdahlquist** [comment]
closing.
