### ISSUE TITLE
Don't show Edge Weight Options when an unweighted graph is loaded

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#419]
I don't think that the edge weight options should show when an unweighted graph is loaded. Also, when an unweighted graph is loaded, the event handlers should not be added to the links. When the event handlers are added on unweighted graphs, it spams the console with errors when you mouseover a node.

**Comment by NAnguiano** [comment]
@kdahlquist, would the normalization factor options need to be shown on an unweighted graph either? I'm thinking they wouldn't need to be, but I wanted to confirm.

**Comment by NAnguiano** [comment]
That's a good point. I'll have it always showing then, for now.

**Comment by kdahlquist** [comment]
Verified that this is functional on beta, by alternately loading the demo weighted and unweighted graphs.  I note that GRNsight remembers what the last setting was, which is fine.  I'm going to label this issue with "documentation" so I remember to describe this behavior to the documentation page when it comes time to write up the new features for beta.
