### ISSUE TITLE
GRNsight team meetings for Fall 2017

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#431]
Registration for Fall 2017 is just around the corner and we should start talking about when our GRNsight team meetings will be in the Fall.

Times that are off the table due to @kdahlquist's teaching and meeting schedule are:
Mondays 10:10-12:30
Tuesdays 11:30-12:30, 2:40-3:55
Wednesdays 10:10-12:30
Thursdays 2:40-3:55
Fridays 10:10-12:30

From what I see on the schedule of classes, @dondi is not available
Mondays 	09:10 - 10:00 AM, 11:40 - 12:30 PM 
Tuesdays 2:40-3:55 and 04:30 - 05:20 PM
Thursdays 2:40-3:55
Fridays, not available

Please chime in if I missed something.

**Comment by ebachoura** [comment]
https://www.when2meet.com/?6179582-Vgcvd

**Comment by ebachoura** [comment]
@yshin4 Could you put in your availability for next semester?

**Comment by yshin4** [comment]
done

**Comment by ebachoura** [comment]
Sorry @yshin4 & @eileenchoe but could you fill it out one more time? I just changed some of my classes and I can't log back in to change the times on the old one. https://www.when2meet.com/?6179895-M2tnb

**Comment by kdahlquist** [comment]
@dondi and I reviewed @ebachoura , @eileenchoe , and @yshin4's course schedules on PROWL, as well as our own availability.  It looks like Mondays from 1:00-2:00 would work for a meeting time since no one has class at that time.  Would everyone please confirm their availability for that slot.  We will plan to meet the first day of class on August 28, location TBA.

- [ ] @ebachoura 
- [ ] @eileenchoe 
- [ ] @yshin4

**Comment by yshin4** [comment]
I had to drop a class for now before I get an override but the class I will be adding is at 12:40 pm-02:10 pm, so I won't be able to make that time period. Sorry!

**Comment by kdahlquist** [comment]
OK.  So with the update from @yshin4, it looks like Wednesdays from 3:00-4:00 will work.  Please confirm your availability for that time; first meeting on Wednesday, August 30, location TBA.

- [ ] @ebachoura 
- [ ] @eileenchoe 
- [ ] @yshin4

**Comment by kdahlquist** [comment]
Got confirmation from @ebachoura, so Wednesdays at 3:00 is a go. See everyone at the first meeting on the 30th.  Tune in here for location--I will post it as soon as I get the room reserved.

**Comment by kdahlquist** [comment]
All meetings will be held in LSB 118--the conference room on the first floor.  See you Wednesday at 3:00!

**Comment by kdahlquist** [comment]
All settled, yay!

**Comment by yshin4** [comment]
Sorry everyone, I dropped and added 2 new classes so my schedule went through some changed. As a result I can not do meetings on Wednesday 3-4 anymore and we'd have to reschedule it. Sorry! I can do Tuesdays and Thursdays anytime before 4 or Friday 1-2:30.

**Comment by kdahlquist** [comment]
@yshin4, I'm sorry, but it's not so simple.  Fridays are out because @dondi is not on campus on Fridays.  Both @dondi and I have other meetings scheduled around our lab meeting.  For next week, we will meet at 3:00 on Wednesday as usual.  In the meantime, I will look into what is possible.

**Comment by yshin4** [comment]
@kdahlquist Okay, I can also get the overview from github and Eileen and Eddie if it comes to the worst. Sorry for the inconvenience everyone :(

**Comment by kdahlquist** [comment]
Final changes: @yshin4 will come to the GRNmap coding meetings on Wednesdays 2:15pm and will have a standing meeting with @dondi during his T 11:30am office hours (she can work next door if other students are present).
