### ISSUE TITLE
Grey edges should have only one thickness

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#437]
When investigating #392, I discovered that grey edges can actually have two possible thicknesses, thinnest and one a little thicker than that.  We probably never noticed this before, but it you can see it here:

![check-self-referential-widths-output-v1 18 1](https://cloud.githubusercontent.com/assets/6463867/24980523/801d4596-1f8d-11e7-8229-8267279f390e.jpg)
generated with this file:
[check-self-referential-widths.xlsx](https://github.com/dondi/GRNsight/files/917907/check-self-referential-widths.xlsx)

I think that the grey edges should have only one thickness and that we should review the assignment of thicknesses to edges just in case there are other issues lurking there.

**Comment by kdahlquist** [comment]
This is probably related to #513 and #515.

**Comment by kdahlquist** [comment]
I investigated this as potentially fixed because #513 and #515 are fixed.  However, this is not the case.  I still see the same behavior as reported in a previous comment with the same test file noted above.

Resurrecting part of a comment from #264:

Since there are 12 bins for edge thicknessess, here is what I think the bins should range from for normalized weights (to 4 decimal places, which is what we are rounding to in the display since 12 doesn't go into 1 very nicely) from thinnest to thickest (this is just considering magnitude):
* 0 - 0.0833
* 0.0834 - 0.1666
* 0.1667 - 0.2499
* 0.2500 - 0.3332
* 0.3333 - 0.4165
* 0.4166 - 0.4998
* 0.4999 - 0.5831
* 0.5832 - 0.6664
* 0.6665 - 0.7497
* 0.7498 - 0.8330
* 0.8331 - 0.9163
* 0.9164 - 1.0000

So, in this scheme, all normalized weights between 0 and 0.0500 should be grey and the thinnest bin.  Normalized weights between 0.0501 and 0.0833 are their respective color (magenta or cyan) and the thinnest bin.

However, since we are seeing grey edges with two different thicknesses, something is different about the way this is implemented than I am assuming.  I think we need to:
1. Figure out why this is happening.
2. Make a design decision as to _what_ we actually want to happen.

We now have a slider for setting the gray threshold.  So if the user moves the slider, one could end up with grey edges with multiple thicknesses.  However, I'm just confused why this is happening when the slider is set to the default 0.05.

**Comment by kdahlquist** [comment]
There are 13 thicknesses (2 to 14 pixels) and they should be calculated in this manner:
- Determine the maximum absolute value of the edge weights.
- This creates a range from 0 to maximum edge weight.
- This range is divided by the maximum edge weight to yield a normalized range of 0 to 1.
- This range divides evenly into the 2-14-pixel edge thicknesses.
- The initial gray threshold is the partition from 0 to 1/13; thus, at the initial load, all gray edges are in the thinnest bin.
- Moving the gray threshold changes the level at which gray is chosen; at this point there may be gray edges of different thicknesses.
- Changing the normalization factor changes the edge value that maps to 1.

@dondi will implement this spec.

**Comment by mihirsamdarshi** [comment]
The variance in edge weight comes from the fact that we do not assign all grey edges to the base thickness, because the widths are set independently of the color that we set.

**Comment by mihirsamdarshi** [comment]
This issue is fixed for when _default to black edges_ is set

**Comment by mihirsamdarshi** [comment]
fixed in PR #749

**Comment by kdahlquist** [comment]
Verified fixed on beta 3.1.21 with the workbook mentioned in the first comment. Closing.
