### ISSUE TITLE
Allow numbers as node labels

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#438]
I tried to make a node label be a pure number, i.e., "111" and it got rejected by GRNsight.  I think we need to allow numbers to be node labels because someone may choose to use numbers instead of letters or letter/number combinations as node labels.

Someone else needs to verify this bug.  When it occurred, it was in the last cell on the right/bottom of my worksheet.

**Comment by kdahlquist** [comment]
We need to fix this one before the BioDB crew goes to work on their final project.

**Comment by kdahlquist** [comment]
At the meeting today, @mihirsamdarshi requested this as his priority 0 issue to start work this semester.

**Comment by mihirsamdarshi** [comment]
At Line 293 is where we throw the corruptGeneError

**Comment by kdahlquist** [comment]
@mihirsamdarshi was stuck on this, but we put our heads together in the meeting and discovered that GRNsight is throwing a semantic error and that it's line 293 in spreadsheet-controller.js that needed to be addressed.  The error checking for this needs to be removed.

**Comment by mihirsamdarshi** [comment]
This seems to be more complicated than realized, because node labels were not allowed to be numbers, because the program makes the distinction between labels and input values in the spreadsheet by determining whether they are a string or number. When adding new code to turn node labels into a string, it treated a value in the middle of the spreadsheet as a node label.

**Comment by kdahlquist** [comment]
OK, then we will need to fix this.  It seems that the code should more properly treat the first row and first column as the labels, regardless of content, and then everything else is part of the adjacency matrix.

**Comment by mihirsamdarshi** [comment]
Started the redesign, trying to map out how to change the code without it being a large-scale refactor, however I'm focusing on #518 before I spend my time on this.

**Comment by kdahlquist** [comment]
This impacts spreadsheet-controller and the importers.  @eileenchoe says that the labels get converted to string already and that there is another check to see if the string can be a number.

@yshin4 says that there should be a function that checks for digits in the label and then kicks it back if it is only numbers.

@eileenchoe says work back from the error code.

**Comment by mihirsamdarshi** [comment]
this should be fixed

**Comment by mihirsamdarshi** [comment]
while re-testing before creating a pull request, with this file, my fix doesn't seem to detect the values entered in cells with the Gene names as numbers. Originally, the problem was the .toUpperCase(), in the 2 try catch statements starting at line 284, and deleting these seemed to fix the corruptGeneError message. I then tried to add a .toString() to the currentGene.name, but this seems to have no effect on it not detecting.

**Comment by kdahlquist** [comment]
@mihirsamdarshi, de-prioritize this so that the dashed line and gray % can be debugged.

**Comment by kdahlquist** [comment]
@mihirsamdarshi is going to work on this first during the sprint.

**Comment by kdahlquist** [comment]
Is this going to go live on beta?  I'd like to test it out.

**Comment by mihirsamdarshi** [comment]
I'm updating beta right now

**Comment by mihirsamdarshi** [comment]
Beta is updated

**Comment by kdahlquist** [comment]
I did a basic check with an unweighted graph, a weighted graph, and node coloring, and the graph displays properly.

I have a question for @mihirsamdarshi: for what conditions did you write tests for this feature?

**Comment by mihirsamdarshi** [comment]
I have not implemented the tests for this feature just yet, I plan to do that tomorrow

**Comment by mihirsamdarshi** [comment]
Tests have been implemented an are sitting on my branch, I will issue a pull request with the completion of another issue

**Comment by kdahlquist** [comment]
@mihirsamdarshi please outline here the types of things you are testing for?  Also, gentle reminder of TDD, means tests first!

**Comment by mihirsamdarshi** [comment]
simply having numbers as node labels i.e. worksheets with gene names as solely numbers and worksheets with gene names that exist with solely numbers, solely letters, and a mix of both

**Comment by kdahlquist** [comment]
Upon review by @dondi, this can be closed.
