### ISSUE TITLE
GRNsight won't load in Chrome due to HTTPS error?

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#439]
I'm pretty sure this is an issue only I'm having right now, but I'm not sure if it can affect others in the future, so I'm going to report it.

Neither beta nor master are not loading on the website in chrome. It works if I run it through the command line, but not if try to view it on the website. On both beta and master, I get the following error:
![screen shot 2017-04-17 at 4 24 08 pm](https://cloud.githubusercontent.com/assets/6444156/25108387/5252211c-238a-11e7-942a-5e9cc38349cc.png)

I can just use firefox to get around it, but I'd like to be able to use Chrome. I'm running Chrome version version 57.0.2987.133 (64-bit) on a Mac, no extensions on chrome.

@dondi, any ideas?

**Comment by kdahlquist** [comment]
I think I reported something related to this in #327.  See @dondi's response there.  It's not clear from his response if there is a way to fix this.

**Comment by NAnguiano** [comment]
Yep, that appears to be the exact same issue. I'm not sure why now it's just now starting to affect me, but I'll switch to https for now. Because this is the exact same issue as #327, I'll close this one up.
