### ISSUE TITLE
Implement manual “snap to grid”

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#44]
Distinct from _automatic_ grid (Issue #25), we can just snap to grid as the user drags a node.

**Comment by kdahlquist** [comment]
This could actually be covered by an automatic layout function that places the nodes in a grid.  Cytoscape has this option.

**Comment by kdahlquist** [comment]
I'm tagging this issue as backlog because it is partially taken care of by grid layout.  Note that this issue is for manual, when the user moves things around and let's go.  This would still be a useful feature, but is not a top priority now.
