### ISSUE TITLE
Disallow export of unweighted graphs to weighted SIF/GraphML

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#441]
I noticed as I was writing up the pull request checklist from #440 that we're currently allowing unweighted graphs to be exported as weighted SIF and GraphML. I initially didn't think this affected anything, but when I load the weighted SIF exported from the unweighted demo, it is treated as a weighted file.

![screen shot 2017-04-18 at 6 45 58 pm](https://cloud.githubusercontent.com/assets/6444156/25159855/61d86c3a-2467-11e7-8095-a8e41fc8a7d4.png)

I think this could potentially be misleading. While the weight of 1 in an unweighted xlsx matrix represents just the existence of a relationship, because that weight is exported as a 1 to the weighted SIF, it treats it as a weight of 1. 

I think that we should not allow unweighted graphs to be exported to weighted SIF/GraphML. Only weighted graphs should have both options, while unweighted graphs will be offered only the unweighted option. 

Edit: As seen in @kdahlquist comment below, this behavior is a confirmed bug and should be fixed at some point.

**Comment by kdahlquist** [comment]
When we were coding this up originally we missed this.  I agree with @NAnguiano.  However, we have too much on the docket to deal with this now, so we'll keep it at a priority 1.

**Comment by johnllopez616** [comment]
Will investigate this issue further when GRNsight is refactored to handle large-scale state changes.

**Comment by mihirsamdarshi** [comment]
Fixed this in PR #802

**Comment by kdahlquist** [comment]
confirmed fixed in beta 4.0.5
