### ISSUE TITLE
Protocol for handling pull requests that are not ready to be merged?

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#445]
I think we should have some sort of protocol for pull requests that are not ready to be merged or shouldn't be merged yet - whether it's because they are bugged or because there is additional functionality that's going to be added to them. This would just ensure that incomplete or bugged pull requests don't get added by accident (though hopefully the pull request checklist from #440 would allow bugs to be caught first? :wink:).

Perhaps some sort of label indicating a pull request is not ready for evaluation could be created and added to the pull request. Or, the pull request can be closed and reopened when it is ready for evaluation. Or maybe both - the first being used for small bug fixed and the second being used for more major changes and fixed. 

This could just be an issue that bothers me, but I'm not certain. What do you guys think?

**Comment by kdahlquist** [comment]
I'm not perhaps the best person to comment on this, but I think that a pull request implies that it is ready to be merged, and that if it isn't for some reason, then it shouldn't be there.  @dondi definitely needs to weigh in on this one.

**Comment by dondi** [comment]
It used to be that the act of merging was synonymous with approval—i.e., a pull request remained unmerged until it was deemed ready—but GitHub has since added an explicit "approval" feature (without being merged). This is available when a team member opts to “review” a pull request. When reviewing a request, they can now mark it as approved, or request changes. The coder can then submit additional commits, and the cycle can go on until a pull request is approved. An approved pull request can then be merged whenever.

Of course this feature is optional and need not be used, but its presence does allow for a cycle like I described, where a pull request is first issued, then we can establish that it needs to explicitly get approved before it can be merged.

**Comment by kdahlquist** [comment]
@NAnguiano, does what @dondi suggest fit your needs?  Initially, I was thinking that we could get away with a less formal review process, but if you think it's necessary, then it seems like the process @dondi suggests will work.

**Comment by NAnguiano** [comment]
The initial motivation for creating this issue was two-fold. The first being that I keep seeing we have an open pull request and checking it, only to realize it's something I've already checked. And second being that yesterday, during my work session with @yshin4, I checked and reviewed her pull request (the now closed #436) and was about to merge before she let me know that the PR wasn't actually ready for review because there was more work that needed to be done. The first is a minor annoyance, but I'd like to avoid situations like the second one. 

In this case, it wouldn't necessarily have affected anything should I have just merged it before finding that out. But that may not always be the case. And it's that possible case that worries me.

Of course, beta doesn't necessarily need to be 100% functional, so if bugs get introduced because of a pull request being merged that wasn't ready, it's not the end of the world. But I still think it's nice to have some way of showing that the team member behind the pull request has deemed it ready for review before it is actually reviewed and pulled into the main beta branch. Or to have some sort of documentation on situations like the above two should be handled.

But I do like @dondi's suggestion. Maybe not as something implemented right now so close to the end of the semester, but I think it would be overall helpful in the long run.

**Comment by kdahlquist** [comment]
A team member that submits a pull request should actually do the PR checklist before submitting the request.  Then the reviewer independently does the checklist and either approves or asks for revisions (or closes without merging).  A PR should not be opened if it is not "ready" for this.
