### ISSUE TITLE
Hide "Data" menu in beta

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#447]
The "Data" menu got hidden on Master because there is no functionality there and we didn't want to have any placeholder menu items visible.  This is a reminder that we need to hide this menu option on beta, too, so that when it becomes Master, it suddenly doesn't become visible again.

I'm not sure who to assign this to.

**Comment by NAnguiano** [comment]
I went ahead and did this on my fork. It will be in my next PR, which should come tonight.

**Comment by NAnguiano** [comment]
This is now live on beta as per PR #448.

**Comment by kdahlquist** [comment]
Verified complete on beta v2.0.7.
