### ISSUE TITLE
Beta v2.0.9 crashed when reviewing #362

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#450]
Just letting you all know I crashed beta when testing #362.  Whoever restarts it can close this issue when it's back up.

**Comment by NAnguiano** [comment]
It's back up. Do you know the file that crashed it? I'll post an issue with the error message shortly.

**Comment by kdahlquist** [comment]
The file is posted on issue #362.

At 10:31 PM 4/19/2017, you wrote:
