### ISSUE TITLE
SIF importer crashing due to "entry" being null

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#451]
Looks like something brought the beta server down while @kdahlquist was testing #362. Here's the error message.
![screen shot 2017-04-19 at 10 30 59 pm](https://cloud.githubusercontent.com/assets/6444156/25215085/ffcb0c8e-254f-11e7-858b-71e60712b8fd.png)
It got a little cut off at the bottom, but there's nothing below that. Last line just says `at Object.oncomplete (fs.js:107:15)`. 

@eileenchoe, I'm sending this your way since SIF is your domain. 

The responsible file is posted in #362.

**Comment by kdahlquist** [comment]
The file is posted on #362.

At 10:35 PM 4/19/2017, you wrote:

**Comment by eileenchoe** [comment]
Fixed by handling the null entries generated when the SIF importer detects extraneous new lines. Issuing a pull request that deals with just this issue. Will work through issues brought up in @kdahlquist 's comment on issue #362 tomorrow.

**Comment by kdahlquist** [comment]
Verified that the file that crashed it last night no longer crashes the server and gives an error to the user.  I'm closing this one, but leaving open #362 because there were other issues reported there that still need to be addressed.
