### ISSUE TITLE
We should allow GRNsight to be accessed at dondi.github.io/grnsight/

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#453]
In 402 on Monday, someone tried to access GRNsight but the site appeared to be down. When I tested it out, I discovered that it's because they'd typed the url as dondi.github.io/grnsight/ instead of dondi.github.io/GRNsight/. This seems a bit weird to me because on twitter, I can use both twitter.com/rtoal and twitter.com/RToal to get to Dr. Toal's twitter. I'm don't think every possible permutation of GRNsight needs to link to our website, but I think that allowing it to be typed in all lowercase may be something we want to allow. 

What do you guys think?

**Comment by kdahlquist** [comment]
Yes, I think that all lowercase and all uppercase and perhaps sentence case, Grnsight, should be allowed.

Do we need to do something with Google Analytics so that those are all counted as page views?

**Comment by kdahlquist** [comment]
We should talk about this at a meeting.

**Comment by dondi** [comment]
I don't disagree with this suggestion, but I'm not sure if we can control it. GitHub Pages is the one that maps these URLs to our _gh-pages_ branch, and the capitalization requirement might be baked in. Will need to do some research on this.

**Comment by dondi** [comment]
Workaround can be explored: https://stackoverflow.com/questions/48388057/how-to-make-github-pages-url-case-insensitive/48389490

**Comment by dondi** [comment]
Case sensitivity still exists but this remains attributable more to GitHub functionality than our own code. Still, it would be nice, so will backlog it for future revisiting
