### ISSUE TITLE
Reset sliders and undo reset slider menu options are not working in beta (buttons are still OK)

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#454]
When checking #245, I noticed that the Format > Reset Force Graph Parameters and Format > Undo Reset menu items are not functioning.  The buttons are working, but the menu items are not.

Labeling this as priority 0 because it is a regression from functionality currently available on master.

We will assign this to someone at the meeting in a few minutes.

**Comment by kdahlquist** [comment]
I forgot to talk about this one at the meeting.  I'm tagging it for the release because it is a regression of function.  Still not sure who to assign it to.

**Comment by kdahlquist** [comment]
I'm going to give this one to @eileenchoe.  As I mentioned, what she's got left in #362 is in a good enough state and this one needs to be fixed for the release.

**Comment by eileenchoe** [comment]
@kdahlquist To clarify, the reset and undo reset functionality should be the exact same for the button version and the menu version, correct?

**Comment by eileenchoe** [comment]
Fixed!

**Comment by NAnguiano** [comment]
Merged PR #456. This fix is live on beta and can be reviewed.

**Comment by kdahlquist** [comment]
verified is working on beta 2.0.12
