### ISSUE TITLE
"Fit to window" doesn't fit to window

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#461]
I thought it might be easier if we start making these issues more granular to individual behaviors.

When I select "Fit to window", it doesn't.

I expect that the viewport will "snap" to the lower right corner of my browser.

Instead, I actually get a really long viewport with scroll bars.

Since I have my browser window maximized, "fit to window" should not really make a big change, actually.  It would seem that it would come into play when my browser window was smaller.

**Comment by NAnguiano** [comment]
Ok, I somehow managed to completely miss a comment I'd made in issue #395 about using the iFrame Resizer.. and I straight up just forgot to implement it. The iFrame is supposed to fit itself to the window, but it's not right now. It's fitting width-wise, not length-wise. So the "window" the bounding box is trying to fit itself to is actually the adaptive width but fixed height (1200px) of the iFrame.

I'll do fix this right away.

**Comment by dondi** [comment]
I’ve used iFrameResizer elsewhere and it generally does the trick. However it does have some learning curve if you want to control things precisely. Let me know if you get stuck here.

**Comment by NAnguiano** [comment]
There's something weird going on with the fit to window code. It seems to be generating right-hand side scrollbars for no reason. I'll be taking a look into this in the morning.

**Comment by NAnguiano** [comment]
Of course, the method I used for this doesn't work in Firefox. Only in Chrome :cry:. Still am not sure what's going on with fit to window scrollbars, but I think that

**Comment by kdahlquist** [comment]
That will have to be OK for now.  @kdahlquist will need to get over her aversion to Chrome, but we'll need to bring this back up later.

**Comment by kdahlquist** [comment]
@kdahlquist further says that the restrict/fit/viewport size options really need to undergo some exhaustive testing for unexpected behaviors that we don't have any more time for right now.  So the current solution needs to be OK for now.  Lowering the priority and removing the "for next release" tag.

**Comment by kdahlquist** [comment]
It looks like this has been fixed sometime in the last year.  Selecting fit to window on either my laptop or desktop monitor looks fine.  I still get scroll bars when the size is set to "medium", but that is another issue.  Closing this one.
