### ISSUE TITLE
Reorganize menu options to make sense with v2 feature set

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#462]
As discussed by @NAnguiano and @kdahlquist today, we are going to make smaller, granular tasks out of the "catch-all" #396, #399, and #411, so it is clear exactly what needs to be finished and when.  This is a start on recording stuff from the comments of #411.

From the initial comment on #411:
* The menus need to be reorganized to make sense with the current feature set.  It is worth looking at the menu systems for competing software because users may be familiar with it.  However, we should do what's best for us.
    * The File, Demo, and Help menus should remain as is.
    * The Edit, Format, and Data menus are what will be reorganized pending further discussion.
    * A "View" menu could control the viewport and drafting board options, and the choice to color or use black edges, and possible show/hide edge weights.
    * A "Data" menu would have options related to data.
        * It is not clear whether some options better belonged in "View" or "Data" or maybe should be in both.
    * (once implemented) create a "Graph Layout" menu with the options of "force graph layout" and "hierarchical layout", with submenus that have the slider options.

This is a priority 1 for now because it doesn't affect the critical path for release of v2 and other things have higher priority.

**Comment by kdahlquist** [comment]
I'll comment here because this issue most closely aligns to tweaking the UI.  Upon reviewing #326, it becomes clear that we have some additional UI decisions to make.

For example, on the - [GRNsight Function Availability](https://github.com/dondi/GRNsight/wiki/GRNsight-Function-Availability), the User Action is listed as "Load Graph", but the actual menu item is "Open".  Our documentation and testing should use what is in the UI, but in this case, maybe the UI needs to change.

**Comment by kdahlquist** [comment]
This has now become a priority because both @yshin4 and @eileenchoe have new features that require buttons/menu options.  I want to have a discussion when everyone is here, so we should do this the next meeting when everyone is here.

**Comment by dondi** [comment]
Here is the current v2 menu outline:
* File
    * Open
    * Reload
    * Import
    * Export Data
    * Print
* Edit
    * Preferences
        * Optimized edge weights
        * Black edges
* Format
     * Lock Force Graph Parameters
     * Reset Force Graph Parameters
     * Undo Reset
     * Only Show Edge Weights With Mouseover
     * Always Show Edge Weights
     * Never Show Edge Weights
* Help
     * Getting Started
     * GRNsight Wiki
     * About GRNsight
* Demo
     * Demo 1
     * Demo 2
     * Demo 3
     * Demo 4

**Comment by eileenchoe** [comment]
* File
  * Open
  * Reload
  * Import
    * SIF
    * GraphML
  * Export Data
    * To Unweighted SIF
    * To Weighted SIF
    --
    * To Unweighted GraphML
    * To Weighted GraphML
  * Print

* View
  * Viewport Size
  * Restrict to Viewport
  * Zoom

* Layout
  * Force Graoh
    * Lock
    * Undo Lock
    * Reset
    * Link Distance
    * Charge
    --
  * Grid
    
* Node
  * Top Dataset
    * ... (automatically generated)
  * Bottom Dataset
    * Same as top (default)
    * ... (automatically generated)
  * Log Fold Change Max Value

* Edge
  * Always Black
  * Optimized
  -- 
  * Always Show Edge weights
  * Show on Mouseover
  * Never show edge weights
  --
  * Edge weight normalization factor
  * Reset normalization factor
  * Grey edge threshold

* Help
  * Getting Started
  * GRNsight Wiki
  * About GRNsight

* Demo
  * Demo 1
  * Demo 2
  * Demo 3
  * Demo 4

**Comment by yshin4** [comment]
@eileenchoe and @yshin4 got together on Wednesday night and finished the UI part. Now we have to add logic to the elements. 

@yshin4 will do:

View
- [ ] Viewport Size
- [ ] Restrict graph to viewport
- [ ] Zoom

Layout
- [ ] Link Distance
- [ ] Charge
- [ ] Grid Layout
- [ ] disable force graph or grid depending on which one is applied

@eileenchoe  will do:

Node
- [ ] Disable and Enable Node Coloring
- [ ] Top Dataset
- [ ] Average Replicate (Top)
- [ ] Bottom Dataset
- [ ] Average Replicate (Bottom)
- [ ] Log Fole Change Max Value

Edge
- [ ] Edge Weight Normalization Factor
- [ ] Reset Normalization Factor
- [ ] Gray Edge Threshold

File, Help, and Demo is the same as before.

**Comment by eileenchoe** [comment]
- Put ranges for any open text boxes
- "Select Top Dataset" and nest options in second level
- Under Edge Menu -> Toggle "Show Gray Edges as Dashed" (default: unchecked)
- Put leading zeros on decimal number inputs
- Refactor Grid and Force & disable logic

**Comment by eileenchoe** [comment]
Completed this feature as well as #576 (state management) for the subset of features I worked on for this issue (Node & Edge dropdowns). I've tested a lot combinations and I believe I've got the Node and Edge options both in the menu and sidebars to completely sync & not affect one another. PR will be submitted when @yshin4 completes UI logic for View and Layout.

**Comment by yshin4** [comment]
Finished everything except one thing. Putting a zoom value in the input box in menu does not trigger the function to get applied to the graph. I tried using ```$(".zoomSlider").trigger("input");``` but it did not work. I am wondering if this is because zoomSlider is related to d3.select as it is like this in the code: ```d3.select(".zoomSlider").on("input", function () {```

Any idea @dondi @eileenchoe?

**Comment by yshin4** [comment]
Similar issue, for restrict graph to viewport ```d3.selectAll("input[name=viewport]").on("change", function () {``` manual trigger for the checkbox does no work ```$(".viewport").trigger("change");```. https://stackoverflow.com/questions/10547622/trigger-change-event-select-using-jquery/10547666 This post said `The change event handler must be declared before the trigger.` so I tried putting the manual trigger below the d3.select viewport change function, but it did not change anything.

**Comment by eileenchoe** [comment]
@yshin4 I fixed the zoom slider & restrict graph to viewport issues!

@kdahlquist  I also added input validation to all the text boxes in the menu. What happens is that if the user inputs a numeric value outside of the given range e.g. (0-100% for gray edge threshold), then if the number inputted was less than the minimum, like -5, it will default to the minimum, 0. Likewise if user inputs 300, it will default to 100%. 

@yshin4 I have not implemented validation like this for the open text boxes for charge and link distances text boxes in the menu -- could you finish this up?

**Comment by eileenchoe** [comment]
As discussed in the meeting Monday, we will also need to add the menu-bar equivalents of the UI functions we duplicated to the client side test generator for #575. @yshin4 can you add them for your half of the features & I can add my half?

**Comment by yshin4** [comment]
Thank you @eileenchoe, I checked zoom and restrict and did some testing, looks like it's working fine.
I finished up the charge and link distance validation as well.

**Comment by yshin4** [comment]
On the side note, I have some changes (text toggling for grid layout button) in my d3v4-grid branch. But because something funky happened regarding master, I don't know if I should mess with that branch anymore. Should I apply those changes in the menu branch and merge it together, or submit a PR from d3v4-grid branch?

@dondi @eileenchoe

**Comment by eileenchoe** [comment]
@yshin4 featureList.json should be edited in the `menu-updates` branch (I didn't see the changes when I pulled just now, so can you transfer them over?), because it should be included with the PR. Also, to provide a consistent naming to distinguish duplicated features, I am prefixing them with "Sidebar Menu" and "Dropdown Menu" to distinguish them.

**Comment by eileenchoe** [comment]
@yshin4 I would do a PR just in case. If there are only a few commits you need to transfer, you could do the cherry-pick on those commits to `menu-updates` as we did in the last meeting to merge specific commits

**Comment by yshin4** [comment]
@eileenchoe Yeah sorry I forgot to push, I will add it on top of your updates and change it to Dropdown Menu. Meanwhile, I will make a PR for d3v4-grid.

**Comment by yshin4** [comment]
Live on beta now.

**Comment by kdahlquist** [comment]
Live on v3.0.0.
