### ISSUE TITLE
Changes to zoom slider

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#465]
Now working on making individual tasks from #399.

1. We need a vertical bar on the zoom slider to indicate where 100% is (scale factor 1).
2. We need a label that shows what the current zoom factor is (in terms of percent).
3. The positioning of the zoom slider needs to come up and to the right a little bit so there is some white space surrounding it and it's not flush with the viewport boundary.
4. It was suggested in #399 that using a log transform on the zoom slider might make it behave better.  Was this tried and was it successful?

I know from discussions with @NAnguiano that the zoom functionality is behaving a little erratically, which might make these labels also behave erratically.  I still think we need to have them, however.  As it currently stands, it's not ultra obvious that the slider is referring to zoom.  Adding the current % will clue the user in.

**Comment by dondi** [comment]
Nothing to add here for now; let’s see what emerges then we can tweak from there.

**Comment by NAnguiano** [comment]
Just about done with this. The zoom slider works way better than before, and a vertical bar is set at the scale 1. Just need to have the slider update properly when you're zooming with the mouse wheel, then this is done.

**Comment by kdahlquist** [comment]
After discussion with @NAnguiano, Bostock says himself that zoom is not functioning properly in version 3 of D3, which we are using.  It is supposed to be fixed in version 4, but moving to version 4 will require a complete overhaul of GRNsight.  For example, v4 of D3 is not a single library but a set of smaller libraries that need to be installed independently.  As a test, @NAnguiano tried just using the v4 D3 zoom code in GRNsight and it doesn't work.

Creating the vertical bar for 100% that automatically returns the graph to 100% and showing a numerical zoom factor are sticking points right now that are causing problems.

@kdahlquist says that we can let go of those features for the moment, in favor of simply having a zoom bar that functions without crashing.

**Comment by kdahlquist** [comment]
I've played around with the zoom and it seems to be working OK, with the known issue of it originating with the upper left of the bounding box.  However, using the sun button to center the graph after zooming is not too bad.  I'll go ahead and close this one.  I'm going to open separate issues for creating the 100% bar on the zoom (#484)  and for annotating the zoom factor (#485).  But as agreed, these are not required for the release.
