### ISSUE TITLE
Allowable zooming/scrolling actions when "Restrict Graph to Viewport" is selected

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#470]
Carried over from #396, these are the allowable zooming/scrolling actions for when "Restrict Graph to Viewport" is selected:

The way things work now under the adaptive setting is that scrolling or grabbing the graph moves the entire bounding box to a different relative location within the viewport.

Thus, when "restrict graph to viewport" is selected, to be true to this label, we can't allow scrolling or grabbing of the graph because that would bring the bounding box out of alignment with the viewport.
* At 100% zoom, no scrolling/grabbing is allowed
* Remember, we are not allowed to make graph bigger anyway (zoom in)
* If graph is smaller (zoomed out), then you can scroll/grab, but you can't move the bounding box beyond the edge of the viewport (top, bottom, left, right).
    * if subsequently you do zoom in, the bounding box is going to get pushed so that it never goes outside the viewport, so that it will end up at 100% flush with all four sides of the viewport.

**Comment by dondi** [comment]
Agreed—“restrict graph to viewport” is essentially the current behavior, with the third bullet being the way this mode handles zooming. @NAnguiano and I actually talked about how to implement this today, and I gave her a sketch of how to potentially do it.

**Comment by kdahlquist** [comment]
This is complete as of v2.0.16, but there one remaining small issue that will become its own task for later.
