### ISSUE TITLE
Adaptive bounding box only expands downward and to the right

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#471]
@NAnguiano notes in #396, that the adaptive bounding box only expands downward and to the right.  Fixing it to adapt up and to the left is not in the critical path for release of v2.

**Comment by kdahlquist** [comment]
There is a related issue that we're calling a "Rapunzel effect" where, if a node is dragged to the top or left boundary, the rest of the graph inappropriately expands in the opposite direction. @dondi observes that this might be related to how a node becomes "fixed" once it is dragged. Another factor may be the way SVG sets groups based on their top left corner.

Overall this looks like it is worth a deeper code review by @eileenchoe, who will dig in a bit then report back on what she finds.

**Comment by kdahlquist** [comment]
Temporarily retaining the gray border for the bounding box might also help here, so that you can see visually how the SVG grouping box changes as the force graph expands.

**Comment by eileenchoe** [comment]
I've got a good idea about what's going on here. The logic for expanding the boundingBox is in the tick function. The code is pretty much confirming what we saw. When a node is fixed at the edge of the bounding box, the leftBoundary, the width will get larger until it hits the maximum width of 5000. Same goes for the expansion downward. 

There is no code for decreasing the height and width of the boundingBox, other than when a new viewport size is chosen or when the viewport changes from adaptive to fixed. I'll have to do more thinking about how to fix this later today.

**Comment by dondi** [comment]
OK, so it looks like the potential solution is to apply a “compensating” scroll or translation to the boundingBox, to make it look like it is expanding outward from all directions instead of just downward and to the right. So if the width and height have expanded by _dw_ and _dh_ respectively, it looks like scrolling/translating by _–dw/2_ and _–dh/2_ may help provide the desired visual effect.

**Comment by eileenchoe** [comment]
Leaving this here for reference. Link to tutorial for handling transforms with the svg element.
https://www.dashingd3js.com/svg-group-element-and-d3js

**Comment by eileenchoe** [comment]
I've tried a few ways to go about fixing this, and the problem I kept getting with adding a compensating scroll like @dondi suggested was that it interfered with the translation calculations for centering and zoom. 

I've implemented a pretty simple workaround where the boundingBox expansion only occurs for nodes that are not fixed. So the nodes on the borders will not cause the "Rapunzel effect." I can keep working on this one, but since this workaround stops this unintended behavior I'll include it in the pull request I'm making right now with some other issues.

**Comment by eileenchoe** [comment]
Live on Beta v2.1.6

**Comment by kdahlquist** [comment]
Hmm.  The fix does get rid of the Rapunzel effect.  However, I'm not sure that the new compensating behavior is something that I like.

With this new implementation (and maybe some aspects of the old one), an adaptive bounding box has some restrictions that a graph restricted to viewport has.

When I drag nodes, they now bump up against an invisible bounding box on all four edges, top, bottom, left, and right.  In my mind, a corollary of having an adaptive bounding box means that dragging nodes to the edge could also expand the bounding box.

I'm going to leave this open, but lower the priority for now.  I think we need to think on this one some more.

**Comment by eileenchoe** [comment]
Yes, I agree that we should keep working on this one. Currently, when the viewport is adaptive the bounding box will expand only as a response to force graph parameter changes that cause the nodes to bump up against the bounding box. We will have to rethink how manual node dragging will expand the bounding box without disabling manual-node-dragging-expansion all together. When I was working on this, I ran into issues with centering and zooming, which are also dependent on the position and scale of the bounding box.

**Comment by kdahlquist** [comment]
Another consequence of only allowing the bounding box to expand down/right is that if it gets really large, clicking the center button will center the graph, but not in the middle of the viewport.  The center for a large bounding box will be down and to the right, too.

I was messing around with the force graph parameter sliders expanding and contracting the graph so that the bounding box got large.  Clicking on center did not bring it to the center of my viewport.

We also have no way of making the bounding box smaller again except by checking restrict graph to viewport.

**Comment by kdahlquist** [comment]
Backlogging and closing.
