### ISSUE TITLE
Disable mousewheel zoom after zoom slider is fully functional

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#473]
This has been noted by @kdahlquist and @NAnguiano.  Immediately upon graph load, the mousewheel function switches over to controlling the zoom level, which is disconcerting if the user meant instead to scroll the browser window.

This should be changed somehow, but it is not in the critical path to release.

**Comment by kdahlquist** [comment]
I think at the meeting today, the consensus was that we should disable the mousewheel zoom entirely.  Maybe not until we get the zoom slider working the way we want, but soon after.

**Comment by eileenchoe** [comment]
Did you know that double click in the viewport also zooms GRNsight? I just came across this right now. It zooms with respect to the mouse pointer as the center. I am also disabling this one along with the mousewheel zoom because it interferes with the way that I implemented the slider zoom.

**Comment by kdahlquist** [comment]
Yikes!  Was just writing this comment when @eileenchoe came in.  Definitely disable this!

**Comment by eileenchoe** [comment]
Live on Beta v2.1.6

**Comment by kdahlquist** [comment]
This was easy to test (and quite a relief)!  Closing!
