### ISSUE TITLE
Run the Graph Statistics Report After completing semantic analysis

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#474]
I just managed to freeze beta for a solid few minutes because I uploaded a large graph multiple times. 

Right now, we run the graph statistics report after we finish parsing a network, but before the semantic analysis. This means that we haven't checked to see whether there are too many nodes or edges.

A fully connected graph with 150 nodes takes about 1.5-2 minutes to finish loading when graph statistics is enabled, and about a second with them off - nevermind the fact that one can actually just upload it over and over and over without limit (because they may think that it didn't load correctly - at least that's why I did it...), potentially bringing GRNsight down until they all finish generating.

So I propose that we run the graph statistics report only after the semantic analysis is complete. There's no real reason to run it beforehand that I can think of anyways. 

This would also have the benefit of removing the cytoscape errors spam from the tests when we run them.

Thoughts?

**Comment by kdahlquist** [comment]
Yes, absolutely!

Question: why are you trying to run things with cytoscape turned on?  It's not actually computing the graph statistics correctly as per #296, #298, and #307.  We can't turn it back on until we've addressed those issues, anything we display from it right now will be giving wrong information to the user.

**Comment by NAnguiano** [comment]
I'm actually not fully sure why we have it on right now. It was turned on for issue #343.  I think there are some tests in our test suite that rely on it being on not to fail, but they could be turned off.

**Comment by kdahlquist** [comment]
OK, I see that we probably forgot to turn them off again.

For now we just need to turn cytoscape off.  The GRNmap data analysis team has been working all semester to try and interpret graph stats from Gephi and we're not actually done with that yet.  Until we have an independent way of verifying that what cytoscape is returning is valid, we can't turn it on.

I'm moving this to a 1; it's not in the critical path for release.

**Comment by NAnguiano** [comment]
Sounds good to me! I'll turn it off.

**Comment by NAnguiano** [comment]
It's off. Just so you all know, now that it's off, there are 29 tests that will be returned as "pending". That's because I've set it to just skip them. All of those tests are the graph stats tests.

**Comment by kdahlquist** [comment]
Backlogging because we are putting a freeze on new features for now.  Can re-open in future when we are ready to tackle graph statistics again.
