### ISSUE TITLE
beta v2.0.15, automatic detection or selection of medium/large viewport causes iframe scroll bars

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#477]
I didn't notice this last night because I was working on my laptop and "small" was automatically detected, but now I'm on my larger monitor, the automatic detection of a "medium" viewport causes the dreaded scroll bars on the iframe.

If I resize my browser window smaller, reload the page, then small is detected and everything is fine.

Then I just selected medium or even large viewport and the iframe scroll bars appear.  Medium (as we know) was looking awesome fitted exactly to my screen.  I'm wondering if this is an artifact of the fit to window stuff.

**Comment by NAnguiano** [comment]
So I think I managed to fix this. let me know if you're still getting scrollbars.

**Comment by kdahlquist** [comment]
The fix for this only works in Chrome and not in Firefox.  As noted in #461, this will have to be OK for now.

**Comment by kdahlquist** [comment]
I'm going to close this so that #750 will contain all iframe scroll bar issues.
