### ISSUE TITLE
Create vertical bar on zoom slider to indicate 100% zoom factor

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#484]
As noted in Issue #465, this is broken out as a separate issue to be assigned to someone in the future.

As I play with the zoom, it does become apparent that we need some sort of indicator to return the graph to 100% zoom.  A vertical bar on the slider could do it, or something else.

**Comment by eileenchoe** [comment]
Here's what the vertical bar I have so far looks like in Firefox:
<img width="198" alt="screen shot 2017-05-23 at 11 38 41 am" src="https://cloud.githubusercontent.com/assets/16827883/26370413/8d2225b0-3fac-11e7-8e1a-db63950aa5d8.png">
And in Chrome:
<img width="150" alt="screen shot 2017-05-23 at 11 38 51 am" src="https://cloud.githubusercontent.com/assets/16827883/26370421/92b1614e-3fac-11e7-94a2-294aec7d9b0a.png">

**Comment by kdahlquist** [comment]
The slider and bar look good.  Would it be possible to position the slider at 100% and have the label present even if a graph wasn't loaded?  This would indicate to the user that the vertical bar represents 100% and that that will be the default when the graph is loaded.  Thoughts?

**Comment by eileenchoe** [comment]
Yep, that makes sense. Was a pretty simple fix, so I'll go ahead and do the pull request for this one.

**Comment by eileenchoe** [comment]
Included in PR #500

**Comment by eileenchoe** [comment]
Live on Beta v2.1.3

**Comment by kdahlquist** [comment]
Something for discussion at the meeting today.  When I initially look at the 100% directly underneath the vertical bar, it makes sense that the bar represents 100%.  However, when I move the slider and the value changes, then it seems a little odd because I might interpret that the meaning of the vertical bar has changed.  We'll talk about whether this is weird for other people and what to do about it at our Hangout.

**Comment by kdahlquist** [comment]
Another question--would it be possible to make the vertical bar be "clickable" so that if you click it, the slider immediately goes directly there?  (It might do this already, but I can't test it now that I've crashed beta).

**Comment by eileenchoe** [comment]
Currently, the vertical bar is not clickable. It is a skinny rectangle that is positioned "beneath" the slider so the visible/clickable area currently is the top and bottom that is sticking out from underneath the slider. Not sure if this would be the intended interaction, but I agree that some way to re-center would be useful.

**Comment by kdahlquist** [comment]
in beta 2.1.4
