### ISSUE TITLE
Annotate zoom factor on zoom slider

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#485]
As noted in issue #465, this is broken out as a separate issue to be assigned to someone in the future.  It would be good to indicate the actual zoom factor near the slider like what is done for the force graph parameter sliders.

**Comment by eileenchoe** [comment]
Tackled this one this morning to start figuring out how zoom was implemented. Here's how it looks when a graph is initially uploaded. @kdahlquist when we meet later today I have some questions about how this percentage changes when toggling restrict graph to viewport
<img width="344" alt="screen shot 2017-05-19 at 10 12 59 am" src="https://cloud.githubusercontent.com/assets/16827883/26258963/c40d54ac-3c7b-11e7-9f25-640d92d7c050.png">

**Comment by eileenchoe** [comment]
Zoom percentages are now consistent between fixed and adaptive viewport. The zoom percentage goes from 0% to 200%, starting at the default of 100%. For adaptive viewport, the user is allowed to maximally zoom to 200%, however when the viewport is fixed, zoom is capped at 100%, with the viewport and bounding box the same. 

There are two ways to zoom: the mouse scroll and the zoom slider. 

At this point, it's working fine with the mouse scroll zoom, but there's an issue with the zoom slider when the user tries to zoom to 100% with the *fixed* viewport. The way I coded it simulates disabling the slider by not allowing the zoom event to be triggered if it detects that the viewport is fixed AND the slider zoom value is greater than ADAPTIVE_MAX_SCALE, which is equal to 100% zoom. The zoom event is fired using the *on input* event listener on the zoom slider. What's weird is that when the user zooms using the slider slowly, it correctly renders the 100% view, however when the zooming is done quickly, the graph does not quite get to the 100% zoom. I think that the event listener is not detecting the change fast enough, but have not come across a solution for this. @dondi is there anything that you suggest?

**Comment by kdahlquist** [comment]
@dondi willl look into the aforementioned behavior to see if something can be done to keep things in sync.

**Comment by eileenchoe** [comment]
A solution I found was to make the slider less sensitive by only allowing the discrete options 0%, 25%, 50%, 75% ... 200%. @kdahlquist is this ok or do you think the user should have the full range of zoom values?

**Comment by eileenchoe** [comment]
Actually this doesn't make too much sense because the mouse wheel slider is still more sensitive, so the zoom percentage won't actually capture the true zoom percentage when the user is using the mouse wheel instead.

**Comment by eileenchoe** [comment]
Included in PR #500. Reverted original zoom sensitivity and got the bug fixed!

**Comment by eileenchoe** [comment]
Live on Beta v2.1.3

**Comment by kdahlquist** [comment]
My comment on #484 is related to this one.  Let's discuss at the meeting today.

**Comment by kdahlquist** [comment]
Discussed in meeting and @eileenchoe made screen capture of @dondi's mockup.

**Comment by eileenchoe** [comment]
What is your opinion of having the zoom slider disabled when there is no graph loaded? When a graph is loaded it is automatically zoomed to 100% anyways so any interaction before the graph is loaded wouldn't affect the zoom level upon graph load. 

Graph not loaded:
<img width="160" alt="screen shot 2017-05-24 at 4 01 50 pm" src="https://cloud.githubusercontent.com/assets/16827883/26429183/62c739ec-409a-11e7-9e84-0f5110fa2770.png">

Graph loaded:
<img width="155" alt="screen shot 2017-05-24 at 4 02 00 pm" src="https://cloud.githubusercontent.com/assets/16827883/26429188/647d1e46-409a-11e7-8b9e-ed9bace45ae4.png">

**Comment by dondi** [comment]
I’m not opposed to that. Come to think of it I don’t think I’d mind if those controls were invisible when there is no graph open—their visual absence further emphasizes that state, I’d say.

**Comment by eileenchoe** [comment]
Good point. But I wonder if having those controls there, even when they are disabled, are still useful to the user because then they know what controls would be available to them if a graph was loaded.

**Comment by eileenchoe** [comment]
Live on Beta v2.1.5

**Comment by kdahlquist** [comment]
This looks nice.  Just a couple of micro changes:

* I think the range needs to be from 1 - 200%, not 0 - 200%.  0% seems kind of strange, like it should be invisible or something.
* Also, stylistically, I think all the other ranges have a space on either side of the dash, like 1 - 200% instead of 1-200%.

Thanks.

**Comment by eileenchoe** [comment]
Made these changes, and will be live with next pull request.

**Comment by eileenchoe** [comment]
Live on Beta v2.1.6

**Comment by kdahlquist** [comment]
verified and closing
