### ISSUE TITLE
Upload/Pageview Counter not showing up

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#487]
While working on #486, I noticed that it seems like the upload/pageview counter doesn't seem to be appearing properly.

![screen shot 2017-05-14 at 10 35 02 pm](https://cloud.githubusercontent.com/assets/6444156/26043968/31447368-38f6-11e7-9f52-f45143fcf955.png)

It's appearing this way on both beta and master, both on Chrome v 58.0.3029.110 and Firefox v 52.0.  No extensions on either.

I get the following errors in the console.
Beta:
![screen shot 2017-05-14 at 10 37 07 pm](https://cloud.githubusercontent.com/assets/6444156/26043985/51a31c72-38f6-11e7-86cf-9038923ce679.png)
Master:
![screen shot 2017-05-14 at 10 38 52 pm](https://cloud.githubusercontent.com/assets/6444156/26043992/5cb87f26-38f6-11e7-8d1a-d108c3c9ec8d.png)

This happens when I'm using the website on both http and https, with or without extensions, on both Firefox and Chrome.

Looks like a CORS issue. I'm wondering if the ga-controller needs to be moved to to the top-level directory now that the server is being run from there instead of from within the folders.

That's my best guess at least. Otherwise, I'm clueless.

**Comment by dondi** [comment]
I took a look at this and noticed an error message in the production server logs that was being reported whenever the server reported something to Google Analytics. I resolved the error (it was an incorrect path) and the counter appears to be working again. We should observe this a little more before closing. This fix may also have resolved the equivalent GRNmap issue (https://github.com/kdahlquist/GRNmap/issues/213 I think?).

**Comment by kdahlquist** [comment]
I just took a quick look.  GRNsight is now reporting again, but GRNmap is only recording pageviews, but not times downloaded.  However there is something else strange about GRNmap--The GRNmap homepage is reporting 298 views, but every other page is reporting 712.  I find it extremely unlikely that each page would have the exact same number of views.  I'll post on the GRNmap issue as well.

**Comment by kdahlquist** [comment]
confirmed fixed
