### ISSUE TITLE
@dondi needs to check if Zenodo registered DOI for our release

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#488]
I'm pretty sure that @dondi had registered GRNsight with Zenodo, so we should get a DOI for our release.  But, I'm not sure how that works.  Since he is the owner of GRNsight, he will need to check to see if it happened or not.

**Comment by dondi** [comment]
Ah yes this is coming back to me now. In issue https://github.com/dondi/GRNsight/issues/375 I did sign up but it's true that I didn't see a badge right away. Then the semester got the better of me and I didn't go back (so in hindsight it might have been best to have left that issue open).

But true enough, a badge is ready to go, and true to their word it is up-to-date, pointing to v2.0.20. Shall I add this to the README.md? Alternatively, we can just keep the actual URL and post it elsewhere. The badge looks like this:

[![DOI](https://zenodo.org/badge/16195791.svg)](https://zenodo.org/badge/latestdoi/16195791)

(and if you click on it, you will go to the Zenodo site for v2.0.20)

@kdahlquist after reviewing #375 I think you'll have a badge for the latest GRNmap waiting for you as well. If you visit https://zenodo.org/account/settings/github/ with your login, I think you’ll see it.

**Comment by dondi** [comment]
Just realized, the task is to check for a DOI and it was indeed noted, so closing this one.
