### ISSUE TITLE
@mihirsamdarshi needs to be set up to be able to push new versions to server

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#489]
@mihirsamdarshi needs to be set up to be able to push new versions to server since @NAnguiano, and @anuvarsh have now graduated and @eileenchoe's computer is in the shop.

**Comment by dondi** [comment]
@mihirsamdarshi Follow the instructions on this web page: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ _except_ for the last step 4 at the bottom. (the authentication approach we are using is the same as GitHub’s except for where the keys go at the end)

Instead, the public key file (the one that the process generates whose filename ends in `.pub`) should go to me. You can send it by email; as a public key it is safe to share. Once I have it, I’ll do what I need to do with it then inform you when you can try to connect.

If you want to learn more conceptually about what/how/why we are doing this, read up on "public key infrastructure" on the web.

**Comment by dondi** [comment]
The public key has been installed and @mihirsamdarshi was able to connect, so closing this one.
