### ISSUE TITLE
Need a "reset" button for normalization factor

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#506]
Now that I see the normalization factor in action, I think we definitely need a "reset" button which will reset the normalization factor back to the max value of the current graph.  If you change the value, there's no way to figure out easily what it was before unless you turn on the edge weights and try to look at them all or go back to the original file outside of GRNsight.

Alternately, or in addition, it might be nice to report to the user what the minimum non-zero weight and maximum weight values are so that they can be seen, like we do with the number of nodes and edges on the right hand side of the menu bar.

Anyway, I think a reset button is needed.

**Comment by kdahlquist** [comment]
@mihirsamdarshi, please prioritize the UI changes requested in #264  over this issue.

**Comment by mihirsamdarshi** [comment]
has been created, will be addressed in a pull request later today

**Comment by kdahlquist** [comment]
I will test this later today.  However in the meantime, please change the reset button to say "Reset Normalization Factor" (instead of parameters).

**Comment by kdahlquist** [comment]
I have tested functionality and it seems to work great.  I'm leaving this open until @mihirsamdarshi changes the wording of the button as requested above.

**Comment by kdahlquist** [comment]
Looks good!
