### ISSUE TITLE
When all edges have same weight value, they should render as thickest instead of thinnest edge thickness

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#513]
When closing out #355, we noticed an unexpected behavior when a "network_optimized_weights" sheet has edges with all the same weight values.

Currently, they render as colored (either magenta or cyan, depending on sign), but as the thinnest edge.

By our reasoning of how we are normalizing weight values, they should render as the thickest because when the max edge value is divided into all the others, they are all 1, the maximum thickness.

@mihirsamdarshi looked at the code and said that this is an artifact of how we are using D3 to bin edge weights.  Since there is only a single edge weight, there is no "minimum" reference point.

@mihirsamdarshi suggested that he could write a routine to deal with this particular edge case by telling GRNsight if it encounters only one edge value to make it the thickest edge, but @kdahlquist is worried about collateral damage.  For example, how would this interact when the user changes the normalization value, the thicknesses should then change based on the new normalization value.

@dondi, can you suggest how we should go about fixing this?

**Comment by dondi** [comment]
I think we can preserve existing behavior by treating just this situation—i.e., the one where minimum is equal to maximum—in a different way. I think if we detect this condition, we then substitute the minimum value for 0 and we will get the behavior that we want without disrupting the existing functionality that we already like.

The minimum and maximum are calculated here via D3’s `extent` function: https://github.com/dondi/GRNsight/blob/master/web-client/public/js/graph.js#L62

General sketch would be to pull out the `extent` function so that it is a variable of its own, then replace the minimum value (the first element of the array) with zero if the minimum and maximum are equal:
```javascript
var weightRange = d3.extent(allWeights);
if (weightRange[0] === weightRange[1]) {
    weightRange[0] = 0.0;
}

var totalScale = d3.scale.linear()
      .domain(weightRange) // <--- note substitution from existing line 62
      .range([2, 14]),

// etc. etc.
```

P.S. The variable `normalizedScale` is not used at all—looks like a vestige of earlier work in progress—and that can be safely removed.

**Comment by kdahlquist** [comment]
@dondi's comment makes me wonder this again--shouldn't the minimum value _always_ be zero?  That has been how I thought GRNsight was working, but comments like this make me worry that it isn't.

For example, let's assume a set of edge weights whose smallest non-zero weight is 5 and the largest is 10.  I'm expecting in this situation that the normalized weight values would fall between 0.5 and 1.  If we take 0 as the minimum, the 0.5 normalized weight would have a medium thickness and the normalized weight of 1 would have the thickest.  If 0.5 is taken as the minimum, then it would have the thinnest edge, which is what I _don't_ want.

**Comment by kdahlquist** [comment]
OK, I just tested it with this file:

It is not behaving how I want.  The minimum weight should always be 0.  We never really noticed this before because the smallest weight in the sheets we use for testing have always been sufficiently small simulate being zero.

[test_0.5-1.xlsx](https://github.com/dondi/GRNsight/files/1042267/test_0.5-1.xlsx)

**Comment by dondi** [comment]
So I looked at the `beta` branch rather than `master`, and it appears that the code there is substantially different. I had forgotten that normalization was not part of the 2.0.20 release. I’ll continue these notes in #515 since they pertain to that more closely now.

**Comment by kdahlquist** [comment]
So, when I investigated #515 and confirmed that it was fixed, I suspected that this one is now fixed as well.  

I verified that it is fixed.  However, there are two test files that need to be added to the repo before we close this.
[all-edges-same-weights-negative.xlsx](https://github.com/dondi/GRNsight/files/1298201/all-edges-same-weights-negative.xlsx)
[all-edges-same-weights-positive.xlsx](https://github.com/dondi/GRNsight/files/1298202/all-edges-same-weights-positive.xlsx)

Note the different behavior on the current master and beta with these two files.  Would someone please commit these to the repo?  When that is done, this issue can be closed.

**Comment by kdahlquist** [comment]
@dondi committed the files.
