### ISSUE TITLE
Next release targeted for Friday, June 2

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#514]
We are planning on doing a release by Friday, June 2 to complete our Summer Sprint.  Checklist is below:

- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below; this new version will be 2.1.x where x is incremented one step from the beta it came from)
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [x] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Update the version number and modification date on `gh-pages`
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
- [x] Publish to _npm_
    - [x] Update version numbers in all _package.json_ files
    - [x] _npm_ requires all `.0`s in the semantic version
    - [x] Check to see that BioJS updates its GRNsight entry
- [x] Run Istanbul and note new test coverages (optional): `npm run-script coverage`
- [x] Update the About page with release notes (GitHub release item without issue numbers)
    - [x] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
    - [x] Update modification date
- [x] Add news item about the release to the News page
    - [x] Update modification date
    - [x] Link news item to the corresponding release notes in the About page
- [x] Update Documentation page with any new features or updates to old features
- [x] Update version number/other relevant information at current bioinformatics listing sites
    - [x] Elixir 
        - [x] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] get badge and include in README.md at top level of repo
    - [x] update CITATION.md file with DOI (and badge?) for the new release
    - [x] update "How to cite GRNsight" section on About page

**Comment by kdahlquist** [comment]
Draft of release notes:

GRNsight v2.1.x includes the following new features and bug fixes:
* Improvements were made to the zoom functionality (#465), including:
    * Zoom now originates from the center of the graph #468 
    * Zoom factor is now annotated on zoom slider #485 
    * A vertical bar on the zoom slider indicates where the 100% zoom level is #484 
    * Mousewheel zoom was disabled #473 
    * Various bugs were fixed #479, #480, #508 
* The user can now customize the normalization factor which controls how the thicknesses of the edges are determined based on the weight values #264 
    * The user can also set the threshold upon which a weighted edge is colored gray using a slider
* Additional tests were added:
    * Syntactic tests for malformed Simple Interaction Format (.sif) files were completed which return errors to the user if an incorrectly formatted SIF file is imported into GRNsight #362 
    * The routine that checks for syntactic errors in SIF and GraphML files was integrated with the semantic checker routine that looks for error common to all file formats that GRNsight supports #386 
    * Tests for incorrectly named Excel worksheets were added #355 
    * GRNsight now returns an error if a blank Excel, SIF , or GraphML file is uploaded #428 
* An automatic client-side test generator was created that generates a document that can be followed by a user to systematically test specific combinations of user interface functions #326 
* Additional bugs were fixed #491, #510 
* Code quality was improved by the use of ESLint #503

**Comment by mihirsamdarshi** [comment]
@dondi do I create the draft before doing git push origin with the tag number or after? because right now I get an error when I run `git push origin v2.1.11` that says this:
`error: src refspec v2.1.11 does not match any.
error: failed to push some refs to 'https://github.com/dondi/GRNsight.git'`

**Comment by dondi** [comment]
@mihirsamdarshi The draft can be created anytime. It can tell if a tag exists already, but is OK if it isn’t there yet. It also can detect when the tag does show up.

The error you are seeing is unrelated to GitHub’s release mechanism; it is an issue with how the tag is being assigned and pushed. What exact sequence of actions have you taken so far in assigning the tag?

**Comment by mihirsamdarshi** [comment]
so far I have just created a draft release with the tag that I want to be assigned to the new master release, I have not taken any steps in assigning the tag other than doing `git push origin v2.1.11`

**Comment by dondi** [comment]
OK that explains it. That is not the complete set of steps for creating a tag. Look it up; GitHub themselves may have a page on it.

There’s a `git tag` command that you’ll need to use; you’ll want to make sure that you know the commit ID that receives the tag; then finally you can push the tag.

**Comment by mihirsamdarshi** [comment]
Ah I see, the tag has been created and pushed

**Comment by dondi** [comment]
OK, I know this may sound minor but it is good practice for you @mihirsamdarshi with regard to maintaining full consistency and attention to detail, but note that the tag you specified has a period after the `v`, but none of our earlier tags have that: https://github.com/dondi/GRNsight/tags

I’m going to have to ask you to revise the tag and release information to _not_ include that period (i.e., `v2.1.11`, as your earlier comment stated.

It may seem a lot of work for one pesky period, but the bigger picture here is to practice complete consistency and adherence to a pattern. In other contexts, that single period (or apostrophe, or quote, or semicolon) _does_ matter, and it is good to have practice with that now.

**Comment by mihirsamdarshi** [comment]
That's my bad it was a typo, was trying to be consistent. The only thing I need help with for this release is updating npm. I'm not sure if I'm going to be able to do that or not.

**Comment by dondi** [comment]
I’ve been doing the npm update so don’t worry about that. It requires a login etc. etc. so you’re not expected to deal with it.

**Comment by dondi** [comment]
I can do the npm, Zenodo, and Elixir steps. So you don’t have to worry about those.

**Comment by dondi** [comment]
Oh also I will do the updating of the running master version.

**Comment by mihirsamdarshi** [comment]
According to Istanbul we now have 230 (passing) tests with the following coverage:
- Statements: 69.96% (368/526)
- Branches: 83.12% (192/231)
- Functions: 63.39% (62/101)
- Lines: 69.9% (367/525)

**Comment by kdahlquist** [comment]
@dondi, when is the ETA for updating master on the homepage?  @mihirsamdarshi has already updated the version and date on the page.

**Comment by dondi** [comment]
@kdahlquist Updated just now. I spotted the latest changes after a reload.

**Comment by kdahlquist** [comment]
Awesome!

**Comment by dondi** [comment]
Remaining release tasks finished: `npm`, `biotools`, `zenodo`, BioJS.

Closing now.
