### ISSUE TITLE
Change gray edge threshold value to percent scale (0 - 100%)

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#518]
Leftover issue from #264.  Gray threshold value should be shown as percent, 0 - 100%, instead of fraction from 0 - 1.  @mihirsamdarshi noted that this wasn't a straightforward change and left it for later work.

**Comment by mihirsamdarshi** [comment]
This is taking longer than I expected, but I hope to push something to fix this problem by this Wednesday's work session.

**Comment by mihirsamdarshi** [comment]
I can't seem to figure this one out, because of the way that I designed the variable gray threshold. I think I have found a way to fix it, by appending a string to the value, however I am not sure how to incorporate it yet. I will try to fix this later this week.

**Comment by kdahlquist** [comment]
@mihirsamdarshi is looking at the code for zoom on how to do this.

**Comment by mihirsamdarshi** [comment]
I've figured out how to actually do this, now I simply have to implement my solution

**Comment by dondi** [comment]
@mihirsamdarshi I saw the PR; I submitted a review. One small note and you should be good to go.

**Comment by kdahlquist** [comment]
@yshin4 merged the PR.  However, she does not have rights/does not know how to make the changes live on the server.  Who has rights to do that these days?

**Comment by mihirsamdarshi** [comment]
@yshin4 check issue #388 to generate an SSH key, and send that to Dondi to gain access to the server

**Comment by yshin4** [comment]
@mihirsamdarshi oh, I do have the ssh key from last year. How do I make changes live on the server?

**Comment by mihirsamdarshi** [comment]
https://github.com/dondi/GRNsight/wiki/Quick-Guide-to-Refreshing-GRNsight

**Comment by yshin4** [comment]
@mihirsamdarshi nice, thanks! Followed the guide but I did not know why we would have to do multiple screens, so I just did it once. Tell me if I am wrong. But other than that I pulled on the server.

**Comment by mihirsamdarshi** [comment]
@yshin4 you do have to screen multiple times. currently beta is down.

**Comment by yshin4** [comment]
@mihirsamdarshi Yeah, sorry I didn't know how many times to do it. I reported to dondi an hour ago and he said he'll give it a look when he's in front of a computer. I tried to reset the pull and changed the head to a previous commit and pull again, but screens were already all closed. Let me know if you know a fix.

**Comment by dondi** [comment]
@mihirsamdarshi @yshin4 Things are back up. Not sure what happened, but the root cause was that the server wasn't running. There was a leftover `screen` process but nothing was running inside it.

**Comment by kdahlquist** [comment]
On the current beta (v2.3.4), the slider works to change the edges gray or not, but the numerical value displayed does not update, it is fixed at 0.05

**Comment by mihirsamdarshi** [comment]
this is fixed in my branch, and I will fix this in my next pull request

**Comment by kdahlquist** [comment]
This is also not working.  When I move the slider, the number does not change, it stays at 5%.  The edges are changing color, so that is working, but the number is not reading out correctly.

**Comment by eileenchoe** [comment]
I fixed this issue while working on #462 and #576 and will be included in menu reorganization PR

**Comment by yshin4** [comment]
Live on beta 2.3.7 now.

**Comment by kdahlquist** [comment]
Confirmed.
