### ISSUE TITLE
Explore feasibility/effort in porting code base from D3v3 to D3v4

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#520]
D3v4 has been out for over a year at this writing (https://github.com/d3/d3/releases/tag/v4.0.0) and it may be prudent to look at porting our code to version 4.

Key issue is looking at potential effort in doing that. We'll a decision based on what we find.

**Comment by eileenchoe** [comment]
https://github.com/d3/d3/blob/master/CHANGES.md here's a good reference for changes made in v4

**Comment by eileenchoe** [comment]
Based off of this documentation, today we went through graph.js and cross checked the d3 functions used to those that were changed in v4. While some functions just underwent name changes (i.e. d3.scale.linear() => d3.scaleLinear() and d3.scale.quantile() => d3.scaleQuantile()), it seems that the d3-force library itself went through some more significant changes, such as breaking up the positioning forces into x and y. So, there's more we'll have to investigate with the d3-force library itself, as expected.

**Comment by dondi** [comment]
Hmmmm, this may be an issue. Certainly more to investigate. You might want to make an experimental branch where you actually change over to v4, make the initial changes, then see what happens. The firsthand attempt at porting may give us the best information on what the time/effort will be.

**Comment by eileenchoe** [comment]
Branch d3v4 set up with experimental changes on my fork (https://github.com/eileenchoe/GRNsight/tree/d3v4).

**Comment by eileenchoe** [comment]
[d3-force library](https://github.com/d3/d3-force/blob/master/README.md)

[example of force directed graph using d3v4](http://blockbuilder.org/mbostock/f584aa36df54c451c94a9d0798caed35)

**Comment by kdahlquist** [comment]
After reviewing the information from @eileenchoe , we have decided to go ahead with the transition. The potential benefits outweigh the foreseen costs of the transition. #523 covers this transition.
