### ISSUE TITLE
New `npm start` procedure has errors in Windows

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#521]
The new startup sequence triggers an error in Windows. This looks related to the syntax that the Windows command line accepts. This StackOverflow question may provide a lead:

https://stackoverflow.com/questions/25777858/running-concurrent-commands-with-npm-on-windows

**Comment by yshin4** [comment]
Solved after pulling from beta branch and updating node to 8.4.

**Comment by ebachoura** [comment]
I'm not sure why it wasn't working on my computer/fork before, but I decided to refork and it works fine now.

**Comment by dondi** [comment]
OK, good to know! I suspect that `node_modules` might not have been cleaned out as thoroughly as y’all originally thought. The clean clone ensured that there was an absolutely new `node_modules` that got installed into.

If this has been resolved for all Windows users, go ahead and close the issue.

**Comment by ebachoura** [comment]
Issue has been resolved for all Windows users!
