### ISSUE TITLE
Honors Thesis Abstract

### ISSUE THREAD

**Issue by eileenchoe** [dondi/GRNsight#531]
Submission info TBD.
Deadline: September 30th

**Comment by kdahlquist** [comment]
Ah, yes.  Please start a draft on the wiki for group editing.  It would be great if you could have a draft ready for Wednesday's meeting for comment.  It will be finalized for you to submit at the meeting on the 27th.

I'm adding the "CMSI 402" label to this so that this can be tracked as a senior capstone task.

**Comment by eileenchoe** [comment]
[Abstract Link
](https://github.com/dondi/GRNsight/wiki/CMSI-402-Thesis-Abstract-(Eileen-Choe))@kdahlquist can we set up a time to meet and discuss the node coloring feature, so I have a better background on it? Are you available Friday morning anytime between 8:30AM-11AM?

**Comment by kdahlquist** [comment]
I can do Friday at 9:30 am.  It sounds like you have decided on that for your 402 and not anything to do with other layouts?

With regards to node coloring, I recommend reading:

[Salomonis, N., Hanspers, K., Zambon, A. C., Vranizan, K., Lawlor, S. C., Dahlquist, K. D., ... & Pico, A. R. (2007). GenMAPP 2: new features and resources for pathway analysis. BMC bioinformatics, 8(1), 217.](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-8-217)

to get a sense of what that used to look like in GenMAPP.

**Comment by eileenchoe** [comment]
@kdahlquist might have been discussed at the end of the first meeting, but yes we decided that @yshin4 would do the layouts and I would do node coloring for 402

**Comment by eileenchoe** [comment]
Wrote up a first draft of the abstract. Is future tense ok because I am writing about research that I am planning to do? Also, can I refer to the finished state of GRNsight with the new data structure for spreadsheet controller and the node coloring as 'GRNsight v4' (assuming we will have a release by the end of the semester)?

**Comment by kdahlquist** [comment]
I'll try to take a look before the meeting, but quickly, it will be v3 we are releasing at the end of the academic year.  Any prior releases before that will be v2, updating the middle number of the semantic versioning.

Typically abstracts are written in the past tense, but in this case, future will be OK.

**Comment by eileenchoe** [comment]
Submitted!
