### ISSUE TITLE
@yshin4  needs to complete the online safety training

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#537]
@yshin4  needs to complete the online safety training.  You will need to do this or the department will revoke your card key privileges for the lab door and LSB outer doors.  Thanks.

**Comment by yshin4** [comment]
I did complete the training before the deadline and submitted an online form with my certificate ID. @kdahlquist Should I submit another form?

**Comment by kdahlquist** [comment]
I'll double-check with Stephanie and get back to you.

**Comment by kdahlquist** [comment]
Stephanie got back to me, she didn't know that you went by Jen because I gave her your given name.

**Comment by yshin4** [comment]
Oh, my bad. Thank you for taking care of it.
