### ISSUE TITLE
Clean up linting errors

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#538]
With the resolution of #535, we now have a true indication of linting errors that need to be fixed. As a group let's chip away at this. One request: don't mix commits with both linting fixes and functionality changes. Set out to fix just linting for certain commits.

**Comment by dondi** [comment]
Labeling as `bug` because these “break the build” for Travis.

**Comment by kdahlquist** [comment]
@ebachoura said that @yshin4 said that she would be happy to do it. Right @yshin4? This is a good task to do at Thursday's office hours session with @dondi.

**Comment by yshin4** [comment]
Yes, will do.

**Comment by dondi** [comment]
So @ebachoura @eileenchoe, @yshin4 is working on this right now. I told her that since she is doing linting-only fixes, she can commit straight to `beta`. When she is done, just pull and merge from beta directly and that should clean all our branches up.

**Comment by yshin4** [comment]
Got 301 errors down to 105. Will be working on the rest before next meeting. @dondi please update me if you find anything new about exports.

**Comment by dondi** [comment]
@yshin4 Did you push the 105-error one, or are you holding off until more are fixed? I did another pull but am still at 301. (no need to actually push if you haven't yet; just checking if my repo is OK)

**Comment by yshin4** [comment]
@dondi oops, yeah my bad, your repo is fine. It got so chaotic at the end I forgot to push. I just pushed!

**Comment by dondi** [comment]
@yshin4 Cool, I’m at 103 errors now (did you fix a couple more before pushing?). I’ll do some research into the export/environment configuration, but meanwhile keep chipping away at the errors that are easy to fix.

@ebachoura and @eileenchoe, to minimize the possibility of merge conflicts, try to pull/merge `beta` a little more often as @yshin4 lints her way to green 🙂

**Comment by dondi** [comment]
@yshin4 I got something working; pull `beta` when you get the chance. 99 linting errors now. I ended up turning off `no-unused-vars` selectively—i.e., just for those pseudoglobals in sliders.js. Not ideal but in terms of information, it is the same information we would have supplied for `export`.

**Comment by yshin4** [comment]
I did the same for graph.js and container.js, all the linting errors are gone now. @dondi please check and let me know if there is anything I'm missing.

**Comment by dondi** [comment]
Confirmed! Zero errors on my end. Travis reports zero errors as well.

We’re back in business @ebachoura and @eileenchoe. When you next get the chance, merge `beta` into your respective branches. Fix any merge conflicts, knowing that the incoming changes from @yshin4 are purely lint cleanup. `npm run lint` to confirm zero errors, commit, and push.

When we’re all done doing this, we can close this issue.
- [x] https://github.com/dondi/GRNsight/tree/dondi
- [ ] https://github.com/dondi/GRNsight/tree/yshin4
- [ ] https://github.com/dondi/GRNsight/tree/ebachoura
- [ ] https://github.com/dondi/GRNsight/tree/echoe

**Comment by eileenchoe** [comment]
Merged, and travis is happy! Thanks @yshin4 and @dondi !

**Comment by ebachoura** [comment]
To be honest, I don't want to try and merge and screw everything up again so I'm going to wait till the meeting lol. Package-lock.json scares me

**Comment by dondi** [comment]
@ebachoura You can always abort a merge :) I don’t think package-lock.json was touched here so I don’t foresee issues.

Once we are all merged, we should also introduce a linting error on purpose to make sure that it gets caught this time. That’s what triggered this whole issue chain after all.

**Comment by ebachoura** [comment]
@dondi I tried it once and there was some weird business going on and I aborted. I'll just wait till the meeting, I'll feel safer with you around lol

**Comment by ebachoura** [comment]
Definitely referenced the wrong issue mb

**Comment by yshin4** [comment]
Okay, I merged beta onto my branch. I hope I did it right...

**Comment by dondi** [comment]
Everyone's branches have been updated so we will close.
