### ISSUE TITLE
Catch missing < in GraphML node tags

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#540]
An error that is not caught by the third-party parser is a missing < preceding `node`, probably because that content is being interpreted as text. Visually it is more clearly a syntax error.

**Comment by kdahlquist** [comment]
I think this might be a targeted issue that @igreen1 could address.  @Onariaginosa is working on the Excel-based import, but this is a GraphML import issue.

**Comment by igreen1** [comment]
Unable to reproduce. The following error message appears when a "<" is removed from <node id=[]>

![image](https://user-images.githubusercontent.com/40191185/95776785-d9d31e80-0c79-11eb-92a5-dec65c9574ec.png)

**Comment by dondi** [comment]
OK, looks like we may have this handled already. As long as GRNsight doesn't “lose its composure” for something like that and provides some guidance (which it does, based on the screenshot), that’s half of the battle.

The second half is to see whether the error message is helpful. Is the guidance of `line 13 at column 7` valid? And interesting that the message said that the error may be _caused_ by `<` when the issue is a _missing_ `<`.

Let’s see what’s in `line 13 at column 7` (and its neighborhood) to determine viability of the message.

**Comment by igreen1** [comment]
The guidance is in the right neighborhood but off by a character like many programming tools. This is best illustrated by an example:
8: `<node id="ABF1"`
9:     `<data key="name">ABF1</data>`

The above will point to the error on line 9 despite the problem existing at the end of line 8.
@igreen1 explored some solutions, but it seems like it would require a remaking of the xml parser, which seems unnecessary given that it is pointing the user in the general neighborhood of the error, off by one character.

Note, the error is not simply skipping a line. It is merely pointing to the character immediately after the missing error. In the following, the error will point to the < in <data.

8: <node id="ABF1" <data key="name">ABF1</data>

**Comment by dondi** [comment]
One possible closing activity for this is to see whether the latest XML2JS library version for:
1. Improved error messages
2. Continued compatibility
This may at least incrementally improve the messages that we relay, and if XML2JS is among the libraries that are due for a security update anyway, this will let us chip away at that impending issue.

If the latest version breaks compatibility, let’s assess the appropriate next step.

**Comment by dondi** [comment]
Clarification here: this is a behavior that @igreen1 has already seen as functional so the review is for verification by @dondi that this is the case.

**Comment by dondi** [comment]
Didn’t manage to close out…OK to go.
