### ISSUE TITLE
Need a different place to meet on 11/1

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#544]
Someone else needs LSB 118 on November 1 at 3:00, so we will need to meet somewhere else.  I think it will work to just go to my or @dondi 's office on that day.

**Comment by kdahlquist** [comment]
We'll hold this meeting in @dondi's office, possibly shifting to the Keck lab if we need big screen AV.

**Comment by eileenchoe** [comment]
Confirming that we are meeting in @dondi 's office?

**Comment by dondi** [comment]
We are now in @dondi's office.
