### ISSUE TITLE
Release 2.2.7

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#548]
The list is coded up using checkboxes, so that its source can be copied into a GitHub issue as a starting point for preparing a new release.

- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [ ] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [ ] the [data.json](https://github.com/dondi/GRNsight/blob/beta/documents/developer_documents/testing_script_generator/data.json) file should be updated
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [ ] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Update the version number and modification date on `gh-pages`
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
- [ ] Publish to _npm_ (`npm publish`)
    - [ ] Update version numbers in all _package.json_ files
    - [ ] _npm_ requires all `.0`s in the semantic version
    - [ ] Check to see that BioJS updates its GRNsight entry
- [x] Run Istanbul and note new test coverages (optional): `npm run-script coverage`
- [ ] Update the About page with release notes (GitHub release item without issue numbers)
    - [ ] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
    - [ ] Update modification date
- [ ] Add news item about the release to the News page
    - [ ] Update modification date
    - [ ] Link news item to the corresponding release notes in the About page
- [ ] Update Documentation page with any new features or updates to old features
- [ ] Update version number/other relevant information at current bioinformatics listing sites
    - [ ] Elixir 
        - [ ] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [ ] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [ ] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by dondi** [comment]
@ebachoura seems to have resolved the linting errors and can now proceed with additional release steps, particularly tagging onward. The branches have actually been pushed already; just tagging needs to take place as well as the later steps.

**Comment by kdahlquist** [comment]
As discussed in the meeting today, we are going to abandon this release and start fresh so that we can incorporate the refactoring work from @eileenchoe and @yshin4.  New issue to be made momentarily.
