### ISSUE TITLE
GRNsight meetings Spring 2018

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#553]
Based on everyone's course schedules, it looks like the best time for meeting this semester will be on Monday's 11:30-12:30.  However, this is a problem for the first two weeks of school.  So for the first week _only_, we will meet on Friday, January 12 from 11:30-12:30, skip a meeting for week 2, and then begin our regularly scheduled Monday meetings on Monday, January 22.

@dondi will be meeting with us on an every-other-week basis starting on Monday, January 22 (because he is on sabbatical and not on campus most of the time).

Please confirm your availability for this schedule by posting a comment on this issue.

**Comment by kdahlquist** [comment]
Oops, I meant Monday, January 22.

**Comment by mihirsamdarshi** [comment]
Sounds good. Is the location still LSB 331?

**Comment by eileenchoe** [comment]
Works for me, see you Friday!

**Comment by yshin4** [comment]
I can do other Mondays except the 22nd because I have an interview from 11-1 that day.

**Comment by kdahlquist** [comment]
@ebachoura, still waiting for confirmation.

@yshin4, missing 1/22 will be fine.

Friday's meeting on 1/12 will be held in LSB 331 (third floor conference room)

All Monday meetings, starting on the 22nd will be held in LSB 118 (first floor conference room)

@mihirsamdarshi, @ebachoura, will need to pick up independent study forms from me and turn them in to North Hall 100, Isabella Rand by Friday's add deadline.

@mihirsamdarshi will need to schedule safety training with me to get authorization for access to my lab.

**Comment by yshin4** [comment]
@kdahlquist I think I need to do an independent study as well because I am 1 credit short from minimum credit to graduate.

**Comment by kdahlquist** [comment]
OK, @yshin4 I'll get a form ready for you, too.

**Comment by yshin4** [comment]
@kdahlquist I talked to someone in the office and things worked out, so I do not have to take another Independent Study this year and I will be doing grnsight only for my 402. Sorry to bother!

**Comment by kdahlquist** [comment]
Independent study forms are filled out and ready for pick up by @mihirsamdarshi and @ebachoura.  They are pinned to the bulletin board outside my office door.  The top needs to be filled out and the form taken to Isabella Rand in North Hall 100 by Friday 1/12.

**Comment by kdahlquist** [comment]
@eileenchoe, @mihirsamdarshi, @yshin4, please comment on this issue when you have figured out your weekly joint work session day/time for the semester so that it is recorded on the issue.

**Comment by kdahlquist** [comment]
Reminder to @eileenchoe, @mihirsamdarshi, @yshin4, please comment on this issue when you have figured out your weekly joint work session day/time for the semester so that it is recorded on the issue.  I.e., when do you plan to work this week and subsequent weeks?

**Comment by yshin4** [comment]
@eileenchoe and I decided to meet Wednesday noon to work 402 assignments together. I will be working on my issue Wednesday afternoon as well.

**Comment by mihirsamdarshi** [comment]
I will not be there today due to a previous commitment, but after my class on Wednesday’s from this week onwards it will be the time.

**Comment by kdahlquist** [comment]
We don't need this anymore, closing.
