### ISSUE TITLE
@dondi please review PR#552

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#555]
@dondi please review PR#552

**Comment by dondi** [comment]
OK, this has been reviewed. I did find a few things worth changing, although all at the refinement level and not buggy. @eileenchoe @yshin4 let me know when a revision is up.

**Comment by dondi** [comment]
I’ll keep this issue open until the PR is approved.

**Comment by yshin4** [comment]
Merged, closing the issue.
