### ISSUE TITLE
Spring 2018 LMU Undergraduate Research Symposium

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#556]
The LMU Undergraduate Research Symposium will take place on Saturday, March 24.

Abstracts are due Friday, February 9, 5:00 PM.

This will become a higher priority, closer to the date.

**Comment by kdahlquist** [comment]
Drafts of symposium abstracts are due at next week's meeting, 2/5.  Please write on wiki and we'll group edit at next week's meeting.

@mihirsamdarshi will do a poster and @eileenchoe and @yshin4 will each do a talk.

@mihirsamdarshi  will also submit the abstract to the TriBeta Conference which will take place on March 17 at Concordia University in Irvine.

**Comment by eileenchoe** [comment]
[Link to Eileen's Abstract on Wiki](https://github.com/dondi/GRNsight/wiki/LMU-Symposium-Abstract-2018---Eileen-Choe)

**Comment by yshin4** [comment]
[Link to Jen's Abstract for Symposium](https://github.com/dondi/GRNsight/wiki/Jen-Shin-::-LMU-Undergraduate-Research-Symposium-Abstract-2018)

**Comment by eileenchoe** [comment]
Submitted application for oral talk @ symposium.

**Comment by yshin4** [comment]
![image](https://user-images.githubusercontent.com/16246811/35826636-29723d06-0a6e-11e8-9859-f1a98b86b144.png)

Submitted as well.

**Comment by mihirsamdarshi** [comment]
submitted

**Comment by kdahlquist** [comment]
For @mihirsamdarshi here is the info about the TriBeta conference:

The TriBeta Conference will be held on Saturday, March 17 at Concordia University in Irvine.  Abstracts are Due Feb. 17. @bklein7 and @maggie-oneil will give oral presentations.  @lkelly9, we'll see if there will be enough results for you to present a poster by then.

The Sample abstract form is in the repo on the master branch under documents/abstracts

https://github.com/kdahlquist/GRNmap/blob/master/documents/abstracts/TriBeta-Conference_2018_Sample-Abstract-Form.doc

Abstract submission site: https://docs.google.com/forms/d/e/1FAIpQLSeT1HZaa9GWBMQBy-Yx0-yW1LNB-JWA3kEtg7EdNCF-c70Ixg/viewform

Please go ahead and submit your LMU symposium abstract once you have it formatted.

**Comment by mihirsamdarshi** [comment]
The Tri-Beta conference abstract was submitted

**Comment by mihirsamdarshi** [comment]
I pushed to master a first draft of a poster for the Tri-Beta Conference this Saturday

**Comment by yshin4** [comment]
TODO: Make a powerpoint for block layout oriented grnsight presentation

**Comment by eileenchoe** [comment]
Oral presentations are fifteen minutes in length with an additional three minutes allotted for a question-and-answer period.

**Comment by kdahlquist** [comment]
Schedule for Saturday:
* @mihirsamdarshi, @jtorre39, and @johnllopez616 are presenting posters 1:30-3:00pm
* @yshin4, @maggie-oneil, and @Nvafadari and Kat are presenting in a session from 3:10-4:25, UH1405
* @eileenchoe and @bklein7 are presenting in a session from 1:50-3:05, UH3222
* @lkelly9 is presenting a poster in the session from 3:00-4:30

Let's all meet at 1:15 at the big tree outside of UH first floor for our group pictures.
