### ISSUE TITLE
v2.3.0 Release

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#557]
As discussed at the meeting today, we are aborting the v2.7.9 release and starting the process fresh so that PR #552 can be incorporated in the new release.  This one will be v2.3.0 because it is a substantive change from the previous (although most work is "under the hood").

- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [x] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [x] the [featureList.json](https://github.com/dondi/GRNsight/blob/master/documents/developer_documents/testing_script_generator/featureList.json) file should be updated
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
    - [x] Update Travis and Coveralls badges to reference the master branch
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [x] Update version numbers in _package.json_
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [x] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Refresh (pull) the `master` clone on _grnsight.cs.lmu.edu_
    - [x] Update the version number and modification date on `gh-pages`
    - [x] Update the About page with release notes (GitHub release item without issue numbers)
        - [x] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [x] Update modification date
    - [x] Add news item about the release to the News page
        - [x] Update modification date
        - [x] Link news item to the corresponding release notes in the About page
    - [x] Update Documentation page with any new features or updates to old features
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
    - [x] Update Travis and Coveralls badges to reference the beta branch
    - [x] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [x] Publish to _npm_ (`npm publish`)
    - [x] _npm_ requires all `.0`s in the semantic version
    - [x] Check to see that BioJS updates its GRNsight entry
- [x] Update version number/other relevant information at current bioinformatics listing sites
    - [x] Elixir 
        - [x] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [x] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [x] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by eileenchoe** [comment]
@yshin4 and I feel like we've done all the steps for the release that we can for now. Tested the merged `master <- beta` locally and there were no conflicts or bugs detected. Drafted release notes v2.3.0 for @kdahlquist to approve. Since @dondi will be at the next meeting, can we finish the actual code merge and publish during the meeting?

**Comment by kdahlquist** [comment]
I saw the comment on #560 asking me to review the draft release.  I'm fully booked today and most of tomorrow.  I looked at beta quickly and it seems OK, but I don't have time for an extensive review.  I think we can proceed with the release and report bugs as they come up.  One thing is to take a look at the issues that were closed since the last release so that the release notes are complete.  I will have time, potentially Monday morning to look at this before the meeting, but I would be OK with moving along in advance of the meeting if necessary.

**Comment by dondi** [comment]
Most tasks are done here, with just the following left:
- Website updates (@mihirsamdarshi )
- Documentation updates (@eileenchoe  and @yshin4 )
- Elixir update (@dondi)

Let's check these as we go then close the issue when everything is done.

**Comment by yshin4** [comment]
@eileenchoe and @yshin4 met up and updated:
* Finished the release documentation.
* Updated news.
* Updated documentation.
* Updated about.
* Updated date accordingly as well.

**Comment by dondi** [comment]
@dondi has updated the [Elixir page](https://bio.tools/tool/GRNsight) with the latest version and credits. The URL didn’t change so the Links page didn’t need updating.

I think that’s everything…I’ll set this issue to `review requested` just in case, then anyone can close this if we think we’re set.

**Comment by kdahlquist** [comment]
Everything is checked off, so closing!
