### ISSUE TITLE
Setting the normalization factor changes the zoom factor to 100%

### ISSUE THREAD

**Issue by eileenchoe** [dondi/GRNsight#561]
Found a bug while testing beta for release #557 (the bug also exists in master). When the normalization factor is applied via the "Set Factor" button, it forces the zoom to go to 100%. @yshin4 and I think the graph should remain at it's current zoom level when the normalization factor is changed.

**Comment by kdahlquist** [comment]
Bug is still there in 3.1.12

**Comment by mihirsamdarshi** [comment]
addressed by PR #749

**Comment by kdahlquist** [comment]
Verified fixed in Beta v3.1.17.
