### ISSUE TITLE
test-files>graph-tests>different-sized-networks filenames do not match content of files

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#570]
When @yshin4 and I were trying to load test files from test-files>graph-tests>different-sized-networks to view in block layout, we discovered that the filenames are not matching the contents of the files.  For example a file named 75-nodes_150-edges.xlsx, when loaded in GRNsight, an error said that there were 129 nodes.  Upon visual inspection of the files, the node names on the top and side did not match, so this made sense.  However, it is a problem that the filename does not match the contents of the file.

I wonder if these files are being used for anything or were they supplanted by unit tests.  We need an audit of this folder.

**Comment by kdahlquist** [comment]
Write a script for detecting whether files are referenced in the code?  Then we can review the ones that are not referenced to see if they are needed and/or write a test for it.

**Comment by Onariaginosa** [comment]
I did a workspace search for the the path "test-files/graph-tests/different-sized-networks" and found that only 8 files were being used in that folder. I moved the unused files to a new folder called "unused-files" within the original folder. 

Files used in `errors-graph-tests.js`:
- Returns no errors:
`test-files/graph-tests/different-sized-networks/10-genes-0-edges.xlsx`
- Should return invalid workbook size error:
`test-files/graph-tests/different-sized-networks/80-genes-0-edges.xlsx`
`test-files/graph-tests/different-sized-networks/45-genes-max-edges.xlsx`
- Should return invalid workbook size warning:
`test-files/graph-tests/different-sized-networks/52-genes-0-edges.xlsx`
`test-files/graph-tests/different-sized-networks/34-genes-111-edges.xlsx`

Files used in `graph-library-tests.js`:
- Used in testing shortest path between nodes in undirected and directed graphs. Also used to test the undirected and directed betweenness centrality of a single node.
`test-files/graph-tests/different-sized-networks/75-genes-150-edges.xlsx`
`test-files/graph-tests/different-sized-networks/10-genes-max-edges.xlsx`
`test-files/graph-tests/different-sized-networks/12-genes-max-edges.xlsx`

The inconsistent files among those are, not including `75-genes-150-edges.xlsx`:
-  `test-files/graph-tests/different-sized-networks/45-genes-max-edges.xlsx`: where there was 44 source genes and 45 target genes. 
- `test-files/graph-tests/different-sized-networks/80-genes-0-edges.xlsx`: error message says there are 134 genes. Source genes and target genes are not the same in the file, so this makes sense.

The inconsistent files amongst the unused files:
- `35-genes-max-edges.xlsx`: has 34 source genes and 35 target genes
- `40-genes-0-edges.xlsx`: has 39 source genes and 40 target genes
- `40-genes-max-edges.xlsx`: has 39 source genes and 40 target genes
- `42-genes-max-edges.xlsx`: has 41 source genes and 42 target genes
- `50-genes-max-edges.xlsx`: has 49 source genes and 50 target genes

I didn't have enough time to check whether the unused files have the same gene names for the source and target genes.

**Comment by dondi** [comment]
Some courses of action regarding these files:
* inconsistently-named and unused—same to delete; they're in GitHub forever anyway
* graph-library tests…by the same token, safe to delete
* used but some inconsistencies—sounds like the tests are valid but the filenames just happen to be inconsistent with content; inconsistent source vs. target is allowed by GRNsight but not GRNmap; decision is to convert those from errors to warnings
    * For filename mismatches, just change the filename for consistency
    * For files that have asymmetric source vs. target lists, convert to warnings

**Comment by Onariaginosa** [comment]
I did the above actions, however when I went to change the test to warnings, I realised that I misremembered. The tests threw an error if the network genes and the expression genes were mismatched. Should these tests still be changed to warnings?

**Comment by dondi** [comment]
Response to this question is that the issue should remain an error.

**Comment by ahmad00m** [comment]
@ahmad00m tested the files that @Onariaginosa mentioned at test-files/graph-tests/different-sized-networks/
It was found that the tests threw the correct error/warning for each corresponding files.

- 35-genes-max-edges.xlsx: has 34 source genes and 35 target genes. The names were consistent, but target genes have one more gene called XBP1.
- 40-genes-0-edges.xlsx: has 39 source genes and 39 target genes. The gene names were consistent 
- 40-genes-max-edges.xlsx: has 39 source genes and 40 target genes. The names were consistent, but target genes have one more gene called XBP1.
- 42-genes-max-edges.xlsx: has 41 source genes and 42 target genes. The names were consistent, but target genes have one more gene called XBP1.
- 50-genes-max-edges.xlsx: has 50 source genes and 50 target genes. However, the last gene in source genes has no values and is an empty column (FKH2 gene).
