### ISSUE TITLE
Adding the Fall 2017 BIOL/CMSI-367 gene backpages to GRNSight

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#573]
I would like to begin the process of cleaning up the Biological Databases Web API project and merging it to GRNSight. Below is a preliminary checklist, to be changed as more information arises.

- [x] Fixing any bugs associated with the project.

- [x] ESLinting the Code

- [x] Merging it to the GRNSight.

Here are the API Sources:
https://github.com/dondi/GRNsight/wiki/Web-API-Sources

**Comment by kdahlquist** [comment]
- All BIOL367 branches need to be merged into a single branch (preferably master) on Blair's fork so that it is consolidated.  
- Then a pull request from Blair's fork master branch into GRNsight John's branch so he can finish the integration.
- at Monday's GRNsight meeting on Monday @dondi can show how he got the BIOL367 code working on his computer and @kdahlquist can make a list of things to fix.

**Comment by dondi** [comment]
Blair’s fork looks complete with the exception of 2-3 dangling commits. We can re-examine those later, but for now:
- Make sure that @johnllopez616 can run this branch (after merging)
- Look at @kdahlquist's notes on the PDF screenshot
- When @johnllopez616 is more familiar with the code, you can revisit the dangling commits to see if there is anything to salvage from there

**Comment by kdahlquist** [comment]
Things to get started on:
- Use the main GRNsight banner at the top of the page, instead of the custom one.  @kdahlquist will use the svg file of the eye to see if a smaller version can be incorporated somewhere on the page.
- Add the GRNsight navigation bar to the left hand side (and also the links bar at the bottom of the page.
- Make a menu bar at the top of the page, below the gene title which helps the user to navigate to the different sections of the page below.
- Move the ID's to the general information section
- _Saccharomyces cerevisiae_ needs to be italicized

**Comment by kdahlquist** [comment]
PDF from @dondi attached here.
[Information About HAP5.pdf](https://github.com/dondi/GRNsight/files/1849255/Information.About.HAP5.pdf)

**Comment by dondi** [comment]
Merge succeeded to `johnlopez` branch.

**Comment by kdahlquist** [comment]
@johnllopez616, one more item for the TODO list:

Would you please annotate the gene page so that I know which piece of information is coming from which source?  Maybe it would be best to put this information on a wiki page.  I know that the hAPI team made some decisions as to where the data would come from and I want to review that.  We might need to change the data source for some items.  So, if you could list on the wiki, each data source and then the information coming from that source, that would be great.  Thanks.

**Comment by johnllopez616** [comment]
I do not see any notes on the PDF document :(

**Comment by johnllopez616** [comment]
Everything but the GRNsight banner and Navigation bar has been added. I will discuss with you how I plan to do this at tomorrow's meeting.

**Comment by johnllopez616** [comment]
<img width="1747" alt="screen shot 2018-04-06 at 5 30 54 pm" src="https://user-images.githubusercontent.com/21348600/38449236-fc986f62-39c0-11e8-8ee0-b64d9290f6a4.png">
Here is a shot of the changes made today.

**Comment by johnllopez616** [comment]
I just added the link to the issue, but here it is as well:
https://github.com/dondi/GRNsight/wiki/Web-API-Sources

**Comment by dondi** [comment]
The suggested approach given by @dondi to @johnllopez616 would be to do the header and sidebar as iframes within the gene page:
1. Revise the `gh-pages` branch to generate header-only and sidebar-only published pages based on the header and sidebar templates.
2. Load the header-only and sidebar-only files as iframes within the gene page. The iframes will need to be pre-sized and laid out like headers and sidebars.

**Comment by johnllopez616** [comment]
<img width="1959" alt="screen shot 2018-04-13 at 4 16 52 pm" src="https://user-images.githubusercontent.com/21348600/38761284-351ee5c6-3f36-11e8-8648-82d59d1d0d43.png">
As @dondi and I discussed, I was not able to successfully generate it using iframes from the server, but I was able to get it using iframes. It is ready for a pull request!

**Comment by johnllopez616** [comment]
`{
        "title": "Load Gene Information Page",
        "text": "Loading a gene page does not prohibit:",
        "options": {
            "Drag Node With Mouse": "dragging node with mouse",
            "Scroll Through Graph": "scrolling through the graph",
            "Increase Zoom Level": "zooming in (getting larger)",
            "Decrease Zoom Level": "zooming out (getting smaller)",
            "Toggle Grid Layout": "toggling the 'grid' layout",
            "Toggle Force Graph Layout": "toggling the 'force graph' layout"
        }, 
        "included": false,
        "availability": {"NoGraphLoaded": false, "WeightedGraphLoaded": true, "UnWeightedGraphLoaded": true }
    }`

Would this be a proper change to the featureList.json document?

I plan to meet with @yshin4 and @eileenchoe on Sunday to properly walk me through the testing document as well as discuss how to hard code the tests for the gene page, for I am completely unsure how to do that.

**Comment by johnllopez616** [comment]
> On the client side, your feature is most likely going to interact with node dragging, zooming, scrolling, and toggling between grid and force graph layouts.

Based off @eileenchoe 's revisions, does this mean that I would have to modify the node dragging, toggling, zooming, etc.'s tests?

Also, I will meet with @yshin4 later today to discuss the procedure for developing the web tests.

**Comment by johnllopez616** [comment]
I have a working branch of johnlopez on my laptop, and I fixed a bug regarding the clicking functionality. The pull request should be ready to go!

**Comment by johnllopez616** [comment]
@mihirsamdarshi and I confirmed that the right-click functionality does not work on Safari. To our knowledge, it only works on Chrome. Will investigate further on other browsers.

**Comment by johnllopez616** [comment]
Can the issue be closed?

**Comment by kdahlquist** [comment]
I think there may be some unresolved comments in this thread.  If we break them out to new issues, then we can close this one.

**Comment by kdahlquist** [comment]
I want to wait until I review the next beta refresh before closing this one.

**Comment by kdahlquist** [comment]
Looking at beta v3.0.5, here is some feedback:
- [ ] the gene page also needs the GRNsight footer
- [ ] the gene page is opening, but data is not being loaded (@johnllopez616 and @mihirsamdarshi are trouble-shooting right now.

**Comment by johnllopez616** [comment]
I discovered that at least one of the data loading issues is related to the first part of ` getUniProtInfo()` within `api.js`.  What this function does is make a request to UniProt Retrieve/ID Mapping to retrieve the UniProt entry ID as part of the UniProt API request. I've noticed that the current function to make this request isn't reliable. I will investigate further later today.

**Comment by johnllopez616** [comment]
@dondi @kdahlquist  would you like me to keep the page count at the bottom of the Gene Pages? If so, are you interested in keeping track of how many times a user visits an individual gene, or how many times a user visits an arbitrary gene page / uses the feature?

**Comment by kdahlquist** [comment]
@johnllopez616, let's not use the counter at the bottom of the Gene Pages.  It seems like that would be a headache to deal with and we don't really need the information.

After thinking about it for a while, I'm going to close this issue and open more granular issues that fall into specific areas (that roughly fall into the teams from biodb):
- look and feel of gene page
- integration and interaction (right-click behavior on node on main GRNSight, opening of page)
- API issues
- documentation 

I will close this issue once all relevant items have been moved.

**Comment by johnllopez616** [comment]
When all the above issues are complete, I will have a new pull request ready!

**Comment by kdahlquist** [comment]
All open threads on this issue have been moved to new issues: #620, #621, #622.  So, closing this one.
