### ISSUE TITLE
Consolidate state management into a single controller for user selected options

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#576]
Right now each feature's state is held in different variables, chosen by the person who wrote that feature.  This needs to be consolidated into a single controller because GRNsight is not remembering the state.  They need to be synchronized.

**Comment by kdahlquist** [comment]
Based on what I see in current beta, we really need this.

**Comment by yshin4** [comment]
Noticed that when the slider value is changed and the graph reloads, the graph itself is reloaded with default values (link distance 500 and charge -50). But the sliders do not reload and they stay the same as before the reload. The values stay as how the user changed, but it is not applied to the graph so there is an inconsistency between the slider value and the graph. 

Also, the graph froze and did not react to the change according to the sliders when I was trying to change the value for linked distance, similar to how grid layout sometimes does not toggle properly. I do not know how to recreate this event yet.

**Comment by eileenchoe** [comment]
Completed state management for node and edge features while working on  #462

**Comment by yshin4** [comment]
I don't think I can reorganize all the parts I'm working on for the menu into one controller. Focusing on getting the new menu working right now and I probably can't refactor all of them in slider/upload.

**Comment by yshin4** [comment]
@eileenchoe's updates are live on beta 2.3.7 now.

**Comment by kdahlquist** [comment]
I think this was included in v3.0.0 release.  @dondi should do the "review requested" this one and close.

**Comment by dondi** [comment]
This can be done without changing tech stacks. General steps are:
- Create a new `grnState` object that represents the model for the app (i.e., the complete snapshot of its state)
- Create a new `updateApp` function through which all changes to the app's elements/markup will take place; this function would also trigger a graph redraw if necessary
- Create a new `setupHandlers` function that connects the app's elements/markup to the appropriate event handlers (click, change, mouse, etc.). The handlers should update `grnState`'s properties then call `updateApp` when all necessary updates are done
- The _grnsight.js_ top-level file calls `setupHandlers` as one of its initialization operations

For ease of updates, investigate the use of property mutator functions for `grnState` so that the mere assignment of a property value will trigger code that can launch an update cycle.

Make this structure co-exist with the current code so that values are moved gradually from the old paradigm to the new.

**Comment by dondi** [comment]
Some side tasks to perform while working on this:
- Gradually transition all `require` calls to `import`/`export` where possible
- Issue very small pull requests in the beginning, so that @dondi can validate whether the design is going in the right direction

**Comment by dondi** [comment]
To avoid regressions (i.e., whack-a-mole ad infinitum), do write as many tests as possible. This structure will allow you to write tests using HTML fragments (i.e., focused subsets of the app) that verify the update cycle in isolation.

**Comment by dondi** [comment]
See the "Defining Getters and Setters" section of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects to see how you can assign functions that are triggered by property assignments.

**Comment by johnllopez616** [comment]
Here were the images from today's meeting: 

![img_3370](https://user-images.githubusercontent.com/21348600/40089281-c3fc91e8-585f-11e8-80dc-9abae7d4ce1d.JPG)
![img_3371](https://user-images.githubusercontent.com/21348600/40089282-c585762e-585f-11e8-82cf-20a2a31ab46d.JPG)
![img_3372](https://user-images.githubusercontent.com/21348600/40089284-c6d7d60c-585f-11e8-8204-0efae85fe1cd.JPG)
![img_3373](https://user-images.githubusercontent.com/21348600/40089286-c7dd92d0-585f-11e8-9773-8fb824f1dce1.JPG)
![img_3374](https://user-images.githubusercontent.com/21348600/40089287-c8cf45f8-585f-11e8-8bde-1f87ab6c97d7.JPG)

**Comment by kdahlquist** [comment]
Got an update from @mihirsamdarshi just now.  He's stopped work on graph.js because it is too complicated.  Instead he is working on upload.js because loading a graph is a simple function that doesn't interact with much other stuff.  Goal is to have a PR by the end of today for the load graph function to see if he's on the right track with this and to tackle the more complicated graph.js next week.

**Comment by mihirsamdarshi** [comment]
@dondi, my latest commits have the basis of the architecture down, however I have a technical question to ask you. In line 19, I have to re-call _drawGraph_  in order to implement the gray edges. How would I import the other parameters that are implemented? Would that all go in grnState as well?

**Comment by mihirsamdarshi** [comment]
@dondi now that a framework was established, I am going to start moving the gray edges into the single state controller

**Comment by mihirsamdarshi** [comment]
additionally @dondi what should I be looking for to consolidate with `annotateLinks` in _grnstate.js_

**Comment by kdahlquist** [comment]
Question for @dondi:  Are we going to release the beta-consolidation stuff with the 3.1.0 release tomorrow?  @mihirsamdarshi is thinking that he doesn't want to do that until it's all finished.

I thought that as long as nothing is broken, we should, but he is worried that since it hasn't been thoroughly tested, something might be broken.

Please comment.

**Comment by dondi** [comment]
@kdahlquist @mihirsamdarshi I see nothing wrong with releasing this with 3.1.0. True that we haven't done UI-level unit tests, but there are some model-level unit tests and the code review cycle on this set of changes was pretty strict. Unless there is a blatant regression, I am OK with releasing.

The overall task is large enough that waiting for it to be all finished will hinder more than help. Better to dole this out piecemeal and let it "settle" than to keep it on the side for too long.

**Comment by mihirsamdarshi** [comment]
So far, as of release v3.1.0, the following features have been consolidated into out MVC framework: network object, normalization, edge weight display options, enabling/disabling edge coloring/thicknesses, gray edge threshold, and displaying gray edges as dashed lines. Going forward, the whole of _upload.js_ can be added to the MVC, as well as figuring out a way to move the whole of _graph.js_. Moving node-coloring and sliders.js should be next on our priority list.

**Comment by mihirsamdarshi** [comment]
I am currently working on sliders.js, moving over the constants right now

**Comment by mihirsamdarshi** [comment]
@dondi, I believe the next best course of action is to move `updateSliderDisplayedValue` to update-app.js, what do you think?

**Comment by dondi** [comment]
OK @mihirsamdarshi give that a shot. Looks slightly trickier than it looks, because I think that code applies to multiple sliders. Each slider becomes its own property in the model, but ideally you still find a way to use the same view and controller code, with the property being stored as some kind of variable or parameter.

**Comment by dondi** [comment]
After looking at the code, @dondi recommended that the _sliders.js_ code can be broken up for now, into the new MVC structure, without having to copy the existing functions. Just code `charge` and `link` changes according to the MVC cycle and let’s see how that looks when you’re done.

**Comment by mihirsamdarshi** [comment]
@dondi I just pushed the first part of my split, I was wondering if I was on the right track or if I should approach it in another way?

**Comment by dondi** [comment]
After code review of @mihirsamdarshi’s work in progress, the green light was given to proceed. After separating the controller code, some functions will need to go to the view vs. controller modules. Also, some code duplication is expected, and a consolidation step is expected at the end. Unit tests are expected as well.

**Comment by mihirsamdarshi** [comment]
I am currently in progress with the move. Currently, the move has broken the sliders on my branch. I don't know if I should restart, considering our goal is to move sliders with minimal detriment to functionality. I also ran into a question regarding whether we should move sliderObject itself to grnState or its individual components.

**Comment by dondi** [comment]
@mihirsamdarshi has identified a new approach to refactoring the slider code which will require him to back out some of his work and start over. However he also has some work which can be considered as done. His upcoming pull request sometime Monday will include this work, but with the slider code reverted so that he can go on a fresh start after this cycle.

**Comment by dondi** [comment]
@mihirsamdarshi is back in the saddle and will aim to finish the slider code refactor over the weekend. The goal is to have a pull request by early next week in order to have a beta ready for @kdahlquist on Thursday.

**Comment by kdahlquist** [comment]
@mihirsamdarshi reported progress on the sliders and says we are on track to complete the refactoring of all features by the end of the semester.  He is going to be out of town on the weekend and has a couple of midterms next week, so his next PR will likely not come until next Wednesday night.

**Comment by dondi** [comment]
@mihirsamdarshi is continuing to refactor the sliders code and is getting close. Emphasis was made on enforcing the one-directional flow of MVC information even if some iterations are carrying the same values.

**Comment by kdahlquist** [comment]
@mihirsamdarshi has questions for @dondi in PR #706 .

Here is the list of what has been completed so far (@mihirsamdarshi, please edit this comment if I got something wrong):
* Lock/unlock Force Graph Parameters
* Reset Force Graph Parameters
* Hide/show edge weights
* Edge weight normalization factor set/reset
* Gray threshold slider
* Show gray edges as dashed
* Link distance and charge sliders are almost done

What hasn't been done:
* Grid layout
* Node coloring
* Zoom
* D-pad
* Viewport size/restrict graph to viewport.

To finish off the semester, let's get link distance and charge sliders done.

**Comment by dondi** [comment]
Carrying on thread from PR #706 @mihirsamdarshi will refactor the "layout" property of the app to the new MVC structure and aim to make the PR mergeable into beta after that is done.

**Comment by mihirsamdarshi** [comment]
Just as I guessed, moving the code that specifies layout to grnState fixed any issues that we were having

**Comment by mihirsamdarshi** [comment]
@dondi the code has all been compartmentalized, and so far everything except for the code that controls the DOM of the graph is working. For that I have created two new sets of functions within graph.js `setNodesToGrid()` and `setNodesToForceGraph()` at around line 1234. I know that I am missing something extremely basic, because this code can't be called from within updateApp because there is a TypeError stating that `drawGraph.setNodesToGrid()` or `drawGraph.setNodesToForceGraph()` are not functions.

**Comment by kdahlquist** [comment]
In its current form those functions are declared as local variables and this is why they are not visible to the outside. `drawGraph` should probably transition to an object eventually, so that its functions can be viewed as methods on the graph. As a transitional step, try to assign those functions to `this`. This should make those functions visible to outside code as properties of the `drawGraph` function itself.

**Comment by mihirsamdarshi** [comment]
All major features, except node coloring, have been added to the new architecture structure. Discussions are underway for the conversion of graph.js to be an object.

**Comment by kdahlquist** [comment]
Version on beta looks good. Additional refactors will be done as new issues.
