### ISSUE TITLE
Need new demo #1 and #2 files in correct format for node coloring

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#585]
Need new demo files in correct format for node coloring.  @kdahlquist will select files to replace demo 1 and demo 2.  Demos 3 and 4 need to stay the same because they are tied to the original GRNmap and GRNsight papers.

I'm wondering if we need to give a message to the user if their uploaded file won't work with node coloring?

**Comment by kdahlquist** [comment]
Working on this now.  I will have something for you tomorrow morning.

**Comment by kdahlquist** [comment]
Here are two new demo files to replace demo's 1 and 2.  They were generated with GRNmap v1.9.

One consequence of the new data structure is that we can have node coloring with an unweighted network.

We might consider defaulting an unweighted network to no have node colors either, but let's not mess with things right now.
[15-genes_28-edges_db5_Dahlquist-data_input.xlsx](https://github.com/dondi/GRNsight/files/1948360/15-genes_28-edges_db5_Dahlquist-data_input.xlsx)
[15-genes_28-edges_db5_Dahlquist-data_input_output.xlsx](https://github.com/dondi/GRNsight/files/1948361/15-genes_28-edges_db5_Dahlquist-data_input_output.xlsx)

**Comment by eileenchoe** [comment]
@kdahlquist Ok, working on updating this now. Will also be included in the menu updates #589 PR. Should I still include "Dahlquist Lab unpublished data" in the parenthesized part for Demo #2?

**Comment by kdahlquist** [comment]
Yes, actually both 1 and 2 should be annotated that way since the node coloring shows up for the input file as well.

**Comment by yshin4** [comment]
Live on beta 2.3.7 now.

**Comment by kdahlquist** [comment]
Confirmed.
