### ISSUE TITLE
v3.0.0 release

### ISSUE THREAD

**Issue by eileenchoe** [dondi/GRNsight#588]
- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [x] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [x] the [featureList.json](https://github.com/dondi/GRNsight/blob/beta/documents/developer_documents/testing_script_generator/featureList.json) file should be updated
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
    - [x] Update Travis and Coveralls badges to reference the master branch
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [x] Update version numbers in _package.json_
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [x] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Refresh (pull) the `master` clone on _grnsight.cs.lmu.edu_
    - [x] Update the version number and modification date on `gh-pages`
    - [x] Update the About page with release notes (GitHub release item without issue numbers)
        - [x] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [x] Update modification date
    - [x] Add news item about the release to the News page
        - [x] Update modification date
        - [x] Link news item to the corresponding release notes in the About page
    - [x] Update Documentation page with any new features or updates to old features
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
    - [x] Update Travis and Coveralls badges to reference the beta branch
    - [x] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [x] Publish to _npm_ (`npm publish`)
    - [x] _npm_ requires all `.0`s in the semantic version
    - [x] Check to see that BioJS updates its GRNsight entry
- [x] Update version number/other relevant information at current bioinformatics listing sites
    - [x] Elixir 
        - [x] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [x] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [x] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by eileenchoe** [comment]
Compiling the list of issues to be included in this release below. I have marked the issues with `for next release` if they weren't marked so already. I will begin writing up the release notes tonight. @yshin4 can you go through the issues again and make sure I didn't miss any?

- #568 Make gray edges have dashed line instead of solid line
- #564 Resolve "qs" package security vulnerability: port to v4.16.0 of Express
- #585 Need new demo #1 and #2 files in correct format for node coloring
- #577 Webpack Configuration & Source Map
- #576 Consolidate state management into a single controller for user selected options
- #575 Add new features to client-side testing document
- #566 Node Coloring
- #558 Create block layout
- #518 Change gray edge threshold value to percent scale (0 - 100%) 
- #462 Reorganize menu options to make sense with v2 feature set 
- #587 Documentation needs to be written for new features in v3.0.0
- #241 Data structure design for reading expression data from GRNmap input/output sheet

**Comment by yshin4** [comment]
LGTM

**Comment by eileenchoe** [comment]
Started the draft release for v3.0.0
Release notes have been drafted [here](https://github.com/dondi/GRNsight/releases/tag/untagged-cdf19a8150d26b890faf) @kdahlquist can you review please?

**Comment by kdahlquist** [comment]
Changed block layout to grid layout.  Otherwise looks good.

**Comment by kdahlquist** [comment]
That's fine, but I reserve the right to make content changes to other pages besides home and beta :)

**Comment by eileenchoe** [comment]
Completed most of the major release steps with @yshin4 today! A few more steps at the bottom for @dondi to complete. GRNsight v3.0.0 is up on the home page, and documentation has been changed accordingly. 🎊

**Comment by kdahlquist** [comment]
Congratulations!  When @dondi finishes the last tasks (npm, BioJS, Elixir, Zenodo), he can close this.

**Comment by dondi** [comment]
npm, BioJS, Elixir, Zenodo, and citation links all check out…closing! 👏
