### ISSUE TITLE
Grid Layout bugs

### ISSUE THREAD

**Issue by yshin4** [dondi/GRNsight#592]
Basic functionality of grid layout is now live on beta 2.3.7. However, there are some remaining bugs.

- [ ] manually reheat to unfreeze the graph between the toggles.
@eileenchoe said to look for the .reheat method in sliders.js or graph.js
The method was sliderController.simulation.alpha(1); but this did not fix my issue.
I figured out how to recreate the issue, 1. load a graph 2. grid layout 3. click somewhere in the graph, i think it is okay as long as you click anywhere else other than the button itself? 4. go to another app, i used atom, and did an activity (like writing on and saving the file) 5. Click the button again, it does not work.

- [ ]  According to @kdahlquist when the sliders are locked, clicking the grid layout button does not change the layout to grid. Will investigate, I wonder if this is related to graph freezing between toggles.

- [ ] #576

**Comment by kdahlquist** [comment]
This can be closed because any outstanding tasks are in new issues.
