### ISSUE TITLE
Allowing force graph layout to reach equilibrium and then trying to enable force graph layout results in no movement until further manipulation of graph

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#598]
Allowing force graph layout to reach equilibrium and then trying to enable grid layout results in no change.  You have to move a node to get the grid layout to work.

**Comment by kdahlquist** [comment]
This is related to something @kdahlquist observed, which is once the force graph layout reaches equilibrium and stops moving, the force graph parameter sliders no longer work.

Clicking on the grid layout button after equilibrium also doesn't work.  So there seems to be issues with functions not working after the graph reaches equilibrium.

**Comment by kdahlquist** [comment]
This is fixed upon the MVC refactor. Confirmed in beta 3.1.12
