### ISSUE TITLE
Dropdown menu and sidebar menu viewport sizes do not initialize to same values

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#599]
Dropdown menu and sidebar menu viewport sizes do not initialize to same values

**Comment by kdahlquist** [comment]
Dropdown menu and sidebar menu viewport sizes do not initialize to same values

@mihirsamdarshi, when reporting bugs, will you:
- copy title into description field instead of leaving blank
- add labels `bug`, `priority 1`, `functionality`

Thanks.

**Comment by kdahlquist** [comment]
@mihirsamdarshi will try to reproduce this bug; it might be fixed--it didn't show up on @kdahlquist's computer with Firefox.

**Comment by kdahlquist** [comment]
Can't reproduce this bug on v3.1.12, so closing, adding label backlog, in case it comes back.
