### ISSUE TITLE
In v3.0.4 and Firefox 60.0, opening a gene page causes cookies banner to show up twice on page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#603]
In v3.0.4 and Firefox 60.0, opening a gene page causes cookies banner to show up twice on the new page that opens.

It shows up in the upper right corner as expected, but also superimposed and interleaved with the sidebar menu on the left.

**Comment by johnllopez616** [comment]
Should be resolved now, it doesn't happen to my firefox or chrome now.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta v3.0.6, so closing.
