### ISSUE TITLE
Source buttons at top of gene page should act as "anchor tags" and shift page to that section when clicked

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#606]
The buttons at the top of the gene page need to not only open the corresponding section of the page, but also act like anchor tags and shift the page so that sections content is at the top.

**Comment by johnllopez616** [comment]
I would also like to add a better arrangement of the buttons. As of now the buttons align in a row as large as the user's window. If the window size changes to a size less than the buttons can fit on a single row, another row is created.

**Comment by johnllopez616** [comment]
It links to part of page as requested, but it doesn't exactly do it to the center of the page. Will investigate further.

**Comment by johnllopez616** [comment]
The buttons should link as intended now.

**Comment by kdahlquist** [comment]
Further discussion of buttons will move over to #620.
