### ISSUE TITLE
Font and color scheme discussion for gene pages

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#607]
At today's GRNsight meeting, I want to discuss and make style decisions for the gene pages.  We need to make sure that the style of the gene pages is consistent with the GRNsight main pages.  
- Specifically, I want the font for the buttons and information to match what we are already using for the menus on GRNsight home and beta.  
- Also, I would like the text to be black instead of gray for the section information.
- Let's also talk about the button colors, so no color is duplicated.
- Finally, I think we may be changing the labels for the buttons/sections slightly and potentially changing the order.  The actual data is not being pulled and displayed on beta right now, so I can't say more about that yet, but be advised that it is coming down the pike.

**Comment by johnllopez616** [comment]
To do:

- [ ] Make 

font - same as main grnsight
make card label text black
universal font (except for sequence)
fixed width (courier) sequence font
get rid of margins in buttons
