### ISSUE TITLE
Hide/show relevant node coloring information

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#608]
The node coloring should probably be hidden and shown based on whether node coloring has been turned on or off

**Comment by johnllopez616** [comment]
The solution to this issue will begin with the transition of the Node Coloring-related variables in `graph.js` as a part of #614

**Comment by kdahlquist** [comment]
Let's talk about this at a meeting and either implement or close.

**Comment by kdahlquist** [comment]
This one is superseded by #803, so closing this one.
