### ISSUE TITLE
Need to be able to select with mouse the fillable fields in the menus so the values can be replaced without using backspace/delete key

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#615]
I think when the top dropdown menus got reorganized, @eileenchoe changed the control for the edge weight normalization factor so that a user could not type an edge weight normalization factor and instead had to click the down or up arrows to set the value.  However, this means that you can only set integer values when clicking on the arrows, defeating the purpose of this feature to be able to set something that matches another graph (which likely won't be integer values).

We need to revert this back to the previous behavior when a user could type a real number into this field.  It should allow and display up to four places to the right of the decimal.

The behavior of this field in the side bar and in the dropdown menu needs to be the same (which is maybe whey she changed it).

**Comment by kdahlquist** [comment]
So, I see what is happening here.  I was mistaken that I cannot type a value in here.  It's not allowing me to select the value with my mouse pointer.  I can type in the field, but I can't select the value there for replacement, I just have to type.  So to get rid of the value there, I have to use the backspace or delete key.  It seems like I should be able to select with my mouse to replace the number.

**Comment by johnllopez616** [comment]
I noticed that this is the case with every one of the text input fields. Would you like a solution implemented that resolves it for all of the fields or just for the edge weight normalization factors?

**Comment by johnllopez616** [comment]
Currently the field is defined as a number input type. This means that the text input and the spinner arrows are considered to be the same object by the browser. To allow the values in the fields to erase whenever the user clicks on the text field would also mean that the values are lost whenever the user manipulates the adjacent spinners. So the spinner functionality of adjusting the values +1 or -1 would be lost.

**Comment by kdahlquist** [comment]
I'm going to unassign @johnllopez616 because this is a low priority and should only be tackled once the refactor of the state controller is completed.

**Comment by kdahlquist** [comment]
Moving the priority up again to focus on the next release.

**Comment by dondi** [comment]
This has been fixed on my branch and will be available for review upon the next beta refresh.

**Comment by kdahlquist** [comment]
Verified fixed in beta 4.0.1
