### ISSUE TITLE
Move show gray edges as dashed check box to below slider

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#616]
Please move the show gray edges as dashed check box to below the slider.

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/40566044-ce6ca1b0-6023-11e8-9c21-2f61f90dae63.png)

This change should be displayed with the next PR

**Comment by kdahlquist** [comment]
Confirmed complete in v3.0.13.
