### ISSUE TITLE
Store gene page information as cookies to offset the likelihood of database downtime

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#618]
Store gene page information as cookies to offset the likelihood of database downtime. Determine if this is viable (i.e. can data be stored in a small enough and can this information be pulled from the cookie first?)

**Comment by kdahlquist** [comment]
We also need to discuss whether this is really desirable.  The point of doing the API call is to get the latest info.  If the data is sitting around in a cookie for a long time, it might get stale.

**Comment by kdahlquist** [comment]
Backlogging and closing this issue.
