### ISSUE TITLE
Tweaks to look and feel of gene page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#620]
Moving relevant items from #573 to this issue which is all about tweaks to the look and feel of the gene page.

- [x] the gene page also needs the GRNsight footer (but not the page view counter); confirmed finished in beta v3.0.6 by @kdahlquist
- [x] title text for the new tab that opens should be "GRNsight - name of gene" instead of "Information about name of gene"  For example, instead of "Information About STB5" it should say "GRNsight - STB5"; confirmed finished in beta v3.0.6 by @kdahlquist
- [x] @kdahlquist will provide feedback on what colors to use for the buttons/section headers (see below); confirmed finished in beta v3.0.7 by @kdahlquist
- [x] Can the buttons be left-justified instead of centered above the accordian sections; confirmed finished in beta v3.0.7 by @kdahlquist
- [ ] Will you reduce the white space on the top and left?  See the News or About page for how much margin there should be.  This could still be reduced more.  The margin on the News and About page is something like 0.5 cm; left margin looks good in v3.0.10, but the top margin needs to be shortened still.  There appears to have been a regression in v3.0.13: the left margin is too big again.  The top margin could be shortened a little; see the News or About page for the appropriate height.  _moved this to new issue_
- [x] Font for the species name is too large, the species name is taking up too much room at the top of the page.  It makes sense to have the name of the gene be large, but not the species name.  Confirmed by @kdahlquist in beta v3.0.10 (looks nice).
- [x] There needs to be some white margin on the left in the different sections when they are populated with data.  Right now, the text appears flush with the edge.  Confirmed complete in beta 3.0.9 by @kdahlquist.
- [x] In the Sources section, please number the sources like this instead of using the superscripts and left-justify instead of center in the section: (@kdahlquist says almost complete in v3.0.13, but see note in bold below about NCBI *Gene* Database.)

1. Saccharomyces Genome Database
2. UniProt
3. NCBI Gene Database **(note the inclusion of the word "Gene" there)**
4. Jaspar Database
- [x] In the Sources section, "Saccharomyces" is spelled incorrectly. (@kdahlquist can't review yet because data not loaded due to Jaspar bug.)
- [x] Delete "Gene Map" button and section; there doesn't appear to be any data that goes there.  Confirmed complete in beta 3.0.9 by @kdahlquist.
- [x] Need to alter behavior of layout when window size is reduced.  Note that on the other GRNsight pages (like News, About), it will adaptively shrink down to a pre-set minimum, after which scroll bars appear.  Right now, the page will shrink down so much that the gene information overwrites the sidebar menu.

**Comment by johnllopez616** [comment]
This is the color of the GRNsight navbar:
#dfebe5

**Comment by kdahlquist** [comment]
Let's try these colors for the buttons:
- #16693f
- #3f1669
- #693f16
- #166969
- #691640

**Comment by johnllopez616** [comment]
[GRNsight - YHP1.pdf](https://github.com/dondi/GRNsight/files/2018728/GRNsight.-.YHP1.pdf)

**Comment by kdahlquist** [comment]
On beta v3.0.7, clicking on the links on the left side bar causes a weird phenomenon where the gene page is superimposed on the page that was clicked on, like the gene page superimposed on the About page.  Clicking on the links on the bottom causes the GRNsight header to be shown along the bottom of the gene page.

**Comment by kdahlquist** [comment]
I've gone through and confirmed, when possible, what fixes were made.  There are a couple I can't confirm until we get around the API bug.  I also requested another tweak in the list in comment 1.  Fixing the functionality takes precedence, though.

**Comment by kdahlquist** [comment]
I'm going to start a new checklist in this comment because the one above is getting too long.  Note that there are still some unresolved issues above as well as the new ones here.

- [ ] The cookie banner is underneath a white box, it should be on top.  See screenshot below.

![image](https://user-images.githubusercontent.com/6463867/40391874-9806e510-5dce-11e8-8f0f-65cf8411b6df.png)

- [ ] Let's make the hyperlinks on the page to be the main green GRNsight color, instead of multi-colored.  The buttons and section headers look nice with the different colors, but I think to be clear, the rest of the hyperlinks should just be the main GRNsight green color.  This affects both the General and Sources sections.
- [ ] Let's use the Wikipedia convention of putting the source citations in square brackets like this <sup>[1]</sup>.
- [ ] Let's make the source citations in the square brackets link to the sources section (like a Wikipedia page does).
- [ ] In the Sources section, please move the list of citations over to the left-hand side, with the same margin as the other sections above it.
- [ ] Let's regularize the font size and bolding for all the sections.  For example, in the regulation section, the field names are not bolded, in the protein section the font is really large.  Whatever the size they are in the general section is good (and bolded).
- [ ] The protein sequence is not displaying correctly.  It has a leading space that should be removed and there are line breaks in the sequence that are not being respected when the window is maximized.
- [ ] In the general section, it is "NCBI Gene ID" not just "NCBI ID".  NCBI has a lot of different databases and the one we are calling is the "Gene" Database.
- [ ] The Jaspar sequence logo image and matrix need to be moved a little to the right.  The matrix is actually overlapping the edge of the section on the left-hand side.
- [ ] Can the Jaspar sequence logo image be made a little smaller?

**Comment by kdahlquist** [comment]
I'm going to do what review I can from here.  But the computer I have access to is running Window's Vista with an outdated version of Chrome (which can't be updated because Windows Vista is no longer supported).

**Comment by kdahlquist** [comment]
Looks like I can't open a previous comment to edit.  I'll have to comment on them here in a new comment.
- Let's make the hyperlinks on the page to be the main green GRNsight color, instead of multi-colored. Confirmed in beta v3.0.11 by @kdahlquist.
- Let's use the Wikipedia convention of putting the source citations in square brackets like this [1]. Confirmed in beta v3.0.11 by @kdahlquist.
- Let's make the source citations in the square brackets link to the sources section (like a Wikipedia page does). Confirmed in beta v3.0.11 by @kdahlquist.
- In the Sources section, please move the list of citations over to the left-hand side, with the same margin as the other sections above it.  This has been done, but on the machine I am on, Saccharomyces Genome Database gets broken into two lines.
- Let's regularize the font size and bolding for all the sections. For example, in the regulation section, the field names are not bolded, in the protein section the font is really large. Whatever the size they are in the general section is good (and bolded); this has mostly been done, but in the general section, the actual ids on the right look like they are a different, bigger font size than the field names.
- The protein sequence is not displaying correctly. It has a leading space that should be removed and there are line breaks in the sequence that are not being respected when the window is maximized; I will have to look at this again when I'm back at my own computer.
- In the general section, it is "NCBI Gene ID" not just "NCBI ID". NCBI has a lot of different databases and the one we are calling is the "Gene" Database; confirmed in beta v3.0.11 by @kdahlquist.
- The Jaspar sequence logo image and matrix need to be moved a little to the right. The matrix is actually overlapping the edge of the section on the left-hand side.  These have bee moved, but the sequence logo is still too large (at least on this computer).  It needs to be half of it's current size.  There's no reason for it to dominate the page.

**Comment by johnllopez616** [comment]
@kdahlquist 

![image](https://user-images.githubusercontent.com/21348600/40501136-d7886902-5f3b-11e8-8e64-e2dbbc49bfa8.png)

![image](https://user-images.githubusercontent.com/21348600/40501181-fb635cd8-5f3b-11e8-8935-6a4326f5cd26.png)

![image](https://user-images.githubusercontent.com/21348600/40501236-1c317d32-5f3c-11e8-9018-90e2d9b97641.png)

![image](https://user-images.githubusercontent.com/21348600/40501248-2ab16a16-5f3c-11e8-8c01-18878243cf46.png)

All of these changes have been made and are live on beta. I am unsure as to why they are not showing up on your laptop.

**Comment by johnllopez616** [comment]
@kdahlquist You may view the changes here. This is a direct beta link to a sample gene. Trying to access the genes on beta directly right now will not work. http://grnsight.cs.lmu.edu/beta/client/info?symbol=YHP1

**Comment by kdahlquist** [comment]
@johnllopez616, I commented on the previous check-lists.  Please review the previous comments for things that I unchecked and commented on.  I am also adding some new items here.

- [ ] What happened to the white space between the buttons at the top?  I liked the small white margins between them.
- [ ] The font size for the actual IDs in the general information section is larger than the field names.  For example, "S000005476" is appearing larger than "SGD ID:".  Please make them the same size.
- [ ] In the general information section, the IDs should not be bolded.  For example, "S000005476", "854033", "YOL116W", "MSN1_YEAST" and "MA0363.1" should _not_ be bolded.
- [ ] The open/close behavior of the accordian sections needs to be regularized.  When you open a new section, sometimes the previous sections close and sometimes they stay open.  Let's make it so that the sections all stay open unless the user manually closes them.
- [ ] An issue related to the above is that if you click on a button at the top of the page and that section is already open, it actually closes.  The correct action would be for it to simply shift the page down to the open section.

**Comment by johnllopez616** [comment]
Created a new checklist regarding the unresolved issues:
- [ ] An issue related to the above is that if you click on a button at the top of the page and that section is already open, it actually closes.  The correct action would be for it to simply shift the page down to the open section.
- [ ] The Jaspar sequence logo image and matrix need to be moved a little to the right. The matrix is actually overlapping the edge of the section on the left-hand side. These have bee moved, but the sequence logo is still too large (at least on this computer). It needs to be half of it's current size. There's no reason for it to dominate the page.
- [ ] The protein sequence is not displaying correctly. It has a leading space that should be removed and there are line breaks in the sequence that are not being respected when the window is maximized; I will have to look at this again when I'm back at my own computer
- [ ] In the Sources section, please move the list of citations over to the left-hand side, with the same margin as the other sections above it. This has been done, but on the machine I am on, Saccharomyces Genome Database gets broken into two lines.
- [ ] Need to alter behavior of layout when window size is reduced. Note that on the other GRNsight pages (like News, About), it will adaptively shrink down to a pre-set minimum, after which scroll bars appear. Right now, the page will shrink down so much that the gene information overwrites the sidebar menu.
- [ ] Will you reduce the white space on the top and left? See the News or About page for how much margin there should be. This could still be reduced more. The margin on the News and About page is something like 0.5 cm; left margin looks good in v3.0.10, but the top margin needs to be shortened still. There appears to have been a regression in v3.0.13: the left margin is too big again. The top margin could be shortened a little; see the News or About page for the appropriate height.
- [ ]  The cookie banner is underneath a white box, it should be on top. See screenshot below.

**Comment by kdahlquist** [comment]
All remaining issues have been moved to either #653 or #654.
