### ISSUE TITLE
Gene page API issues, documentation, and testing

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#621]
Currently on beta v3.0.5, the gene page is opening, but data is not being loaded.

Copied over a post by @johnllopez616 from #573:

_I discovered that at least one of the data loading issues is related to the first part of ` getUniProtInfo()` within `api.js`.  What this function does is make a request to UniProt Retrieve/ID Mapping to retrieve the UniProt entry ID as part of the UniProt API request. I've noticed that the current function to make this request isn't reliable. I will investigate further later today._

Once the basic functionality is up for @kdahlquist to look at on beta, we also want to make sure that if a user has a gene that is not found in one or more databases, the appropriate "not found" messages come up.  There are two cases to consider:
- if the gene is just not found at all in any database
- if the gene is found in one or more, but not all databases

When the Fall 2017 BioDB wiki is back up, @kdahlquist will review the documentation there to generate a guide to the expected results.  If it's not up by Monday the 21st, she will re-generate this documentation so it is not a blocker to progress on this issue.

**Comment by kdahlquist** [comment]
Problem: identical requests to UniProt will sometimes work and sometimes will not. A request for information about a particular gene will either return the proper information or will return an error.  Note that we don't know why this is happening.

Solution: have it make identical requests until one of the requests is successful and returns proper data. 

Next problem: None of the gene information will display on gene page unless all API calls are successful.

Proposed solution: These need to be independent of each other.  Not found or other such message should display on gene page for information not found from a particular database.

**Comment by kdahlquist** [comment]
I just looked at beta v3.0.6 and there still isn't any information populated on the gene page.

**Comment by johnllopez616** [comment]
It would appear that the api.js file returns a 404 error on beta when uploaded to the server.

**Comment by dondi** [comment]
Yes, try using a fully-relative URL. (no leading slash)

**Comment by kdahlquist** [comment]
@johnllopez616 and I discussed that an error modal will only come up if there gene information is not found at all in any database.

I'm noting here in the demo that @johnllopez616 showed me that the biodb class put "N/A" for information I requested that they were not able to implement during the semester.  @kdahlquist will need to review each of these items and determine whether we should give up on it or try to implement it.

**Comment by johnllopez616** [comment]
The following error emerges on Chrome when the API call to JASPAR is made unless [the following](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en-US.) plugin is installed.
`Failed to load http://jaspar.genereg.net/api/v1/matrix/?tax_id=4932&format=json&search=YHP1: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://grnsight.cs.lmu.edu' is therefore not allowed access.`

**Comment by kdahlquist** [comment]
Change text of Error that comes up when gene information not retrieved from the database:

Three-part framework:
1. Explain what the problem is.
2. Explain why the problem exists.
3. How the user can approach solving the problem.

So in the case of the gene backpages:

- Let's not throw a warning unless _no_ gene information is retrieved at all.  If some, but not all, gene information is retrieved, we will just fill those fields with "not found".
- Then if no gene information is retrieved at all, then the Error should come up.  Let's make the error read:

No gene information was retrieved for <insert name of gene>.

This could have happened because either GRNsight could not access the gene information from one of the source databases or because no information exists for the gene in the source databases.

You can check back later to see if gene information can be retrieved or submit an issue to https://github.com/dondi/GRNsight.

**Comment by dondi** [comment]
Does the error continue to persist? Make sure that it isn’t transient. As far as I know, JASPAR did use to work, and their website says they do support it:

http://jaspar.genereg.net/api/overview#cors-requests

(You might need to read up on CORS a bit so you can get more background)

If we do determine that this isn’t a transient error, then there appears to be inconsistency between their documentation and the actual API, and it may be necessary to contact the developer directly regarding their CORS support (or lack of).

**Comment by mihirsamdarshi** [comment]
I advised @johnllopez616 to break down the `filterData` function into its various sub-parts so as to make each individual call easily diagnosable.

**Comment by kdahlquist** [comment]
The BioDB class had to make a relay to get around the CORS problem at Jaspar.

**Comment by kdahlquist** [comment]
The relay file that BioDB class made needs to be moved into `server`; they put it in the wrong place.

**Comment by johnllopez616** [comment]
Will begin investigating the process for writing tests, particularly those involving the API calls. I'm reading up on the [SinonJS](http://sinonjs.org) framework now, as suggested by @dondi

**Comment by kdahlquist** [comment]
This is still in progress, so I'm removing the "for next release" tag.

**Comment by kdahlquist** [comment]
Remaining threads from this issue have been broken out into new issues, #681 and #682, so closing this one.
