### ISSUE TITLE
Weight values are too dark in beta v3.0.7

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#625]
The edge weight values are showing up as too dark in beta v3.0.7.  Not sure when this arose, but it's not in current v3.0.0 master.  See side by side image below.

![image](https://user-images.githubusercontent.com/6463867/40260611-6a469d12-5ab0-11e8-911a-a347977e7ae8.png)

**Comment by johnllopez616** [comment]
Turns out some code was missing from grnsight.css:
```
  stroke-width: 0.5px;
  transition: opacity 0.25s;
```
This should fix the problem with the next beta PR.

**Comment by kdahlquist** [comment]
I looked at this in beta v3.0.13.  When you have "show weights on mouseover" selected, the weights show up properly when you mouse over the edge.  However, if you choose "always show weights", they are still too dark like in the image in one of the previous comments.

**Comment by johnllopez616** [comment]
Should be fixed by the next PR

**Comment by kdahlquist** [comment]
Confirmed fixed in beta v3.0.14.
