### ISSUE TITLE
Rewording preference for "Format edges based on optimized weight parameters" and make it function like enable/disable node coloring

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#627]
Upon reviewing the Client Side Testing Document #575, it occurred to me that there might be a simpler way to say "Format edges based on optimized weight parameters" vs. "Default to black edges with regular arrowheads".

For node coloring, we have a toggle that says either "Enable Node Coloring" vs. "Disable Node Coloring" that turns node coloring on and off in the presence of expression data.

In the case of edges, it could be "Enable Formatting of Edges Based on Weight Values" vs. "Disable Formatting of Edges Based on Weight Values".

This is a low priority item since it's fine now, but I wanted to record the thought in an issue.

**Comment by kdahlquist** [comment]
I see the wording change on beta v3.0.13.  @johnllopez616, you are right, it is still not symmetrical with the way we enable/disable node coloring.

The functionality for enable/disable node coloring works like a toggle switch and the change is made immediately upon clicking.

The colored vs. black edge coloring feature was originally envisioned as a "preference" and requires a reload to take effect.

I think that, if it is possible, it would make more sense to turn the edge coloring on/off just like we do for node coloring and make the menu item work the same way.  To be clear, toggling the switch on/off would turn the edge coloring on/off immediately.

There is another bug associated with this feature, #591.

**Comment by mihirsamdarshi** [comment]
I made a change so that upon clicking _Default to black edges with regular arrowheads_ the graph is reloaded

**Comment by kdahlquist** [comment]
@mihirsamdarshi made it so that a reload is triggered when choosing the option.  However, we need to convert this to an enable/disable toggle switch like node coloring before closing this issue.

**Comment by kdahlquist** [comment]
Actually, the enable/disable toggle doesn't work right for node coloring either in terms of the text on the menu item (the functionality works, though).

**Comment by kdahlquist** [comment]
This is done.
