### ISSUE TITLE
Link to Ensembl from general information/sources sections on gene page goes to ACT1, no matter what the gene is

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#641]
The link to Ensembl from the general information section on gene page goes to the Ensembl page for ACT1, no matter what the gene is.  It looks like a default hard-coded link was left in there.

**Comment by johnllopez616** [comment]
Fixed, will see changes in next PR

**Comment by kdahlquist** [comment]
Confirmed fixed in beta v3.0.14
