### ISSUE TITLE
Retrieve GO Biological Process, Molecular Function, and Cellular Component terms for gene page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#642]
We need to populate the Gene Ontology section with the GO terms for Biological Process, Molecular Function, and Cellular Component retrieved from SGD.

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/40693275-67f91b52-636b-11e8-96d9-db64d3499e06.png)
Preview of next PR

**Comment by kdahlquist** [comment]
Looks good.  Is there a reason that the GO:0000083 is repeated twice?  

Can the definitions be moved to the same line as the ID to save vertical space?

The reference [1] looks a little strange hanging out on its own line.  

There needs to be a colon after "Molecular Function:"

**Comment by johnllopez616** [comment]
For some reason several of the GO terms are repeated: will investigate and fix before next PR

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/40738393-4e440ca2-63f8-11e8-8ab8-b0e6e33ccead.png)
Will be ready by next PR

**Comment by kdahlquist** [comment]
Looks good.  Looking forward to seeing it on beta.

**Comment by kdahlquist** [comment]
Confirmed that the cosmetic fixes noted above are fixed.  Also, IDs do not appear to be duplicated.  However, the cellular component terms being retrieved are incorrect.  It looks like it is repeating the biological process terms instead of retrieving the correct cellular component terms.

![image](https://user-images.githubusercontent.com/6463867/40754013-cdb318f6-642b-11e8-8b98-a9bb7ad400c2.png)

**Comment by kdahlquist** [comment]
In beta v3.0.15, the cellular component terms are now correct.

- [ ] However, we are still seeing duplicated terms in all three categories, biological process, molecular function, and cellular component.  The duplicated terms are not right next to each other, they are interleaved with other terms.  @johnllopez616 says that the code that is checking for duplicates only checks for when the duplicates are right next to each other.
- [ ] Please make the GO IDs, not bolded, but regular text.

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/40814622-1929c06c-64f6-11e8-9052-faa47a11c25e.png)

**Comment by kdahlquist** [comment]
confirmed that the duplication of GO terms has been fixed.  @johnllopez616 is now looking into an issue where the GO IDs and GO definitions are not aligned in Firefox with v3.0.16

**Comment by kdahlquist** [comment]
Complete.
