### ISSUE TITLE
"Description" field in gene page general information section needs to be retrieved from SGD, not Ensembl

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#643]
The "Description" field in gene page general information section needs to be retrieved from SGD, not Ensembl.  SGD is the original source of that information, so we should get it from them.

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/40734357-0827f432-63ed-11e8-8f6a-8234384fb554.png)
Will be ready by next PR

**Comment by kdahlquist** [comment]
This is something that I can't directly confirm because the text isn't really changing.  I'm going to assume this is done because at least the correct text is being retrieved and referenced correctly.
