### ISSUE TITLE
Retrieve "Regulators" and "Targets" information from SGD for gene page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#644]
We need to retrieve the "Regulators" and "Targets" information from SGD for the Regulation section of the gene page.

**Comment by kdahlquist** [comment]
This is on the back burner while final look and feel tweaks are being completed and tests are written.

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/40755358-0927b7c8-6433-11e8-8234-038d067a3f35.png)
My mistake...

**Comment by kdahlquist** [comment]
Here is the link to the API documentation again: http://github.com/yeastgenome/SGDBackend-Nex2/blob/master/docs/webservice.MD

**Comment by dondi** [comment]
Marking as priority 0 because this will be in @johnllopez616's next PR.

**Comment by dondi** [comment]
Verified, data loads.
