### ISSUE TITLE
Prepare for release of v3.1.0

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#646]
We have as our goal to produce a release to master on Friday to close off the summer work.  That release will be v3.1.0.  Today, we need to scope out what will be included in the next release and tag the issues with the "for next release" label.  We need to leave enough time so that all the release preparation steps can be comfortably completed on Friday.  The release needs to be clean in the sense of no new bugs and the features are in a good state.

**Comment by kdahlquist** [comment]
- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [ ] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [ ] the [featureList.json](https://github.com/dondi/GRNsight/blob/beta/documents/developer_documents/testing_script_generator/featureList.json) file should be updated
    - [ ] the new feature also needs to be added to the [Pull Request Checklist](https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist)
- [ ] Test the candidate build (typically the `beta` branch)
- [ ] Merge the branch(es) under development (typically `beta`) into `master`
    - [ ] Resolve any version control conflicts
    - [ ] Test the final merged version
    - [ ] Perform hotfixes on `master` as needed
- [ ] Update README.md at top-level directory of master branch, if necessary
    - [ ] Update Travis and Coveralls badges to reference the master branch
- [ ] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [ ] Update version numbers in _package.json_
    - [ ] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [ ] Create draft release item on Github repository (name it exactly like the tag)
    - [ ] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [ ] Publish GitHub release item
- [ ] Publish release to GRNsight home page
    - [ ] Refresh (pull) the `master` clone on _grnsight.cs.lmu.edu_
    - [ ] Update the version number and modification date on `gh-pages`
    - [ ] Update the About page with release notes (GitHub release item without issue numbers)
        - [ ] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [ ] Update modification date
    - [ ] Add news item about the release to the News page
        - [ ] Update modification date
        - [ ] Link news item to the corresponding release notes in the About page
    - [ ] Update Documentation page with any new features or updates to old features
- [ ] Increment beta version
    - [ ] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [ ] Update version number and modified date on `gh-pages`
    - [ ] Update Travis and Coveralls badges to reference the beta branch
    - [ ] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [ ] Publish to _npm_ (`npm publish`)
    - [ ] _npm_ requires all `.0`s in the semantic version
    - [ ] Check to see that BioJS updates its GRNsight entry
- [ ] Update version number/other relevant information at current bioinformatics listing sites
    - [ ] Elixir 
        - [ ] Then change hyperlink on the GRNsight Links page, if necessary
- [ ] Get DOI for new release from Zenodo
    - [ ] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [ ] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [ ] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by kdahlquist** [comment]
Note that since we made a few more changes, master will be v3.1.3

**Comment by dondi** [comment]
Very odd—I could have sworn that BioJS updates itself automatically, but for this release it seems severely out of date (2.1.11), with no obvious way to update versions. It makes me wonder whether BioJS has reset itself somehow, to some outdated backup archive. Will monitor to see if it refreshes.

**Comment by kdahlquist** [comment]
It looks like they have a summer of code student(s) redoing the website.  See the blog at  http://biojs.net/

Maybe we should check back in a month or two.

**Comment by kdahlquist** [comment]
The unresolved BioJS issue has been moved to it's own issue, so closing this one. #668
