### ISSUE TITLE
@johnllopez616 needs to write an abstract for SURP

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#647]
To fulfill his SURP contract, @johnllopez616 needs to write an abstract about the summer work he has completed.  He should write it on the wiki and have a draft ready on Thursday, May 31.  @kdahlquist and @dondi will then review so it is completed by Friday.

**Comment by kdahlquist** [comment]
@johnllopez616 and I have finished the abstract.  It is available here: https://github.com/dondi/GRNsight/wiki/John-Lopez-2018-SURP-Abstract.

**Comment by kdahlquist** [comment]
Forgot to say,  @dondi, please review.

**Comment by dondi** [comment]
@johnllopez616 @kdahlquist I just read it, and it looks good. There is a slight redundancy of wording in the last two sentences around the words "feature" and "available" but isn't a big deal. One way to remove it is to combine the sentences:
> This new feature enables users to easily access information about the genes to facilitate biological interpretation of the GRN data, and is available in GRNsight version 3.1.0 at http://dondi.github.io/GRNsight.
I'm good whether this revision is included or not.

**Comment by kdahlquist** [comment]
I went ahead and added it, you changed my abstract golf score from 250 to 248 :)
