### ISSUE TITLE
Sigma Xi conference on Big Data and the Future of Research, October 25-28

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#650]
The Sigma Xi conference in the fall will be on Big Data and the Future of Research.  They have a student poster session as part of the conference.  The conference will be October 25-28 at the San Francisco Hyatt near the SFO airport.  This seems like a good venue to present GRNsight/GRNmap.

Abstracts are not due until September 28, but the early bird registration deadline is June 30.

@kdahlquist will look into getting costs covered, but needs to know who is interested in going.

https://www.sigmaxi.org/meetings-events/annual-meeting-and-student-research-conference/student-research-conference

**Comment by johnllopez616** [comment]
I am interested in attending this

**Comment by kdahlquist** [comment]
@mihirsamdarshi also wants to go.

**Comment by kdahlquist** [comment]
@kdahlquist is not going to be able to go to this after all.  However, if students want to go, she can assist with asking for money from the appropriate sources.
