### ISSUE TITLE
Tweaks to look and feel of gene page - part 2

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#653]
The previous issue, #620 on this was getting too unweildy with multiple check lists.  I have closed that issue and pulled over the remaining issues here.

- [x] Still need to reduce white space on left side.  Top looks good, but space could be smaller on left.  See About and News page for guide, about 0.5 cm.  Note that the spacing looks good when I reduce the window, but not when the window is maximized. _Confirmed completed in beta v3.0.16 by @kdahlquist_
- [ ] The cookie banner is underneath a white box, it should be on top. This is still there.  See screenshot in #620. _I am going to give this its own issue; we'll leave it alone for now_
- [x] All hyperlinks on page need to be green GRNsight color.  This includes the citations (e.g., <sup>[1]</sup>) and the GO IDs. _Confirmed complete in beta v3.0.15 by @kdahlquist._
- [x] The JASPAR citation in the Sources section is shifted out of alignment to the left from the other four sources. _Confirmed complete in beta v3.0.15 by @kdahlquist._
- [x] In the Protein Information section, "Protein Type" should simply be "Protein". _Confirmed complete in beta v3.0.15 by @kdahlquist._
- [x] In the General Information section, "Family" should be "JASPAR Family" and "Class" should be "JASPAR Class". _Confirmed complete in beta v3.0.15 by @kdahlquist._
- [x] In the Regulation section, let's comment out the "Regulators" and "Targets" fields and we'll work on retrieving this info in the Fall. #644 _Confirmed complete in beta v3.0.15 by @kdahlquist._
- [x] Can we size the accordian section bars to be a little smaller, like the size they are for the News and About pages on the main site? _confirmed completed in beta v3.0.16 by @kdahlquist_
- [x] The section titles on the accordian section bars need to have underlines like in the main GRNsight News and About pages. _Confirmed complete in beta v3.0.15 by @kdahlquist._
- [x] The text in the actual sections needs to be aligned on the left with the section title on the accordian bars.  Again, see the News and About pages.  This probably means that the titles need to move a little to the left and the text in the section needs to move a little to the right.  Actually, the buttons look to be about the right size and spacing for the text, as compared to the News and About pages. _Confirmed complete in beta v3.0.15 by @kdahlquist._
- [x] When you mouseover a hyperlink, it currently shifts to a blue color, it should shift to the purple color like on the main GRNsight site. _confirmed complete by @kdahlquist in beta v3.0.16._

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/40755298-bcbb94cc-6432-11e8-9c56-e953228b9455.png)
 
Shoot, I already got the Regulators and Targets...

**Comment by kdahlquist** [comment]
That's OK, let's just comment them out for now.  I'm going to ask for a lot of tweaks to this and I'd rather not do it in a rush.

**Comment by kdahlquist** [comment]
I reviewed the tweaks.  See my notes on the first comment in this thread; I added one more "to do".

**Comment by johnllopez616** [comment]
Changes should be finished and will be ready by tomorrow morning's PR

**Comment by kdahlquist** [comment]
Last remaining issue will be moved to its own issue.
