### ISSUE TITLE
Gene page accordian open/close issue

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#654]
Moving this one over from #620 to its own issue.

If you click on a button at the top of the page and that section is already open, it actually closes. The correct action would be for it to simply shift the page down to the open section.

**Comment by johnllopez616** [comment]
Upon investigation, it would seem that the collapse() functionality of the bootstrap accordion acts as a state change, changeable by both the buttons AND the links on the page. To accomplish this desired functionality would require us to modify this state change, or possibly the implementation of our own collapsible accordion. Will examine further in the Fall.

**Comment by johnllopez616** [comment]
I believe I have accomplished desired functionality! Will display next meeting!

**Comment by dondi** [comment]
@johnllopez616 will polish off the work for this issue then issue a PR on it.

**Comment by johnllopez616** [comment]
@dondi Verified the accordion works as should. Closing issue.
