### ISSUE TITLE
Refactor the gene pages with respect to gh-pages and the iframes

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#658]
I've opened this issue to capture a discussion between @mihirsamdarshi, @johnllopez616, and @kdahlquist.  @mihirsamdarshi suggested refactoring the gene pages in jade and rework how the iframes were implemented to make the styling issues to make the gene pages look more like the main GRNsight website easier to do.  We decided not to do this at this late date in the sprint, but to revisit in the Fall.

**Comment by dondi** [comment]
Next PR of @johnllopez616

**Comment by dondi** [comment]
Almost there, but with some loose ends:
* LMU logo appears to have a different width
* Space between sidebar and main content needs to match main page
* Gene name should be fully right-justified (i.e., its container should span the entire content area)

**Comment by kdahlquist** [comment]
To clarify what @dondi said above:

* It is the species name that needs to be right-justified, the gene name is left-justified.

**Comment by dondi** [comment]
@johnllopez616 did some work here but has not yet issued a pull request because it turned out that his approach works only in Chrome. He has come up with a new approach that should improve consistency, and will aim to complete that work this week.

**Comment by kdahlquist** [comment]
@johnllopez616 has restructured the gene page to be identical to the rest of the GRNsight pages.  The three specific bullets from before have been addressed:
* LMU logo appears to have a different width
* Space between sidebar and main content needs to match main page
* Species name should be fully right-justified (i.e., its container should span the entire content area).

A new issue has cropped up with the menu at the bottom of the page not being centered, but a new issue will be created for that.
