### ISSUE TITLE
Gene information page cookie banner is underneath a white box

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#665]
Gene information page cookie banner is underneath a white box.  Moving this to its own issue to be resolved in the Fall.

**Comment by dondi** [comment]
The cookie banner should not even appear in the gene page to begin with, so @johnllopez616 will track the JavaScript that invokes this banner, and remove it solely for the header iframe in the gene page.

**Comment by johnllopez616** [comment]
Modified the 'onlyheader.html' file in 'gh-pages' to remove the cookie banner. @dondi verified that this solution works. Closing issue.
