### ISSUE TITLE
Fall 2018 GRNsight meetings on Thursdays 1:30-2:30?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#671]
For this Fall, we will have joint GRNmap and GRNsight meetings with @dondi, @bengfitzpatrick, @kdahlquist, @mihirsamdarshi, @johnllopez616, @jtorre39, @lkelly9, and a new student joining the GRNmap data analysis team, Jazmin Quezada.

We will be meeting in LSB 118.  Our first meeting will be on the first Wednesday of the semester, August 29.  All meetings will be in the LSB 118 conference room.

**Comment by johnllopez616** [comment]
Got it, will see you  guys there at 12:30 next Wednesday!

**Comment by kdahlquist** [comment]
@johnllopez616 has requested to move the meetimg. I believe that Thursdays 1:30 - 2:30 would work. Will @johnllopez616 and @mihirsamdarshi , please confirm?

**Comment by kdahlquist** [comment]
Would @dondi be able to host meetings in his office on Thursdays?

**Comment by lkelly9** [comment]
Hi,

Unfortunately I have lab on Thursdays from 1-4:50pm.

Thank you,
Lauren

**Comment by mihirsamdarshi** [comment]
I have a work shift scheduled until 2, I would be able to make it after that

**Comment by kdahlquist** [comment]
@lkelly9 , the Thursday time was only meant for the GRNsight team.

**Comment by lkelly9** [comment]
Got it! My mistake

**Comment by dondi** [comment]
Yes the GRNsight one can be in my office.

**Comment by mihirsamdarshi** [comment]
Wait I’m sorry just to clarify do we have two meetings a week this semester?

**Comment by kdahlquist** [comment]
No. I was trying to just have one joint lab meeting on Wednesday, but John asked to move it. The Thursday time is the only one available due to class schedules, I didn't know you were working at that time.

So, we are splitting the lab meetings and it looks like you can only make part of it. GRNsight on Thurs and GRNmap on Wed.

Scheduling is complicated, sigh.

**Comment by kdahlquist** [comment]
Thanks, that is very helpful.

**Comment by kdahlquist** [comment]
So we are settled on Thursdays at 1:30 in @dondi's office. @mihirsamdarshi, @johnllopez616, and Justin will all be meeting.  I'm closing this now.
