### ISSUE TITLE
Any questions about SGD or Yeastmine?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#672]
The whole SGD team is here at the conference I am at.  Does @dondi , @mihirsamdarshi , or @johnllopez616 have any questions that I could ask them directly? Or feature requests or issues?

**Comment by dondi** [comment]
No questions that I could think of. @mihirsamdarshi and @johnllopez616 please chime in when you can. It’s a great opportunity, while @kdahlquist has in-person access to them.

**Comment by kdahlquist** [comment]
I spoke to the head API programmer, Travis Sheppard (could not figure out his Github hsndle) last night. He says that anything displayed on the web site should be accessible by API, but admitted that the documentation was hard to find/not up to date.

Here is link to their md version of the docs on Github.

I have an idea if we can grab the data for the network graphs they display on their pages, we could grab the data and display it automatically with GRNsight. 

yeastgenome/SGDBackend-Nex2/blob/master/docs/webservice.MD

**Comment by kdahlquist** [comment]
Quick question, does node-xlsx also export to Excel or does it just read from it?

**Comment by dondi** [comment]
@kdahlquist node-xlsx can both read and write Excel workbooks: https://www.npmjs.com/package/node-xlsx (note the "Building xlsx" examples halfway down the page)

I haven’t tried it myself so this is solely going on what the documentation is saying.

**Comment by kdahlquist** [comment]
This can be closed.
