### ISSUE TITLE
@kdahlquist giving Biology Department seminar on Friday, 9/14/18, 2:00PM, LSB Auditorium

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#673]
Please come to my Biology Department seminar on Friday, 9/14/18, 2:00PM, LSB Auditorium.

Title:  From the lac operon to the spaghettiome, what can we learn from modeling gene regulatory networks on a medium scale?

**Comment by dondi** [comment]
The seminar has been presented so closing this issue.
