### ISSUE TITLE
Incorrect JASPAR data lingering in gene page

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#679]
If I load a dummy network in to beta with gene names that are not real genes (A, B, C), and open the gene page, there is lingering data from JASPAR that should not be there.

Under General Information it says:
JASPAR ID: MA0265.1

A sequence logo and frequency matrix (presumably from that ID shown above) is also displayed.

I'm attaching the file I used to trigger this.
[A-B-C_network.xlsx](https://github.com/dondi/GRNsight/files/2444096/A-B-C_network.xlsx)

Instead, "Not found" should be displayed.

**Comment by kdahlquist** [comment]
Even though we have a kind of solution to this, I'm going to leave it open so that @johnllopez616 can go back and fix the queries as discussed in the previous comment.

**Comment by dondi** [comment]
@dondi's commit comment can be found here: https://github.com/dondi/GRNsight/commit/c36323dbf9539b6f0fe5cdf8f9ccece80aaa6f86

Also @johnllopez616 let's shadow you the next time you refresh beta, in order to see what the gap in the documentation might be which is preventing successful refreshes.

**Comment by kdahlquist** [comment]
@dondi commented on the commit with specifics, but what we want you to do is search for the `name` in the API request itself, not in the results that come back from a general search.

Please let us know if you have questions.

After we get the JASPAR query cleaned up, we are going to need to review the API requests for the other databases to make sure that they are not falling into this trap as well.  Furthermore, we see that the species (taxon id for _Saccharomyces cerevisiae_) is hard coded into the JASPAR query.  We are going to need to write a functionality so that the species is dynamically filled by whatever is found by the UniProt query.  Separate issues will be opened for each of these issues.

**Comment by johnllopez616** [comment]
Changes reflected in PR #702

**Comment by kdahlquist** [comment]
PR #702 will be updated with final changes requested by @dondi.  We will be able to close this issue when the changes are up on beta and @kdahlquist can review.

**Comment by dondi** [comment]
This is now running on beta 3.1.8 where the following issues are observed:
![image](https://user-images.githubusercontent.com/382242/48585090-6800c780-e8e0-11e8-8756-82dfc3bec348.png)
That is an apparent 400 on Ensembl and 503 on Jaspar. Let's focus on tracking down these errors before closing this issue.

**Comment by johnllopez616** [comment]
I will investigate this during my next work session using `curl` requests.

**Comment by johnllopez616** [comment]
Made some discoveries regarding this API call as documented on #696 . As of 11/28/18, the Jaspar 503 status seems to have resolved itself on beta and my local branch.

**Comment by kdahlquist** [comment]
This issue is closable. The discussion about Ensembl is moved to #696.
