### ISSUE TITLE
Investigate writing tests for gene pages using SinonJS framework

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#682]
Elevating this to its own issue because it got buried in #621.

@johnllopez616 will begin investigating the process for writing tests, particularly those involving the API calls. He should read up on the [SinonJS](http://sinonjs.org) framework, as suggested by @dondi.

**Comment by johnllopez616** [comment]
Pull Request Checklist
- [ ] Travis C.I. build passes
- [ ] All four Demos look as expected when loaded
- [ ] Reload works as expected
- [ ] Loading file with Error brings up error modal, and it looks as expected
- [ ] Loading file with Warning brings up warnings modal
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF and GraphML
- [ ] Print works as expected
- [ ] Restrict graph to viewport works as expected (check/uncheck)
- [ ] Viewport Size Changing works as expected (small/medium/large/fit)
- [ ] Toggle between Grid Layout and Force Graph Layout works as expected
- [ ] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [ ] Enabling and disabling node coloring works as expected
- [ ] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [ ] Weighted graph loaded with the "default to black edges" option checked appears as expected
- [ ] Hide/Show Weights works as expected (always/never/upon mouseover)
- [ ] Edge Weight Normalization Factor can be changed (set/reset)
- [ ] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [ ] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [ ] D-pad left/right/top/bottom/center works as expected
- [ ] Zoom slider changes number and has effect on graph (viewport and menu)
- [ ] Right click on a node opens gene page, page is populated with correct data

**Comment by johnllopez616** [comment]
Work on this has begun and will be on a separate branch

**Comment by johnllopez616** [comment]
Writing tests have begun on branch `johnlopez-api-tests`. Still working to configure the tests. Might need _some_ reconfiguration or restructuring of the APIs. Will discuss further in today's meeting.

**Comment by johnllopez616** [comment]
Will investigate further over the weekend in a two hour work session

**Comment by kdahlquist** [comment]
@johnllopez616 is going to meet with @dondi to get unstuck on this.  Specifically, he has un-hardcoded the species name/taxon from the API queries, but he needs to write the tests before he can do the PR.

**Comment by kdahlquist** [comment]
I forgot to ask in today's meeting: did @dondi and @johnllopez616 meet to work on this?  Have the tests been written?

**Comment by johnllopez616** [comment]
Met with @dondi today and set up the work environment for the tests. Dondi and I determined that the way forward would be to create stubs for all of the API functions to create mock API data, and test the function that populates the gene page by collecting all of this mock data from different mock sources.

**Comment by johnllopez616** [comment]
Progress has been made! I spent the work session _successfully?_ completing the tests for the UniProt API Call! I would like to go over what I did with @dondi on Tuesday before I move on to doing the other tests to ensure that I am indeed writing it correctly.

**Comment by dondi** [comment]
@johnllopez616 has made good progress at getting accustomed to Sinon. Upon deeper inspection of the code being tested, it looks like Sinon fake servers are the better mocking mechanism than stubs. After learning a bit about fake servers, @johnllopez616 can work with @dondi in a future session to insert a fake server into the gene API code.

**Comment by johnllopez616** [comment]
I was not able to make much progress with this portion, but I began to put together a basic template for the fake server. I am presently 2 hours behind of the 4 hours of commitment, so I wanted to let @dondi and @kdahlquist that I fell behind for the sake of academic integrity. Additionally, I need to schedule a time to meet with @dondi regarding the fake servers, since that did not happen this week.

**Comment by johnllopez616** [comment]
Spent last week's work session working on this, discovering the functionality of Sinon's servers and how it works. Will need more time. I caught up an additional hour so now I'm at a one hour deficit.

**Comment by johnllopez616** [comment]
After three unsuccessful work session attempts to create this, I want to seek the help of the entire GRNsight team for this task. Therefore, I would like to show everybody where I'm at.

Before the last work session, I had the following set up as my test for the API call with the fake server, abiding by the sinon documentation seen [here](https://sinonjs.org/releases/v7.3.1/fake-xhr-and-server/)
```
 describe("getUniProtInfo", () => {

// final result is a promise
// call this with known input
// part of what the function needs is a network request, alongside the query -
// tell fake server "idc who asks, make this response"
// mocks return the data ONLY IF the correct parameters are supplied
// set up fake server to only return happy answers with expected URLS and fail everything else

    let server;
    beforeEach(() => {
      server = sinon.createFakeServer();
    });
    
    const query = {
      symbol: "YHP1",
      species: "Saccharomyces_cerevisiae",
      taxon: 12345
    }
    const results = "{matrix_id : 69}";
    
    
    
    it("Make the correct calls", done => {
      const url = serviceRoot + "/uniprot/uploadlists/?from=GENENAME&to=ACC&format=tab&taxon=559292&query=YHP1"
      server.respondWith("GET", url, [
      200,
      {"content-type": "application/json"},
      '[{ "id": 12, "comment": "Hey there" }]']);
      
      let callback = sinon.spy()
      global.window.api.getUniProtInfo(query, callback);
      server.respond();
      
      console.log(callback);
      
      sinon.assert.calledWith(callback, [{ id: 12, comment: "Hey there" }]);
      server.restore();
      done();
    }) 
  });
```

When I run this, it results in the following error:
<img width="570" alt="Screen Shot 2019-04-16 at 1 21 58 PM" src="https://user-images.githubusercontent.com/21348600/56241554-fd001c00-604a-11e9-857c-98a091b7889e.png">

I spent this week's work session trying another API to create a fake server, known as  [nock](https://semaphoreci.com/community/tutorials/mocking-external-http-requests-in-node-tests-with-nock). I created a basic test for a the url to see how a working 'nock'  call operates as seen here. It works fine.
```
describe('fetch test', ()=> {
   
   let spy;

     before(() => {
       nock("https://www.uniprot.org")
       .get("/uploadlists/?from=GENENAME&to=ACC&format=tab&taxon=559292&query=YHP1")
             .reply(200, { events: ['foo'] })
      spy = sinon.spy(global.window.api, "getUniProtInfo");
    });

     after(() => {
       nock.cleanAll()
       global.window.api.getUniProtInfo.restore();
     });

      
      it('should get events', () => {
          return fetch("https://www.uniprot.org/uploadlists/?from=GENENAME&to=ACC&format=tab&taxon=559292&query=YHP1")
              .then(response => {
                
                return response.json()
              });
              .then(json => {
              
              console.log(spy.wrappedMethod);
                  expect(json.events[0]).to.equal('foo')
              });
      });
});
 
```

However, when I try to test getUniProtInfo, done in the following code, I recieve a seperate error:
```
 
 describe('fetch test', ()=> {
    before(() => {
      nock("https://www.uniprot.org")
      .get("/uploadlists/?from=GENENAME&to=ACC&format=tab&taxon=559292&query=YHP1")
            .reply(200, { events: ['foo'] });
    });

    after(() => {
      nock.cleanAll()
    });

    it('should get events', () => {
      
      const YHP1 = {
        symbol: "YHP1",
        species: "Saccharomyces_cerevisiae",
        taxon: "559292",
      };
        return global.window.api.getUniProtInfo(YHP1) 
            .then(response => {
              console.log(response.json());
              return response.json()
            })
            .then(json => {
              console.log(json.events);
                expect(json.events[0]).to.equal('foo')
            })
    })
})
```

<img width="570" alt="Screen Shot 2019-04-16 at 1 21 58 PM" src="https://user-images.githubusercontent.com/21348600/56242129-6af91300-604c-11e9-8a4f-e7afdec4e156.png">

**Comment by dondi** [comment]
The overall structure of the first attempt looks right except for this:
```javascript
    global.window.api.getUniProtInfo(query, callback);
```

The `getUniProtInfo` function only takes _one parameter_ (https://github.com/dondi/GRNsight/blob/johnlopez_api_tests/web-client/public/gene/api.js#L50) and so the above call essentially disregards `callback` entirely.

The key here is to realize that `getUniProtInfo` returns a promise (`$.get`) and the way to attach a follow-up function to that is:
```javascript
    global.window.api.getUniProtInfo(query).then(callback);
```

That is one definite issue. A second issue is that this is asynchronous, so doing an assert right after this call is not guaranteed to take place after `callback` is invoked. To get around this, it is probably best to not use a spy but to simply assert the value:
```javascript
    global.window.api.getUniProtInfo(query).then(function (data) {
        // Assert _here_ that `data` is what you expect it to be.
        done();   // <---- this is provided by the test framework.
    });
```

**Comment by johnllopez616** [comment]
After an additional two hours of trial and error, I have crafted this piece of code to display what passes in the harness. The changes have been pushed to the 
johnlopez_api_tests` branch. To say that it works, however, would not be correct. 
```
 describe("getUniProtInfo", () => {
    let server;
    beforeEach(() => {
      server = sinon.createFakeServer();
    });
    
    afterEach(() => {
      server.restore();
    })
    
    const query = {
      symbol: "YHP1",
      species: "Saccharomyces_cerevisiae",
      taxon: 12345
    }
    
    
    
    it("Make the correct calls", done => {
      const url = serviceRoot + "/uniprot/uploadlists/?from=GENENAME&to=ACC&format=tab&taxon=559292&query=YHP1"
      
      server.respondWith('GET', url, [
        200,
        {'Content-Type': 'application/json' }, '[{ "id: 1"}]'])
        
      global.window.api.getUniProtInfo(query).then((data) => {
        expect((data).toJSON()).to.equal([{id: 2}]); //this shouldn't work but does
        done(); //calling this doesn't prohibit the timeout from occurring 
      })
    done(); //this is the done() that prohibits the timeout from occuring 

  });
});
```
The first thing I would like to point out is that the `done()` call within the `getUniProtInfo()` call is not what prevents the `Timeout of 2000ms error`, typical of testing asynchronous functions, from occurring. Instead, the `done()` call outside of the function is what does it.

The second, and most important thing I would like to point out, is that the `expect()` call, designed to be incorrect, does not throw a failing test when the harness runs. Instead, it passes as if it were to give the correct information.

With two hours left of work to do before the meeting, I will see if an opportunity was had to respond to this. I am, once again, stuck on this issue. In addition, with two hours left to work on this issue before the meeting, and a single work session remaining before the last week of school, I wanted to ask if it was at all possible to be assigned to another issue. I believe that working on this portion of GRNsight is not working out for me and that I'd like to move on to something else in the project, for the remaining time that I'm here. I have tried my best to work on these tests, but I feel like a flailing fish out of water. Thus, @dondi and @kdahlquist , I would like to know that I can do that would best benefit the project for the remaining time I'm here.

**Comment by dondi** [comment]
Sorry I couldn't get to this until now. I think this is quite close, actually.

The thing I notice right away is that the fake server isn’t being set to auto-respond. By default, the fake server does not send a response until the code tells it to via `server.respond()`.

However, it can be unwieldy to keep calling `server.respond()` for every request that we make. Sinon provides for this via a property you can set on the fake server:
```javascript
    server.respondImmediately = true;
```
So, try adding that to `beforeEach`.

I can see a few more loose ends to tie up if `respondImmediately` does the trick for invoking the `then` callback, but let’s get past this first.

**Comment by dondi** [comment]
P.S. For reference, here is the information on `respondImmediately`: https://sinonjs.org/releases/latest/fake-xhr-and-server/#boolean-respondimmediately

**Comment by dondi** [comment]
@johnllopez616 To summarize the discussion from today's meeting, you are very close to finishing this test, needing these remaining tasks:
- Modify the first fake server response to actually return something that the code expects (see a real-world response for specifics)
- Add a second fake server response for the _xml_ request that the function makes at the very end

**Comment by johnllopez616** [comment]
After working with @dondi last night on this issue via slack, I was able to create a simple test. I would like to spend a bit more time working on a few more tests, even though this next meeting session will be our last.

**Comment by johnllopez616** [comment]
As mentioned in PR #748 , I have created basic API tests for each of the functions.

**Comment by kdahlquist** [comment]
backlogging all gene page issues
