### ISSUE TITLE
Having node coloring and formatting of edge weights based on values disabled, and selecting grid layout causes graph to malfunction.

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#687]
As identified by @mihirsamdarshi and I, if you have the following selections, in this order, it causes the graph to cease existing for weighted graphs:
(1) Node Coloring is disabled
(2) Grid Layout is selected
(3) Disable Formatting of Edge Weights Based on Values

**Comment by kdahlquist** [comment]
Yikes!  Hopefully this can be tackled with the refactor.

**Comment by kdahlquist** [comment]
Checked this on beta 3.1.12, and what happened to demo file 2 is that HMO1 dislodged from the grid and floated around, while the rest of the nodes stayed fixed in place.

**Comment by mihirsamdarshi** [comment]
@dondi I am having a little trouble attacking this one because I am not sure where to start, especially because only one node in particular is being affected

**Comment by kdahlquist** [comment]
Have you tried a non-demo file to see what happens?  Like a "toy" file, for instance?

**Comment by dondi** [comment]
Keep me posted, I can look whenever you need to pass it along.

**Comment by dondi** [comment]
Based on my initial triage, it looks like "Disable Formatting of Edges Based on Weight Values" is sufficient to trigger anomalies. The problem varies depending on the file loaded, but so far, something goes wrong any time that this option is chosen.

Based on this, it looks like a deep dive into just the code for this option is called for next. I’ll report back as I find things out.

**Comment by dondi** [comment]
OK, I think I found the issue. A proposed fix can be found in https://github.com/dondi/GRNsight/pull/761

**Comment by mihirsamdarshi** [comment]
Thanks @dondi, that fix was useful

**Comment by kdahlquist** [comment]
The series of actions reported at the top of this comment thread no longer triggers any problems, so I'm closing this one.
