### ISSUE TITLE
When sequence logo is not found on gene page, don't display the "image not found" box

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#691]
When a JASPAR sequence logo image is not found because there is no JASPAR data to display, the browser shows an image box for the not found image.  We want to get rid of this box and just have it say "Not found" in text.

**Comment by johnllopez616** [comment]
I believe I have corrected this issue. Will show at the next pull request

**Comment by kdahlquist** [comment]
Fixed in beta 3.1.7
