### ISSUE TITLE
Review API query for UniProt

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#694]
TODO: review API query for UniProt

**Comment by johnllopez616** [comment]
What are the details?

**Comment by kdahlquist** [comment]
We'll talk about it at the next meeting after #679 is fixed.

**Comment by kdahlquist** [comment]
@johnllopez616 will copy the API call out of the code and paste it as a comment to this issue for @kdahlquist to review.

**Comment by johnllopez616** [comment]
```
let getUniProtInfo = function (geneSymbol) {
    return $.get({
        url: serviceRoot + "/uniprot/uploadlists/",
        data: {
            from: "GENENAME",
            to: "ACC",
            format: "tab",
            taxon: "559292",
            query: geneSymbol,
        },
        dataType: "text",
        timeout: 5000,
    }).then(function (data) {
        const regex = new RegExp(geneSymbol + "[ \t\r\n\v\f]*([A-Z0-9]+)", "gm");
        const id = regex.exec(data)[1];
        return $.get({
            url: serviceRoot + "/uniprot/uniprot/" + id + ".xml",
            timeout: 5000,
        });
    }).fail(function () {
        return $.get(this);
    });
};
```

**Comment by johnllopez616** [comment]
Turns out changing the species is as simple as providing the taxon ID.
`    let taxon = "559292";
    return $.get({
        url: serviceRoot + "/uniprot/uploadlists/",
        data: {
            from: "GENENAME",
            to: "ACC",
            format: "tab",
            taxon: taxon,
            query: geneSymbol,
        },
        dataType: "text",
        timeout: 5000,
    }).then(function (data) {`

**Comment by johnllopez616** [comment]
When the taxon Id is changed to that of humans (9606), and a human gene is provided, you get the following, working results:
![image](https://user-images.githubusercontent.com/21348600/49561074-286b4100-f8ca-11e8-9b40-551574ea2a45.png)

**Comment by kdahlquist** [comment]
What happens if you use taxon ID 4932 for yeast?

**Comment by johnllopez616** [comment]
There's no data for taxon 4932:

No data displayed by the query:
![image](https://user-images.githubusercontent.com/21348600/51866812-c98cdb80-22fe-11e9-9c26-72294b552072.png)

It makes an API call, but the result is blank:
![image](https://user-images.githubusercontent.com/21348600/51866874-f5a85c80-22fe-11e9-902b-71d76a2c933e.png)

**Comment by kdahlquist** [comment]
We will need some code to provide the taxon ID expected by UniProt for yeast.  See also:  https://github.com/dondi/GRNsight/wiki/Web-API-Guide
