### ISSUE TITLE
Write function to dynamically populate species id in API queries

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#698]
Upon review of the JASPAR API query, it was found that the taxon ID for yeast is hard-coded into the query.  To make the gene pages more generic for species other than yeast, we will need to set up some code that allows the species to be discovered via the UniProt query, like it is for naming the species at the top of the page, and then dynamically populate the other queries.

**Comment by johnllopez616** [comment]
I would like to discuss this tomorrow in detail because I have several questions as to how this would work. What if the UniProt API is not functioning? Would this new code resort to Saccharomyces cerevisiae as a default? Moreover, what if it is a gene like ACE2, which is found in both humans and yeast?

**Comment by kdahlquist** [comment]
That way information is captured in the network object and can be exported (like what @jtorre39 is working on).

**Comment by dondi** [comment]
After today's meeting, the sequence of recommended tasks:
1. @johnllopez616 completes review of UniProt, NCBI, and JASPAR to verify the ability to unhardcode species from each of their APIs
2. IF review fails, we need to determine reliable ways to unhardcode species for each database
3. If review succeeds (except Ensembl), we have a decision point on whether to unhardcode first vs. to solve Ensembl first (probably for next semester).

**Comment by johnllopez616** [comment]
Looks like it's quite possible to un-hardcode  UniProt, NCBI, and JASPAR. 

It seems that UniProt and JASPAR require an organism's taxon while NCBI and Ensembl use an organism's species name. However, using an NCBI function as described in (#697), it's possible to get that as long as NCBI is operating.

**Comment by kdahlquist** [comment]
Let's keep in mind for later that we could ask the user for the taxon ID directly or we could ask them for the species name or both.  We might move the species look-up function that you have made to the point when we are asking the user for the species instead of at the point of opening the gene page.

**Comment by kdahlquist** [comment]
*@kdahlquist needs to review whether we will keep ensembl as a data source.
*@kdahlquist will define where the species will live in the GRNmap workbook, so then it can be parsed and added to the GRNstruct.
*@johnllopez616 will start work on un-hardcoding the species from the API calls.

**Comment by johnllopez616** [comment]
Spent a 2 hour work session on 1/16/19 allowing data from graph.js to be sent to the gene page for construction. So far, the gene name and taxon is a hardcoded value in graph.js but is passed to the gene page. The only visible change would be the url for the gene page now has a query for species name and taxon, instead of just gene symbol. Is this something you would like to see in a pull request, or should we wait until the entire gene symbol is unhardcoded for the PR?

**Comment by dondi** [comment]
This is a good intermediate step. Let's work toward making the species name or taxon ID a gene page parameter then take it from there.

One question for @kdahlquist is whether we can get away with standardizing on just one or the other. They are somewhat redundant and ideally we have a single value.

**Comment by kdahlquist** [comment]
To answer @dondi, we are probably going to need an internal converter in our code.  From what @johnllopez616 found out, some API's are using species name and others are using taxon ID (at least that's what I remember).  It would be better (and less ambiguous) if they used taxon ID, but I don't know if that's possible for all the databases.

Another wrinkle is bacterial (and other species) that have substrains with different taxon IDs.

In terms of specifying in the GRNmap input workbook, we can certainly say the user has to use the taxon ID.  

If we want to force the user to use it upon file upload, we can ask for the ID and maybe provide a link for them to look it up if they don't know it or something.  Just a thought.

**Comment by kdahlquist** [comment]
To record discussion from today, @johnllopez616 will work on closing other API issues before tackling this one.  Note that once we start work on this we will tackle the case of the xlsx input workbook first.

We may end up having a "favorites" list of a dozen species or so that a user can choose from and if their species isn't on the list, then they can type in the taxon ID.

**Comment by johnllopez616** [comment]
@johnllopez616 Note to self: add “review requested”
