### ISSUE TITLE
Nodes go slightly over edge when "Restrict Graph to Viewport" and "Fit to Window" is selected

### ISSUE THREAD

**Issue by jlopez616** [dondi/GRNsight#700]
While testing for PR #692, I noticed that, as you can see in the image below, when the "Restrict Graph to Viewport" and "Fit to Window" options are selected, and a node is pushed to the right, it goes slightly past the viewport.

I tested this on beta, and the same results apply.

![image](https://user-images.githubusercontent.com/21348600/48169720-2ef5a100-e2a9-11e8-9343-f317ad4a4fda.png)

This was discovered on through the 21-genes_31-edges_Schade-data_input.graphml file.

**Comment by kdahlquist** [comment]
I have confirmed this behavior.  It is not just when "Restrict Graph to Viewport" is selected.  There is no "white space" boundary between nodes and and the right edge of the bounding box/viewport that is noticeable when Fit to window or small or medium is selected.

**Comment by kdahlquist** [comment]
Duplicate with #444. I closed that one and kept this one.  See that issue for any further relevant notes.

**Comment by igreen1** [comment]
I can fix this issue easily by moving the right boundary. The calculation for the boundary doesn't account for the slight padding within the node. See commit b68595c from igreen1 branch.

However, the issue in #444 is more difficult. Working on that :)

**Comment by igreen1** [comment]
After some issues with branching, @igreen1 issued a solution to this bug with commit #1498514. Note, that #1498514 is after the commits for #444, as its parent is #639acc4. So, if the fixes for #444 are rejected, @igreen1 will rebase to #b68595c.

Review requested :)

**Comment by kdahlquist** [comment]
Verified that this is fixed in beta v4.0.21.  Closing.
