### ISSUE TITLE
iFrame Menu at Bottom of Gene Page is still not aligned to where it needs to be

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#701]
Contrary to the closure of issue #689, the iFrame at the bottom of the gene page is cut off from the left. I have displayed it in the image below.

![image](https://user-images.githubusercontent.com/21348600/48171620-aa5b5080-e2b1-11e8-908b-83061befea88.png)

**Comment by johnllopez616** [comment]
![image](https://user-images.githubusercontent.com/21348600/48173464-b0a0fb00-e2b8-11e8-8d51-58c94d68422c.png)

As of now, I can achieve the following desired bottom display, which differs from the display on the main GRNsight website.

Is it absolutely imperative that it must align precisely with what is on the GRNsight page? I understand that it is best practice to have things synchronized with each other. However, in your opinion, would this be acceptable?

![image](https://user-images.githubusercontent.com/21348600/48173489-d0d0ba00-e2b8-11e8-9137-5d5178b46c23.png)

**Comment by johnllopez616** [comment]
Changes reflected in PR #702

**Comment by johnllopez616** [comment]
In order to achieve the desired effect, several changes were made in gh-pages via the following commit: https://github.com/dondi/GRNsight/commit/e2531fa30cdb5b9fc5c78a41217d60e3d0332a29

**Comment by kdahlquist** [comment]
looks good on beta 3.1.8
