### ISSUE TITLE
Gene page navbar links cannot be accessed

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#704]
As identified with @dondi at the last meeting, the implementation of the `z-index` style change put the gene page in a state where the user cannot access the gene page navbar. I will investigate and correct during my next work session.

**Comment by johnllopez616** [comment]
By removing the z-indexes from the iFrames, seen in PR #705 ,I have resolved the issue created from PR #702. I have verified the solution works on Chrome, IE, and Firefox, while avoiding any overlapping style issues.

**Comment by kdahlquist** [comment]
The PR #705 has been approved, let's get it up on beta so that @kdahlquist can review.  We would like to be able to close this one by the end of the semester.

**Comment by kdahlquist** [comment]
Beta has not yet been refreshed with PR #705, so my review of this issue is still pending.

**Comment by kdahlquist** [comment]
Fixed as of beta 3.1.9
