### ISSUE TITLE
Normalization factor not chosen correctly by GRNsight

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#708]
I've been making figures of DB1-DB6 using GRNsight and I have discovered that there is a bug with the way the edge weight normalization factor is chosen by GRNsight.  

The way it is supposed to work is that the highest magnitude weight is used as the normalization factor.  Since the highest magnitude could be either negative or positive, it should be looking at the absolute value of the weights to determine this.  For example, if the largest magnitude positive weight is "5" and the largest magnitude negative weight is "-6", the normalization factor should be "6".

However, right now, in that situation, GRNsight is choosing "5" instead.

This will need to be fixed as a high priority in the Spring semester.

**Comment by kdahlquist** [comment]
For an example input workbook, try
[15-genes_28-edges_db5-BK-dHAP4-fam_Sigmoid_estimation_output.xlsx](https://github.com/dondi/GRNsight/files/2654491/15-genes_28-edges_db5-BK-dHAP4-fam_Sigmoid_estimation_output.xlsx)

The largest positive weight is 3.224297 and the largest magnitude negative weight is -4.04334.  GRNsight is choosing 3.22... as the normalization factor when it should be choosing -4.04...

**Comment by mihirsamdarshi** [comment]
addressed by PR #749

**Comment by kdahlquist** [comment]
This is not fixed in beta 3.1.17; it might actually be more broke than it was before.

Take a look at the attached file which has just two weights in it's network_optimized_weights sheet.   The positive weight is "1.5" and the negative weight is "-10"  There are two phenomena to fix:
1. The 1.5 weight should be a thin red arrow and the -10 weight should be a thick blue blunt-end edge.  However, the two edges have the same thickness.
2. If you look at the value displayed in the edge weight normalization factor field, it says 1.5.  If I delete the 1.5, then 10 shows up underneath (gray).

[test-normalization-value.xlsx](https://github.com/dondi/GRNsight/files/3230053/test-normalization-value.xlsx)

**Comment by mihirsamdarshi** [comment]
I have diagnosed the problem and it will be fixed in the next PR

**Comment by kdahlquist** [comment]
This one is fixed in beta 3.1.21. Closing.
