### ISSUE TITLE
Release 3.1.9

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#710]
- [ ] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [ ] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [ ] the [featureList.json](https://github.com/dondi/GRNsight/blob/beta/documents/developer_documents/testing_script_generator/featureList.json) file should be updated
    - [ ] the new feature also needs to be added to the [Pull Request Checklist](https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist)
- [ ] Test the candidate build (typically the `beta` branch)
- [ ] Merge the branch(es) under development (typically `beta`) into `master`
    - [ ] Resolve any version control conflicts
    - [ ] Test the final merged version
    - [ ] Perform hotfixes on `master` as needed
- [ ] Update README.md at top-level directory of master branch, if necessary
    - [ ] Update Travis and Coveralls badges to reference the master branch
- [ ] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [ ] Update version numbers in _package.json_
    - [ ] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [ ] Create draft release item on Github repository (name it exactly like the tag)
    - [ ] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [ ] Publish GitHub release item
- [ ] Publish release to GRNsight home page
    - [ ] Refresh (pull) the `master` clone on _grnsight.cs.lmu.edu_
    - [ ] Update the version number and modification date on `gh-pages`
    - [ ] Update the About page with release notes (GitHub release item without issue numbers)
        - [ ] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [ ] Update modification date
    - [ ] Add news item about the release to the News page
        - [ ] Update modification date
        - [ ] Link news item to the corresponding release notes in the About page
    - [ ] Update Documentation page with any new features or updates to old features
- [ ] Increment beta version
    - [ ] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [ ] Update version number and modified date on `gh-pages`
    - [ ] Update Travis and Coveralls badges to reference the beta branch
    - [ ] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [ ] Publish to _npm_ (`npm publish`)
    - [ ] _npm_ requires all `.0`s in the semantic version
    - [ ] Check to see that BioJS updates its GRNsight entry
- [ ] Update version number/other relevant information at current bioinformatics listing sites
    - [ ] Elixir 
        - [ ] Then change hyperlink on the GRNsight Links page, if necessary
- [ ] Get DOI for new release from Zenodo
    - [ ] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [ ] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [ ] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by johnllopez616** [comment]
Pull Request Checklist
- [ ] Travis C.I. build passes
- [ ] All four Demos look as expected when loaded
- [ ] Reload works as expected
- [ ] Loading file with Error brings up error modal, and it looks as expected
- [ ] Loading file with Warning brings up warnings modal
- [ ] Import works for both SIF and GraphML
- [ ] Graph can be exported to SIF and GraphML
- [ ] Print works as expected
- [ ] Restrict graph to viewport works as expected (check/uncheck)
- [ ] Viewport Size Changing works as expected (small/medium/large/fit)
- [ ] Toggle between Grid Layout and Force Graph Layout works as expected
- [ ] Force Graph Parameter Sliders change the number above them and have an effect on the graph
- [ ] Locking/Unlocking/Resetting/Undo Resetting the force graph parameters works as expected
- [ ] Enabling and disabling node coloring works as expected
- [ ] Node coloring options work as expected (selection top/bottom dataset, averaging values, changing max value)
- [ ] Weighted graph loaded with the "default to black edges" option checked appears as expected
- [ ] Hide/Show Weights works as expected (always/never/upon mouseover)
- [ ] Edge Weight Normalization Factor can be changed (set/reset)
- [ ] Gray Edge Threshold can be changed, slider changes the number and has an effect on the graph
- [ ] Checking Show Gray Edges as Dashed works as expected (check/uncheck)
- [ ] D-pad left/right/top/bottom/center works as expected
- [ ] Zoom slider changes number and has effect on graph (viewport and menu)
- [ ] Right click on a node opens gene page, page is populated with correct data

**Comment by kdahlquist** [comment]
@johnllopez616 found a bug on beta that prevents a release this semester.  I'm going to close this for now and when we are ready for a release next semester, we will open a new issue.
