### ISSUE TITLE
Spring 2019 Conferences

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#712]
Happy New Year!  The following are conferences that are happening during the Spring 2019 semester.  Each student will present at the LMU Undergraduate Research Symposium and 1-2 outside conferences.

* LMU Undergraduate Symposium is Saturday, March 23th, 2018, Abstracts due: Friday, February, 8, 2019, 5:00pm
* Southern California Systems Biology Conference, UC Irvine, February 9, Abstracts usually due the week before
* WCBSURC: U. San Diego; conference April 6, 2019, Abstracts usually due about a month earlier
* TriBeta Western District II Convention: University of San Francisco, April 13, 2019, Abstracts usually due about a month earlier
* SCAS (Southern California Academy of Sciences): Cal State Northridge; May 3, 2019, Abstracts likely due end of March

I would recommend the SoCal Systems Biology Conference because it will have a great line-up of faculty speakers with an informal poster session at the end.

**Comment by kdahlquist** [comment]
@mihirsamdarshi wants to go to the SoCal Systems Biology conference, as well as the LMU (and maybe one other).
@johnllopez616 and @afiller1 will do the LMU conference.

**Comment by kdahlquist** [comment]
@mihirsamdarshi will send me an abstract for the SoCal Systems Biology Conference on Thursday.

@johnllopez616 and @afiller1 will have an abstract ready for the LMU symposium by next Tuesday's meeting, 2/5/19.

**Comment by mihirsamdarshi** [comment]
@kdahlquist the draft of the abstract has been added to the wiki page

**Comment by kdahlquist** [comment]
@mihirsamdarshi, I've looked at your abstract and have a few comments:
* Check the spelling of "refactor" in the title :)
* Our color scheme is now red/blue instead of magenta/cyan
* Say a little more about node coloring, it is not entirely clear that it is the nodes that are colored and how that works.
* Name the version of the software

We'll do a final pass-through at the meeting on Tuesday and submit.

**Comment by kdahlquist** [comment]
Also, @mihirsamdarshi , please list the co-authors on your abstract (with middle initials).  Thanks.

**Comment by johnllopez616** [comment]
@kdahlquist The first draft of @afiller1 ‘s and my abstract is on the wiki page

**Comment by kdahlquist** [comment]
@mihirsamdarshi, I've asked @dondi to review the MVC description.  There are some minor wordsmithing changes I will make here and there.  The major thing I see missing is any mention of the gene pages.  If there is time, I would replace the section on "Improved Developer Tools and Testing" with a description of the gene pages.  Let me know if you have time this morning for this.  If not, I can give it a shot myself.

**Comment by mihirsamdarshi** [comment]
@kdahlquist I cannot believe I forgot about that new feature. I am currently in class until 12:30, however I can work on it afterwards.

**Comment by mihirsamdarshi** [comment]
@kdahlquist I have revised the poster and it is up again.

**Comment by kdahlquist** [comment]
LMU Symposium abstracts were submitted last week.  De-prioritizing this issue until it is time to prepare poster/talk in March.

**Comment by johnllopez616** [comment]
I spent today's work session working on the poster for the symposium. Which branch should I upload it? It's presently stored on `johnllopez616`, does it need to be placed in beta or master?

**Comment by mihirsamdarshi** [comment]
@johnlopez616 master under documents > presentations

**Comment by afiller1** [comment]
I have uploaded the revised version of our Symposium poster.

**Comment by kdahlquist** [comment]
Final versions of poster and talk are in the documents folder on the master branch.  Congrats!
