### ISSUE TITLE
@afiller1 will update wiki on setting up her laptop with the GRNsight project

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#715]
After getting herself set up to run GRNsight, @afiller1 will update the wiki with instructions.

**Comment by afiller1** [comment]
@kdahlquist @dondi I updated almost all of the files under the "Instructions and Tutorials" category in the Wiki with more detailed instructions that would have been helpful when I was going through it all for the first time. In some, I just added a sentence here or there, but I did the most editing in the "Getting Started" page. It would be great if Dondi could look through and make sure I didn't misspeak anywhere on these pages. And Dr. Dahlquist, you can go through and see if the instructions make sense to someone downloading the content onto their machine. Let me know if I need to improve anything.

**Comment by kdahlquist** [comment]
Do we need to check the library dependencies here:  https://github.com/dondi/GRNsight/wiki/Library-Requirements

to make sure that our internal documentation is consistent?

**Comment by dondi** [comment]
Wiki review can be considered closed but a new issue will be opened for library version review.
