### ISSUE TITLE
Replace Ensembl link with directly-synthesized URL

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#718]

**Comment by kdahlquist** [comment]
Out of the suite of issues opened today, this one seems like a good place for @johnllopez616 to start.

Make sure that this change doesn't break the gene page and it can be it's own PR.

**Comment by johnllopez616** [comment]
Implemented a working solution in PR #726

**Comment by kdahlquist** [comment]
Ensembl link confirmed.
