### ISSUE TITLE
Store species name and taxon in GRNstate and display/configure as needed

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#719]

**Comment by kdahlquist** [comment]
This is being broken out from #698, and is also related to #720.  This current issue stores the data in GRNstate and then displays it for the user (in a yet to be determined place in the UI).  Other issues need to be tackled first.

**Comment by kdahlquist** [comment]
@johnllopez616 will work with @mihirsamdarshi to figure out how to store this in the GRNstate this week.

**Comment by johnllopez616** [comment]
Worked on this, this week. Changes reflected in PR #738

**Comment by dondi** [comment]
This is nearly done; @johnllopez616 just needs to move the speciesInfo object that is currently hardcoded into the `genePageInfo` function so that it resides in `grnState` instead. `genePageInfo` gets rewritten to return the value in `grnState`. Once this is done, future UI or import code would then simply populate `grnState.speciesInfo` and the gene page should follow suit.

**Comment by johnllopez616** [comment]
Changes should be reflected in PR #738, which somehow had its deployment lost in the shuffle of Symposium prep

**Comment by johnllopez616** [comment]
Spent last week's work session completing this. I should get the final approval from @dondi at today's meeting to move forward with its corresponding PR, #738

**Comment by mihirsamdarshi** [comment]
this should be closed as it has been implemented in beta

**Comment by kdahlquist** [comment]
@mihirsamdarshi, I don't think this is something I can check, since it is invisible to the user, right?  As long as you can see the appropriate behavior of the code, you can go ahead and close this.
