### ISSUE TITLE
Create and maintain a curated species name-to-taxon table

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#721]

**Comment by kdahlquist** [comment]
@kdahlquist will curate the list of supported species and the corresponding taxon IDs that work with UniProt and JASPAR.

**Comment by kdahlquist** [comment]
As noted in the meeting, I will add species to this comment as I have time.  Starting out with yeast:

* Uniprot expects taxon ID 559292 for yeast, while JASPAR expects taxon ID 4932 for yeast.
*  The reason for the discrepancy is that 4932 refers to ''Saccharomyces cerevisiae'', but 559292 is for ''Saccharomyces cerevisiae'' S288c.
* Therefore, in our list, we need to have both IDs.  They will be interchangeable for users, but the software needs to know which one to use for Uniprot or JASPAR.  See issue #723 (which is currently closed).

**Comment by kdahlquist** [comment]
* _Homo sapiens_, taxon ID 9606 (human)
* _Drosophila melanogaster_, taxon ID 7227 (fruit fly)
* _Caenorhabditis elegans_, taxon ID 6239 (nematode worm)
* _Mus musculus_, taxon ID 10090 (house mouse)
* _Arabidopsis thaliana_, taxon ID 3702 (thale cress)

**Comment by kdahlquist** [comment]
Rat seems to have the same issue that yeast does
* _Rattus rattus_, taxon ID 10117 (black rat): used by JASPAR
*_Rattus norvegicus_, taxon ID 10116 (rat): used by Uniprot

Let's hold off on Rat until I can do some more investigating.  The other ones above seem OK, though

**Comment by kdahlquist** [comment]
I think this issue can be closed after we do some testing to make sure that gene information retrieval works for the other species besides yeast.

**Comment by kdahlquist** [comment]
I'm closing this one, test of input workbooks is in issue #720.
