### ISSUE TITLE
Prune undisplayed values from API responses

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#722]

**Comment by johnllopez616** [comment]
Implemented these changes during work session on 2/18/19. Changes will be available in next PR

**Comment by kdahlquist** [comment]
State which PR this is in, please.

**Comment by johnllopez616** [comment]
Should be fixed following PR #731 , can @dondi confirm?

**Comment by dondi** [comment]
Yes, this was noted on code review but I forgot to update the comment.
