### ISSUE TITLE
Regulators and Targets are displaying improperly

### ISSUE THREAD

**Issue by johnllopez616** [dondi/GRNsight#730]
Found this bug while working on #722 , the Targets are not being displayed at all, and the regulators have repeating values. Gonna try to fix before the next PR

**Comment by johnllopez616** [comment]
Fixed it, will be available in the next PR

**Comment by kdahlquist** [comment]
Say what PR it is in, please.

**Comment by johnllopez616** [comment]
Confirmed fixed in beta following PR #731 , closing.
