### ISSUE TITLE
Allow sheet names to be case-insensitive on Excel input workbooks

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#732]
A user in the Biomathematical modeling course reported that an input workbook with a worksheet called "Network" instead of "network" would not display in GRNsight.  We should allow the worksheet names to be case-insensitive.

**Comment by kdahlquist** [comment]
This came up for three students in the 2019 BioDB course.  I believe @mihirsamdarshi put a fix for this in PR #807 or #806.  

However, I want to make sure that the we don't just address the "network" sheet, but that we address the other sheets in a GRNmap workbook.  I also want to make sure that the appropriate tests are in place.

Note that when we _export_ to a GRNmap workbook, we need to enforce the lower case of the sheet names because the GRNmap software will not be robust to changes in case.

In some sense, GRNsight becomes a workbook validator because a user could import it to GRNsight and then export it to correct any simple mistakes like this before inputting into GRNmap.

**Comment by mihirsamdarshi** [comment]
Fixed in PR #806, including with tests

**Comment by kdahlquist** [comment]
This is fixed for the specific case of the "network" sheet.  However, this leaves open the issue of case-sensitivity/insensitivity for the other worksheets.

For example, if I take a GRNmap output workbook and change the "network_optimized_weights" sheet to "Network_optimized_weights" sheet, then the latter is not recognized by GRNsight and it loads an unweighted graph.

I am going to close this one and start another issue about this.
