### ISSUE TITLE
Refactor node coloring to fit new MVC paradigm

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#735]

**Comment by dondi** [comment]
To address the data set dropdown question, the notion of "Same as Top Dataset" can be isolated to the view level. Let grnState store the dataset names directly, but upon updating the views, if top and bottom are the same, the dropdown can show "Same as Top Dataset".

**Comment by kdahlquist** [comment]
@mihirsamdarshi, this is done, right?  If so, please close.
