### ISSUE TITLE
On beta 3.1.11, slider lock check box is not working

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#736]
On beta 3.1.11, slider lock check box is not working; can't review #592 until this is fixed.

**Comment by dondi** [comment]
After some triage, we were able to find the root cause (interference by code later in the function). @mihirsamdarshi will enforce the "single source of truth" purpose of `grnState` to make sure that the state of the lock checkbox always follows what `grnState` says that should be.

**Comment by dondi** [comment]
Code appears to be done but not released to beta. May require a new release so that the issue can be closed.

**Comment by dondi** [comment]
Fixed on beta 3.1.13.
