### ISSUE TITLE
BIOL 588 capstone paper

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#741]
Opening this issue to record feedback on @mihirsamdarshi's capstone paper.  @kdahlquist is reviewing the results section and has the following feedback:

I think that the results need to be re-organized and expanded as follows:
* The section should begin with a description of the current features of GRNsight v3.x.x.  What you have as figure 5 is great for a poster where there is limited space, but it can be expanded.  I believe I gave you the Powerpoint with the series of screenshots highlighting the new features in GRNsight v3.x.x.  You can use those figures, 2 to a page (one top, one bottom) to run through the new features, instead of compressing them into one.  Those would replace what you currently have as figures 2-5.  Then in the text, you would describe what the features are briefly, with a bit of an expanded explanation of the ones you directly touched, which is what you currently have in the "Visualization Improvements" section.
* The next thing you would explain is the architecture of v1.x.x.  You can use Figure 1 from the GRNsight PeerJ Computer Science paper.  It has a DOI, so you can directly cite it.
* With those two pieces in place, you can then explain the rationale for the refactor.    I'm thinking that you need your current Figure 1, but that you also need to integrate it with the architecture figure from the PeerJ paper so that we can see how the new paradigm changes things.
* You are describing a lot of files in the text.  It would be also helpful to see this in a diagram.
* You are talking about the file structure, but I'm not sure this is the same thing as "architecture".

I marked up the hard copy and it is pinned to the bulletin board outside my office door.

**Comment by kdahlquist** [comment]
@mihirsamdarshi, would you please upload your most recent draft of your paper, concatenated together as one document?  I have time today to look at it and won't have another chance until Thursday of next week.  As it is due as week from Friday, I want to give you feedback on this, your penultimate draft.

**Comment by mihirsamdarshi** [comment]
@kdahlquist the paper has been pushed to the master branch.

**Comment by kdahlquist** [comment]
Got it.  I should have feedback on it for you later today.  Don't forget that you need to write an abstract.

**Comment by kdahlquist** [comment]
@mihirsamdarshi, your paper with comments is ready to be picked up.  I've pinned it to the bulletin board outside my office door.

**Comment by kdahlquist** [comment]
Final paper can be found here: https://github.com/dondi/GRNsight/blob/master/documents/reports/Samdarshi_Mihir_2019/Samdarshi_2019_Final.docx
