### ISSUE TITLE
Buggy Workbook from BIOL 388 has multiple issues

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#742]
One of the GRNmap output workbooks displayed multiple bugs in the visualization; beta v3.1.12 behaved the same as master v3.1.3 with regard to these bugs.

To reproduce the behavior:
1. upload this file: 
[dZAP1_GRNmap_Input_Workbook_ET_output_edited.xlsx](https://github.com/dondi/GRNsight/files/2933280/dZAP1_GRNmap_Input_Workbook_ET_output_edited.xlsx)
2. change the bottom dataset for node coloring to wt_optimized_expression.  You will see that the color overlays the label of the nodes and that some of the nodes are not even displaying the wt_optimized_expression data.
3. Click "grid layout".  The nodes don't layout in a grid, instead they cluster toward the center of the viewport and black stripes appear on the nodes.  If you click and drag a node, black fills in the arcs made by edges.

**Comment by kdahlquist** [comment]
I made a "clean" version of the buggy workbook from scratch and re-ran it through GRNmap.  I am attaching it here for reference.  It works fine in GRNsight.  I found one more potential problem in the buggy workbook, two of the expression worksheets had "3" instead of "30" for one of the timepoints.  There may still be more errors, though.
[16-genes_19-edges_ET_20190307_Sigmoid_estimation_output.xlsx](https://github.com/dondi/GRNsight/files/2942819/16-genes_19-edges_ET_20190307_Sigmoid_estimation_output.xlsx)

**Comment by kdahlquist** [comment]
Gave the file that triggered the original comment a whirl in beta 3.1.22, but it still is buggy.  Not a priority for now.

**Comment by Onariaginosa** [comment]
I tested this in beta and the original workbook fails to load due to many errors in various sheets. The clean version of the buggy workbook only displays a species warning. I tried recreating the bug with the clean workbook, but the bug does not appear. This issue appears to have been resolved at some point.

**Comment by dondi** [comment]
We saw this together at the meeting at are good with the behavior.
