### ISSUE TITLE
Check this input workbook, does not load anything

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#747]
Check out this workbook, generated in the BIOL 388 course this semester.  It has a "network" worksheet, but no graph loads and no error or warning is given.

Whatever the problem is with the formatting, it should at least throw an error.  Investigate further later.

[BIOL388_S19_microarray-data_dZAP1_AK.xlsx](https://github.com/dondi/GRNsight/files/3168375/BIOL388_S19_microarray-data_dZAP1_AK.xlsx)

**Comment by kdahlquist** [comment]
Looks like this one crashed beta.  @mihirsamdarshi is restarting it right now.

**Comment by mihirsamdarshi** [comment]
@dondi this one is interesting because the graph loads on my localhost server, however it does seem to work on the actual GRNsight website

**Comment by mihirsamdarshi** [comment]
@kdahlquist this file fails because it is nearly 5 MB large. That is too large for the server-hosted version of GRNsight to handle, although I am unsure of the largest size GRNsight is capable of.

**Comment by kdahlquist** [comment]
Closing this one because #766 was opened.
