### ISSUE TITLE
iframe scroll bar issues

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#750]
I'm bringing this over from issue #559 and is related to issue #477.

I'd like us to examine what actions trigger the scroll bars, so that we can figure out how to reduce or eliminate them.

As noted in #477, at some point in the era of @NAnguiano, the "medium" designation for the viewport fit exactly on my monitor.  However, it no longer does so, and scroll bars are present.  This might have something to do with our expanded sidebar of options, but ideally on the "medium" setting, I'd like the viewport to fit entirely on my monitor without scroll bars.

As noted in #559, a slightly different issue is a user expectation that when you click "Fit to window" when your browser is small, the user is expecting it to fit, but id doesn't.  To truly fit it, we'd probably have to zoom in at the same time.

**Comment by mihirsamdarshi** [comment]
@kdahlquist are you using the Firefox browser? (related to #477)

**Comment by kdahlquist** [comment]
Yes.

**Comment by mihirsamdarshi** [comment]
ok, would you mind using a different browser to test that? I believe that bug is browser-specific, and I think there is a fix specifically for Firefox

**Comment by kdahlquist** [comment]
If I open GRNsight beta in Chrome, it detects "medium" size, but it still has a vertical scroll bar on the right side of the iframe.  This is the default view, I haven't loaded anything yet.

**Comment by mihirsamdarshi** [comment]
is the scroll bar within the iframe, or the window itself?

**Comment by kdahlquist** [comment]
It's the iframe, not the browser window I'm talking about.  Screen shot below:

![image](https://user-images.githubusercontent.com/6463867/58349385-f0c06900-7e17-11e9-9af8-d2d69a74de71.png)

**Comment by kdahlquist** [comment]
Upon playing with this some more, if I select "Fit to Window" before loading a graph, the viewport fits to my window properly.  However, once I load a graph, I get both vertical and horizontal scroll bars in the iframe.  I can understand why the vertical scroll bar is there, it is to accommodate all the sidebar options.  However, there should be no reason why there is a horizontal scroll bar because the width of the viewport should not have changed.

However, as seen in this screen shot, it looks like the viewport did get larger by about a half centimeter on the right.  If you look at the top where the menu bar ends, the viewport is extending past the menu bar by about half a centimeter.

![image](https://user-images.githubusercontent.com/6463867/58726101-af8b0480-8395-11e9-9539-a25065485801.png)

**Comment by dondi** [comment]
Some progress made here and preset sizes appear to work better on my branch. Fit-to-window needs a little more work though.

**Comment by dondi** [comment]
Fit-to-window (finally) potentially addressed. Will be testable in next beta.

**Comment by kdahlquist** [comment]
Verfied fixed--I'm so happy!
