### ISSUE TITLE
If you change the "Gray Edge Threshold" the Zoom level resets itself.

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#751]
If you change the "Gray Edge Threshold" the Zoom level resets itself.  Bug reported by @qlanners in the 2017 BioDB class. #559.

**Comment by mihirsamdarshi** [comment]
this has been resolved in my latest PR #749

**Comment by kdahlquist** [comment]
So you tested all other features and they don't reset the zoom?

**Comment by mihirsamdarshi** [comment]
no zoom reset happens upon modulation of any feature now

**Comment by kdahlquist** [comment]
Awesome!  I put review requested so we can test once the new PR is up.

**Comment by kdahlquist** [comment]
Verified fixed in Beta v3.1.17.
