### ISSUE TITLE
When show all edge weights is checked, the edge weights might overlap

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#752]
As reported by @ArashLari in the 2017 BioDB Week 9 assignment, when show all edge weights is checked, the edge weights might overlap.  It would take some doing to make this not happen, but I wanted to record this as an issue. #559.

**Comment by dondi** [comment]
Degree of difficulty is relatively high, based on these factors:
1. Shifting edge weights to behave as nodes will require deeper changes to the graph algorithm
2. Edge weights are further constrained by their associated edges

Will lower the priority and revisit when higher-priority issues are addressed.

**Comment by kdahlquist** [comment]
Backlogging this issue.
