### ISSUE TITLE
When node coloring data doesn't exist in a spreadsheet, other features break

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#753]
Most notably, grid layout doesn't work because the drawGraph function looks for expression data to parse

**Comment by mihirsamdarshi** [comment]
Just fixed, will push to a new PR

**Comment by mihirsamdarshi** [comment]
this one should be reviewed and closed soon

**Comment by kdahlquist** [comment]
I made a simple 3 node network with just a "network" sheet and this seemed to be OK.  I tried going back and forth between grid layout and force graph layout.  Closing.
