### ISSUE TITLE
Default force graph slider charge value is off in beta

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#758]
When I load the GRNsight master page, the default force graph slider values are set at:
* 500 for link distance
* -50 for charge

When I load the GRNsight beta page (v3.1.17), the force graph slider values display as:
* 500 for link distance
* -1000 for charge

Then, when I load a graph, the charge slider jumps to "-50" and the graph behaves as if this is the value it is using.

So, the charge slider needs to be set to "-50" when the page is loaded and before a graph is displayed.

Also, if I then reload a page in the browser, the slider bar stays in the "-50" position, but the numerical display goes back to "-1000".

**Comment by mihirsamdarshi** [comment]
issue fixed, will be in PR #757

**Comment by kdahlquist** [comment]
Beta 3.1.21 has multiple issues with sliders.  I can't say for sure, but it looks like the charge/link distance that are actually applied does not match the slider values.  The reset button is not working...

@mihirsamdarshi, let's meet up when you get to campus today.

**Comment by mihirsamdarshi** [comment]
Fixed the issues in my branch, will be added in next PR

**Comment by kdahlquist** [comment]
Closing this one because the default values are correct, but will open a new one to report a bug.
