### ISSUE TITLE
Log Fold Change Max Value field should only accept positive values

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#759]
This is a bug/feature request.  Currently, the Log Fold Change Max Value field has a label that says "(-100 - 100)" and it allows a user to type a negative number in the field (or use the arrows to select a negative number).  This does not really make sense since you are putting in a "max" value; it should only allow values between 0 and 100 and should be labeled as such.  The lower bound is automatically the negative of whatever the upper bound is, we don't allow an asymmetric scale around 0.

Right now, if you put a negative number in, it flips the color scale so that negative values are red and positive values are blue.  I think this is confusing.

Also, if you use the up or down arrows to select a number, it will let you scroll past 100 (or -100 for now), but then when you release the mouse button, it will revert back to 100 (or -100).  It should just stop scrolling at 100 and not let you go past.

**Comment by mihirsamdarshi** [comment]
fixed in PR #757

**Comment by kdahlquist** [comment]
There is still some strange behavior on this one.
* I can type a negative number into the field and click on "Set", for example, I tried -200.
* When I click "Set", the value displaying in the field changes to "0"
* But, the color legend then changes to -200 to 200 as the range of values, and the node coloring itself changes to that scale.
* So the value in the field is behaving as we would want, but the actual node coloring functionality is not.
* If I go outside the range on the positive side, it basically does the same behavior.  The number in the field reverts to 100, but the scale and the node coloring display as what I typed in there.
* I note that as I put larger and larger numbers in there, it pauses to think about it for several seconds before it displays anything.

Second issue:
* I think our lower bound needs to be a small, but nonzero number, like 0.01.
* If you type 0 and "Set", all the nodes change to dark red because the range is from 0 to 0.  If the lower bound is 0.01, then at least the negative fold changes will be dark blue, instead of them all being red. 
* If I do type 0.01 into the field and "Set" it seems to work properly, but since the scale does not support decimal places, it looks like the scale is going from zero to zero.
* Also, if you type 0 and "Set", the color scale goes away.

**Comment by mihirsamdarshi** [comment]
@kdahlquist I don't understand why it would be appropriate to allow values under 1 at all?

**Comment by kdahlquist** [comment]
A log fold change of 1 is actually a 2-fold change, a log fold change of 0.25 is approximately a ~1.2 fold change (20%).  So if you had a range of -0.25 to 0.25, you would be showing the effect of small changes. 

Admittedly the changes are small, but they can exist and maybe someone has a need for that.

**Comment by mihirsamdarshi** [comment]
Fixed in my branch, will be issued in the next PR

**Comment by kdahlquist** [comment]
This particular issue is fixed, but I identified a new one, which I will document in a different issue.  Closing this one.
