### ISSUE TITLE
Clicking Grid Layout changes force graph slider values back to their defaults

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#760]
Clicking the Grid Layout button changes the force graph slider values back to their defaults, even if I have changed them.  The slider values should be left alone.

**Comment by mihirsamdarshi** [comment]
Fixed in PR #757

**Comment by kdahlquist** [comment]
This appears to be fixed in beta 3.1.21, but now there are other issues with the sliders.  Closing this one, though.
