### ISSUE TITLE
Client Side Testing

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#768]
Attached are the 3 testing documents containing 20 tests each (all different) and one document containing 100 tests.

20 Test Files: 
[Test Document 1](https://github.com/dondi/GRNsight/files/3259494/GRNsight.Test.3_20.pdf)
[Test Document 2](https://github.com/dondi/GRNsight/files/3259495/GRNsight.Test.2_24.pdf)
[Test Document 3](https://github.com/dondi/GRNsight/files/3259496/GRNsight.Test.1_20.pdf)

100 Test File
[Big Test Document](https://github.com/dondi/GRNsight/files/3259499/GRNsight.Test.4_80.pdf)

**Comment by kdahlquist** [comment]
I'm going to work through as many of the tests as I can before I leave to go home today.

**Comment by kdahlquist** [comment]
I haven't found any bugs yet, but one thing I'm noticing is that we may need to update the document for which conditions trigger a graph reload.  Some things are not triggering a reload anymore (as we want).

For example, clicking the reset to the default normalization factor button no longer reloads the graph (as it should).

Another thing I'm noticing is that we should probably update our function availability table (as seen on wiki) with a longer list of functions.  Right now the table is just listing what types of graphs are loaded, but for example, the testing document is telling me to reset the force graph parameter sliders when they haven't been changed.  Essentially, we would be documenting the allowed states and actions.

**Comment by kdahlquist** [comment]
I finished going through the document: GRNsight.Test.1_20.pdf.  The way these tests were organized, it was having me click the Reset Factor button, even though it didn't instruct me to type anything in the normalization factor field.  The locking/unlocking force graph parameters check box works, but as noted in a different issue, the reset force graph parameters button is not working.  Moving on to the next document.

**Comment by kdahlquist** [comment]
I went through the document: GRNsight.Test.2_24.pdf.  I didn't quite do all the tests, but it seems like everything was behaving OK, except for the bug noted #777.

**Comment by kdahlquist** [comment]
Closing this one because #575 is what we need to do now.
