### ISSUE TITLE
Add "Last modified" date/timestamp to all GRNsight web pages

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#77]
I'd like us to add a "Last modified" date/timestamp to all of the GRNsight web pages.  Real estate-wise, it would be nice to have it appear underneath the left links sidebar.  If that doesn't work, then somewhere at the bottom of the page would be good.  See Dr. Dionisio's personal web page for an example:  http://myweb.lmu.edu/dondi/

**Comment by kdahlquist** [comment]
@mihirsamdarshi is going to investigate the use of git commit hooks to fix this.

**Comment by mihirsamdarshi** [comment]
@dondi in github, these processes are called web hooks, and there is actually a setting in the settings page of the repo where you can configure them.

**Comment by dondi** [comment]
OK, those are some good initial steps; now it is that last sentence of your comment that should either be confirmed or refuted definitively. i.e., Let’s turn that “not sure” to “sure,” one way or the other. If it works in our favor, then great, let’s implement it. If not, then we stay with the current manual protocol until another automated possibility emerges in the future.

**Comment by kdahlquist** [comment]
@dondi says:
Step 1: write a harmless script like echo a message and see if the message reliably appears upon a commit or a push
Step 2: write the script that replaces the modified date on each HTML file with the correct date

These tasks are interchangeable, it doesn't matter which one is explored first.

**Comment by kdahlquist** [comment]
@mihirsamdarshi has written some test scripts and now he will try to attach the scripts to commit hook to see if they can run automatically on commit.

When this works, will substitute another script that actually modifies the date.

**Comment by kdahlquist** [comment]
The github webhook feature is not what we want, @mihirsamdarshi can keep looking for git commit hooks.

**Comment by mihirsamdarshi** [comment]
I am learning bash scripting right now, and want to continue learning how to use it. I did find a way to run the python script via git commit hook, but as @dondi said, I should find a way to make the script run in another more open format.

**Comment by kdahlquist** [comment]
Lowering the priority on this one because we have other stuff to do.

**Comment by kdahlquist** [comment]
Moving this to the backlog and closing since we are in the practice of changing this manually.
