### ISSUE TITLE
Node coloring scale colors are reversed left to right

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#772]
Related to #759.  The scale bar that shows the color scale for the node coloring has it's colors reversed.  Red should be on the right (positive values) and blue should be on the left (negative values).  I think the nodes are being colored properly (red for + and blue for -) but the scale bar is reversed.

**Comment by dondi** [comment]
https://github.com/dondi/GRNsight/pull/780 seeks to address this. It appears to entail just a sign change.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 3.1.23.  Closing.
