### ISSUE TITLE
Reset force graph parameter button not working in v3.1.22

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#774]
Reset force graph parameter button not working in v3.1.22. Noticed when testing #758.

**Comment by mihirsamdarshi** [comment]
Tho is unexpected as it was working in my branch. I will try to fix it in the next PR.

**Comment by dondi** [comment]
@mihirsamdarshi Hold off on any work for now. I’m in the middle of looking into everything that has been tagged as `for next release`. Please keep an eye out for a new PR on Friday morning.

**Comment by dondi** [comment]
https://github.com/dondi/GRNsight/pull/780 seeks to address this issue. The problem was an `off` call in `displayNetwork` within _update-app.js_, which deactivated the `click` handler on this button. Removing that `off` call appears to eliminate the problem.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 3.1.23. Closing.
