### ISSUE TITLE
Should export to Excel be disabled for release?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#776]
Should we export the export to Excel feature for tomorrow's release?  I have no idea how fully tested it is.

**Comment by dondi** [comment]
Agreed; I will go ahead make those items invisible.

**Comment by dondi** [comment]
Rendered invisible in https://github.com/dondi/GRNsight/pull/780.

**Comment by kdahlquist** [comment]
Confirmed comlete in beta 3.1.23.  Once we do the release, I'd like to turn it back on in beta so it is available for testing.
