### ISSUE TITLE
Interaction between grid layout and lock force graph parameters

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#779]
Perform the following actions:
* lock force graph parameters
* click grid layout
* click force graph layout

The lock force graph parameters checkbox becomes unchecked.

**Comment by mihirsamdarshi** [comment]
This is a side effect of allowing the slider parameters to be saved upon changing the layout to a grid and vice versa.

**Comment by dondi** [comment]
I reinterpreted this behavior as “when using Grid Layout, force graph parameters are not applicable”—and thus, it doesn’t actually matter whether the Lock Force Graph Parameters is checked or not, as long as the other controls are disabled.

Upon taking this approach, the checkbox value now preserves its value across layout changes.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 3.1.23.  Closing.
