### ISSUE TITLE
GRNsight production and beta sites down with 502 error (bad gateway)

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#787]
As of now, the GRNsight production and beta sites are down (iframe) with a 502 error (bad gateway).  Just noticed it now when we wanted to use it, so I don't know how long it's been like this.

**Comment by dondi** [comment]
OK, thanks, I’ll look after lunch. I think it was up on Monday afternoon so something must have happened since then.

**Comment by mihirsamdarshi** [comment]
I restarted beta, there was no screen process running so it must have been shut down somehow

**Comment by dondi** [comment]
Odd, turns out the server was rebooted 20 hours ago. I’ll have to ask Masao about that. Anyway, I have restarted the prod screen now as well.

**Comment by kdahlquist** [comment]
OK, thanks!  Closing.
