### ISSUE TITLE
Can we have more vertical area in "fit to window"?

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#792]
I'm not sure whether this is a bug or a feature request.  This hearkens back to when @NAnguiano had gotten the viewport to fit perfectly to my monitor.  Right now "fit to window" maxes out the area in the horizontal direction, but it is short in the vertical direction.  If I scroll my browser to move the headers out of the way, there could be a lot more space taken up by the viewport.  See empty space below.

![image](https://user-images.githubusercontent.com/6463867/62252088-a4108580-b3a6-11e9-95eb-9b38da09b42d.png)

**Comment by dondi** [comment]
Testing on Mac Safari, Firefox, and Chrome, "Fit to Window" takes the graph region all the way to the bottom. So this looks like a bug or a browser difference issue…I’ll look into it to see if a quick resolution can be found.

**Comment by dondi** [comment]
OK, I just realized what’s happening and I think we can now call this a bug (which I can look to fix before finalizing this release). The current fit-to-window height calculation actually takes into account the vertical space above the GRNsight menu bar. i.e., if the window is scrolled all the way to the top such that the GRNsight banner is visible, the bottom of the graph viewport will line up with the bottom of the window.

However, in the screenshot, the green menu bar has been scrolled up, and thus the bottom of the graph viewport looks short.

So, just to confirm (such that I can adjust the fit-to-window height calculation properly), we want fit-to-window to adjust the graph viewport such that it spans the available height of the window when the menu bar is scrolled to the top, and not when the entire GRNsight window is scrolled to the top, right?

Or, as a third option, should "fit to window" actually be dynamic, such that the bottom of the graph viewport always stays aligned with the bottom of the window as the user scrolls up and down? i.e., the graph viewport gets taller/shorter depending on how much of the content above the green menu bar is visible?

If these descriptions aren't sufficiently clear, I can just take a stab at something and put it on beta, and we can confirm if that's the more desirable fit-to-window behavior. Bottom line is that I can see now how the expectation differs from the actual behavior, so I now know how to adjust this once we establish the desired basis for the fit-to-window height.

**Comment by kdahlquist** [comment]
Sorry for the delay--

_So, just to confirm (such that I can adjust the fit-to-window height calculation properly), we want fit-to-window to adjust the graph viewport such that it spans the available height of the window when the menu bar is scrolled to the top, and not when the entire GRNsight window is scrolled to the top, right?_

This is the option I was thinking.  I don't think we should do dynamic, I think that would be too visually confusing and potentially mess up what the user may be doing.

When I was just checking what was happening, I realize that the fix you did to get rid of the scroll bars fixed the "medium" setting so it fits my office monitor pretty good again.  So that's a plus.

**Comment by dondi** [comment]
Got it, I will adjust the height calculation accordingly and signal when it can be tried out on beta.

**Comment by kdahlquist** [comment]
This works great!
