### ISSUE TITLE
GRNsight meeting times for Fall 2019

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#795]
It's time to set the GRNsight meeting time for the Fall semester.

Looking over schedules for @mihirsamdarshi , @afiller1 , @dondi and myself, it looks like Monday or Wednesday at 3:00-4:00 would work for all of us.

Please confirm your availability and a preference for one or both of those by commenting on this issue.

**Comment by dondi** [comment]
Monday 3-4pm would be my pick.

**Comment by afiller1** [comment]
I am free for both, but I would prefer Wednesday 3-4.

**Comment by mihirsamdarshi** [comment]
Either is fine for me.

**Comment by kdahlquist** [comment]
We will do Wednesdays 3-4.  I need to reserve a room, so standby for the location of Wednesday's meeting.  We will start the first week of school on August 28.  See you then!

**Comment by kdahlquist** [comment]
I got confirmation that _all_ meetings will be in LSB 118 this semester.  I'll leave this open until the next meeting.
