### ISSUE TITLE
Numerical values don't change when force graph sliders move when no graph is loaded

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#798]
We allow users to move the force graph parameter sliders when no graph is loaded, i.e., upon initial launch of GRNsight in the browser.  However, on Beta 4.0.2, I can slide the sliders, but the numerical value doesn't change in the display.  When I load a demo, the demo loads based on the positions of the sliders (correctly) and the correct numbers do then display, they just weren't changing value until the graph was loaded.

**Comment by dondi** [comment]
@mihirsamdarshi has tracked down what's wrong and checked with @dondi on how to fix it. An approach was decided upon and @mihirsamdarshi will work on it.

**Comment by mihirsamdarshi** [comment]
Fixed in PR #796, due to be merged and in beta soon

**Comment by kdahlquist** [comment]
confirmed fixed in beta 4.0.4
