### ISSUE TITLE
Font is changed in beta 4.0.4

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#800]
The node font is now a serif font in beta 4.0.4.  Can we change it back to what it was before?

**Comment by kdahlquist** [comment]
![image](https://user-images.githubusercontent.com/6463867/65647365-533a9900-dfb3-11e9-8800-d4dc7d616db6.png)

**Comment by mihirsamdarshi** [comment]
Added fix for this, will be issued in next PR

**Comment by kdahlquist** [comment]
confirmed fixed in beta 4.0.5
