### ISSUE TITLE
When enabling colored edges after disabling, the graph does not maintain the correct normalization max

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#809]

**Comment by mihirsamdarshi** [comment]
This was fixed in PR #806. The graph was re-calculating the max weight at every re-render, which means that upon changing back to a weighted graph from an unweighted graph, it would calculate the maximum weight to be 1. I have now set the calculation pre-condition to be a new network.

**Comment by kdahlquist** [comment]
Verified that this is fixed in beta 4.0.8
