### ISSUE TITLE
keep edges within the bounding box

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#81]
The nodes are bound within the bounding box, but I've noticed that the edges are not.  For example, a node with a circular edge that is right up against the bounding box will have the circle go outside the bounding box.  Also, other types of edges can go outside the box.  See screenshot below:

![screenshot_edgesoutsideboundingbox_20140708](https://cloud.githubusercontent.com/assets/6463867/3513108/d6532564-06bf-11e4-8d3c-4f2d218ad206.jpg)

The edge between SWI6 and SWI4 at the top goes out of the box and the self-referential edge for FKH2 goes outside the box at the bottom.

**Comment by dondi** [comment]
I have implemented the addition of the radius for nodes with self-referring edges. The behavior can be reviewed upon the next beta release. Once this is QA'ed, we can close the issue.

**Comment by NAnguiano** [comment]
This has been put live on the beta. Reassigning to @kdahlquist for review.

**Comment by kdahlquist** [comment]
It looks pretty good.  I think we need to make a small adjustment, though.  I think there should be some "white space" between the edge and the bounding box so that the two don't merge into each other.

Right now in Firefox (v35) or Chrome (v39.0.2171.99 m) a couple rows of pixels of the edge disappear behind the bounding box when the self-referential edge is pushed all the way over to the right or bottom of the bounding box.  This seems to be more of an issue with the skinnier edges.  For example, the ZAP1 self-referential edge of Demo number 2 has white space on the right side of the bounding box, but not on the bottom.  But the self-referential edge of PHD1 gets hidden by quite a lot (in comparison) by the bounding box.

It's a very slight adjustment, but I think we should take the care to get this exactly right.

By the way, this issue occurs with the nodes as well.  We lose a row or two of pixels behind the bounding box when a node is pushed all the way to any of the four sides of the bounding box.  We should also have a "white space" buffer around them as well, I think.

**Comment by dondi** [comment]
I've tweaked the bounds-checking algorithm a bit to add white space plus make the spacing of self-referential edges more uniform. See how the latest version looks upon the next update.

**Comment by dondi** [comment]
Reviewed and approved...
