### ISSUE TITLE
Reload menu item doesn't appear to be working

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#815]
In beta v4.0.8, the reload menu item does not appear to be working.  For example,
1. Load a demo file
2. Select File > Reload
3. The graph should reload as if you clicked the menu item Demo > filename or File > Open > filename

If you are reloading when it is set to grid, nothing visible should happen.  However if you reload when layout is set to force graph, it should do something.

**Comment by mihirsamdarshi** [comment]
fixed
