### ISSUE TITLE
In v4.0.8, grab hand seems missing

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#816]
I'm playing around with beta v4.0.8 and the grab hand seems to be completely missing.  Is this an artifact of work on #804?

**Comment by mihirsamdarshi** [comment]
I cannot seem to replicate this in any browser

**Comment by dondi** [comment]
Replication is uncertain now; @kdahlquist will try again.

**Comment by dondi** [comment]
Can no longer replicate as of v4.0.18.
