### ISSUE TITLE
Node coloring not functional in beta v4.0.8

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#817]
Node coloring does not appear to be functional in beta v4.0.8.  Loading a demo or other file with expression data and the nodes don't get colored.

This is an argument for instituting the PR checklist again.

**Comment by mihirsamdarshi** [comment]
I cannot replicate this either, in Safari, Firefox or Google Chrome

**Comment by dondi** [comment]
This discrepancy was tracked down to running a different branch on @mihirsamdarshi's machine vs. on the server. The branch has been identified as specifically `beta`, so @mihirsamdarshi will triage and work from that point.

**Comment by mihirsamdarshi** [comment]
This was fixed, the expression data simply wasn't getting pushed to the network following the changes that would parse and check the expression data.

**Comment by dondi** [comment]
This is blocking #803 so will work on this next then go back to #803 to review how the Node section looks.

**Comment by dondi** [comment]
This should now be fixed and available in beta 4.0.10.

**Comment by kdahlquist** [comment]
Confirmed fixed and closing.
