### ISSUE TITLE
Graph does not display properly if expression data is incomplete (i.e. one node doesn't have expression data)

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#821]
First bug from the Biological Databases class, this file does not load properly:

File:
[ymesfin_Barreto_GRNmap_input_output.xlsx](https://github.com/dondi/GRNsight/files/3935459/ymesfin_Barreto_GRNmap_input_output.xlsx)
Image:
(https://github.com/dondi/GRNsight/files/3935454/ymesfin_Barreto_GRNmap_input_output.xlsx)
<img width="1306" alt="Screen Shot 2019-12-07 at 11 16 27 AM" src="https://user-images.githubusercontent.com/5462077/70379570-2bd14800-18e3-11ea-947a-bda78cc632dd.png">
The bug appears to occur in node coloring functions. In beta, the graph does not look like the above picture, but no node coloring data appears

Update: the cause of the bug in master is undetermined, but in beta this is a side effect of @afiller1's work. Expression data sheets simply do not get added to the network. I am trying to add this right now. This is a tie-in to issue #817, and further discussion of that specific bug has been moved there.

**Comment by mihirsamdarshi** [comment]
This has been fixed on my branch, the data is getting added after the error check (only in `wt_log2_expression` sheets). The demos work, but I realized node coloring does not address the case if their is expression data is incomplete (i.e. one node doesn't have expression data)

**Comment by mihirsamdarshi** [comment]
The file still has problems but the node coloring data not showing up has been updated in the appropriate issue (#817)

**Comment by mihirsamdarshi** [comment]
I believe issue #808 is related to this

**Comment by mihirsamdarshi** [comment]
I have fixed this issue in my new PR

**Comment by dondi** [comment]
@Onariaginosa actually did look at it and on her latest error handling code, a dialog does now show up reporting the error, preventing the anomalous graph state.

**Comment by dondi** [comment]
@ahmad00m will do independent verification of this behavior and report back.

**Comment by dondi** [comment]
Notes are forthcoming from @ahmad00m

**Comment by ahmad00m** [comment]
When the file was tested no graph was drawn; however, the errors that GRNsight provided were not very accurate and self contradicting. "Column A of wt_log2_expression missing one or more gene" and "Column A of wt_log2_expression have one or more extra genes".
<img width="1435" alt="Screenshot 2021-01-30 at 1 06 31 pm" src="https://user-images.githubusercontent.com/75926755/106368114-23647980-62fc-11eb-88b4-83554d97a39f.png">

**Comment by dondi** [comment]
Looks like a collaboration opportunity between @ahmad00m and @Onariaginosa to track down why the conflicting messages are appearing.

**Comment by ahmad00m** [comment]
@Onariaginosa fixed the error pertaining to this issue by changing the capitalised S in suggestedFix to lower case. I believe the issue should be fixed after her incoming pull request.

**Comment by dondi** [comment]
Ready for verification as of beta 4.0.31

**Comment by ahmad00m** [comment]
@ahmad00m reviewed the issue again on beta 4.0.31, but the conflicting messages are still showing up. I checked the excel file that was tested for this issue and I believe the issue rises because the gene names are more than those of network sheet and the gene names are replaced with numbers which causes the tests to fail.

**Comment by dondi** [comment]
@ahmad00m can show @Onariaginosa the behavior then we can determine next steps based on that triage.

**Comment by dondi** [comment]
After discussion between @ahmad00m and @Onariaginosa, it was determined that the “conflicting” messages were indeed correct because of the way the gene names were arranged.
