### ISSUE TITLE
Expression Database design

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#826]
I posted on Box the Microsoft Access database produced by the students in the Biological Databases course last semester, along with the ReadMe's written by the three groups.  The ReadMe's may not be so helpful since there weren't clear guidelines for them, but they are there.  You should have received an invite to edit to your lion e-mail address.

The idea is that there will be several type of tables:
 - several expression tables that hold the actual expression data from my lab and other published data
 - some metadata tables that describe the other data
 - a degradation rates table with degradation rates
 - a production rates table with initial guesses for production rates

the latter two are for GRNmap.

There are at least five tasks, as I see it (@dondi will help scope this for your 402)
- review the database design and finalize it
- port it to whatever is compatible with AWS
- connect it to GRNsight so it can be used to color nodes
- design a user interface so the user can choose the data they want to visualize
- be able to export to an Excel workbook in GRNmap-compatible format

**Comment by afiller1** [comment]
Wrote 402 proposal document and proposal presentation, due today (will put both into the 402 folder on master before the end of the day). Spoke with Dondi and Dr. Dahlquist about the general structure of this project, looked at the data to be used, made a calendar of tentative deliverable dates. This week, my goals are:
* check on status of AWS Educate account
* read up on RDS
* 402 assignment 1 (due next week)
* draw up database design

**Comment by kdahlquist** [comment]
redundant with #836
