### ISSUE TITLE
Lock Force Parameters does not gray out Undo Reset button

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#831]
Checking the "Lock Force Parameters" box does not gray out (make unavailable) the Undo Reset button.

Do the following:
1. Move the sliders
2. Click Reset Force Parameters button
3. Click Lock Force Parameters box
4. The Undo Reset button is still available and works when it shouldn't.

**Comment by luluriffic** [comment]
lines 262-264 in update-app.js don't function properly. possible issue in line 262: grnState in (!grnState.showUndoReset) is a constant when I believe it should be a parameter, not sure how to fix.

**Comment by dondi** [comment]
@luluriffic @Onariaginosa @igreen1 and @dondi did a brief screen share during the meeting to follow up on the lines that @luluriffic pointed out. Some prospective and promising changes were made live which @luluriffic will follow up on this week.

**Comment by luluriffic** [comment]
implemented fix discovered in previous meeting and committed changes to new branch (luluriffic).

**Comment by kdahlquist** [comment]
When pull request #881 is merged and beta updated, @kdahlquist will review.

**Comment by kdahlquist** [comment]
Confirmed that this is fixed in beta v4.0.24
