### ISSUE TITLE
Gray Edge Threshold set to 100% should make all edges gray

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#832]
When I slide the Gray Edge Threshold all the way to the right and it says 100% using demo file 2, all the edges turn gray except for one that is still red.  I think they should all be gray.

**Comment by igreen1** [comment]
Fixed in pull request from igreen1 branch #876 Awaiting review

(link since I'm not entirely sure the number is correct!)
https://github.com/dondi/GRNsight/pull/876#issue-486977387

**Comment by igreen1** [comment]
Issue resolved in beta 4.0.19, pr #876 by merging igreen1 into beta branch :)

**Comment by kdahlquist** [comment]
Confirmed fixed in Beta 4.0.19
