### ISSUE TITLE
CMSI 402 Assignments and Docs

### ISSUE THREAD

**Issue by afiller1** [dondi/GRNsight#834]
- [x] Assignment 1 due 2/3/2020.
 - [x] Requirements doc due 2/10/2020
 - [x] Assignment 2 due 2/17/2020
 - [x] Written status reports in SDF due 2/24/2020
 - [x] Software Development Plan or Software Design Description (Initial) due 3/2/2020
 - [x] Assignment 3 due 3/23/2020
 - [x] Software Development Plan or Software Design Description (Updated), Written Status Reports in SDF due 3/30/2020
 - [x] Requirments Document (Re-submit) due 4/6/2020
 - [x] ABCDR Presentations/Demonstrations [week 1] due 4/6/2020
 - [x] Written Status Reports in SDF due 4/6/2020
 - [x] Preliminary poster due 4/13/2020
 - [x] Written Status Reports in SDF due 4/20/2020
 - [x] Final demonstrations/presentations 5/1/2020

**Comment by afiller1** [comment]
I have uploaded to my folder the initial draft of my software requirements specification, if @dondi wouldn't mind giving it a look.

**Comment by afiller1** [comment]
@Kevboe and I have to prep a preliminary version of our poster for Monday. I have some small questions on that... The posters usually have lots of specifics about the background of GRNsight, with "GRNs Can be Illustrated by Directed Graphs" and GRNsight Fulfills a Specific Software Niche for Visualizing GRNs" sections, for instance. Should we keep those sections in there, or would it be more appropriate, for our 402 posters, to focus on the background of GRNsight more generally and go more in depth on our specific projects? @dondi @kdahlquist

**Comment by kdahlquist** [comment]
I would say that you need enough background to motivate why we created GRNsight in the first place.  If you are looking at the "Samdarshi-et-al_SoCalSysBio_2019.pptx" in the posters folder, the two sections you mention are a pretty small part of the poster.  You could add to the requirements that it display expression data on nodes, either user-uploaded or through your new database, and export to Excel as new features.

The top center panel needs to be reworked based on the new UI and your added features.

There is then room around the edges to explain your new features, I think.

**Comment by afiller1** [comment]
Ok. Kevin and I will be preparing a first draft of the poster this weekend, so it would be great if we could allot a few minutes in the meeting Monday to go over it!

**Comment by kdahlquist** [comment]
Yes, please upload it to the master branch documents folder as soon as it is ready and make a comment on this issue to let me know that it's there.  It will be easier for me to look at it ahead of time and have my comments prepared than to do it on the fly during the meeting.  We can definitely talk about it at the meeting, but I just want to look at it first.

**Comment by afiller1** [comment]
All documents have been completed and submitted. Requesting review to close this issue. @kdahlquist  @dondi

**Comment by kdahlquist** [comment]
There are still some documents that need to be uploaded:
 - [ ] final version of symposium presentation (if the document up there is not the final one)
 - [ ] final version of 402 presentation that you gave last friday
 - [ ] final version of poster you made for 402; the document in there still says "draft" on it.
 - [ ] might as well upload the video of the symposium presentation, if GitHub allows files that large
 - [ ] in the Box folder, I see xlsx/csv files, but not the PostgreSQL database itself.  Can you upload the final version of the Postgres database to Box?  I would then be able to open it with PGAdmin and look at it.  I can't access it easily on AWS myself.  I realize that we don't want to commit it to GitHub, but Box should be able to handle it.

**Comment by afiller1** [comment]
GitHub won't allow me to upload the symposium presentation video because it is too large. Should I put it in Box?

I'm looking for options of how to download the database... it looks like an option would be to store files on an Amazon S3? I also found a response that said to use the pg dump program? @dondi can you point me in the right direction?

**Comment by kdahlquist** [comment]
Put the video in the GRNsight folder on Box.  Let me know if there is a permission problem.

@dondi will have to weigh in, but pg dump sounds about right.

**Comment by kdahlquist** [comment]
Pasting the link to the YouTube version of the CMSI 402 talks for future reference:

https://youtu.be/j8MMqDeOjJY

**Comment by afiller1** [comment]
It may be a bit of a process to download the database because I would have to add a security group to the AWS with my computer's IP and add that security group to the database, but in order to do that I have to get some help with Masao since he's the admin. So just a warning that it might take a moment for me to figure that out/correspond with Masao.

**Comment by afiller1** [comment]
Ok I finally have the full sql file downloaded I believe. Should I just put it in the Box folder, @kdahlquist  ?

**Comment by kdahlquist** [comment]
Yes, that will work.  Hopefully you still have access to Box now that you've graduated.  Let me know if there's a problem and we'll work out another solution.

**Comment by afiller1** [comment]
Ok, it's in there. Take a peek and let me know if it looks like everything is there, and of course let me know if anything looks off.

**Comment by kdahlquist** [comment]
I opened the file--just in a text editor, I don't have time to try to get it loaded in PGAdmin right now.  However, from what I can see, it looks good.  Since it sounds like you had to take some trouble to get this dump, maybe you can put some instructions on how to do it in the wiki?

**Comment by afiller1** [comment]
Ok. Masao did it because he is the admin on the account, so it was easier for him just to do it and then I went on and retrieved the files. I can ask him for the commands he used or something? @kdahlquist

**Comment by kdahlquist** [comment]
@afiller1, no worries.  We an always ask Masao later.  Closing this!
