### ISSUE TITLE
Review status of AWS Educate account, research RDS

### ISSUE THREAD

**Issue by afiller1** [dondi/GRNsight#835]
## FINISH BY MEETING 2/3/2020
- [x]  Review status of AWS Educate account. Make sure that account functions, has credits.
- [x]  Take note of how account presents web services
- [x]  Look into starting an instance of RDS (how to toggle, what data is necessary, what features exist, etc.)

**Comment by afiller1** [comment]
I would like to discuss what I have found in terms of how to use AWS (RDS specifically) at the meeting on 2/3/2020 and maybe schedule another meeting with @dondi to walk through the metrics we want to set up for the database.

**Comment by afiller1** [comment]
I forgot to say anything on this at the time, but Dondi and I went through and set up and RDS instance that uses a PostgreSQL engine and is connected to an EC2 instance (this was all on 2/4/2020). I now have the capability to create tables, etc. with psql commands. Refer to #836 for updates on the database progress. Requesting to close this issue @dondi .

**Comment by kdahlquist** [comment]
Confirmed done at an office hours session w/ @dondi around 2 weeks ago.
