### ISSUE TITLE
Undergraduate Research Symposium

### ISSUE THREAD

**Issue by afiller1** [dondi/GRNsight#839]
I just got the email saying that URS applications are due this Friday 2/7. We didn't bring them up in our meeting on Monday, but I know this is generally required of us. @dondi @kdahlquist can you assign this issue appropriately and add the labels as well as link any important info?

**Comment by dondi** [comment]
Good catch @afiller1 —yes, we should do this. Start a new wiki for your abstract; you can use prior abstracts as models. For example, here is one from last year: https://github.com/dondi/GRNsight/wiki/2019-LMU-Symposium-Abstract,-Alexia-Filler-and-John-Lopez

Revise this to reflect the work that you are slated to do this semester. The turnaround is short but this should still be doable by Friday.

UGRS application: https://academics.lmu.edu/orca/symposium/application/

**Comment by kdahlquist** [comment]
I think that @afiller1 and @Kevboe can do a joint oral presentation.  Please comment on this issue when the abstract is read for review.

**Comment by afiller1** [comment]
Ok I have created a rough draft [here](https://github.com/dondi/GRNsight/wiki/2020-LMU-Undergraduate-Research-Symposium-Abstract,-Alexia-Filler-and-Kevin-Patterson). @Kevboe you just need to add your section and then we can review it with Dr. Dahlquist.

**Comment by kdahlquist** [comment]
I'm looking at it now.  @Kevboe needs to just add a little bit about expanding the number of species for the Gene Page, but @afiller1 needs to actually write something about making the database with other expression data in it, I didn't see that in the abstract.  The intro part at the top may need to be shortened a little to make way.

You guys also need to come up with a different title.

**Comment by kdahlquist** [comment]
@Kevboe, I was looking at the wrong year.  follow the link in the above comment to get to the 2020 version.

**Comment by Kevboe** [comment]
I have updated the rough draft for the research symposium. Thanks @afiller1 for starting the draft. Waiting for @kdahlquist to read and approve.

**Comment by dondi** [comment]
OK, thanks. Here is my proposed revision: I slightly de-emphasized features from previous presentations (force/grid layout; node coloring) and reworded some of the new features both for word count purposes and consistent tense:

> GRNsight is a web application and service for visualizing models of gene regulatory networks (GRNs). A gene regulatory network consists of genes, transcription factors, and the regulatory connections between them which govern the level of expression of mRNA and protein from genes. GRNmap, a MATLAB program that performs parameter estimation and forward simulation of a differential equations model of a GRN, can mathematically model GRNs. Using a GRNmap output workbook, GRNsight automatically visualizes the network as a graph. GRNsight uses the model output to color-code the edges based on the activation and repression relationships between the transcription factors and colors the nodes based on time course gene expression data. We have added a feature to store expression data in a database, so that users of GRNsight can view and interact with already-existing expression data pulled from the Dahlquist lab and other publicly available datasets. The database is hosted by Amazon Web Services (AWS) Relational Database Service (RDS) and uses a PostgreSQL engine, from which GRNsight performs dynamic queries in response to user requests. Additionally, we have expanded the availability of gene-specific data to a greater number of species. The feature allows user to specify the species of interest either based on a GRNmap workbook or direct user input, and save it for the remainder of the user's session. With the species indicated, the gene page can query the appropriate databases and return information relevant only to species-specific genes. GRNsight is available at http://dondi.github.io/GRNsight.

This version clocks in at 243 words. 250 is the limit, right? I decided not to edit the wiki directly so that it's easy to compare what changed.

Please revise further (or revert unwanted changes) as needed. My main goal was word count and slightly greater emphasis on what's new in this iteration.

**Comment by kdahlquist** [comment]
I'm good with @dondi's version reported in the comment above. Can @afiller1 copy it back over to the wiki and submit?

**Comment by Kevboe** [comment]
Your revisions look good @dondi , I have updated the wiki with the new version, but Alexia will need to submit  the application still. Thanks for the edits.

**Comment by afiller1** [comment]
I have submitted the application using the updated wiki text. The title was apparently too long to be accepted, so I just left it as "An Expression Database for Node Coloring and Expansion of Species for Gene Pages for GRNsight" for the purpose of the application (just a heads up). Thanks everyone! @dondi @kdahlquist permission to close the issue?

**Comment by dondi** [comment]
I’m good with this 👍 Pencil in that we’ll need to write a future issue for preparing the talk in the event that the abstract is accepted.

**Comment by kdahlquist** [comment]
LMU has communicated the details about the symposium.   They want the students to upload both the slides and a video of of themselves giving the presentation (for both poster and oral) by Thursday the 16th at 5:00.  However, they are saying that they only want the oral presentations to be 5-7 minutes instead of the normal 15 min +5 for questions.

@dondi and @kdahlquist want to ask @afiller1 and @Kevboe whether they still want to do the presentation, given these constraints (it's actually harder to make a shorter presentation than a longer one).

It would be OK with us if you would rather skip the symposium in favor of focusing on your 402 presentation later in the semester.  If you'd rather do both presentations, that is also an option.  Please let us know what you think by commenting on this issue.

**Comment by afiller1** [comment]
@Kevboe and I just did our ABCDR presentation with brief demos on Monday for our 402 class, and that presentation definitely surpassed that time limit...even with revisions, I honestly don't think we could do a terribly high quality presentation within those time constraints. @kdahlquist do you think you can provide a link for where they made that time constraint? I can't seem to find it anywhere.

**Comment by kdahlquist** [comment]
It's in this PDF under the section labeled "Oral, Film, & Live Arts..."

[URS 12 Student Presentation Instructions.pdf](https://github.com/dondi/GRNsight/files/4458703/URS.12.Student.Presentation.Instructions.pdf)

I agree that the 5-7 min. limit is to short.  I can ask if that's a hard limit.

**Comment by afiller1** [comment]
That would be great. I would be interested in presenting still, since we have a presentation prepped already that could just be altered a bit, and it would be nice to show off the project. But I don't know how good it would be if we each only had 3.5 minutes max.

**Comment by kdahlquist** [comment]
OK. Please upload your slides to the Master Branch documents folder.  You can see there the patter we are using for the filenames.  We will spend time at the next meeting reviewing slides and your presentation.  I will contact the symposium folks about the time limit.

**Comment by kdahlquist** [comment]
I heard back from Elizabeth Wimberly that the presentations can be longer.  All the presentations are asynchronous anyway, so it doesn't really matter how long they are in terms of timing of the symposium.  They just need to be uploaded by the deadline of Thursday at 5:00.

**Comment by kdahlquist** [comment]
I just went through and made edits and comments on the slides that @afiller1 shared via Google Slides link.  I both made changes to the slides and made comments in the notes field.

It's kind of messy, so it will need to be cleaned up.  Let me know if you have questions.

**Comment by kdahlquist** [comment]
Update on symposium logistics:

The Biology Department is setting up a special session from 10:00-12:00 on Saturday for all presenters (both oral and poster) from the department.  We are assigning faculty to look at/watch 2 presentations each so that during the live session we will

1. Have each student/group introduce themselves and give a 1-2 min elevator pitch describing their project.
2. Answer questions about their project.

I'm moderating the session.  Since @afiller1 and @Kevboe's presentation is biology related, I'm inviting them to this session because I don't exactly know how any of the other sessions will work.

@afiller1 and @Kevboe, please comment on this issue to let me know whether you are available to participate 10-12 on Saturday.

The information on Hubb right now is kind of a mess.

**Comment by Kevboe** [comment]
I can participate on Saturday from 10 to 12. How should @afiller1 and I work on the logistics of creating a single video presentation for the project, which we need by tomorrow? Are the slides which you have updated the final version, or is there updating that we need to do to them still?

**Comment by kdahlquist** [comment]
The slides still need to be edited.  There's quite a lot of work to be done, actually.  I was trying to add background information and remove some of the specific 402 stuff that would not be needed for a general audience, but I did not finalize the presentation.

You can record a video using a zoom session.  For example, @afiller1 can be the host and share her screen and you can take turns talking for your slides.  When you are recording, select saving it to your local machine and when you are done, the video will be in a Zoom folder on your hard drive.  You have to click on the file and then it will be further processed into an mp4.  It also has an option to get an audio-only file.

**Comment by afiller1** [comment]
I am available 10-12 on Saturday. I will comment when we get the slides edited.

**Comment by afiller1** [comment]
Kevin and I have edited the and recorded our presentation. I have uploaded the Box link containing the video to Hubb as instructed in the upload guidelines that were sent out. You can test out the link by looking [here](https://lmu.box.com/s/ba2dy51dzyh19vnbfv8wm812uypjjhws). Perhaps everyone can try it out just to make sure it works? @Kevboe @kdahlquist @dondi

**Comment by kdahlquist** [comment]
It works!

**Comment by kdahlquist** [comment]
The instructions for how to join the biology Zoom meeting on Saturday from 10-12 have been sent via e-mail.  @afiller1 @Kevboe @dondi

**Comment by dondi** [comment]
Understood and got the email; thanks for setting all of this up @kdahlquist!

**Comment by kdahlquist** [comment]
Great job everyone!
