### ISSUE TITLE
GRNsight meetings during campus closure: remainder of Spring 2020

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#842]
President Snyder just announced that classes will move online from March 16-31.  We will continue to hold our GRNsight meetings on Mondays 9:00-10:00 am, but we will do them by conference call or other online technology.  Please check this issue by Friday, March 13 so you will know how to meet on Monday morning when we get back.

**Comment by kdahlquist** [comment]
For Monday's meeting, 9:00-10:00 AM Pacific Daylight Time, we will use the Zoom web conferencing system to meet.   @dondi will send out a meeting invitation.  If you need information on how to use Zoom, see the Help page I created for one of my classes here:  https://openwetware.org/wiki/BIOL368/S20:Help#Instructions_for_Online_Class_Sessions

@dondi, can I meet you in your office?

**Comment by dondi** [comment]
@kdahlquist Yes we can physically be in my office. @afiller1 @Kevboe @Onariaginosa I have posted the Zoom URL in the `grnsight` Slack channel.

**Comment by kdahlquist** [comment]
LMU announced last night that instruction will be delayed until Monday, March 23, so we will not be having a GRNsight meeting on Monday, March 16; we will wait until Monday the 23rd at 9:00 AM PDT to have our next meeting on Zoom.

I will be reaching out to you personally via e-mail this next week just to check in with you individually.  Let me or @dondi know if there's anything we can do to be of assistance.  Stay safe.

**Comment by dondi** [comment]
Understood—stay safe everyone. @Kevboe I saw your PR comments and have that queued up for a look when I get the chance.

**Comment by afiller1** [comment]
Should we still prepare a presentation for the symposium which is, as far as I've seen, still scheduled virtually for the 20th?

**Comment by dondi** [comment]
Looks like we just got our answer:
> Dear LMU Symposium Participants and Faculty Mentors,
>
> In order to provide time for the transition to online instruction and to allow students and families to focus on moving out of residence halls, the 12th Annual LMU Undergraduate Research Symposium is postponed to the weekend of Friday, April 17th and Saturday, April 18th.  The Symposium will be held in a virtual medium with opportunities for presentation evaluation and feedback.
>
> For more information on the Symposium, please visit our website at lmu.edu/symposium. Thank you again for your tremendous support.

So it looks like we will still prepare a presentation, but not for this weekend.

**Comment by kdahlquist** [comment]
Everyone has answered the poll.  These are the options when all are available:

Monday 11:30-12:30
Wednesday 5:00-6:00
Friday 11:30-12:30
Friday 12:00-1:00
Friday 12:30-1:30

@Kevboe, do any of these times work better where you will be able to talk at the meeting?

I would prefer to keep the meeting on Monday, since that was when were meeting, but if another time is better for @Kevboe, so he can talk, please let us know.

**Comment by Kevboe** [comment]
A class schedule changed, so I cannot guarantee that I will be available at 11:30 every Monday, although most Mondays I will. The other times all work for me. I don't know my dad's meeting schedule, but I think I will be able to talk at these times.

**Comment by kdahlquist** [comment]
@Kevboe, there are three weeks left in the semester.  Will you please check your calendar and let us know which of the Mondays at 11:30 you are available?  Are you available this coming Monday, the 13th?  Even if your dad is in a meeting, would you be able to stand outside your front door or something so that you can talk?

**Comment by Kevboe** [comment]
Unfortunately I cannot say when I will have class and when I will be free, my teacher emailed us and said "I might choose to have a class or two between 10 and 12" so be free. I would assume that I am not free at 11:30. This coming Monday I can do our regular time, and will make sure that I can use my voice.

**Comment by kdahlquist** [comment]
OK, thanks for clarifying.  So, for Monday the 13th, we will meet at 9:00 AM Pacific time like we have been doing.  We can check in with everybody at the meeting to see about the following week.

**Comment by kdahlquist** [comment]
We are going to just keep the Monday at 9:00 AM meeting, so I'm closing this one.
