### ISSUE TITLE
Pulled from beta and local server crashed

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#852]
Is beta okay? I pulled from beta into my branch, and GRNsight crashed. I switched to beta's branch and pulled as well and it also crashed. Attached is a screenshot of my terminal.
![Screenshot from 2020-04-27 09-34-05](https://user-images.githubusercontent.com/21343072/80397108-82c3c380-886a-11ea-9af2-1c4ce29d7b54.png)

**Comment by dondi** [comment]
`EADDRINUSE` —that means another program is running at the host/IP. Verify that you don’t already have GRNsight running in another terminal. The server process also sometimes takes some time to release the resources it was using so also just waiting to run the server again can resolve this.

**Comment by dondi** [comment]
@Onariaginosa when you get a chance, let us know if this issue has been resolved, in case we need to look at other possible causes. Thanks!

**Comment by Onariaginosa** [comment]
I restarted my computer because my terminal said that their were no processes running, and the `EADDRINUSE` error changed. Here are the attached photos @dondi 
![Screenshot from 2020-04-27 22-07-19](https://user-images.githubusercontent.com/21343072/80449361-cc94c400-88d3-11ea-8c2b-30dc0569d25a.png)
![Screenshot from 2020-04-27 22-06-49](https://user-images.githubusercontent.com/21343072/80449363-cdc5f100-88d3-11ea-98de-a04747f967c4.png)

**Comment by Onariaginosa** [comment]
This error occurred in the beta branch.

**Comment by dondi** [comment]
Ah yes @Onariaginosa —this `beta` branch now integrates Kevin and Alexia’s work. Do `nom install` to update your packages.

**Comment by kdahlquist** [comment]
Nom nom nom!
![image](https://user-images.githubusercontent.com/6463867/80514682-b1f33700-8935-11ea-9f68-0ad296d91d70.png)

**Comment by dondi** [comment]
@kdahlquist Heh yes I get that typo of `npm` being changed to `nom` a lot 😂
