### ISSUE TITLE
Format of gene page warning does not match format of general GRNsight warning

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#855]
For consistency, we should have all the warning/error modals match in terms of format/fonts.  Here is an example of the main one that should be matched:

![image](https://user-images.githubusercontent.com/6463867/80515750-49a55500-8937-11ea-9097-08b7c791d0cd.png)

This is the gene page one that should be matched to the one above in terms of font and style (wording is OK).
![image](https://user-images.githubusercontent.com/6463867/80515779-5b86f800-8937-11ea-8a83-1b5dbc9d22e9.png)

**Comment by Kevboe** [comment]
I believe I have fixed this issue, and the changes will be reflected in the next PR I make.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 4.0.18.  Closing
