### ISSUE TITLE
Gene Page says "Species not found" even though species has been selected

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#856]
When I select a species other than yeast from the menu or panel in GRNsight beta 4.0.17 and right-click on a gene to open the gene page, the Gene page says "Species not found" in the upper right-hand corner.  It should say the selected species name whether or not data are found.

This might be a holdover from the way this was first implemented where the species name was discovered from one of the API's (don't remember which one).  But now we are setting it, so this should be a straightforward change.

**Comment by kdahlquist** [comment]
Update:  this is a problem when Arabidopsis and C. elegans is selected, but not yeast or human.  Can't test fly or mouse unless I make my own test files.

**Comment by kdahlquist** [comment]
Update: this seems to be a problem when a prior species has been selected.  Doing a refresh of the browser for beta and starting from scratch seems to resolve this.  So, I think this is a matter of something not being refreshed when species are changed.

**Comment by Kevboe** [comment]
I'm not quite sure where the issue is occurring, or what you were expecting. I think you are saying where the page shows the "loading..." and then swaps to the species after loading, and if it does not find the gene/species combo then it shows "no species found" What you would like is that once it swaps from loading, it displayes the selected species regardless of what is returned.

**Comment by kdahlquist** [comment]
Yes, the upper right corner of the gene page.  It should display the selected species, no matter what.  We are not discovering the species at this point, it has been already been selected by the user (or has defaulted to yeast).

There is a separate warning to the user that no data was found.

**Comment by kdahlquist** [comment]
Drosophila is OK.

**Comment by kdahlquist** [comment]
Mouse is OK.

**Comment by kdahlquist** [comment]
Human is OK.

**Comment by Kevboe** [comment]
Issue has been resolved. Changes will be reflected in my next PR.

**Comment by kdahlquist** [comment]
Confirmed fixed in beta 4.10.18.  Closing.
