### ISSUE TITLE
No species information detected not added to no expression data warning when a workbook with both issues is loaded

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#861]
The "No species information detected" is not added to the "No expression data" warning when a workbook with both issues is loaded. beta 4.0.17

**Comment by afiller1** [comment]
Oh, so only the "no expression data" warning pops up? That should be simple enough to fix, I imagine the "no species information" warning just isn't being added to the warnings array correctly.

**Comment by dondi** [comment]
Sounds like a good collaboration opportunity for @afiller1 and @Kevboe. Maybe you can pair on this and this learn a little about each other’s modifications? I think it will be OK for the fix to go directly to beta because this involves your merged work.

**Comment by Kevboe** [comment]
Issue solved on API branch. Will be reflected in the next PR. Currently working on API stuff which is why it's not up yet.

**Comment by kdahlquist** [comment]
Confirmed that this is working in beta 4.0.18.  Closing.
