### ISSUE TITLE
GRNsight meeting schedule for fall, 2020

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#870]
After looking at the combined class and meeting schedules of @dondi, @kdahlquist, @Onariaginosa, @igreen1, and @luluriffic, it’s looking like the only universally free slots fall on Friday. Fridays are usually my consulting days, but in these work-at-home times I can get away with a 1-hour meeting as long as I don't already have another one scheduled.

Open slots on Fridays are 10:30am-12pm, 2:30-3:30pm, then after 4:30pm. Please comment on this issue to state preferences/availability or if you have additional scheduling factors like work or other meetings. Thank you!

**Comment by kdahlquist** [comment]
I would prefer he morning at 10:30, followed by the 2:30 time slot. 4:30 would not work for me.

**Comment by igreen1** [comment]
I would prefer morning (10:30) followed by 2:30 followed by 4:30

**Comment by luluriffic** [comment]
I would prefer 10:30 as well and then 2:30 or 4:30 work for me!!

**Comment by Onariaginosa** [comment]
I would prefer 10:30, then 2:30. I work from 4 to 8, so 4:30 would not work for me.

**Comment by dondi** [comment]
Looks like we have a clear winner—10:30am on Fridays it is then. I’ll send a link under separate cover.

As such, it appears that our first meeting will be this Friday, September 4, at 10:30am. Just in time to see how everyone’s first week of online classes went 😄 See you then!
