### ISSUE TITLE
When importing a workbook results in an error, the `Select New File Button` doesn't work

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#874]
When importing a Workbook results in an error the `Select New File` button doesn't actually let you select a new file. It just closes the notification window. Here is a [link](https://lmula.zoom.us/rec/share/N6clpwbC-K5hcQmrCwHJZA18mQff7MLul-XxeDMhsXLmkQ-GrBtcqPyphWSiw7NK.8QcukxJZhgFmWI2e) to a video demonstrating it. This occurs on both beta and my local server.

**Comment by Onariaginosa** [comment]
In the `web-client\views\upload.jade` file, in the `errorModal` div, the Select New File Button did not call the `upload` function, nor have the `onclick` event listener. It was commented out in other sections that do not use the Select New File Button, so placed it after the close button. I also tested it to make sure that the Select New File Button appeared and worked as it should.

**Comment by dondi** [comment]
Verified by @ahmad00m as resolved.
