### ISSUE TITLE
When running locally, resizing the window doesn't resize all elements properly 

### ISSUE THREAD

**Issue by igreen1** [dondi/GRNsight#877]
See the below image. When the window is 1/2 of the total screen area on my display (likely, this ratio will vary depending on the ratio of your screen size), the green bar from the top causes issues by overlaying the graph. The issue happens exactly when the filename (in this case Demo #1: ...) reaches the gray text with the number of nodes/edges.

![image](https://user-images.githubusercontent.com/40191185/93656369-a97fc380-f9de-11ea-9d97-33668dc8e4e9.png)

When the window is shrunk more, the issue disappears since the labels are erased.

![image](https://user-images.githubusercontent.com/40191185/93656384-e6e45100-f9de-11ea-877b-2a0e045e8449.png)

It appears that the function deciding when to stop displaying the labels is slightly off.

To replicate:
Open local server
Open any graph (long names are better, the demos work well)
Shrink the horizontal size of the window until the issue occurs.

**Comment by igreen1** [comment]
Needs to be replicated on other computers. @luluriffic and @igreen1 found this issue earlier when talking about the program so it persists at least on those two machines.

**Comment by kdahlquist** [comment]
I don't see this running beta 4.0.19 on Firefox on Windows.  I get a left-right scroll bar when I resize the window like this.  Check which browser this is happening on.

**Comment by igreen1** [comment]
Issue exists in Firefox 80.0.1 and 81.0 (tested on Ubuntu 20 and Windows 10)

Issue exists in Microsoft Edge version 85.0.564.63 (tested on Windows 10)

Issue exists on Google Chrome version 85.0.4183.121 (tested on Windows 10)

@kdahlquist I've edited the issue to include that you must open a graph to see this. Did you open a graph?

**Comment by kdahlquist** [comment]
I did open a graph, but I still don't see it.  I'm looking at your screenshot and see that a hamburger menu appeared.  I've never once had a hamburger menu show up when resizing the window for GRNsight.  I'm wondering if there is some setting for optimizing the browser for tablets/phones that is interacting with this.  I can share my screen on Friday if you will remind me.

**Comment by dondi** [comment]
Issue has been verified but solely affects the case when the GRNsight app in itself is in a resizable window, which is generally only visible to developers working on the app. The issue appears to be a standard “responsiveness” issue and can potentially be fixed but in terms of priority it can definitely wait.

**Comment by kdahlquist** [comment]
I'm going to close this--typically we close backlogged issues.
