### ISSUE TITLE
Reverse arrow button directions for graph

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#888]
The visible arrow buttons correspond better to moving the graph, therefore the left arrow should move the graph to the _left_, etc.

**Comment by dondi** [comment]
Already merged from PR #887.

**Comment by dondi** [comment]
Directionality was confirmed but additional logic is needed to keep the graph within the gray border (for now, while it’s present—see #889). The arrows should move the _graph_ inside the border and the border shouldn’t “tag along” with the movement. Feel free to contact @dondi is @luluriffic runs into any issues.

**Comment by dondi** [comment]
@luluriffic and @dondi have been interacting during the week with how to implement this, with @luluriffic specifically reading through the code and seeking clarification when necessary.

**Comment by luluriffic** [comment]
In the process of writing moveWithinViewport() function

**Comment by dondi** [comment]
@luluriffic is continuing with this and has become more familiar with the code now; there is confidence that is will be done soon.

**Comment by igreen1** [comment]
@dondi I'm a little confused on this issue. Now that the gray border is removed, what is the goal here?

Should the graph be pushed up 'against' the now invisible border ? From #804, 'the arrow keys and center button should still move the entire graph but solely within the visible boundaries' Does 'visible boundaries' mean the viewport (entire 'artboard') or the bounding box within the viewport? Or should behaviour be changed such that viewport size = bounding box size?

**Comment by dondi** [comment]
Indeed, good point @igreen1—there are actually more nuances to this, which is why this set of issues turned out to be trickier than they seemed. I was meaning to ask to brief you after Wednesday but the week got away from me. Do you have some availability to chat about this, maybe Monday afternoon? Probably best to walk you through what we're after over a screenshare

**Comment by igreen1** [comment]
Monday afternoon works perfectly! I'm free after 2pm

**Comment by dondi** [comment]
OK—I have a meeting right at 2pm but 3pm will work; is that OK?

**Comment by igreen1** [comment]
sounds great!

**Comment by igreen1** [comment]
Fixed by moving the graph in the `move` function instead of the camera

**Comment by igreen1** [comment]
`move` was reverted to old logic, with a flip of signs to fix directions. This was done as @kdahlquist didn't want to nodes to 'drift' when movement was done. Now the camera moves but in the opposite direction, mimicking the movement of the graph without requiring an actual movement so the nodes don't drift

**Comment by ahmad00m** [comment]
@ahmad00m confirms that the behavior required is correctly implemented.
