### ISSUE TITLE
Refactor warnings code so that addition of new warning types don’t require changes on the web client

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#892]
_web-client/public/js/warnings.js_ appears to have code that makes it more difficult to add new warning types to the system. This should be modified so that the GRNsight app no longer needs to have a “master list” of warnings in order to display them.

**Comment by Onariaginosa** [comment]
@Onariaginosa fixed this issue in the Onariaginosa_refactor branch.

**Comment by dondi** [comment]
The refactor structure itself has been reviewed and looks good.
