### ISSUE TITLE
Implement Empty Matrix Data and Empty Row Data error tests

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#894]
I am separating these two tests from #417 because they are implemented and will be in a new pull request.

**Comment by dondi** [comment]
The .xlsx test files were all successfully opened in Microsoft Excel and their contents were verified to contain the stated error. Unit tests all passed and when these were opened by GRNsight, the expected errors/warning appeared.

Based on this, the issue looks good to close.
