### ISSUE TITLE
Scheduling GRNsight meetings for Spring 2021

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#903]
This issue is for working out scheduling the GRNsight meetings for Spring 2021.
@kdahlquist is available at the following times:
- Mondays 9:00-12:00, 1:00-2:00
- Tuesdays, 9:00-12:00, 2:00-5:00 (once a month not available 3:00-4:00)
- Wednesdays, 9:00-10:00, 11:00-12:00, 1:00-5:00
- Thursdays, 10:00-11:00 (I just updated this).
- Fridays, 9:00-11:00, 12:00-2:00

**Comment by Onariaginosa** [comment]
Within the above specified time blocks @Onariaginosa is available at the following times:
- Monday: Unavailable
- Tuesday: 9:00 - 12:00
- Wednesday: 9:00 - 10:00, 3:15 - 5:00
- Thursday: 9:00 - 11:00
- Friday: 9:00 - 11:00

**Comment by igreen1** [comment]
Going the two above comments, @igreen1  is available :
- Monday: none
- Tuesday: 9:00-12:00
- Wednesday: 15:15 - 17:00
- Thursday: none
- Friday: none

**Comment by dondi** [comment]
Based on responses so far (and integrating my availability), the primary spot that’s open for all of us is Wednesday afternoons, within the window of 3:15-5pm. We can pick out something within that range.

And that’s it, actually 😅 Here’s hoping that @luluriffic and @ahmad00m have availability on Wednesday afternoons as well…

**Comment by ahmad00m** [comment]
With regards to the time slots given, @ahmad00m is available:

- Monday: 9:00 - 11:00
- Tuesday: 9:00 - 11:30,  2:00 - 5:00
- Wednesday: 9:00 - 10:00, 3:20 - 5:00
- Thursday: 10:00 - 11:00
- Friday: 9:00 - 11:00

**Comment by kdahlquist** [comment]
I looked at @luluriffic's schedule on PROWL and based on what @ahmad00m commented, I think we can safely do 3:30 on Wednesdays.  I'm going to pencil that in now so I don't lose that spot to other meetings.
