### ISSUE TITLE
Log Fold Change Max value selection on sidebar has issues

### ISSUE THREAD

**Issue by igreen1** [dondi/GRNsight#905]
On @igreen1 machine (Firefox 84.0.2, Ubuntu 20.04), the Log Fold Change Max value selection on the sidebar does not work. It does, however, work on the dropdown (Node ->  Log Fold Change Max Value). This issue exists even after every single extensions was removed from @igreen1's browser (including the seemingly unrelated ones)

![image](https://user-images.githubusercontent.com/40191185/106072451-1443b880-60bd-11eb-95a1-dae31d7751df.png)

This is possibly linked to the lack of a 'set' button. On @dondi's machine there is an additional 'set' button next to the input value. This issue requires additional help in replication to find where the bug lies.

No relevant web console output was logged on page load. @igreen1 will try to replicate this issue on Windows Firefox and on Windows Edge/Chrome.

**Comment by igreen1** [comment]
@ahmad00m has confirmed that this issue does not occur on his installation of Chrome or Safari on MacOS

**Comment by igreen1** [comment]
This issue does not exist on Windows with Firefox 80.4.2, Chrome, or Edge (odd!)

It might be an issue with Linux or Firefox's linux version. Therefore, definitely a lower priority. Of note, because of Firefox Sync, the firefox test on Windows was done with all the same extensions as in the Linux Firefox test. And, of course, was also tested with all of those extensions turned off.

@Onariaginosa uses Linux I believe, so might be helpful if they could test on their computer? @igreen1  will try it on a virtual machine later (having a few virtualbox kernel errors at the moment)

**Comment by igreen1** [comment]
Issue confirmed on a virtualbox Ubuntu 20.04 running Firefox 80.4.2

So Linux Firefox has a bug. Low priority but fascinating!

**Comment by mihirsamdarshi** [comment]
I am unable to replicate this on my Ubuntu 20.04 machine running Chrome, which is interesting because Chrome and Firefox are basically the same thing.

**Comment by igreen1** [comment]
Bug identified! The button is 'present' but overflows and is made hidden as a result (other elements are placed on top). This bug only appears in Linux Firefox 84.x.x. and above as far as tested (interesting!) Present on resizing as well. 

![image](https://user-images.githubusercontent.com/40191185/108609547-6bb70a80-7383-11eb-9029-5f12dc57c5c3.png)

Simple solution. The numeric input field can be limited to 75% of sidebar size. This was done in commit 2598170cfbda751fe02a3008056b62c84865e8bb

Would like further testing to confirm this works on other configurations before a PR to beta.

This also required a 'force' commit as 'grnsight.css' is in the gitignore. Is there a reason for this?

**Comment by dondi** [comment]
Will need independent verification on anyone who has access to Linux Firefox 84.x.x. Also, force commit was due to original styles actually being derived from _.styl_ files, so @igreen1 will make those changes there instead.

**Comment by igreen1** [comment]
Better fix thanks to @dondi 

@Onariaginosa would love a review! Works on my machine (Ubuntu 20.04) with Firefox 86

Would appreciate a Mac user taking a glance as well to make sure it didn't break compatibility @ahmad00m

**Comment by Onariaginosa** [comment]
On Firefox 86 the set button is still slightly hidden for me. Maybe make the input bar 50% - 60% of the sidebar size?
![Screenshot from 2021-03-17 11-50-45](https://user-images.githubusercontent.com/21343072/111522218-4c5b9500-8717-11eb-9f44-83fff2c4b112.png)

**Comment by ahmad00m** [comment]
@ahmad00m check it the set button on Chrome 89, Firefox 86, and Safari 14 and it was fully visible.

**Comment by dondi** [comment]
This input field doesn't seem like it needs that much room so sounds OK to be more aggressive with tightening size. @igreen1 after making this adjustment, let’s have one more round similar to the one that just transpired.

**Comment by igreen1** [comment]
Changed to 50% in commit e8dc3b9c325df14196900b2cf811efe96b899104commit e8dc3b9c325df14196900b2cf811efe96b899104

On Linux 20.04, Firefox 86

![image](https://user-images.githubusercontent.com/40191185/111550628-b84ff480-873b-11eb-9930-753ccc5b808a.png)

**Comment by ahmad00m** [comment]
@ahmad00m verifies that this change is compatible with Mac.

**Comment by Onariaginosa** [comment]
@Onariaginosa confirms that it visible on Firefox 86

**Comment by dondi** [comment]
Looks verified; PR forthcoming.

**Comment by ahmad00m** [comment]
@ahmad00m confirms that it is visible on Safari 14.0.2 and Firefox 88.
