### ISSUE TITLE
Excel export not working

### ISSUE THREAD

**Issue by ahmad00m** [dondi/GRNsight#907]
I encountered a bug during testing excel files on GRNsight. The problem is when you download the demo file in excel format and try to upload it back again to GRNsight from your computer. I have attached a screenshot of the bug.
<img width="1434" alt="Screenshot 2021-01-30 at 12 32 39 pm" src="https://user-images.githubusercontent.com/75926755/106367493-d41c4a00-62f7-11eb-933c-3d538b54bd6e.png">

**Comment by igreen1** [comment]
The first error with the network and network weights is due to an error in the renaming with issue #897. @igreen1  identified and fixed this portion of the error. 
The problems with the production_rates and degradation_rates sheets are still outstanding however.

**Comment by ahmad00m** [comment]
It seems the errors associated with production_rates and degradation_rates sheets come up with all files with excel format and it is not specific to files exported from GRNsight. I used a file from master branch/ test-files / demo-files / 21-genes_31-edges_schade-data_input.xlsx and uploaded the file on GRNsight. The errors are shown in the attached screenshot.
<img width="1432" alt="Screenshot 2021-01-30 at 2 03 48 pm" src="https://user-images.githubusercontent.com/75926755/106369183-0af85d00-6304-11eb-9271-bcd1cfa168eb.png">

**Comment by igreen1** [comment]
The issue with production_rates and degradation_rates is from the demo_workbooks.js file in `server/controllers`. Demo workbooks 3/4 have this issue. Demo workbooks 1/2 are totally fine, though there is still some issue with the adjacency matrix. 
The production_rates and degradation_rates in demo workbooks 3/4 appear to have genes and their longer form names? No entirely clear, I'll paste below if someone else has better insight

This does NOT help with all the issues as workbooks 2, when tested, still threw the error `The value in the cell C 2 in the adjacency matrix appears to have a missing value. Please ensure that all cells have a value, then upload the file again.`.

So adjacency matrix is still an issue for import/export (unclear which part of the system is broken)

Sorry, I was tinkering yesterday but forgot to report !

![image](https://user-images.githubusercontent.com/40191185/106824426-a6a50880-6637-11eb-9698-3aedc6968fce.png)

**Comment by dondi** [comment]
Ties in with @Onariaginosa's current track so @ahmad00m and @Onariaginosa can coordinate on this as the Excel export feature is being revived/resuscitated.

**Comment by Onariaginosa** [comment]
I fixed the export functionality for the network sheets. I split the issue into #919 to focus on fixing the additional sheets (Optimization Parameters, Optimization Diagnostic, and Two Column sheets)

**Comment by Onariaginosa** [comment]
This issue should be fixed once pull request #920 is accepted!

**Comment by ahmad00m** [comment]
@ahmad00m tested the demo export function and it seems that demo 3 & 4 return return an error meaning they did not export properly.

**Comment by dondi** [comment]
Because Demos 3 & 4 are in legacy state at this point, the suggestion is to detect when these are being exported and omit the sheets that are not formatted as expected.

**Comment by Onariaginosa** [comment]
Fixed it.

**Comment by ahmad00m** [comment]
@ahmad00m confirms this issue is fixed.
