### ISSUE TITLE
LMU URS poster preparation

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#911]
This fell off my radar, but we'd better talk about this at todays meeting!

On another note--Github has now taken away the assignee list completely!  So, now I have to remember people's usernames and type them?

**Comment by dondi** [comment]
Current draft: https://github.com/dondi/GRNsight/wiki/2021-Undergraduate-Research-Symposium-Abstract —to be revised by @Onariaginosa, @igreen1, and @ahmad00m for subsequent review by @dondi and @kdahlquist before 2/5.

**Comment by igreen1** [comment]
@kdahlquist @dondi 
Please review the changes made ! Thanks

**Comment by dondi** [comment]
Thanks! Here are my notes so far:
* Revise the title to reflect the specific elements that you did. Something like "Improving the Test Foundation of…" or "Testing and User Interface Improvements to…"—something like that
* I'm unclear what is meant by "graphics pipeline"—what's being referred to here?
* Can specificity be increased for the sentence on tests? Instead of plethora, can you estimate how many tests were added? (you can checkout `master`, run the test suite on that, then go back to `beta` and run the test suite on that to see how many tests were added). Also by "refactoring," did you simplify? Consolidate? Debug? All of the above?
* The remaining sentences read OK though might need a little wordsmithing—I think that will be best done after the content has settled

Hope that's useful!

**Comment by kdahlquist** [comment]
I agree with @dondi.  I also want to note that the abstract submission form has a 100 character limit, so the title will need to be shortened.

**Comment by Onariaginosa** [comment]
@kdahlquist @dondi We updated the abstract and changed what was requested. Please advise. Thanks!

**Comment by dondi** [comment]
Thanks for the quick turnaround!

I think the content looks good now and we just need one last pass of wordsmithing. Those last sentences don’t flow for me upon reading—they feel like bullet points but they should read more narratively. Put another way, each sentence feels isolated, not moving from one to the next. The 2nd and 3rd sentences are a slight exception, thanks to that “Additionally” glue word. Unfortunately we can’t really put “additionally” before every sentence 😅

> We improved the import and export functionality. We added 28 new tests to increase user awareness of errors and warnings in the import and export process, as well as consolidated and debugged the testing suite. Additionally, we updated the User Interface to fix graph edge display bugs, as well as viewport selection and movement issues. We explored GRNsight's compatibility issues with uncommon operating systems and web browsers. We updated libraries to maintain GRNsight's compatibility with modern web browsers and take advantage of new features available. 

If anyone wants to take a stab at it, go ahead. I’ll mull over it a bit and give it a shot later if no one has yet.

Alternatively, if it’s just me and it otherwise reads OK to everyone else, then I’m good with it 😂

**Comment by dondi** [comment]
Oh oops and the title still needs to be shortened. I'm counting 122 characters.

**Comment by igreen1** [comment]
on the title, i removed the 'a' before `web application` which should just get us to the character count.

Alternatively, we could probably changed 'user interface' to just 'interface' or 'user interface' to 'graphics' as we did technically improve the graphics (by fixing the various bugs in the graph display and viewport)

About the word smithing, I agree. There are a lot of 'we verbed'. I can try to edit this tomorrow morning, but I have a midterm in the morning so I'll be studying the rest of the evening.

**Comment by Onariaginosa** [comment]
I edited it. The title is now "Testing/UI Annexes to GRNsight: a Web Application for Visualizing Models of Gene Regulatory Networks"

**Comment by kdahlquist** [comment]
I did an editing run on the abstract, adding the idea of Excel workbook validation to the rationale for the updates we made.  I've substantially changed the title.  I don't usually approve of using abbreviations in titles, but if they are going to limit us to 100 characters, they are asking for it :)  I think the new title better summarizes the work you all did.  The title is 97 characters and the abstract body is 242 words.

This version is OK for submitting, pending @dondi's approval.

**Comment by dondi** [comment]
Works for me! I substituted “To this end” with “Along the way” to make it a little different from the earlier “Toward this end” but that’s it. Ready to ship :shipit: 👍

**Comment by dondi** [comment]
@kdahlquist Apparently these are the final choices…“in the classroom” never did get edited out…any preference on the format?
![image](https://user-images.githubusercontent.com/382242/107098289-b7828500-67c3-11eb-9836-3ad6356deac3.png)

**Comment by kdahlquist** [comment]
I'm OK with poster or oral.  Usually we have seniors to oral, so poster, maybe?

**Comment by Onariaginosa** [comment]
Kk, I will select poster then!

**Comment by Onariaginosa** [comment]
[2021 Undergraduate Research Symposium Abstract.pdf](https://github.com/dondi/GRNsight/files/5935807/2021.Undergraduate.Research.Symposium.Abstract.pdf)
Is this fine for the pdf version of the abstracr?
@kdahlquist @dondi

**Comment by dondi** [comment]
PDF looks good to me @Onariaginosa

**Comment by Onariaginosa** [comment]
Cool. I will submit now!

**Comment by kdahlquist** [comment]
Changed title to "poster preparation".

**Comment by dondi** [comment]
Biology synchronous session is targeted for 3/19 Friday late afternoon. We'll target a draft by around 3/10 with finalization 3/17.

**Comment by Onariaginosa** [comment]
@Onariaginosa @igreen1 @ahmad00m created a poster draft for URS. It is  attached below in pdf and powerpoint format.
[Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx.pdf](https://github.com/dondi/GRNsight/files/6113639/Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx.pdf)
[Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx.pdf](https://github.com/dondi/GRNsight/files/6113638/Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx.pdf)

**Comment by dondi** [comment]
Some notes from poster review:
* Restore GRNsight overview from Samdarshi 2018 poster, except remove edge weight figures on right
* Some layout changes may be needed

[Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx](https://github.com/dondi/GRNsight/files/6119528/Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx)

**Comment by kdahlquist** [comment]
[Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx](https://github.com/dondi/GRNsight/files/6119567/Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx)
[Samdarshi-et-al_SoCalSysBio_2019_edited_2021-03-10.pptx](https://github.com/dondi/GRNsight/files/6119571/Samdarshi-et-al_SoCalSysBio_2019_edited_2021-03-10.pptx)

**Comment by dondi** [comment]
A few more notes for new content:
* Move revised background information (as edited during the meeting on earlier poster) to left side of the poster
* Provide introductory bullets in the new sections that state the problem (current content states the solution but poster readers will need an explicit statement for why we did the work that we did)
* Move "User Interface Improvements" panel above "Library Updates" panel
* Update Google Analytics pie chart

**Comment by dondi** [comment]
Latest GA data:
- New users: 7160
- Sessions: 17412
- Pageviews: 36413

**Comment by Onariaginosa** [comment]
We updated the powerpoint:
[Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx (2).pdf](https://github.com/dondi/GRNsight/files/6137398/Igbinedion_Green_Mersaghian_LMU_Symposium_2021.pptx.2.pdf)

**Comment by dondi** [comment]
Revised version included, mostly periods and hyphens, plus reformatting of References section.

TODO: Include upload numbers in analytics table

[Igbinedion_Green_Mersaghian_LMU_SYMPOSIUM_BACKUP_2021.1.pptx](https://github.com/dondi/GRNsight/files/6160233/Igbinedion_Green_Mersaghian_LMU_SYMPOSIUM_BACKUP_2021.1.pptx)

**Comment by dondi** [comment]
Post-poster finalization action items:
- Put PDF in _documents_ folder on `master`
- Link to it on the Publications page
- Create a news item

**Comment by Onariaginosa** [comment]
Fixed Poster, submitted poster, put pdf in documents folder on master, created news item. Will do publications page soon.

**Comment by dondi** [comment]
Converted the action items to a checklist and at this writing, we just need to do a publication link.

**Comment by Onariaginosa** [comment]
Linked on the Publications page

**Comment by dondi** [comment]
Link to publication verified at 4/14 meeting.
