### ISSUE TITLE
Dependency issue regarding jsdom and canvg

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#913]
So when my local server broke and I was trying to fix it, I did the usual delete "node_modules" and "package-lock.json" method. When I did that this error message popped up:
![Screenshot from 2021-02-10 13-41-21](https://user-images.githubusercontent.com/21343072/107576574-2e45c680-6ba6-11eb-9011-1b316ffbcefe.png)
It appears that canvg@2.0.0 requires jsdom@13.0.0 or higher now. I just changed my "package.json" file to have jsdom as 13.0.0 to debug make my local server, but I'm not sure if I was supposed to do that. Any thoughts @dondi

**Comment by igreen1** [comment]
This bug is replicable by removing node_modules and package_lock.json.

Achieved on @igreen1 branch and beta branch after deleting the node_modules folder.

**Comment by dondi** [comment]
@dondi tried to replicate steps on macOS (remove package-lock.json; run fresh `npm install`) but did not see the same errors. The one consistent factor appears to be operating system. Some next steps:
- research may be warranted to see if there is a known issue on Ubuntu
- If @Onariaginosa or @igreen1 have access to a different platform, they can try it there
- @ahmad00m can try it on his own machine to check if it can be replicated on macOS

**Comment by dondi** [comment]
@igreen1 also reported that the (stale) `dondi` branch doesn't show this issue, so another potential possibility is looking at what libraries have changed between that branch at beta.

**Comment by dondi** [comment]
During the meeting we discovered that another common thread appears to be that @Onariaginosa and @igreen1 are on npm 7.x while @dondi is on npm 6.x. @Onariaginosa and/or @igreen1 will try going back a version to see what happens.

**Comment by igreen1** [comment]
Tested on Windows 10 with `npm 6.14.8 ` and `node 14.13.0`. No error on install

Upon updating to `npm 7.5.3` the error returned.

Error seems to be related to npm version and not operating system, then.

**Comment by dondi** [comment]
With this being fixed by `security-updates`, @dondi will seek to resolve the build errors to actually merge its PR into beta

**Comment by dondi** [comment]
Apparently `security-updates` has not been merged—will need to review this.

**Comment by dondi** [comment]
PR #912 involving `security-updates` was actually closed—need to refresh memory on what happened here then figure out definitively.

**Comment by dondi** [comment]
We have undergone multiple notable changes to our dependencies as software (ours and third parties’) has evolved, and this has not been observed of late so closing
