### ISSUE TITLE
Beta appears to be down

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#914]
I was on the beta version of GRNsignt to compare things, and I noticed that I could not upload demo files or any workbook file. I wanted to check whether this was reproducible.

**Comment by kdahlquist** [comment]
Yup, that's what I'm seeing, too.  I'm on Windows 10, Firefox.

**Comment by Onariaginosa** [comment]
I was on Ubuntu 18.04, Firefox and Chrome

**Comment by kdahlquist** [comment]
Are folks running through the Pull Request checklist here: https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist to make sure everything's functional before accepting the PR and updating the server?  We might have gotten out of the habit of doing this lately.

**Comment by dondi** [comment]
@Onariaginosa @kdahlquist Not sure what happened but it was a server-side issue—something at the middleware level. Loading demos works for me now

That said, true that I haven't going through the full checklist. I've been reloading and pulling some demos but no further, and sometimes I only do it locally—something that wouldn't have caught this issue. Going through the checklist _on_ beta would cover the most bases

**Comment by dondi** [comment]
(P.S. The fix was to restart both _nginx_ and GRNsight on the server)

**Comment by dondi** [comment]
Confirmed fixed at 2/17 meeting.
