### ISSUE TITLE
Export to excel not working for Additional Sheets

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#919]
Export to excel is not working for `optimization_parameters`, `production_rates`, `degradation_rates`, `threshold_b` sheets

**Comment by Onariaginosa** [comment]
I fixed the optimization_parameters export. But now the export functionality in my local machine is very suspicious. Sometimes it exports properly, but other times it redirects me to the site attached: 
![Screenshot from 2021-03-17 13-25-57](https://user-images.githubusercontent.com/21343072/111533742-5df76980-8724-11eb-8b83-f508ef15c2de.png)
And throws this error in my console: 
![Screenshot from 2021-03-17 13-13-07](https://user-images.githubusercontent.com/21343072/111533928-9b5bf700-8724-11eb-9e29-cf642cc17029.png)
But when I temporarily changed the code to what they requested, it doesn't export anything or show any signs of exporting.

**Comment by dondi** [comment]
The 400 status code suggests that our code is returning it—typically a server-level issue is a 5xx status code. So we can try search the sequence for /export-to-excel for cases when a 400 is returned.

Second possibility: keep the dev tools open while trying this and look at the payload just in case there is some information that may  be useful.

**Comment by Onariaginosa** [comment]
It turns out that the issue was in the demo objects. They were structured slightly differently than workbooks that we parse ourselves. Additional sheets usually have a section for data, errors, and warnings, but the demos didn't have that wrapper. They just contained the data directly. 

I fixed the optimization_parameters sheet export, as well as the two column sheet exports. Just need to add optimization diagnostics, and export functionality will be fully supported!

**Comment by dondi** [comment]
Looks like we are on our way here, just waiting for those remaining sheets mentioned above.

**Comment by Onariaginosa** [comment]
Completed export to excel for all additional sheets! Exported sheets re-upload with no warnings/errors! See pull request #920

**Comment by dondi** [comment]
Verified by @ahmad00m as fulfilled.
