### ISSUE TITLE
Inconsistency of viewport size in Dropdown menu 

### ISSUE THREAD

**Issue by ahmad00m** [dondi/GRNsight#923]
The dropdown menu for viewport size does not correctly reflect the size of the graph. I have attached a picture for this issue. 

<img width="1222" alt="Screenshot 2021-04-13 at 6 45 37 pm" src="https://user-images.githubusercontent.com/75926755/114642396-b15bc980-9c88-11eb-85bd-de00fe417233.png">

**Comment by igreen1** [comment]
In a last minute sprint, a refactor is ready that puts the viewport size options within `grnstate` and puts the control of viewport size in the `updateApp` logic.

Commit 06982c1fa30bcbcda52e7853ff9fb815426c48f6 holds the final fix for this bug.

**Comment by dondi** [comment]
PR pending; will try to include in the release.

**Comment by dondi** [comment]
Was released with v5.0.0
