### ISSUE TITLE
Release v5.0.0

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#928]
This page summarizes the steps that need to be taken when performing the next major GRNsight release. Steps are manual for now, but documenting them is the first step toward facilitating automation in the future.

The list is coded up using checkboxes, so that its source can be copied into a GitHub issue as a starting point for preparing a new release.

- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [x] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [x] the [feature JSON files](https://github.com/dondi/GRNsight/tree/beta/documents/developer_documents/testing_script_generator) file should be updated
    - [x] the new feature also needs to be added to the [Pull Request Checklist](https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist)
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
    - [x] Update Travis and Coveralls badges to reference the master branch
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [x] Update version numbers in _package.json_
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [x] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Refresh (pull) the `master` clone on _grnsight.cs.lmu.edu_
    - [x] Update the version number and modification date on `gh-pages`
    - [x] Update the About page with release notes (GitHub release item without issue numbers)
        - [x] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [x] Update modification date
    - [x] Add news item about the release to the News page
        - [x] Update modification date
        - [x] Link news item to the corresponding release notes in the About page
    - [x] Update Documentation page with any new features or updates to old features
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
    - [x] Update Travis and Coveralls badges to reference the beta branch
    - [x] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [x] Publish to _npm_ (`npm publish`)
    - [x] _npm_ requires all `.0`s in the semantic version
    - [ ] Check to see that BioJS updates its GRNsight entry
- [x] Update version number/other relevant information at current bioinformatics listing sites
    - [x] Elixir 
        - [x] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [x] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [x] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by dondi** [comment]
For posterity, before installing a long-overdue security update on the server
<img width="547" alt="image" src="https://user-images.githubusercontent.com/382242/131886149-0bdddb71-a6a4-4e8c-9d4e-112d8d9040e9.png">

**Comment by Onariaginosa** [comment]
I made sure that the features generator had all of the current features in GRNsight beta. I then regenerated the client side testing document, and tested the beta branch. I then updated the client side testing document wiki with the current document iteration.

**Comment by Onariaginosa** [comment]
There is a bug on master. The expression sheet database will load forever, and the nodes look like the picture below when you try and change the bottom data set to something from the database. On beta this occurs temporarily, but resolves once the database expression sheet data loads. The picture also shows the error shown in the web console.
![Screenshot from 2021-09-16 11-48-47](https://user-images.githubusercontent.com/21343072/133668488-2eb3858b-6b2e-4363-9f91-d26602857b57.png)

**Comment by dondi** [comment]
All done, but BioJS status is currently unknown.
