### ISSUE TITLE
Scheduling GRNsight meeting for Fall 2021

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#930]
It's time to schedule our weekly GRNsight meeting for the Fall semester!

It's easier for me to put down the times I'm *not* available:
Mondays: 8-9, 10-11
Tuesdays: not available
Wednesdays, 8-9, 10-11
Thursdays: 11:30-1:00
Fridays: 8-9, 3:30-5:00

There is some wiggle room for me on Tuesdays, but generally it's not a good day for me.

**Comment by dondi** [comment]
@Onariaginosa @igreen1 @ahmad00m go ahead and post/send me your respective schedules as well and I’ll collate to find intersections

**Comment by kdahlquist** [comment]
@dondi, I usually just look up student schedules on PROWL.

**Comment by dondi** [comment]
True—so students, you really only need to send restrictions that are outside of what your course schedules show. I will assume that scheduled courses are blocked off too, and I have access to those via PROWL

**Comment by Onariaginosa** [comment]
I have no restrictions (sans the classes scheduled in prowl) at the moment.

**Comment by ahmad00m** [comment]
I have no restrictions either.

**Comment by igreen1** [comment]
I should add that I am process for registering for a class Monday 6:30-9:30pm (overload so not on Prowl yet)

**Comment by dondi** [comment]
Greetings everyone,

After sorting through everyone’s schedules, the following slots have emerged as currently un-busy, for at least one hour, for all five of us:
* Thursdays 1–2pm
* Thursdays between 3:30-6:30pm
* Fridays 2-3pm

Ummm…that’s it 😅 There are other openings but they are all 30 minutes or less.

Any preferences/constraints among these? Please post here, thanks!

**Comment by Onariaginosa** [comment]
I prefer Thursdays between 3:30 to 6:30.

**Comment by kdahlquist** [comment]
I'd rather not have a meeting end later than 5:00 on Thursdays.  I could stretch that to 5:30 if I really had to, but it's not preferable.  So that means on Thursday afternoons, a start of 3:30 or 4:00 would work for me.  The other times work, too.

**Comment by Onariaginosa** [comment]
I have a class that ends exactly at 3:30 in St. Robs, so I might be a tad bit late to a 3:30 meeting. I'm fine with starting sometime between 3:30 to 4pm.

**Comment by dondi** [comment]
Yes sorry, for those slots I logged times right before and right after folks freed up, so that may eliminate the Thursday 1–2pm and Friday 2–3pm slots if people are coming from or heading to someplace sufficiently distant.

Given that factor and the comments so far, it’s looking like Thursday 3:45-4:45pm or 4-5pm is the leading candidate.

**Comment by kdahlquist** [comment]
I'll block off 3:45-5:00 on Thursdays just in case. Do we want to do in-person or on Zoom?

**Comment by Onariaginosa** [comment]
I am fine with either. I will be on campus during that time frame, so both in-person and Zoom work for me.

**Comment by igreen1** [comment]
Either works but I always lean for earlier is better (345-445)

Regardless, I can't make it 02/09 (first week) fyi as I'm taking the GRE

**Comment by ahmad00m** [comment]
I don’t have a preference either. I’m fine with both in-person or online.

**Comment by dondi** [comment]
Greetings—just wanted to let y’all know, I haven’t heard back yet from our admin in terms of getting a conference room reserved. I asked last week but then gearing up for this first week took over 😔 I finally managed to follow up today and will relay something as soon as I get a response.

As a backup, in case we don't get a conference room in either Featherston or Doolan, we can just meet in the Keck Lab. The annex side (Doolan 114) should have sufficient room.

We can also revert to Zoom; we've been operating that way anyway…

**Comment by dondi** [comment]
Directions for fall:
* 2021 senior project 
    * Database-related improvements: making existing datasets more flexible (full ability to manage them instead of loading them up manually)
    * Export to GRNmap to run models
    * Loading data into networks themselves
* Dr. Dabir’s project
    * Undirected arrows
* Some fresh issues (does not need to be fixed for 5.0.0)
    * Just discovered: arrow/blunt edge positioning on the right size (too far)
    * Adjustment anomaly upon first change to fit-to-window

**Comment by dondi** [comment]
The ball is rolling for fall now so I think we can close this.
