### ISSUE TITLE
Implement workbook export with user-chosen expression datasets

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#938]
Implement the user interface and functionality for choosing expression datasets to include in an exported workbook.

This task aligns with #935

For maximum flexibility, the user will be allowed to choose from any available dataset, regardless of whether they have used or selected it.

_But_ restrict the selections only to one source at a time, because expression data from multiple sources may not co-exist well, especially with GRNmap.

**Comment by Onariaginosa** [comment]
New Database Schema

**Comment by dondi** [comment]
@Onariaginosa and @dondi looked this and traced the root cause to a missing `id` header row on the problematic expression data sheet. However, the sheet also didn't have any data; this issue may be related. @Onariaginosa will investigate.

**Comment by Onariaginosa** [comment]
I added the fall2021 database to the aws database. On the Onariaginosa_temporary branch, I changed the query to match our current internal database structure, but I was having trouble accessing the results of said query, or even checking to see what the query returns.

**Comment by dondi** [comment]
@Onariaginosa will continue to learn some Sequelize to work out how to access query results and data; she will also provide sample of the expression metadata table so we can populate that table with appropriate values for the Dahlquist data.

**Comment by Onariaginosa** [comment]
Needed for the expression_metadata table:
replicate_index | ncbi_geo_id | pubmed_id | control_yeast_strain | treatment_yeast_strain | control | treatment | concentration_value | concentration_unit | time_value | time_unit | number_of_replicates | expression_table

**Comment by Onariaginosa** [comment]
1 | GSE9336     | 12269742  | S288C                | S288C                  | No Thiuram   | Thiuram   |                  75 | uM                 |         15 | m         |                    3 | Kitagawa_2002_log2_expression   | 
               2 | GSE9336     | 12269742  | S288C                | S288C                  | No Thiuram   | Thiuram   |                  75 | uM                 |         30 | m         |                    3 | Kitagawa_2002_log2_expression   | 
               3 | GSE9336     | 12269742  | S288C                | S288C                  | No Thiuram   | Thiuram   |                  75 | uM                 |        120 | m         |                    3 | Kitagawa_2002_log2_expression   | 
               1 | GSE6129     | 17327492  | W303-1A              | W303-1A                | No Arsenite  | Arsenite  |                   1 | mM                 |         60 | m         |                    6 | Thorsen_2007_log2_expression    | 
               2 | GSE6129     | 17327492  | W303-1A              | W303-1A                | No Arsenite  | Arsenite  |                   1 | mM                 |         15 | m         |                    3 | Thorsen_2007_log2_expression    | 
               3 | GSE6129     | 17327492  | W303-1A              | W303-1A                | No Arsenite  | Arsenite  |                   1 | mM                 |         30 | m         |                    3 | Thorsen_2007_log2_expression    | 
               4 | GSE6129     | 17327492  | W303-1A              | W303-1A                | No Arsenite  | Arsenite  |                   1 | mM                 |       1080 | m         |                    3 | Thorsen_2007_log2_expression    | 
               1 | GSE24712    | 23039231  | BY4741               | BY4741                 | No Potassium | Potassium |                  50 | mM                 |         10 | m         |                    2 | Barreto_2012_wt_log2_expression | 
               2 | GSE24712    | 23039231  | BY4741               | BY4741                 | No Potassium | Potassium |                  50 | mM                 |         20 | m         |                    4 | Barreto_2012_wt_log2_expression | 
               3 | GSE24712    | 23039231  | BY4741               | BY4741                 | No Potassium | Potassium |                  50 | mM                 |         40 | m         |                    4 | Barreto_2012_wt_log2_expression | 
               4 | GSE24712    | 23039231  | BY4741               | BY4741                 | No Potassium | Potassium |                  50 | mM                 |         60 | m         |                    4 | Barreto_2012_wt_log2_expression | 
               5 | GSE24712    | 23039231  | BY4741               | BY4741                 | No Potassium | Potassium |                  50 | mM                 |        120 | m         |                    4 | Barreto_2012_wt_log2_expression |

**Comment by Onariaginosa** [comment]
Everything works now. We query the fall2021 database and the results are the same as when we query in the master branch. Exported results are as expected. I initially found a bug where the gene mappings were incorrect, but when I looked at the source data, the Thorsen_2007 data had incorrect gene names. Because that came last, what I did was I collected the gene data from all of the other sources first, the the Thorsen data last, so that I would get the correct mappings from the earlier sources. This worked properly, and now we have the same database functionality that we did in the spring 2020 Expression Database. The pull request from the export auto updated, so it is now valid once more.

**Comment by Onariaginosa** [comment]
To ensure that the Expression Data in the database is correct I will check that the original Thorsen data from the [BioDB class data](https://xmlpipedb.cs.lmu.edu/biodb/fall2019/index.php/Sulfiknights_Deliverables#GRNmap_input_workbook) to track down where the data glitch came from.

**Comment by Onariaginosa** [comment]
The glitch appeared in the original Thorsen data. 
![Screenshot from 2021-12-02 09-41-25](https://user-images.githubusercontent.com/21343072/144474909-2b5a5ff7-0d70-40a5-9d64-682ee6f8f8f9.png)
YJR139C -> HOM6
YNL015W -> PBI2

**Comment by dondi** [comment]
“That’s very done” — @Onariaginosa
