### ISSUE TITLE
On beta and master workbooks or demos don't load at all

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#939]
The workbooks don't load whether you upload it, or use the demos. It works on my local server that I pulled from beta, but it is not working here. I attached a screenshot of the console when you attempt to load a workbook in both master and beta.

![Screenshot from 2021-10-07 09-31-47](https://user-images.githubusercontent.com/21343072/136426551-50e067b4-135b-4d31-abe3-1e8647bfcdaf.png)
![Screenshot from 2021-10-07 09-31-13](https://user-images.githubusercontent.com/21343072/136426554-783cdde0-df04-4c4a-9e97-f32182232f10.png)

**Comment by dondi** [comment]
The Google Analytics issue was traced to a typo in the presented credentials. All good now 🥴
