### ISSUE TITLE
Scheduling GRNsight meeting for Spring 2022

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#946]
Please add any scheduling constraints here. Class schedules can be retrieved from PROWL so we just need constraints outside of that.

**Comment by kdahlquist** [comment]
- I have weekly meetings from 11:30-1:00 on Tuesdays and Thursdays.  
- I teach 5:00-7:00 on Thursdays and would prefer not to run exactly up to 5:00 so I have a little buffer before my class.  
- Our department seminars are some Fridays at 3:00
- Other than that, I'm pretty open (although, I expect I will have other meetings scheduled)

**Comment by Sarronnn** [comment]
- My only constraints is  I work MWF from 9 AM - 2 PM

**Comment by ahmad00m** [comment]
I'm available any time after 11:10 am on MWF. On Thursdays I'm available after 4:10 pm and on Tuesdays I'm available between 11 am and 2:30 pm and after 4:10 pm.

**Comment by dondi** [comment]
Happy New Year folks!

After sorting through these plus class schedules, it’s looking like Monday 4pm is the main shared availability. There are windows on TR from 1:30-2:30pm but those are sandwiched between things for various folks so look less workable, but I’ll put those out there anyway just in case

Any thoughts on these?

**Comment by kdahlquist** [comment]
I would prefer Monday at 4:00.  I would not reliably be able to do the TR time slot you mention because of random meetings.

**Comment by dondi** [comment]
Temporarily reopening to check for one-off reschedule due to MLK holiday. Looks like it will be either Tuesday or Thursday within the range of 1–2:30pm; possibly Tuesday because it is closer to Monday.

Please comment as needed…

**Comment by dondi** [comment]
Leading candidate is 1–2pm Tuesday.

**Comment by ahmad00m** [comment]
I was wondering whether we could push the meeting tomorrow either earlier or later a bit. This is because I have a doctors appointment from 1-2 pm.

**Comment by kdahlquist** [comment]
I can do later, but not earlier.  @ahmad, we can meet separately layer if it doesn't work for others.

Kam D. Dahlquist, Ph.D.
Professor & Chair of Biology
Loyola Marymount University
________________________________

**Comment by Sarronnn** [comment]
My last class ends at 4. I can meet anytime after

**Comment by dondi** [comment]
According to my notes on who’s available, yes we don’t have @Onariaginosa and @kdahlquist prior to 1pm, then @ahmad00m, @Sarronnn, and I have class at 2:40pm. Everyone but me is free after 4:10pm but I have office hours

One possibility is that we meet after 4:10pm but sit in my office hours link. If no one walks in for office hours then the meeting can proceed. How does that work?

**Comment by ahmad00m** [comment]
If rescheduling is a lot of trouble I can meet separately with @kdahlquist and @dondi after 4:10 pm if that works (or any other time if that works better). I don’t want to mess up the set meeting time.

**Comment by Sarronnn** [comment]
4:10 works for me.

**Comment by dondi** [comment]
Perhaps the separate meeting will be best then? 4:10pm is on the late side and there is a risk of overlap with my office hours (admittedly small because it’s early in the semester but you never know)

**Comment by kdahlquist** [comment]
How about keeping the original meeting time. Ahmad and I will come to Dondi's office hours and if other people show he can put us in  breakout room.

Kam D. Dahlquist, Ph.D.
Professor & Chair of Biology
Loyola Marymount University
________________________________

**Comment by dondi** [comment]
Yes, I think that’s the best of both worlds 👌🏽 I’ll send my office hours Zoom link under separate cover
