### ISSUE TITLE
Investigate Yeastract and SGD APIs for regulatory information

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#949]
SGD may be YeastMine. We want to look for regulation information there if available.

In the absence of API availability, we may need to develop a mechanism for storing the GRNs in our own database, and importing into them based on published files.

**Comment by Onariaginosa** [comment]
During this weekly session I went to YeastMine and selected the regulators tab. From there I was able to get all of regulator genes, and search for the targets of each regulator. YeastMine provided code to do this, so I am currently creating a file to generate all of the regulator and target genes.

During the meeting @kdahlquist mentioned that I should generate 2 adjacency matrices, a 295x295 regulator by regulator matrix that is primarily used in GRNmap, as well as the 295x???? regulator by target matrix.

**Comment by kdahlquist** [comment]
200x6000 regulator X target

I'm not sure how many genes SGD will classify as a regulators, it will be ~175-250.

**Comment by Onariaginosa** [comment]
I created the script to generate the regulators by regulators adjacency matrix as well as the regulators by targets adjacency matrix. There were 294 genes classified as regulators, and I generated all of their targets. Some genes did not have a standard name, so in the script they are not currently in the matrices.

**Comment by kdahlquist** [comment]
When there is no standard name, we need to substitute the systematic name instead.

**Comment by Onariaginosa** [comment]
I made the appropriate fix and regenerated the adjacency matrices.

**Comment by dondi** [comment]
Decided at the meeting to commit this work to a new top-level folder called _database_. _.gitignore_ will also be revised to avoid accidental committal of files produced by these scripts

**Comment by Onariaginosa** [comment]
This is complete
