### ISSUE TITLE
Refactor existing database code into a genuine DAL module

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#950]
Our existing database code needs a refactor to a full-fledged DAL, especially if our database capabilities will continue to expand.

**Comment by Onariaginosa** [comment]
I think I created a sort of DAL. I isolated the querying of the expression database and getting a response into a file called `grnsight-dal.js` and made the database-controller compatible with querying to the network database as well. I also cleaned up the code a bit so there is less repetitions. This is in the Onariaginosa branch.

**Comment by dondi** [comment]
Upon review of the work so far, the direction looks good and next steps are:
1. Pull out the database code from the _database-controller.js_ file and place it in _dal/expression-database.js_ (or similar), with _database-controller.js_ being renamed and very likely getting a lot smaller than it is now
2. The work done in _grnsight-dal.js_ actually pertains to the API rather than the database and has been separated out as a new issue #957

**Comment by Onariaginosa** [comment]
This is complete

**Comment by dondi** [comment]
Code is reviewed and will go out with the next GRNsight release.

**Comment by dondi** [comment]
DAL code was merged into beta but when it was deployed to the GRNsight server it produced an error relating to a new import statement—we’ll need to look into this.

**Comment by dondi** [comment]
In order to try a new deployment, make sure to do the following:
* `git checkout beta`
* `git pull`

This is because we reverted beta to a prior state in order to keep the service running.

**Comment by dondi** [comment]
Need to review status of this with @Onariaginosa

**Comment by dondi** [comment]
Confirmed as finished
