### ISSUE TITLE
Define data model and schema for GRNs

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#951]
The schema should allow imports from other sources; it will also allow us to store our own GRN data. The model should also support multiple species in the event that we expand to those later.

**Comment by dondi** [comment]
Looking forward to #954, let’s seek to include a timestamp in the schema wherever it’s appropriate.

**Comment by Onariaginosa** [comment]
I have a preliminary schema for the network database
![ProposedNetwork Database Schema](https://user-images.githubusercontent.com/21343072/153932723-634535e9-b117-4458-a353-d7efec1237f0.jpg)

**Comment by Onariaginosa** [comment]
I have completed the preprocessing of this data and will begin working on the loader to load it into the database

**Comment by dondi** [comment]
Follow-up issue for this (loader) is #960
