### ISSUE TITLE
Design and implement a user interface for accessing GRN data

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#952]
With the emerging GRN database for this semester, we will need an end-user UI for navigating and accessing that database. The UI should allow a user to query our GRN data and to derive a visualizable network based on the query.

**Comment by Onariaginosa** [comment]
Proposed UI
Note, for the top bar the Network tab would be before layout. I just put it where the old species tab was for convienience and visualization purposes
![GRNsight Proposed Network Database UI ](https://user-images.githubusercontent.com/21343072/159354028-6406c11f-2c48-4da5-b85d-f6200e476ee0.png)

**Comment by dondi** [comment]
Some design notes:
- Move _Network_ to the leftmost spot, replacing _File_
- The _Open_ and _Reload_ items in _File_ now go to _Network_; plan on providing feedback (maybe on the right side of menu bar) indicating active source of what’s visible
- Factor in _Demo_ as a third source of network data
- Move _Export_ and _Print_ items to a new _Export_ menu that is positioned where _Species_ is now
- Use the right side of the menu bar (where demo or file name currently appear) to give the user a status on what they’re looking at

**Comment by Onariaginosa** [comment]
Began creating the UI in GRNsight
![Screenshot from 2022-03-28 13-53-09](https://user-images.githubusercontent.com/21343072/160486342-50991459-cc44-455a-9864-0b43c3931a87.png)
![Screenshot from 2022-03-28 13-45-28](https://user-images.githubusercontent.com/21343072/160486346-096af28f-3cfb-45b6-a894-e8c7d456e549.png)
![Screenshot from 2022-03-28 13-45-18](https://user-images.githubusercontent.com/21343072/160486347-53110c38-cdc8-4258-bbd4-2e2aba9fbcf6.png)

Ran into issues with the top navbar implementation. On click the top nav collapses. This means that we can't actually search in the search bar. I am considering making the create a network a button that pops out to a modal, then both upper nav and side can look as follows:

Top Bar / Box Navigation:
- Network
  -  Reload
  -  Species (works in accordance with original species tab)
  -  Load from Workbook (Title)
     -  Open FIle (Button)
  - Load from Demo
     - Dropdown of all the demo network options
  - Create custom Network (Title)
     -   Create Network (Opens a modal that lets you create using Network Database
         -  Page 1
            -  Species Selection (Only shows species in Database, so only yeast)
            -  Dataset Selection 
         -    Page 2
              - Gene search bar
              - Genes added ( on click to remove)
 
  -  Species (works in accordance with original species tab)

**Comment by dondi** [comment]
Try attaching a `click` handler to the `input` element and make it have the following:

```javascript
event => {
  event.stopPropagation()
  // .....etc.
}
```

**Comment by dondi** [comment]
Proposed new hierarchy:
* Network Source
    * Demo
    * Open File…
    * Load from Database…
* Reload
* Species (informational only—eliminate warning as well)

We should also transition existing species functionalities out and possibly the Gene Page completely.

**Comment by dondi** [comment]
Also look into Pug’s `include` feature to make the overall source file more readable and have fewer copied elements

**Comment by Onariaginosa** [comment]
Created a bare bones version of this. Once I connect the Network database to the front end we should be able to test it out.
All other functionality (reload, loading demos, opening a file) appears to be working in all of the Network sections, and will pretty up the css once a workable product is made
![Screenshot from 2022-04-04 13-50-45](https://user-images.githubusercontent.com/21343072/161630196-94a79163-f202-4f35-93e0-f4546cc2f094.png)
![Screenshot from 2022-04-04 13-50-38](https://user-images.githubusercontent.com/21343072/161630197-08770d70-ab27-44ce-a140-f1d4d5948aa6.png)
![Screenshot from 2022-04-04 13-49-59](https://user-images.githubusercontent.com/21343072/161630198-39944f6d-0286-4803-8ffe-8144a74dfaf5.png)

**Comment by dondi** [comment]
@dondi reviewed this with @Onariaginosa and overall it looks good, with some suggested tweaks for greater clarity. Primarily, in the sidebar version, we’ll try to make it clearer that Demo, File, and Database are “under” the Network Source heading (in the same vein as in the dropdown menu version). Also, to save space, the file extension guidance for “Open File” will be turned into a tooltip

**Comment by Onariaginosa** [comment]
Attached are the pictures of the UI. I made the changes above and began connecting the backend network database to the Create Network Modal.  I have successfully connected the Network Source dropdown menu, and am in the process of connecting the search bar to select genes from said source. 
![Screenshot from 2022-04-11 13-03-41](https://user-images.githubusercontent.com/21343072/162824470-9b7b0044-40eb-4e7d-8570-4ec4ce742c33.png)
![Screenshot from 2022-04-11 13-20-14](https://user-images.githubusercontent.com/21343072/162825119-d1598047-7182-4636-9452-4df81bb14da2.png)
![Screenshot from 2022-04-11 12-59-37](https://user-images.githubusercontent.com/21343072/162824833-eeff7763-c984-46f8-a08d-b865e9956f4b.png)
![Screenshot from 2022-04-11 13-16-54](https://user-images.githubusercontent.com/21343072/162824799-dfa64315-89c5-4f7c-b5eb-c26ba2517493.png)

**Comment by dondi** [comment]
Progress is looking good; we discovered a behavior that appears to be correct only on Firefox (i.e., selection of demo from sidebar `select` element) and @Onariaginosa will look into using the jQuery `change` event rather than `click` to see if that addresses things

Next up is continuing work on the database dialog

After the functionality is established, we’ll do a styling pass to ensure uniform padding, sizes, etc.

**Comment by dondi** [comment]
We found this page, which may have relevant information on `select` behavior: https://caniuse.com/?search=select

**Comment by dondi** [comment]
The feature looks nearly ready, just needing some wrap-up work:
- Minor styling tweaks just to line things up
- Updates to the testing document (@ahmad00m said he would help)
- Final pull request for review and eventual merge into beta
- Potential target of GRNsight v6.0.0 (with @Sarronnn’s fixes potentially) in early summer (or maybe even before May 16 😉)

**Comment by dondi** [comment]
@Onariaginosa is slated to present this work on Wednesday 4/20 4:30pm in Featherston 120. @Onariaginosa will seek to acquire a streaming link for those who can’t be there physically

**Comment by Onariaginosa** [comment]
@kdahlquist 
@dondi 
Streaming link obtained:  https://lmula.zoom.us/j/87301578677

**Comment by dondi** [comment]
@Onariaginosa try revising your event handlers such that they invoke `event.preventDefault()` and/or `event.stopPropagation()`. Try some combination of those two calls in the event handler(s) and see if that makes a difference

**Comment by dondi** [comment]
If this doesn’t get resolved @dondi can take a deeper dive

**Comment by kdahlquist** [comment]
Feature has been implemented.  Feature requests and bugs will be reported as new issues.
