### ISSUE TITLE
Work on Undergraduate Research Symposium 2022 posters

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#953]
Likely due on the first week of February

Targeting two abstracts:
* Talk—focus on database and @Onariaginosa’s work (like it or not 😁)
* Poster—broader, more general improvements etc.

**Comment by dondi** [comment]
Abstracts confirmed due February 4; symposium is March 18–19 (biology is on the 18th 3–6pm in LSB, oral in auditorium and poster session in courtyard)

**Comment by Onariaginosa** [comment]
I completed the abstract for the talk discussing the database work [here](https://github.com/dondi/GRNsight/wiki/2022-Undergraduate-Research-Symposium-Abstract,-Onariaginosa-Igbinedion)

**Comment by ahmad00m** [comment]
Here is the [Abstract](https://github.com/dondi/GRNsight/wiki/2022-Undergraduate-Research-Symposium-Abstract,-Ahmad-Mersaghian-and-Sarron-Tadesse) for adding the new dataset to GRNsight.

**Comment by Onariaginosa** [comment]
Hello! Is it confirmed whether I am a talk or a poster yet?

**Comment by kdahlquist** [comment]
Standby.  I'll be able to confirm later today, still working things out in my department.

**Comment by kdahlquist** [comment]
@Onariaginosa, you are off the hook for a talk (for the URS).  Please submit your abstract for a poster.

**Comment by Onariaginosa** [comment]
Kk, will do!!! 😁

**Comment by Onariaginosa** [comment]
I officially submitted!

**Comment by kdahlquist** [comment]
Did @ahmad00m and @Sarronnn submit?  I didn't get an e-mail like I did when @Onariaginosa submitted.

**Comment by ahmad00m** [comment]
Yes, I submitted it this morning. I put you and Dr. Dionisio in the Mentor section and @Sarronnn as a group member.

**Comment by ahmad00m** [comment]
Did Dr. @kdahlquist receive the email for verifying the abstract submission?

**Comment by kdahlquist** [comment]
I didn't, but if you listed @dondi first, it may have just gone to him.  The system that they use is not too reliable, so I'm not worried.

**Comment by ahmad00m** [comment]
I actually listed you first.


<img width="1440" alt="Screenshot 2022-02-04 at 10 08 06 am" src="https://user-images.githubusercontent.com/75926755/152580609-97193982-efa9-460b-a561-0d33db0493d1.png">

**Comment by kdahlquist** [comment]
OK, but I'm still not worried.  I bet their system can't handle two names.  You could e-mail "symposium@lmu.edu" if you want, but I'm sure it's fine.

**Comment by ahmad00m** [comment]
Okay, sounds good. Thank you!

**Comment by dondi** [comment]
I haven’t gotten anything, but that may be because the due date was extended by a week? I just got notification of that this morning.

**Comment by ahmad00m** [comment]
I emailed the symposium and they confirmed the abstract was submitted.

**Comment by dondi** [comment]
Target: have the poster ready over the week of March 7 so that it can be finalized during the March 14 meeting

**Comment by Onariaginosa** [comment]
Here is my poster draf
[Igbinedion_LMU_SYMPOSIUM_2022.pptx](https://github.com/dondi/GRNsight/files/8244569/Igbinedion_LMU_SYMPOSIUM_2022.pptx)
t

**Comment by ahmad00m** [comment]
I drafted a poster but it seems very empty as I did not have a lot of improvements to add. But here it is
[Mersaghian_Tadesse_LMU_SYMPOSIUM_2021.pptx](https://github.com/dondi/GRNsight/files/8248762/Mersaghian_Tadesse_LMU_SYMPOSIUM_2021.pptx)

**Comment by Onariaginosa** [comment]
Here is a second draft of my poster all changes made, sans the availability section.
![Igbinedion_LMU_SYMPOSIUM_2022 pptx](https://user-images.githubusercontent.com/21343072/158285980-754e261d-d66f-442e-8cef-1c27068faee1.jpg)
[Igbinedion_LMU_SYMPOSIUM_2022(1).pptx](https://github.com/dondi/GRNsight/files/8249332/Igbinedion_LMU_SYMPOSIUM_2022.1.pptx)

**Comment by ahmad00m** [comment]
This is the second draft of the poster.
[Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx](https://github.com/dondi/GRNsight/files/8256562/Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx)

**Comment by kdahlquist** [comment]
@ahmad00m and I met over Zoom to review the new version.  We finalized the text and he just has to make some rearrangements to make it all fit.  New version is attached here.  Once he finalizes it, I'll get it printed.
[Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx](https://github.com/dondi/GRNsight/files/8257327/Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx)
.

**Comment by kdahlquist** [comment]
@Onariaginosa, I reviewed your poster and made some changes to the wording and alignment--it is attached here.  If @dondi approves it is good to print.  I'll wait for his approval before I put it in the print queue in the department.

[Igbinedion_LMU_SYMPOSIUM_2022.4.pptx](https://github.com/dondi/GRNsight/files/8257899/Igbinedion_LMU_SYMPOSIUM_2022.4.pptx)

**Comment by ahmad00m** [comment]
I have some space left in the preparation of dataset section. Should I create a flow chart summarising the number of records at each step in this section?

**Comment by kdahlquist** [comment]
That sounds great!

Kam D. Dahlquist, Ph.D.
Professor & Chair of Biology
Loyola Marymount University
________________________________

**Comment by kdahlquist** [comment]
I did a few small edits.  This is the final version for printing
[Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx](https://github.com/dondi/GRNsight/files/8268713/Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx)
.

**Comment by kdahlquist** [comment]
I'm having it printed.

**Comment by dondi** [comment]
Oops sorry for the delay! Yes let’s ship it :shipit:

**Comment by kdahlquist** [comment]
OK, printing @Onariaginosa 's poster

**Comment by dondi** [comment]
Posters from the session will be used to update existing posters in Doolan and Featherston
