### ISSUE TITLE
GRNsight 5.1.0 appears to be running inconsistently

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#955]
- @Sarronnn’s fresh start-from-scratch build appears to be running into errors
- Beta is also broken for everyone
- Home (production) is broken for some, but not for all

**Comment by kdahlquist** [comment]
@kdahlquist is running Firefox 96.0.2

**Comment by Onariaginosa** [comment]
Firefox: 96.0
Chrome: Version 97.0.4692.71 
It is broken on beta and home on both browsers.

**Comment by dondi** [comment]
Clearing cache causes the problem to _consistently_ appear (for @dondi)

**Comment by ahmad00m** [comment]
- Safari 15.0
- Chrome 97.0.4692.99

**Comment by dondi** [comment]
After doing some tinkering on the GRNsight server, both production and beta appear to be working for me now. I haven’t done a full sweep, but I can load the demos and change various settings. Dataset loading also works for me.

When folks get a chance, can you confirm what I’m seeing? Thanks!

**Comment by dondi** [comment]
Clarification—this is for the website; Sarr’s installation continues to need further investigation.

**Comment by ahmad00m** [comment]
I was able to load the demo files and see the graph. Also, the feature on GRNsight work as expected with no issues.

**Comment by Onariaginosa** [comment]
It works properly on Chrome and Firefox for me. It does the same incorrect placement for the Zoom buttons for a second then loads correctly on both. I think it might just be the web-client loading.
