### ISSUE TITLE
Consolidate existing web app API calls into an abstraction layer

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#957]
@Onariaginosa started some work in #950 which, although is different from a DAL, works on the same principle of consolidating implementation code behind functions so that other code does not have to factor in those implementation details. On the web client side, this involves all networking code. Ideally, network code is restricted to a single module which declares functions that deliver the results of that code, and the rest of the web app only “sees” these as functions

**Comment by Sarronnn** [comment]
ISSUE: GRN sight does not run on versions other than node 14.
- Prof.Dondi suggested downloading node V 14 on Home-brew
     - <img width="1440" alt="Screen Shot 2022-09-14 at 8 52 14 AM" src="https://user-images.githubusercontent.com/89826597/190202949-ecf6c4c0-ba70-47e9-9145-ae258fdd1971.png">
- Tried downloading node V 14 manually:
<img width="1440" alt="Screen Shot 2022-09-09 at 1 33 39 PM" src="https://user-images.githubusercontent.com/89826597/190203216-8c3b03bb-1631-4eea-803e-43702837c67d.png">
    - Now the local host works! But error message still exists : " [nodemon] app crashed - waiting for file changes before starting... "
How would I proceed?

**Comment by dondi** [comment]
Upon revisiting this issue, it appears that it has already been done. @Onariaginosa, @ahmad00m, and @Sarronnn can walk through this code together to verify that the transition has indeed been completed:
* Ensure that all back end interactions go through the _public/js/api/grnsight-api.js_ functions only
* Look for vestigial calls to `$.ajax` or `$.getJSON`, maybe even `window.fetch` and refactor those to use functions from _grnsight-api.js_ instead

If the transition looks complete, we can go ahead and close this issue

**Comment by dondi** [comment]
Code has been reviewed and one last spot check during 10-12 meeting supports this

There are lingering `$.ajax` and `$.getJSON` calls in the code, but these are for server functions that do not access the database. Technically good to also transition but these were not in the scope of this issue
