### ISSUE TITLE
Start working on documentation for database network loading scripts

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#961]
As the network loading code stabilizes, we will need to write up documentation (likely .md files) so that other users can generate new networks and load them into their databases as needed.

Python code should also be run through a linter; OK to do this manually. [PyCharm](https://www.jetbrains.com/pycharm/download/) may be the most convenient because it is Python-based from the ground up and reformatting should be one-key right out of the box (as opposed to having to install additional plugins on other systems)

**Comment by dondi** [comment]
(can already be done for #949 and should also be done for #960 when finished)

**Comment by Onariaginosa** [comment]
I started on the documentation. Progress is slow, but forthcoming.

**Comment by Onariaginosa** [comment]
Documentation is complete as mentioned in issue #988

**Comment by Onariaginosa** [comment]
This is contained in WIP PR #985

**Comment by dondi** [comment]
Will close for prior version of docs; if revisions are needed due to latest time zone changes, open a new issue and work using that
