### ISSUE TITLE
WCBSURC abstract and poster

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#963]
@ahmad00m will prepare an abstract for submission to WCBSURC, Saturday, April 9.  Deadline is this upcoming Thursday so that the abstract can be submitted and Ahmad can register for the conference.

Conference website: https://www.pointloma.edu/news/wcbsurc-announcing-our-45th-year

This is the abstract submission form (you have to follow the link to see the instructions): https://forms.gle/nQ5JSevm8MFjXK9y8
See what the format and length is.  I don't think titles are restricted, so we could have a longer title.

This is the registration form (after abstract is submitted): https://forms.gle/u7sNGLyMUkauZgoDA

Do not pay, the Biology Department will pay for the registration.

**Comment by ahmad00m** [comment]
I checked out the website and it mentions the abstract length should be typed using Times New Roman 12 Font; 250 words maximum. Also, the title should be bolded but they don't specify how long it should be, but the sample abstract has 16 words in its title. So, should I write a longer title for it? 
Also, the deadline for abstract submission and payment is Saturday, March 12th.

**Comment by kdahlquist** [comment]
Actually, I think your title and abstract is OK as is.  Go ahead and format it like they want and submit.  Please also fill out the registration form.  It's a Google Form.  Select "early registration $50" and "credit card".  You won't have to pay.  The Biology department is going to pay on the department credit card.  Although the deadline is the 12th, we need everyone to register by tomorrow so that Toa can do the payment on Friday (she doesn't work on Saturdays).  Thanks!

**Comment by ahmad00m** [comment]
Okay sounds good. Also, should I put anyone elses name beside yours and Dr. Dionisio?

**Comment by kdahlquist** [comment]
You can include Sarr and Ona, but indicate that you are the presenting author.

**Comment by ahmad00m** [comment]
Ok, will do!

**Comment by ahmad00m** [comment]
I finished submitting the abstract and completed the registration form. I have not yet received a confirmation email but I will update you as soon as I receive one. Thank you!

**Comment by ahmad00m** [comment]
I have not yet received the confirmation for my abstract and I doubt I will, but I got a message after submitting the google form saying the submission was successful.

**Comment by ahmad00m** [comment]
I have made some changes to the poster from the symposium, I just replaced some figures to demonstrate the result of GRNmap on the network weights. Also, I briefly changed the future directions. Please let me know if any other changes need to be made.
[Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx](https://github.com/dondi/GRNsight/files/8445802/Mersaghian_Tadesse_LMU_SYMPOSIUM_2022.pptx)

**Comment by kdahlquist** [comment]
I'm sorry, I'm unable to review the poster.  I'm sure it's fine.  Toa is out today.  Please contact Brianne or Tanya to help with printing.  Brianne.Zapata@lmu.edu, Tatiana.Kuzmenko@lmu.edu

**Comment by ahmad00m** [comment]
Ok, thank you Dr. Dahlquist.

**Comment by dondi** [comment]
@ahmad00m make sure to archive all recent posters (UGRS and WCBSURC) in our archives https://github.com/dondi/GRNsight-archive/tree/main/documents/posters
