### ISSUE TITLE
Bug with Species Functionality in Top Toolbar in Master and Beta

### ISSUE THREAD

**Issue by Onariaginosa** [dondi/GRNsight#965]
If you change the species in the top toolbar, the page glitches out. 
I will investigate this, as I incorporate the species tab into the new Network tab.
![Screenshot from 2022-03-27 15-19-48](https://user-images.githubusercontent.com/21343072/160303493-bbfa3e70-f8b0-417d-8be5-2b23019c1209.png)

![Screenshot from 2022-03-27 15-20-01](https://user-images.githubusercontent.com/21343072/160303491-2d5b364a-1ce1-458c-bac8-a5653b5acadf.png)

**Comment by dondi** [comment]
Good for a hotfix—probably best to set `display: none` in order to minimize side effects to other code

**Comment by dondi** [comment]
Closing without fixing—the recent changes to the UI nullify this issue.
