### ISSUE TITLE
creating network from database miscounts edges in display of name

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#972]
I used the create a network from database tool to make a network with 12 genes and 17 edges.  The count of the edges is correct on the far right of the menu toolbar, but the Custom Network "filename" that displays to the right of the demo menu miscounts the edges and says "12 genes, 7 edges".  This carries through to the export to Excel menu.  See screenshots:

![image](https://user-images.githubusercontent.com/6463867/184408619-2d8f56a8-d214-4b5d-8619-b38ad62b1e80.png)

![image](https://user-images.githubusercontent.com/6463867/184408717-c6c80715-cc19-446e-801c-586a26322ca1.png)

**Comment by Onariaginosa** [comment]
This was fixed in WIP PR #985

**Comment by dondi** [comment]
Already merged
