### ISSUE TITLE
Scheduling GRNsight meeting for Fall 2022

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#973]
The new academic year is nigh! And for the first time in a few years, I do believe we have a graduate student among our ranks 😊 Please add any scheduling constraints here. Class schedules can be retrieved from PROWL so we just need constraints outside of that.

**Comment by ahmad00m** [comment]
My only constraint is on Tuesdays 9:40 - 11:10 A.M.

**Comment by kdahlquist** [comment]
My teaching schedule is MWF 8:00-8:50

Additionally, I'm NOT available:
M 1:00-2:00 (although this meeting could be moved)
T 12:00-1:30
W 10:30-11:30
R 11:30-1:00
F 3:00-5:00

**Comment by Sarronnn** [comment]
Update: I am not available T,Th,&F from 9am-3pm.

**Comment by kdahlquist** [comment]
I added some unavailable times to my comment above.  I added my office hours.  These are fungible until Monday when school starts.

**Comment by dondi** [comment]
Apologies, it took a bit for me to finish putting things together. I have sent an email showing the combined schedule. There is only one “everyone is available” slot and that is indicated in the email. We can either go with that or we can consider some splits based on “some are available” ranges

Also, is it safe to say that we have been OK with Zoom and can keep it that way this semester? Or shall we look into an in-person meeting? (thus requiring a room reservation)

**Comment by kdahlquist** [comment]
I can move my Wednesday unavailability so that we can all meet from 11:45-12:45.  That was my office hours, which are not set until I give out my syllabus on Monday :)

**Comment by kdahlquist** [comment]
I'm OK with Zoom.

**Comment by dondi** [comment]
Alrighty, it looks like this semester will be Wednesdays 11:45am–12:45pm on Zoom! I will send the link under separate cover
