### ISSUE TITLE
Demo indicators appear to out of sync

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#976]
In current v6.0.0, choosing a demo from the sidebar dropdown menu does not update the UI consistently.

Choosing from the menubar continues to work as expected.

**Comment by Onariaginosa** [comment]
I fixed this issue on the Onariaginosa branch!

**Comment by kdahlquist** [comment]
PR #985

**Comment by dondi** [comment]
Already merged into beta and verified at an earlier meeting
