### ISSUE TITLE
Intermittent bug with Load from Database modal: cursor doesn't register in search field initially

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#980]
I am finding an intermittent bug with the Load from Database modal.  It seems like when I first open the modal, I can't click on the search field and have the cursor go there for me to type.  This problem then disappears after a while, and I can't figure out why.

**Comment by dondi** [comment]
This may be fixed but we will try this across the board to see if someone can replicate it

**Comment by dondi** [comment]
Will revisit when beta has (finally) been deployed and once confirmed that it can’t be replicated, we can close

**Comment by Sarronnn** [comment]
I was not able to replicate this bug on beta v6.0.4. I can click on the search field and type with no problem.

**Comment by kdahlquist** [comment]
Since @Sarronnn found this is not replicable, we will close this issue.
