### ISSUE TITLE
Export to Excel modal gets messed up if cancel out of it and go back in

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#981]
Do this:
- Export to Excel
- Close out of modal window 1 by clicking the x in the upper right or close button
- Select Export to Excel again, you get this:
![Export-to-Excel-modal-bug_v6 0 0](https://user-images.githubusercontent.com/6463867/188974058-9e666494-8d70-42ee-afaf-c85f06af177f.jpg)

It seems to be recursive in that if you cancel again and export again, it will add another row of radio buttons.

**Comment by dondi** [comment]
Looks fixed at the meeting but will stand for deeper examination

**Comment by kdahlquist** [comment]
confirmed fixed in beta 6.0.7
