### ISSUE TITLE
Bad interaction between node coloring, load network from database, and export to Excel

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#984]
As noted in issue #977, the node coloring menu should be activated all the time now because we have a gene expression database.  One fallout is this interaction. Do the following:
- load a demo file
- load a network from the database
- the node coloring panel/menu is now active, with the enable node coloring checkbox checked, but no node coloring is showing on the graph
- Export to Excel and the modal opens, but you can't actually click on anything (radio buttons or other buttons) nothing works.

**Comment by Onariaginosa** [comment]
I fixed this and it should make its way into the never ending pr #996. The `grnState.node.coloring.topDataset` and `grnState.nodeColoring.bottomDataset` settings weren't getting when a user generates a new network, so I set them = to undefined and it worked.

**Comment by kdahlquist** [comment]
confirmed fixed in beta 6.0.7
