### ISSUE TITLE
Onboard the team with a locally running database

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#988]
After discussing this issue during the meeting, the preferred approach for developers on the team will be to install and run their own copy of PostgreSQL on their respective devices

- Some course notes on installing PostgreSQL: https://dondi.lmu.build/share/db/postgresql-setup-day.pdf
- Configuration can be found in _server/config/config.js_
- Database connection logic can be found in _server/dals_

@Onariaginosa, @ahmad00m, and @Sarronnn will plan a meeting during the week to walk through process, with @dondi being available to consult just in case. Original data files have been linked to under separate cover and may need to updated to @Onariaginosa’s latest copy

We will also take advantage of this to review our database documentation and loader scripts in the _database_ folder of the repository. The hope is to get the documentation to a point where new members can also walk through it in order to get up and running (perhaps something for @ntran18 to try in the future)

**Comment by Onariaginosa** [comment]
I updated the documentation for loading data into an existing database. it is currently located [on my branch](https://github.com/dondi/GRNsight/tree/Onariaginosa/database). I was thinking that maybe we should either create a wiki page on setting up a local psql database or add it to the [almost empty README.md at the top level database folder](https://github.com/dondi/GRNsight/blob/Onariaginosa/database/README.md).

**Comment by Onariaginosa** [comment]
I updated the documentation of the [top level database folder's README.md](https://github.com/dondi/GRNsight/blob/Onariaginosa/database/README.md) so it gives full and in depth instructions on how to set up a local database instance

**Comment by dondi** [comment]
The created documentation looks really good and precise; @ahmad00m will try this on a different computer to test out how it feels when starting fresh

Database documentation can be a slippery slope because it does require a certain level of familiarity to begin with; otherwise the amount of explanation/background needed could expand excessively. So one potential addition to the docs would be a “Prerequisites/Assumptions” section stating the expected familiarity that the reader might have. Some supplementary third-party links may also be useful in order to introduce basic concepts about databases that we prefer to assume is already known to the reader

The link-out to Linux instructions looks good, and again that is hard to cover fully anyway due to the wide range of Linux distributions out there

Minor note for the future: namespace choices can probably be revised to have a more permanent feel (i.e., remove semester timestamps) as this feature settles in

We’ll monitor the Intermine error to see if it was just a one-off or something that might be worth reporting to the package maintainers

**Comment by dondi** [comment]
Also it sounds like the team successfully completed installation, but live testing for successful interaction with the local database has not been verified; that would be part of this issue before we can close it out

**Comment by dondi** [comment]
A common issue reported by both @ahmad00m and @Sarronnn was that the local web app still appears to not connect successfully to the local database. @dondi pointed out that the _server/config/config.js_ file might not be sufficiently updated yet for the `development` configuration. So the group should look at that next in order to accomplish the ultimate goal which is to be able to run the GRNsight software alongside a locally-installed database

**Comment by dondi** [comment]
We were able to resolve this issue; it turns out that the _pg_ library needed to be updated on @dondi’s, @ahmad00m’s, and @Sarronnn’s devices. The database was successfully accessed after that

Committed version was 8.0.0 and updating to 8.8.0 resolved the local database problem

However, a follow-up question remains regarding why @Onariaginosa had an operational stack even while on _pg_ 8.0.0. The two variables that were identified were:
* @Onariaginosa was on Node 12
* The platform was Ubuntu rather than macOS

Everyone had the same PostgreSQL version and the same versions of the other libraries. We will close this issue but open another one that will document this versioning question
