### ISSUE TITLE
Transition remaining “bare” network calls to API module

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#993]
There are some lingering `$.getJSON` and `$.ajax` function calls in the web app, all from the original GRNsight logic that did not need the database. Ideally, these should get folded into the _grnsight-api.js_ module as well so that all such network calls are in one place

**Comment by Sarronnn** [comment]
<img width="1202" alt="Screen Shot 2022-10-19 at 9 02 21 AM" src="https://user-images.githubusercontent.com/89826597/196744510-071cb389-55b6-48dc-a22b-ca4bf78d0694.png">
<img width="1202" alt="Screen Shot 2022-10-19 at 9 02 13 AM" src="https://user-images.githubusercontent.com/89826597/196744537-72693f8c-4ad2-4b5a-9754-3aba4998fa32.png">
I moved the function call of $.ajax from setup-load-and-import-handles.js into the grnsight-api.js file
- Functionality of local host is not maintained
- Question: when moving the $.ajax function call, I have to move everything that calls $.ajax ?
          - Same question for $.getJSON

**Comment by dondi** [comment]
The `done` function is what the `loadGrn` function does with the result of the network call, so what I would do here is:
1. Keep `loadGrn` where it is
2. The part that goes to the _api.js_ file is lines 148-158. This becomes the abstracted function…can’t think of the right name offhand but it will look something like _loadNetwork_—maybe consultation with @ahmad00m or @Onariaginosa will be good here
3. The code in the `done` function stays in `loadGrn` as the callback to perform after _loadNetwork_ finishes

**Comment by Sarronnn** [comment]
Wrote two functions inside gun-sightapi.js :
- LOAD_AJAX
- GET_JSON
<img width="705" alt="Screen Shot 2022-10-26 at 10 52 53 AM" src="https://user-images.githubusercontent.com/89826597/198100740-0f12b894-a7a0-4734-a668-79ec3b7f464b.png">

Then I called these functions inside setup-load-and-import-handlers.js
- Functionality maintained
<img width="705" alt="Screen Shot 2022-10-26 at 10 52 40 AM" src="https://user-images.githubusercontent.com/89826597/198100961-05139941-64c4-41e7-ba5b-e7c8d8a87758.png">
<img width="705" alt="Screen Shot 2022-10-26 at 10 56 02 AM" src="https://user-images.githubusercontent.com/89826597/198100987-6ae20697-e5ab-4fd6-860f-3bce4843e276.png">

**Comment by dondi** [comment]
Looks almost ready for a pull request; we can pre-empt some comments that would have gone into the code review by making just a few more changes:
- The all-caps-with-underscores naming convention generally represents constant values (this goes all the way back to C); as such, these functions should _not_ use that naming convention because they aren’t constant values
- See if you can discover more descriptive/meaningful names for these; `loadAjax` and `getJson` are somewhat generic and do not communicate the specific functionality that is taking place

**Comment by Sarronnn** [comment]
Made few more changes to the functions:
<img width="804" alt="Screen Shot 2022-11-02 at 11 19 04 AM" src="https://user-images.githubusercontent.com/89826597/199570827-54283a9d-4d12-4f98-bcf9-dc1d7746544b.png">

**Comment by dondi** [comment]
Almost ready for PR; just need to move `fullUrl` calculation into the API functions, thus making the arguments into these functions be the true “input” that determines the behavior of the network request

**Comment by dondi** [comment]
@Sarronnn yes, double-check the original versions. A key consideration when rearranging code is to ensure that you use the same code consistently with the initial

Something I can see right away is that in `getWorkbookFromForm`, the code you transplanted for computing `fullUrl` is not the same. Line 142 makes reference to `queryURL` but that variable is not in the original version (it _is_ present in the second function, but not the first)

**Comment by dondi** [comment]
That’s just one thing that leaps out to me; there may be more

Also, keeping your Developer Tools console open while running the web app will help; it will show you any error messages encountered when executing the code

**Comment by Sarronnn** [comment]
<img width="759" alt="Screen Shot 2022-11-15 at 6 52 58 PM" src="https://user-images.githubusercontent.com/89826597/202072072-59449e36-9bae-46f1-a35d-ef325b44a8f5.png">
<img width="1440" alt="Screen Shot 2022-11-15 at 6 52 37 PM" src="https://user-images.githubusercontent.com/89826597/202072101-818f2066-1e6b-4b4c-a7d4-f64c3ce89103.png">


- Error when doing this.
<img width="1277" alt="Screen Shot 2022-11-15 at 6 55 13 PM" src="https://user-images.githubusercontent.com/89826597/202072334-605e720a-d116-4842-acb2-7387e79f60cc.png">

=> Tried setting uploadRoute=fullUrl, error persists

**Comment by dondi** [comment]
404 means the URL didn’t correspond to anything that the server recognized; look at the _Network_ tab to examine the request. Compare it to the one that master/beta sends out and see if there are differences. They should be identical

**Comment by dondi** [comment]
(well identical except for the hostname)

**Comment by dondi** [comment]
Conflicts and branch mixup have been resolved; after one last run of testing, @Sarronnn can commit, push, and issue a pull request for code review

**Comment by dondi** [comment]
@Sarronnn the epic pull request has been merged. Go ahead and merge `beta` into your branch, and retrace the changes you made, as we discussed earlier this week

**Comment by kdahlquist** [comment]
This is done and added to release notes.
