### ISSUE TITLE
Flexibility updates to gene search

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#997]
1. Revise the web app to allow parentheses for gene search (e.g., `MF(ALPHA)2`)
2. The four genes mentioned in #989 may still be searched via their old names; after #989 is fixed, we can smooth out the experience by allowing the old names to be entered but replacing them with the new ones before sending the query to the database

**Comment by Sarronnn** [comment]
Would Ona's change in issue #989 fix this?  She created an exceptions object that maps the irregular name to a name that we accept within GRNsight:
Screenshot from 2022-11-09 11-12-37

**Comment by kdahlquist** [comment]
We don't need to do this because recording the gene exceptions fixed this.
