### ISSUE TITLE
Asynchronous coordination before Thanksgiving 2022

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#999]
We will miss a Wednesday meeting due to the Thanksgiving break but we also don’t want to lose steam due to going 2 weeks without a meeting

As soon as everyone closes out their current issue, post here and we can asynchronously try to establish a good to start prior to the 11/30 meeting

**Comment by dondi** [comment]
🦗🦗🦗(including me) Oh well it was worth a try 😅 Belatedly, I worked with Sarr a bit on Tuesday before break to resolve loose ends with her refactor. Beyond that I didn’t see any further activity though 😔

**Comment by Sarronnn** [comment]
Merge conflict with Ona on the grnsight-api.js

**Comment by dondi** [comment]
Gobble gobble
